UPDATE creature_ai_texts SET content_default='我看到修道院的那帮笨蛋给我们送来新鲜的肉了。' WHERE entry=-1;
UPDATE creature_ai_texts SET content_default='兄弟会不能容忍你的行为。' WHERE entry=-2;
UPDATE creature_ai_texts SET content_default='啊！一个使用这把崭新的锐利之刃的机会。' WHERE entry=-3;
UPDATE creature_ai_texts SET content_default='感受兄弟会的力量吧！' WHERE entry=-4;
UPDATE creature_ai_texts SET content_default='有更多的骨头可以啃啦……！' WHERE entry=-5;
UPDATE creature_ai_texts SET content_default='啊啊啊……新鲜的肉！！' WHERE entry=-6;
UPDATE creature_ai_texts SET content_default='你休想拿走我的蜡烛!' WHERE entry=-7;
UPDATE creature_ai_texts SET content_default='哎呀! 我得逃跑!.' WHERE entry=-8;
UPDATE creature_ai_texts SET content_default='这有多令人恼怒?你会死的很难看!' WHERE entry=-9;
UPDATE creature_ai_texts SET content_default='当你燃烧时，放声尖叫吧！' WHERE entry=-10;
UPDATE creature_ai_texts SET content_default='我会把你化成灰烬！' WHERE entry=-11;
UPDATE creature_ai_texts SET content_default='你的痛苦就是我的快乐！' WHERE entry=-12;
UPDATE creature_ai_texts SET content_default='你在寻找奖赏是吗？死亡这个奖赏如何啊？' WHERE entry=-13;
UPDATE creature_ai_texts SET content_default='你的生命将属于我!' WHERE entry=-14;
UPDATE creature_ai_texts SET content_default='我不想再说，我早就提醒过你' WHERE entry=-15;
UPDATE creature_ai_texts SET content_default='你逃……不远的。' WHERE entry=-16;
UPDATE creature_ai_texts SET content_default='傲慢的傻瓜！你想偷塞雷玛尔的血吗？你会付出代价的！' WHERE entry=-17;
UPDATE creature_ai_texts SET content_default='为了胜利！为阿迦玛甘！' WHERE entry=-18;
UPDATE creature_ai_texts SET content_default='我要把你煮了，然后吃掉！' WHERE entry=-19;
UPDATE creature_ai_texts SET content_default='我希望你去死！' WHERE entry=-20;
UPDATE creature_ai_texts SET content_default='任务完成了。' WHERE entry=-21;
UPDATE creature_ai_texts SET content_default='范克里夫会为你的脑袋出个好价钱的!' WHERE entry=-22;
UPDATE creature_ai_texts SET content_default='保持警戒!' WHERE entry=-23;
UPDATE creature_ai_texts SET content_default='受死吧，看你能挣扎到什麽时候……' WHERE entry=-24;
UPDATE creature_ai_texts SET content_default='知道这是……唯一的出路。' WHERE entry=-25;
UPDATE creature_ai_texts SET content_default='是的，那令人相当满意' WHERE entry=-26;
UPDATE creature_ai_texts SET content_default='最后，我沮丧的目标！' WHERE entry=-27;
UPDATE creature_ai_texts SET content_default='你不属于这里 ！古人，攻打这些入侵者 ！' WHERE entry=-28;
UPDATE creature_ai_texts SET content_default='你没资格挑战我！我将永远为王！' WHERE entry=-29;
UPDATE creature_ai_texts SET content_default='%s的血喷入空气！' WHERE entry=-30;
UPDATE creature_ai_texts SET content_default='%s血溅成河！' WHERE entry=-31;
UPDATE creature_ai_texts SET content_default='电动正义！' WHERE entry=-32;
UPDATE creature_ai_texts SET content_default='警告！警告！入侵者警报！入侵者警报！' WHERE entry=-33;
UPDATE creature_ai_texts SET content_default='过来。我会确保你受到礼貌的对待!' WHERE entry=-34;
UPDATE creature_ai_texts SET content_default='哦，停止你的啜泣' WHERE entry=-35;
UPDATE creature_ai_texts SET content_default='我还没有……开始……' WHERE entry=-36;
UPDATE creature_ai_texts SET content_default='你不会再和那些低等生物打交道了!' WHERE entry=-37;
UPDATE creature_ai_texts SET content_default='(萨拉斯语)准备道别吧!' WHERE entry=-38;
UPDATE creature_ai_texts SET content_default='守卫，集合!消灭这些入侵者!' WHERE entry=-39;
UPDATE creature_ai_texts SET content_default='结束了吗?' WHERE entry=-40;
UPDATE creature_ai_texts SET content_default='什麽会变成-' WHERE entry=-41;
UPDATE creature_ai_texts SET content_default='加入我们吧， $C。' WHERE entry=-42;
UPDATE creature_ai_texts SET content_default='不！' WHERE entry=-43;
UPDATE creature_ai_texts SET content_default='我完成了！' WHERE entry=-44;
UPDATE creature_ai_texts SET content_default='主人..将会很生气...后果很严重' WHERE entry=-45;
UPDATE creature_ai_texts SET content_default='愤怒吧' WHERE entry=-46;
UPDATE creature_ai_texts SET content_default='%s恐惧的想要逃走！' WHERE entry=-47;
UPDATE creature_ai_texts SET content_default='你被邪恶的眼睛发现了！' WHERE entry=-48;
UPDATE creature_ai_texts SET content_default='等等 - 不!不!' WHERE entry=-49;
UPDATE creature_ai_texts SET content_default='不……公平……' WHERE entry=-50;
UPDATE creature_ai_texts SET content_default='命运已转为与我作对!' WHERE entry=-51;
UPDATE creature_ai_texts SET content_default='我在哪里？什麽-' WHERE entry=-52;
UPDATE creature_ai_texts SET content_default='发生了什麽事?' WHERE entry=-53;
UPDATE creature_ai_texts SET content_default='你...将付出代价...' WHERE entry=-54;
UPDATE creature_ai_texts SET content_default='你将受到惩罚！' WHERE entry=-55;
UPDATE creature_ai_texts SET content_default='五秒！我不是在开玩笑！' WHERE entry=-56;
UPDATE creature_ai_texts SET content_default='我说，「是的，但你要额外付出。」' WHERE entry=-57;
UPDATE creature_ai_texts SET content_default='他问小鬼会不会参加……你能相信吗？事实上，那还不够糟糕……' WHERE entry=-58;
UPDATE creature_ai_texts SET content_default='我们会玩的很尽兴!' WHERE entry=-59;
UPDATE creature_ai_texts SET content_default='他们入睡后。我，我睡着了…' WHERE entry=-60;
UPDATE creature_ai_texts SET content_default='我会想念那齣剧的!' WHERE entry=-61;
UPDATE creature_ai_texts SET content_default='对，我想我记起来了……' WHERE entry=-62;
UPDATE creature_ai_texts SET content_default='全都……回到我这里了……' WHERE entry=-63;
UPDATE creature_ai_texts SET content_default='是真的结束了吗？' WHERE entry=-64;
UPDATE creature_ai_texts SET content_default='自由……终于。' WHERE entry=-65;
UPDATE creature_ai_texts SET content_default='是时候继续行动了。' WHERE entry=-66;
UPDATE creature_ai_texts SET content_default='死亡是太仁慈了你的善良' WHERE entry=-67;
UPDATE creature_ai_texts SET content_default='同样的命运等待着谁所有，将窃取的主人' WHERE entry=-68;
UPDATE creature_ai_texts SET content_default='其他人会替代我的位子!' WHERE entry=-69;
UPDATE creature_ai_texts SET content_default='这个……改变不了什麽。永恒的毁灭等待着你!' WHERE entry=-70;
UPDATE creature_ai_texts SET content_default='有空常回来！' WHERE entry=-71;
UPDATE creature_ai_texts SET content_default='你会成功的，只有在诅咒自己的时候！' WHERE entry=-72;
UPDATE creature_ai_texts SET content_default='好黑...' WHERE entry=-73;
UPDATE creature_ai_texts SET content_default='啊啊啊! 差一点就跑掉了.' WHERE entry=-74;
UPDATE creature_ai_texts SET content_default='%s很快走出阴影…' WHERE entry=-75;
UPDATE creature_ai_texts SET content_default='嘿，你以为你要去哪里，鬼鬼祟祟的？' WHERE entry=-76;
UPDATE creature_ai_texts SET content_default='愚蠢！别开枪！基克吉克想要完整的！' WHERE entry=-77;
UPDATE creature_ai_texts SET content_default='没有让它熘走了！我们现在就去抓。' WHERE entry=-78;
UPDATE creature_ai_texts SET content_default='小心！别让他像上次一样抓到你。' WHERE entry=-79;
UPDATE creature_ai_texts SET content_default='基克吉克终于把你抓到了，你现在是基克吉克的了！' WHERE entry=-80;
UPDATE creature_ai_texts SET content_default='你的战略是有缺陷的' WHERE entry=-81;
UPDATE creature_ai_texts SET content_default='是的，唯一合乎逻辑结果。' WHERE entry=-82;
UPDATE creature_ai_texts SET content_default='一个无法预知的……意外。' WHERE entry=-83;
UPDATE creature_ai_texts SET content_default='测量两次;
切一次。' WHERE entry=-84;
UPDATE creature_ai_texts SET content_default='如果我切的没错的话，你应该已经死了。' WHERE entry=-85;
UPDATE creature_ai_texts SET content_default='我预言痛苦的死亡。' WHERE entry=-86;
UPDATE creature_ai_texts SET content_default='你应该趁机逃跑。' WHERE entry=-87;
UPDATE creature_ai_texts SET content_default='该死，我还真厉害！' WHERE entry=-88;
UPDATE creature_ai_texts SET content_default='你这个恶霸!' WHERE entry=-89;
UPDATE creature_ai_texts SET content_default='来吧，使出你最强的招数。我能承受!' WHERE entry=-90;
UPDATE creature_ai_texts SET content_default='你以为你能伤害我吗?你以为我怕你吗?' WHERE entry=-91;
UPDATE creature_ai_texts SET content_default='别说我没警告你！' WHERE entry=-92;
UPDATE creature_ai_texts SET content_default='工作一定要继续进行!' WHERE entry=-93;
UPDATE creature_ai_texts SET content_default='不要逼我杀了你！' WHERE entry=-94;
UPDATE creature_ai_texts SET content_default='这是你给自己惹的麻烦。' WHERE entry=-95;
UPDATE creature_ai_texts SET content_default='一定要完成' WHERE entry=-96;
UPDATE creature_ai_texts SET content_default='你不应该来了。' WHERE entry=-97;
UPDATE creature_ai_texts SET content_default='这是我……应得的……' WHERE entry=-98;
UPDATE creature_ai_texts SET content_default='你不能唤醒沉睡者!' WHERE entry=-99;
UPDATE creature_ai_texts SET content_default='%s发出了高声的尖叫，寻求帮助!' WHERE entry=-100;
UPDATE creature_ai_texts SET content_default='为了龙喉！' WHERE entry=-101;
UPDATE creature_ai_texts SET content_default='龙喉万岁！你的死毫无价值 $R!' WHERE entry=-102;
UPDATE creature_ai_texts SET content_default='脑子……' WHERE entry=-103;
UPDATE creature_ai_texts SET content_default='这片土地属于黑铁矮人。准备看来世， $C!' WHERE entry=-104;
UPDATE creature_ai_texts SET content_default='你将会被我踩在脚下，$R!' WHERE entry=-105;
UPDATE creature_ai_texts SET content_default='%s进入狂暴!' WHERE entry=-106;
UPDATE creature_ai_texts SET content_default='保护无辜者!' WHERE entry=-107;
UPDATE creature_ai_texts SET content_default='让大众信任!' WHERE entry=-108;
UPDATE creature_ai_texts SET content_default='支持法律!' WHERE entry=-109;
UPDATE creature_ai_texts SET content_default='死吧！你的朋友不会再为你哀悼！' WHERE entry=-110;
UPDATE creature_ai_texts SET content_default='用神秘的残滓清洗这个区域！' WHERE entry=-111;
UPDATE creature_ai_texts SET content_default='你们的世界现在属于我们了.' WHERE entry=-112;
UPDATE creature_ai_texts SET content_default='更多更多更多，我现在就要被喂养.' WHERE entry=-113;
UPDATE creature_ai_texts SET content_default='我不能忍受痛苦，我必须找到一个新的水源.' WHERE entry=-114;
UPDATE creature_ai_texts SET content_default='你所造成的伤害还不够吗?你一定要来扰乱我的睡眠吗?' WHERE entry=-115;
UPDATE creature_ai_texts SET content_default='暴力到底能带来甚麽利益?事情已经发生了。我失败了。' WHERE entry=-116;
UPDATE creature_ai_texts SET content_default='放弃希望吧!燃烧军团已经卷土重来，誓言要完成多年前开始的毁灭计画。这次，没有人能活着离开!' WHERE entry=-117;
UPDATE creature_ai_texts SET content_default='Reesh, hokta!' WHERE entry=-118;
UPDATE creature_ai_texts SET content_default='试试我的厉害，还有更精采的在后头。' WHERE entry=-119;
UPDATE creature_ai_texts SET content_default='不要反抗' WHERE entry=-120;
UPDATE creature_ai_texts SET content_default='你的死期就要…到了' WHERE entry=-121;
UPDATE creature_ai_texts SET content_default='你的死期就要…到了。' WHERE entry=-122;
UPDATE creature_ai_texts SET content_default='我是毒蛇之王!我无所不能!' WHERE entry=-123;
UPDATE creature_ai_texts SET content_default='傲慢！' WHERE entry=-124;
UPDATE creature_ai_texts SET content_default='燃烧军团最后的征战已经开始了!世界的掌控权再次落入我们手中。无人可以幸免!' WHERE entry=-125;
UPDATE creature_ai_texts SET content_default='屈服于冰冷绝望的……死亡吧。' WHERE entry=-126;
UPDATE creature_ai_texts SET content_default='你的坟墓中想必会更冷' WHERE entry=-127;
UPDATE creature_ai_texts SET content_default='崩溃和腐烂！' WHERE entry=-128;
UPDATE creature_ai_texts SET content_default='尘归尘，土归土' WHERE entry=-129;
UPDATE creature_ai_texts SET content_default='消灭所有的生命!' WHERE entry=-130;
UPDATE creature_ai_texts SET content_default='燃烧军团必胜!' WHERE entry=-131;
UPDATE creature_ai_texts SET content_default='你虽然赢得了这次战役，但无法……赢得整个战争' WHERE entry=-132;
UPDATE creature_ai_texts SET content_default='麻烦的小龙。我会教你干涉！' WHERE entry=-133;
UPDATE creature_ai_texts SET content_default='我们的新盟友将为我们报仇！' WHERE entry=-134;
UPDATE creature_ai_texts SET content_default='你会为侵占我们的土地付出代价！' WHERE entry=-135;
UPDATE creature_ai_texts SET content_default='呸！这是我的规则！' WHERE entry=-136;
UPDATE creature_ai_texts SET content_default='我会重生，凡人！ 主人会让我从这些灰烬中复活！' WHERE entry=-137;
UPDATE creature_ai_texts SET content_default='它是如此寒冷，如此黑暗的…我没有夸张，夸张吗？' WHERE entry=-138;
UPDATE creature_ai_texts SET content_default='...把它的眼睛放在$n.' WHERE entry=-139;
UPDATE creature_ai_texts SET content_default='死亡的力量会彻底摧毁你!' WHERE entry=-140;
UPDATE creature_ai_texts SET content_default='侵略者！敲响警钟！' WHERE entry=-141;
UPDATE creature_ai_texts SET content_default='在巨大的悲痛中，亚米萨兰的恐怖笼罩了大地，生存的希望淼小。' WHERE entry=-142;
UPDATE creature_ai_texts SET content_default='主人来到我们身边，他用法术保护我们不受伤害。' WHERE entry=-143;
UPDATE creature_ai_texts SET content_default='当晃动停止，显露了他的真实动机。我们被困，他慢慢地耗尽我们的力量。' WHERE entry=-144;
UPDATE creature_ai_texts SET content_default='成百的人被他的法术囚禁，监狱里只有少数活了下来。他有时会来和我们说话。' WHERE entry=-145;
UPDATE creature_ai_texts SET content_default='他担心自己的力量减弱，很快会褪色和死亡。' WHERE entry=-146;
UPDATE creature_ai_texts SET content_default='他的副手，伊克鲁德·玛格苏尔有可能知道时间和地点。' WHERE entry=-147;
UPDATE creature_ai_texts SET content_default='哇喔!谢啦!' WHERE entry=-148;
UPDATE creature_ai_texts SET content_default='%s变的不稳定并开始瓦解!' WHERE entry=-149;
UPDATE creature_ai_texts SET content_default='你能帮我找到我的狗吗?' WHERE entry=-150;
UPDATE creature_ai_texts SET content_default='我很想念我的狗...' WHERE entry=-151;
UPDATE creature_ai_texts SET content_default='%s看到 $N 体型不断变大! ' WHERE entry=-152;
UPDATE creature_ai_texts SET content_default='%s的力量逐渐消褪。' WHERE entry=-153;
UPDATE creature_ai_texts SET content_default='伊利丹统治者！' WHERE entry=-154;
UPDATE creature_ai_texts SET content_default='%s开始装备自走炸弹!' WHERE entry=-155;
UPDATE creature_ai_texts SET content_default='鲜血是我们的力量!' WHERE entry=-156;
UPDATE creature_ai_texts SET content_default='(恶魔语)成战斗队形!' WHERE entry=-157;
UPDATE creature_ai_texts SET content_default='为了卡加斯!为了胜利!' WHERE entry=-158;
UPDATE creature_ai_texts SET content_default='(兽人语)准备作战!' WHERE entry=-159;
UPDATE creature_ai_texts SET content_default='这个世界是我们的!' WHERE entry=-160;
UPDATE creature_ai_texts SET content_default='$r...很快会像我一样的死去。' WHERE entry=-161;
UPDATE creature_ai_texts SET content_default='嗯……我喜欢南海镇的美酒。' WHERE entry=-162;
UPDATE creature_ai_texts SET content_default='杀了他们，我的兄弟!为了天灾军团!' WHERE entry=-163;
UPDATE creature_ai_texts SET content_default='我们统治整个贫瘠之地！' WHERE entry=-164;
UPDATE creature_ai_texts SET content_default='我们将奴役野猪人！' WHERE entry=-165;
UPDATE creature_ai_texts SET content_default='很快，天灾军团就会统治世界！' WHERE entry=-166;
UPDATE creature_ai_texts SET content_default='杀!!!' WHERE entry=-167;
UPDATE creature_ai_texts SET content_default='谁敢打扰我?去死吧， $N!' WHERE entry=-168;
UPDATE creature_ai_texts SET content_default='没有人能与兄弟会抗衡!' WHERE entry=-169;
UPDATE creature_ai_texts SET content_default='受死吧!' WHERE entry=-170;
UPDATE creature_ai_texts SET content_default='你们都只是会摇尾巴的小狗!' WHERE entry=-171;
UPDATE creature_ai_texts SET content_default='笨蛋!我们的理想是正当的!' WHERE entry=-172;
UPDATE creature_ai_texts SET content_default='兄弟会必将获得最终的胜利!' WHERE entry=-173;
UPDATE creature_ai_texts SET content_default=' 你不能拿走我的蜡烛！ ' WHERE entry=-174;
UPDATE creature_ai_texts SET content_default='You land lovers are tougher then I thought! I will need to improvise' WHERE entry=-175;
UPDATE creature_ai_texts SET content_default='$N!你现在让我很生气!' WHERE entry=-176;
UPDATE creature_ai_texts SET content_default='我要把你的皮当作便服来穿!长靴呢?你得将它们从那儿撬下来!!!!' WHERE entry=-177;
UPDATE creature_ai_texts SET content_default='寻找这些吗？？？你不会有时间？！' WHERE entry=-178;
UPDATE creature_ai_texts SET content_default='我释放战争猎犬前，先拖延他们！' WHERE entry=-179;
UPDATE creature_ai_texts SET content_default='我的宝贝们都饿了，你的肉即将会成为他们的晚餐！' WHERE entry=-180;
UPDATE creature_ai_texts SET content_default='我们是真正的部落!' WHERE entry=-181;
UPDATE creature_ai_texts SET content_default='我的!我的!我的!吉兹洛克是这片领域的统治者!你绝对不能泄漏我的行踪!' WHERE entry=-182;
UPDATE creature_ai_texts SET content_default='什麽?哦，好吧，我不在乎你说什麽。我只是喜欢虐待你。' WHERE entry=-183;
UPDATE creature_ai_texts SET content_default='你终究是要说的，还不如现在就说了。' WHERE entry=-184;
UPDATE creature_ai_texts SET content_default='坦白交待了，我们就放你走。' WHERE entry=-185;
UPDATE creature_ai_texts SET content_default='这儿有活人!' WHERE entry=-186;
UPDATE creature_ai_texts SET content_default='%s召唤他的座狼。' WHERE entry=-187;
UPDATE creature_ai_texts SET content_default='USURPERS!!! GNOMEREGAN IS MINE!!!' WHERE entry=-188;
UPDATE creature_ai_texts SET content_default='My machines are the future! They''ll destroy you all!' WHERE entry=-189;
UPDATE creature_ai_texts SET content_default='Explosions! MORE explosions! I''ve got to have more explosions!' WHERE entry=-190;
UPDATE creature_ai_texts SET content_default='...and stay dead! He got served!' WHERE entry=-191;
UPDATE creature_ai_texts SET content_default='它可以在这里非常热的荒地。但至少这是一个干热。' WHERE entry=-192;
UPDATE creature_ai_texts SET content_default='小玩意儿 ...检查。 Doothingies ...检查。 Wizzers ...检查。' WHERE entry=-193;
UPDATE creature_ai_texts SET content_default='总有一天我要成为一个真正的男孩。' WHERE entry=-194;
UPDATE creature_ai_texts SET content_default='啪嗒……咔咔……' WHERE entry=-195;
UPDATE creature_ai_texts SET content_default='主人，这里很危险。但我要去帮你站岗放哨。' WHERE entry=-196;
UPDATE creature_ai_texts SET content_default='我们能让它变得更好，更强，更快。我们不仅拥有技术，而且拥有强大的魔法。' WHERE entry=-197;
UPDATE creature_ai_texts SET content_default='你们不该来这里!杀了他们!' WHERE entry=-198;
UPDATE creature_ai_texts SET content_default='受死吧，你这只卑劣的臭虫！' WHERE entry=-199;
UPDATE creature_ai_texts SET content_default='你会很容易被捕食，$C.' WHERE entry=-200;
UPDATE creature_ai_texts SET content_default='我的魔爪会切碎泥弱小的身躯，$R。' WHERE entry=-201;
UPDATE creature_ai_texts SET content_default='你的头会是一个很好的战利品，$R。' WHERE entry=-202;
UPDATE creature_ai_texts SET content_default='不!!! 把它放在篮子下面或者吃一槌子！' WHERE entry=-203;
UPDATE creature_ai_texts SET content_default='新鲜的面包啦!' WHERE entry=-204;
UPDATE creature_ai_texts SET content_default='新鲜出炉的面包!' WHERE entry=-205;
UPDATE creature_ai_texts SET content_default='擦亮你的装甲？' WHERE entry=-206;
UPDATE creature_ai_texts SET content_default='帮助一个贫穷的家伙呢？' WHERE entry=-207;
UPDATE creature_ai_texts SET content_default='一些硬币吗？' WHERE entry=-208;
UPDATE creature_ai_texts SET content_default='我有一个特别的消息要交给一个名叫 $N 的家伙。那就是:你死定了!' WHERE entry=-209;
UPDATE creature_ai_texts SET content_default='让我送你一程吧，没用的 $C!你可以准备后事了!' WHERE entry=-210;
UPDATE creature_ai_texts SET content_default='为艾德温·范克里夫而战!' WHERE entry=-211;
UPDATE creature_ai_texts SET content_default='啊啊啊!' WHERE entry=-212;
UPDATE creature_ai_texts SET content_default='粉碎!' WHERE entry=-213;
UPDATE creature_ai_texts SET content_default='杀死!' WHERE entry=-214;
UPDATE creature_ai_texts SET content_default='摧毁!' WHERE entry=-215;
UPDATE creature_ai_texts SET content_default='您所有的努力都白费了，因为排在世界之树已经开始了！不久，心脏跳动你的世界将不再有！' WHERE entry=-216;
UPDATE creature_ai_texts SET content_default='你们要守护的世界躲不了毁灭的命运!逃离这儿，也许可以延长你们那可悲的生命!' WHERE entry=-217;
UPDATE creature_ai_texts SET content_default='你没有希望了!' WHERE entry=-218;
UPDATE creature_ai_texts SET content_default='发出恐惧的尖叫声吧!' WHERE entry=-219;
UPDATE creature_ai_texts SET content_default='可惜没时间可以慢慢折磨到死!' WHERE entry=-220;
UPDATE creature_ai_texts SET content_default='时间……仍在……流逝。' WHERE entry=-221;
UPDATE creature_ai_texts SET content_default='虫群们渴望进食。' WHERE entry=-222;
UPDATE creature_ai_texts SET content_default='愿瘟疫降临在你身上!' WHERE entry=-223;
UPDATE creature_ai_texts SET content_default='你看来累了...' WHERE entry=-224;
UPDATE creature_ai_texts SET content_default='祝你好梦。' WHERE entry=-225;
UPDATE creature_ai_texts SET content_default='让火从天而降吧!' WHERE entry=-226;
UPDATE creature_ai_texts SET content_default='大地和天空将烧成灰烬!' WHERE entry=-227;
UPDATE creature_ai_texts SET content_default='我会让你成为魔咒!' WHERE entry=-228;
UPDATE creature_ai_texts SET content_default='杀你很容易.' WHERE entry=-229;
UPDATE creature_ai_texts SET content_default='你将要死了!' WHERE entry=-230;
UPDATE creature_ai_texts SET content_default='我将消灭你!' WHERE entry=-231;
UPDATE creature_ai_texts SET content_default='The Brotherhood will not be hampered by insects.' WHERE entry=-232;
UPDATE creature_ai_texts SET content_default='事情太多，时间太少!' WHERE entry=-233;
UPDATE creature_ai_texts SET content_default='当瓦奇兹威胁地对你扭动，狂暴的风包围着他。' WHERE entry=-234;
UPDATE creature_ai_texts SET content_default='%s的身体因为极度盛怒而颤动!' WHERE entry=-235;
UPDATE creature_ai_texts SET content_default='%s对她周糟的人露出她的毒牙并威胁地发出嘶嘶声。' WHERE entry=-236;
UPDATE creature_ai_texts SET content_default='快来看$N。' WHERE entry=-237;
UPDATE creature_ai_texts SET content_default='蠢蛋!猎鹰精华永远不会是你们的!' WHERE entry=-238;
UPDATE creature_ai_texts SET content_default='乌鸦的时代快到了，但是你的则会在此结束!' WHERE entry=-239;
UPDATE creature_ai_texts SET content_default='你胆敢打扰乌鸦的忠实追随者?' WHERE entry=-240;
UPDATE creature_ai_texts SET content_default='你将会因你的骄傲而死，德鲁伊!' WHERE entry=-241;
UPDATE creature_ai_texts SET content_default='你胆敢打扰乌鸦的忠实追随者?' WHERE entry=-242;
UPDATE creature_ai_texts SET content_default='你将会因你的骄傲而死，德鲁伊!' WHERE entry=-243;
UPDATE creature_ai_texts SET content_default='快来人帮葛利克看一下这张悬赏告示。葛利克不识字!' WHERE entry=-244;
UPDATE creature_ai_texts SET content_default='葛利克试试!' WHERE entry=-245;
UPDATE creature_ai_texts SET content_default='这个油对葛利克没好处!你觉得葛利克看起来像什麽，一个穿着长袍的弱者?' WHERE entry=-246;
UPDATE creature_ai_texts SET content_default='葛利克要喝一杯' WHERE entry=-247;
UPDATE creature_ai_texts SET content_default='我从来没有想到它会变成法力之油! 这将会需要很多，但葛利克不算在内!' WHERE entry=-248;
UPDATE creature_ai_texts SET content_default='寄出它!' WHERE entry=-249;
UPDATE creature_ai_texts SET content_default='学习阅读是一种让人口渴的业务. 来一片烤面包? 呃?' WHERE entry=-250;
UPDATE creature_ai_texts SET content_default='%s昏倒' WHERE entry=-251;
UPDATE creature_ai_texts SET content_default='过来这里，$r。你不会想要把你自己置于身陷牢狱的风险中的，你想吗?污秽地工作，为什麽?一些没有价值的小饰物吗?算了吧，你需要的是我的一个护符。保证有效!' WHERE entry=-252;
UPDATE creature_ai_texts SET content_default='到那边很危险，不是吗?知道你需要什麽吗?保护。我能帮助你对抗死亡本身!在你的脖子上穿戴这魔法护身符，看，然后你将能够回来，假如你发现你身处幽灵世界!只要快步跑向你的尸体，就能重获新生!' WHERE entry=-253;
UPDATE creature_ai_texts SET content_default='惊人的护符!难以置信的古董!新式的珠宝设计师将没有东西可以试验，老格利夫塔真正的神秘方法!透过廉价的这些魔法护符改善你自己吧!' WHERE entry=-254;
UPDATE creature_ai_texts SET content_default='我发誓我的苹果数量应该更多才对。葛罗克!' WHERE entry=-255;
UPDATE creature_ai_texts SET content_default='如果没有人帮忙，葛罗克去杀!' WHERE entry=-256;
UPDATE creature_ai_texts SET content_default='看这里，$c!我这有一些东西。正好是你需要的。它是肥皂，是的……并且它绑在一根绳子上!我并无恶意，朋友，但你看起来不太年轻，知道我在说什麽吗?' WHERE entry=-257;
UPDATE creature_ai_texts SET content_default='喂!喂，$r!我刚好有一些东西要给你。你看过提巴兰吗?令人感到恐惧的生物，他们大概会偷光你的东西。你需要的是我的提巴兰护符。保证可避开全部的提巴兰们!' WHERE entry=-258;
UPDATE creature_ai_texts SET content_default='葛罗克需要帮助!为什麽没人要帮忙?' WHERE entry=-259;
UPDATE creature_ai_texts SET content_default='干瘪的莫格多克告诉葛罗克到城里去，为血槌寻求帮助。葛罗克去。' WHERE entry=-260;
UPDATE creature_ai_texts SET content_default='剑刃氏族打得不公平。有古罗帮忙他们。你到剑刃山脉去。去跟干瘪的莫格多克谈谈。杀掉古罗。' WHERE entry=-261;
UPDATE creature_ai_texts SET content_default='你看起来很疲倦， $C。我准备了一些东西给你。这些护符，他们能帮助你越过障碍，并让你如生于河中般的游泳过河。他们使你吃的食物充满能量，让你的伤口在你看见前就愈合!' WHERE entry=-262;
UPDATE creature_ai_texts SET content_default='那个可怜的兽人在叫喊些什麽?有人该去看看发生了什麽事。' WHERE entry=-263;
UPDATE creature_ai_texts SET content_default='我觉得战争很快就要到来. 水果商人都被征召去帮忙巨魔，我也会尽力帮助..' WHERE entry=-264;
UPDATE creature_ai_texts SET content_default='你看起来像是患了相思病。某位特殊的人使你感到沮丧，是吗?不用担心，不用担心。从我这里买个大勋章，当你看见他们时，戴上它，让他们对你着迷，甜心!' WHERE entry=-265;
UPDATE creature_ai_texts SET content_default='我饿了。水果看起来很好吃。' WHERE entry=-266;
UPDATE creature_ai_texts SET content_default='水果小贩!你的货车还是挡到我们的路了!你的时间到了!我们现在要跟你竞卖水果!' WHERE entry=-267;
UPDATE creature_ai_texts SET content_default='如果不去刀刃找莫格多克谈谈，格罗克会生气的！' WHERE entry=-268;
UPDATE creature_ai_texts SET content_default='没有什麽比用一杯满满的啤酒把我可口的松饼冲下肚里还要好。' WHERE entry=-269;
UPDATE creature_ai_texts SET content_default='耶，正中红心。卖松饼!快过来买你刚出炉的松饼喔!' WHERE entry=-270;
UPDATE creature_ai_texts SET content_default='耶，耶，我是松饼人。你知道为什麽吗?因为我卖松饼，那就是为什麽!' WHERE entry=-271;
UPDATE creature_ai_texts SET content_default='我这儿有松饼。快过来!' WHERE entry=-272;
UPDATE creature_ai_texts SET content_default='但愿如此。' WHERE entry=-273;
UPDATE creature_ai_texts SET content_default='%s 看起来很弱足以捕捉。' WHERE entry=-274;
UPDATE creature_ai_texts SET content_default='在你涉足这里很久很久以前，这片土地就是我的了！' WHERE entry=-275;
UPDATE creature_ai_texts SET content_default='所有东西都是属于我，包括你！' WHERE entry=-276;
UPDATE creature_ai_texts SET content_default='当然，我的朋友。我能为你做些什麽吗?' WHERE entry=-277;
UPDATE creature_ai_texts SET content_default='一个高尚的任务。这是我的荣誉，伊洛丹。' WHERE entry=-278;
UPDATE creature_ai_texts SET content_default='我的朋友，请与我一同加入圣光谦逊的祈祷。' WHERE entry=-279;
UPDATE creature_ai_texts SET content_default='我们拥抱的圣光，我们恳求你……' WHERE entry=-280;
UPDATE creature_ai_texts SET content_default='我们已经派遣我们的孩子加入我们对抗黑暗的战争。' WHERE entry=-281;
UPDATE creature_ai_texts SET content_default='请祝福并且保护他们，并且使他们能成功的阻止那些想要伤害我们的人……' WHERE entry=-282;
UPDATE creature_ai_texts SET content_default='持续庇佑这里，我们古老的家园，我们祈求。' WHERE entry=-283;
UPDATE creature_ai_texts SET content_default='为我们的精灵访客宽容地庇护我们。' WHERE entry=-284;
UPDATE creature_ai_texts SET content_default='以那鲁之名，但愿如此。' WHERE entry=-285;
UPDATE creature_ai_texts SET content_default='%s点点头。' WHERE entry=-286;
UPDATE creature_ai_texts SET content_default='那天失去了几个我最出色的士兵……' WHERE entry=-287;
UPDATE creature_ai_texts SET content_default='但那还不是最糟的。在我们撤退以前，他们一群人发现了我们并发动攻击。' WHERE entry=-288;
UPDATE creature_ai_texts SET content_default='我不知道，蛮兵。我真的不 - 知道……' WHERE entry=-289;
UPDATE creature_ai_texts SET content_default='魔狱兽人...' WHERE entry=-290;
UPDATE creature_ai_texts SET content_default='红色的大溷蛋!比我见过的任何兽人还要大。它的肌肉有这麽大，獠牙有这麽长……' WHERE entry=-291;
UPDATE creature_ai_texts SET content_default='果然，来到飞奔回来，一些兽人下来的路径。他们没有看到我们，所以我们没有想通我们会去结识。' WHERE entry=-292;
UPDATE creature_ai_texts SET content_default='因此，我们 - 我和营，做一次例行侦察下来的骨头的道路。我们会派球探前方环顾四周，以防任何危险的出现。' WHERE entry=-293;
UPDATE creature_ai_texts SET content_default='是我感觉到肉桂? 还是肉豆蔻? 无论是什麽，有一件事是肯定的 - 没有人煮的像你这家伙一样烂.' WHERE entry=-294;
UPDATE creature_ai_texts SET content_default='如果我的胃没有因为拒绝那些本来给犯人吃的食物而威胁我要脱离我的身体的话，我想被这些食物给... 侮辱.' WHERE entry=-295;
UPDATE creature_ai_texts SET content_default='如果我们听到你这别脚货又跑去和纳兹格雷尔抱怨，下次你就会成为我们的一道菜肴……' WHERE entry=-296;
UPDATE creature_ai_texts SET content_default='你的工作服准备好了。来拿吧……' WHERE entry=-297;
UPDATE creature_ai_texts SET content_default='我见过比你还要认真的地精，苦工! 有猪尾巴的地精小女孩，快点!快点！快点!' WHERE entry=-298;
UPDATE creature_ai_texts SET content_default='什麽样的兽人，酋长?' WHERE entry=-299;
UPDATE creature_ai_texts SET content_default='你是说……' WHERE entry=-300;
UPDATE creature_ai_texts SET content_default='但是怎麽会?我以为诅咒已经解除了……' WHERE entry=-301;
UPDATE creature_ai_texts SET content_default='是，我们有问题。我想那是一清二楚的。问题是，我们要对它做些什麽?' WHERE entry=-302;
UPDATE creature_ai_texts SET content_default='是的，我们有麻烦了。我认为这是一清二楚的。问题是，我们该怎幺办呢？' WHERE entry=-303;
UPDATE creature_ai_texts SET content_default='你想要从我身上得到什麽? 萨满?' WHERE entry=-304;
UPDATE creature_ai_texts SET content_default='你没眼睛吗? 你没看到门外都是恶魔? 我手边没有多的士兵!' WHERE entry=-305;
UPDATE creature_ai_texts SET content_default='对您的神祈求 ，萨满. 也许他们会来援助您. 但是部落不能...' WHERE entry=-306;
UPDATE creature_ai_texts SET content_default='哇! 看看他的肌肉!' WHERE entry=-307;
UPDATE creature_ai_texts SET content_default='他会赢? 他赢的了?' WHERE entry=-308;
UPDATE creature_ai_texts SET content_default='他是如此的有教养!' WHERE entry=-309;
UPDATE creature_ai_texts SET content_default='我只是想成为斗者!' WHERE entry=-310;
UPDATE creature_ai_texts SET content_default='这比上一个好一点。不管怎幺说，它像其它的一样受制于脆弱骨头结构。当你召唤其中的一个，你就走上了正确的道路。' WHERE entry=-311;
UPDATE creature_ai_texts SET content_default='他是怎麽做呢?' WHERE entry=-312;
UPDATE creature_ai_texts SET content_default='那是我们所能提供的最好的奖励。希望有人会接受这个任务。' WHERE entry=-313;
UPDATE creature_ai_texts SET content_default='那些可恶的巨魔。诅咒他们进入虚空。没有人要把我们从这些野蛮人手中救出来吗!这是这麽多日子以来第五次绑架了。' WHERE entry=-314;
UPDATE creature_ai_texts SET content_default='什麽时候你们这些劳工想要休息一下，坟场就在那里。' WHERE entry=-315;
UPDATE creature_ai_texts SET content_default='假如让我看见这里有任何偷懒的劳工，我将把他们装进投石机里，并且把他们射到黑暗神庙去!' WHERE entry=-316;
UPDATE creature_ai_texts SET content_default='有这样的奖励，他们怎能拒绝呢，老兄?' WHERE entry=-317;
UPDATE creature_ai_texts SET content_default='上次某人尝试在虚空石身上收集物产，而我们收回的全部都是被压的扁扁的蛮勇冒险者!' WHERE entry=-318;
UPDATE creature_ai_texts SET content_default='或许我该在这次轮班之后召集一些其他的密探前往那里?' WHERE entry=-319;
UPDATE creature_ai_texts SET content_default='沙漠会将你吞噬!' WHERE entry=-320;
UPDATE creature_ai_texts SET content_default='Iman m t''ief fu Fus''obeah italaf' WHERE entry=-321;
UPDATE creature_ai_texts SET content_default='Dim wha Siame cyaa fi so yudo' WHERE entry=-322;
UPDATE creature_ai_texts SET content_default='So ju weh siame is fus nehjo skam worl Uptfeel' WHERE entry=-323;
UPDATE creature_ai_texts SET content_default='是猛攻的时后了!' WHERE entry=-324;
UPDATE creature_ai_texts SET content_default='Er... ''Moke?' WHERE entry=-325;
UPDATE creature_ai_texts SET content_default='I''m... not sure that''s a good idea, ''Moke. Ye might get hurt...' WHERE entry=-326;
UPDATE creature_ai_texts SET content_default='What, with me fists?' WHERE entry=-327;
UPDATE creature_ai_texts SET content_default='%s blinks, a perplexed expression crossing his face.' WHERE entry=-328;
UPDATE creature_ai_texts SET content_default='......这是伟大的！' WHERE entry=-329;
UPDATE creature_ai_texts SET content_default='这样做，你们干的不错！' WHERE entry=-330;
UPDATE creature_ai_texts SET content_default='Nae, that''s fer wimps. Hit me with yer hammer!' WHERE entry=-331;
UPDATE creature_ai_texts SET content_default='Bron! ''Ey Bron! ''Ey Bron! Hit me!' WHERE entry=-332;
UPDATE creature_ai_texts SET content_default='我不是很明白，你是瞎了吗? 你是看不到那些恶魔就在门外? 我要派谁去跟你的萨满朋友说? 指出那个人来!' WHERE entry=-333;
UPDATE creature_ai_texts SET content_default='你认为恶魔们将公正比赛吗?这些野兽比兽人们更野蛮，且比不死身更狡猾。千万不要试图以正常的标准战争方式来与军团抗衡。' WHERE entry=-334;
UPDATE creature_ai_texts SET content_default='还需要死多少士兵，我们才会开始注意外面?' WHERE entry=-335;
UPDATE creature_ai_texts SET content_default='是的，别天真地以为这不是一场战争，而战争是不会自然而然就获得胜利的。如果我们不使尽所有手段，争取这片破碎之地上的每一块小领土，我们就会全面战败了' WHERE entry=-336;
UPDATE creature_ai_texts SET content_default='啊，另一名强而有力的旅人。虚空可是很危险的;
你将会需要任何你所能够携带的有效法术。我提供最好的、普通的和奇特的药剂。来买吧 - 你不会后悔的!' WHERE entry=-338;
UPDATE creature_ai_texts SET content_default='她的呼吸就像是铃声般虔诚低语' WHERE entry=-339;
UPDATE creature_ai_texts SET content_default='%s检查悬赏告示上的讯息。' WHERE entry=-340;
UPDATE creature_ai_texts SET content_default='%s从阴影中跳了出来!' WHERE entry=-341;
UPDATE creature_ai_texts SET content_default='%s从阴影中叫出了更多的同伴。' WHERE entry=-342;
UPDATE creature_ai_texts SET content_default='让我帮帮你吧。' WHERE entry=-343;
UPDATE creature_ai_texts SET content_default='把这个喝了，它对你有好处。' WHERE entry=-344;
UPDATE creature_ai_texts SET content_default='你会好起来的。' WHERE entry=-345;
UPDATE creature_ai_texts SET content_default='%s开始呼唤增援!' WHERE entry=-346;
UPDATE creature_ai_texts SET content_default='舵手来找你了！' WHERE entry=-347;
UPDATE creature_ai_texts SET content_default='轮到你要对付欧拉布斯啦，蠢蛋!' WHERE entry=-348;
UPDATE creature_ai_texts SET content_default='那狗在哪？' WHERE entry=-349;
UPDATE creature_ai_texts SET content_default='你胆敢打扰主人的晚餐!' WHERE entry=-350;
UPDATE creature_ai_texts SET content_default='对你使用那个真是一种浪费!' WHERE entry=-351;
UPDATE creature_ai_texts SET content_default='那可是放了两百年的紫葡萄酒!' WHERE entry=-352;
UPDATE creature_ai_texts SET content_default='我没从$c跑掉，和你一样!' WHERE entry=-353;
UPDATE creature_ai_texts SET content_default='嘢！我杀！' WHERE entry=-354;
UPDATE creature_ai_texts SET content_default='最好的 $R 就是死掉的 $R!' WHERE entry=-355;
UPDATE creature_ai_texts SET content_default='没用的 $C!你无法对抗碎石怪部族!' WHERE entry=-356;
UPDATE creature_ai_texts SET content_default='感觉一下黑铁矮人的力量!' WHERE entry=-357;
UPDATE creature_ai_texts SET content_default='是时后解决你了，$C!' WHERE entry=-358;
UPDATE creature_ai_texts SET content_default='我会粉碎你!' WHERE entry=-359;
UPDATE creature_ai_texts SET content_default='我们将粉碎你！你就要死了！' WHERE entry=-360;
UPDATE creature_ai_texts SET content_default='啊啊啊r!!!我们撕碎 $R!' WHERE entry=-361;
UPDATE creature_ai_texts SET content_default='麦格尼·铜须是个白痴而且还是个骗子!' WHERE entry=-362;
UPDATE creature_ai_texts SET content_default='巨石水坝将会被摧毁!拉格纳罗斯万岁!' WHERE entry=-363;
UPDATE creature_ai_texts SET content_default='哇哈哈! 你像我一样倒下了!' WHERE entry=-364;
UPDATE creature_ai_texts SET content_default='我听厌了这些废话!准备受死吧!' WHERE entry=-365;
UPDATE creature_ai_texts SET content_default='啊啊啊!' WHERE entry=-366;
UPDATE creature_ai_texts SET content_default='嗯? 那是什麽?' WHERE entry=-367;
UPDATE creature_ai_texts SET content_default='这个 $R 看起来很好吃!' WHERE entry=-368;
UPDATE creature_ai_texts SET content_default='扁它!' WHERE entry=-369;
UPDATE creature_ai_texts SET content_default='一个叫做$C 的 $N?你应该是一顿不错的早餐!' WHERE entry=-370;
UPDATE creature_ai_texts SET content_default='死吧 $R! 这块土地属于碎石穴居部落!' WHERE entry=-371;
UPDATE creature_ai_texts SET content_default='这个湖现在属于碎石穴居部落，$N! 死吧!' WHERE entry=-372;
UPDATE creature_ai_texts SET content_default='以拉格纳罗斯之名，去死吧!' WHERE entry=-373;
UPDATE creature_ai_texts SET content_default='[矮人语] Dum mos' WHERE entry=-374;
UPDATE creature_ai_texts SET content_default='%s的眼睛变得通红，一边狂笑一边点燃了火药!' WHERE entry=-375;
UPDATE creature_ai_texts SET content_default='[兽人语] Ogg kaz ko zugas kil mog Tov''nokaz Kagg' WHERE entry=-376;
UPDATE creature_ai_texts SET content_default='[兽人语] Tago mog regas gi mog Tov''nokaz Kagg' WHERE entry=-377;
UPDATE creature_ai_texts SET content_default='狂暴姿态！他们大肆攻击！' WHERE entry=-378;
UPDATE creature_ai_texts SET content_default='我的!你不能占据这个地方!' WHERE entry=-379;
UPDATE creature_ai_texts SET content_default='这不是给你的!滚出这里!' WHERE entry=-380;
UPDATE creature_ai_texts SET content_default='注意!' WHERE entry=-381;
UPDATE creature_ai_texts SET content_default='好吧，各位 ，我们有很多工作要做而且要在非常短的时间内完成.' WHERE entry=-382;
UPDATE creature_ai_texts SET content_default='我曾经和某些德莱尼在司凯堤斯与影月谷并肩。但现在我们身在艾泽拉斯，而情势看来更加险恶。' WHERE entry=-383;
UPDATE creature_ai_texts SET content_default='首先，你们这些辛多雷听着。我指挥一艘严格的船舰…这可跟你们习惯的占卜者船舰不同。要嘛全力以赴，不然就给我滚回去!' WHERE entry=-384;
UPDATE creature_ai_texts SET content_default='现在快滚过来吧，欢迎来到奎尔达纳斯之岛。太阳之井就在南方的高地上，而凯尔萨斯王子所占据的博学者殿堂则在东边。' WHERE entry=-385;
UPDATE creature_ai_texts SET content_default='我们是来这边协助那些厚颜自称『冒险者』的家伙们。我们会帮他们守住岛上的关键地点，并且让他们远离冲突，好让他们可以正常工作。' WHERE entry=-386;
UPDATE creature_ai_texts SET content_default='如果女士们没有任何问题，你们将可以从小组长那边取得进一步的指示与协助。以上。祝好运!' WHERE entry=-387;
UPDATE creature_ai_texts SET content_default='不值一提!' WHERE entry=-388;
UPDATE creature_ai_texts SET content_default='欢迎来到太阳之井。尽管温度适中且风景优美，不过各位先生小姐们，你们可不是来渡假的!' WHERE entry=-389;
UPDATE creature_ai_texts SET content_default='目前的情况看来是:我们尽力固守，而那些较有经验和装备较好的人则去对付凯尔萨斯王子。' WHERE entry=-390;
UPDATE creature_ai_texts SET content_default='我知道，我们也认为他死了，但这不是关键。他试图利用太阳之井将燃烧军团的主人，基尔加丹，带入这个世界。' WHERE entry=-391;
UPDATE creature_ai_texts SET content_default='让我向你们保证，如果他真的成功，这个世界将会变得比外域更悲惨!让我们确保这件事情不会实现。' WHERE entry=-392;
UPDATE creature_ai_texts SET content_default='战士会部属来防守关键位置，你的射手则要协助阻止对方的飞行部队靠近。' WHERE entry=-393;
UPDATE creature_ai_texts SET content_default='我等着你的指派。并且待在这里，做好准备等待关键的一刻!' WHERE entry=-394;
UPDATE creature_ai_texts SET content_default='你好，新兵。我是训练中士巴度恩。接下来几天你将会接受一连串的适应与训练。' WHERE entry=-395;
UPDATE creature_ai_texts SET content_default='奎尔达纳斯之岛充斥着凯尔萨斯·逐日者王子的部队。情报先前认定他已经死了，但情报单位错了。' WHERE entry=-396;
UPDATE creature_ai_texts SET content_default='在高地之上，他和他的恶魔伙伴正打算要重新点燃太阳之井并且打开一道裂隙让他们的老大基尔加丹进入这个世界。' WHERE entry=-397;
UPDATE creature_ai_texts SET content_default='我们的工作是清除过多的东西，我们可以提供特殊的力量。' WHERE entry=-398;
UPDATE creature_ai_texts SET content_default='不用说，我们其中很多人恐怕再也回不了家。但如果你牢记你的训练，并且随时提高警觉，你就可以大大提高自己的存活机率' WHERE entry=-399;
UPDATE creature_ai_texts SET content_default='我现在只能说。集中注意力，孩子们。' WHERE entry=-400;
UPDATE creature_ai_texts SET content_default='该死的破碎之日人渣!自由开火!' WHERE entry=-401;
UPDATE creature_ai_texts SET content_default='瞄准那些恶魔。我们今天不是来消灭天谴军团的。' WHERE entry=-402;
UPDATE creature_ai_texts SET content_default='龙鹰由西面突袭! 射下那些德鲁伊!' WHERE entry=-403;
UPDATE creature_ai_texts SET content_default='我不能让你进入圣殿！我要摧毁你的货物！' WHERE entry=-404;
UPDATE creature_ai_texts SET content_default='%s看起来已经平静不少了。现在他已经吃下了$N的残骸' WHERE entry=-405;
UPDATE creature_ai_texts SET content_default='不要放过一个黑铁，$C.' WHERE entry=-406;
UPDATE creature_ai_texts SET content_default='我会放干你的血，$C!' WHERE entry=-407;
UPDATE creature_ai_texts SET content_default='有人想休息一下？太糟糕了！必须接着工作！' WHERE entry=-408;
UPDATE creature_ai_texts SET content_default='向下移动这部分，让它靠近船！' WHERE entry=-409;
UPDATE creature_ai_texts SET content_default='嗯，这一个看起来也就比风铃好一些。做好记录同学们……这不是在战斗激烈的时候你们想要召唤的东西。' WHERE entry=-410;
UPDATE creature_ai_texts SET content_default='今天的汉堡我会很高兴地在星期二那天付钱给你。' WHERE entry=-411;
UPDATE creature_ai_texts SET content_default='给我这个可怜的瞎子一点零钱吧?……你说我不是瞎子是什麽意思?……我真的不瞎了!我看的见了!!这真是一个奇迹!' WHERE entry=-412;
UPDATE creature_ai_texts SET content_default='这都是他们的错，愚蠢的联盟军队。刚在我的农场后面建立自己的水塔。' WHERE entry=-413;
UPDATE creature_ai_texts SET content_default='如果被上尉发现，我就死定了。' WHERE entry=-414;
UPDATE creature_ai_texts SET content_default='他们一定是得到了某些人的帮助。' WHERE entry=-415;
UPDATE creature_ai_texts SET content_default='突然之间，到处都是那帮家伙了。' WHERE entry=-416;
UPDATE creature_ai_texts SET content_default='先生，我们的客户在抱怨我们的致命毒药中魔女的痛苦不够多。' WHERE entry=-417;
UPDATE creature_ai_texts SET content_default='先生，我们的客户在抱怨我们的麻醉里太多丧命草了。' WHERE entry=-418;
UPDATE creature_ai_texts SET content_default='先生，我想我们那个最新的毒药配方中死草根用得太少了。' WHERE entry=-419;
UPDATE creature_ai_texts SET content_default='那麽下次放两倍的量下去!' WHERE entry=-420;
UPDATE creature_ai_texts SET content_default='下次放一半就好了。' WHERE entry=-421;
UPDATE creature_ai_texts SET content_default='小子，记住:你总是比你自认为的还要更糟。放两倍下去!' WHERE entry=-422;
UPDATE creature_ai_texts SET content_default='想想我开始穿车辙的铺路石。' WHERE entry=-423;
UPDATE creature_ai_texts SET content_default='杰克和吉尔我的皱纹 patoot！我所有的水卢金轮在这里。' WHERE entry=-424;
UPDATE creature_ai_texts SET content_default='我一天要走好多趟到水井那边去打水，现在的年轻人啊……' WHERE entry=-425;
UPDATE creature_ai_texts SET content_default='有水吗，艾玛?去弄点水，艾玛?你要是再不去打水，我都快忘了水是什麽样的了……' WHERE entry=-426;
UPDATE creature_ai_texts SET content_default='我这麽多年来好像都没干过比打水更有意义的事情似的!' WHERE entry=-427;
UPDATE creature_ai_texts SET content_default='我只是在自言自语罢了，和这里的其他人说话的时候，我总是得不到应有的尊重。' WHERE entry=-428;
UPDATE creature_ai_texts SET content_default='还没到吗?' WHERE entry=-429;
UPDATE creature_ai_texts SET content_default='我腿疼!' WHERE entry=-430;
UPDATE creature_ai_texts SET content_default='真的吗?运河里真的有鳄鱼吗?' WHERE entry=-431;
UPDATE creature_ai_texts SET content_default='我们为什麽要走这条路?' WHERE entry=-432;
UPDATE creature_ai_texts SET content_default='我们要去哪里?' WHERE entry=-433;
UPDATE creature_ai_texts SET content_default='我要去看法师塔。' WHERE entry=-434;
UPDATE creature_ai_texts SET content_default='不要召唤这样的东西。它如此脆弱，用棒敲击就能使它粉身碎骨。' WHERE entry=-435;
UPDATE creature_ai_texts SET content_default='看起来你要继续前进，棘轮，告诉他，我已经破坏了碎纸机。' WHERE entry=-436;
UPDATE creature_ai_texts SET content_default='我会留下来，警惕的残骸。快点！希望没有人会发现烟 …' WHERE entry=-437;
UPDATE creature_ai_texts SET content_default='我们被出卖了!' WHERE entry=-438;
UPDATE creature_ai_texts SET content_default='我们不会失败的!' WHERE entry=-439;
UPDATE creature_ai_texts SET content_default='死亡的最后的守护者！' WHERE entry=-440;
UPDATE creature_ai_texts SET content_default='我们还没被击败!' WHERE entry=-441;
UPDATE creature_ai_texts SET content_default='你的努力…都是白费力气。' WHERE entry=-442;
UPDATE creature_ai_texts SET content_default='我们一定要保护裂隙!' WHERE entry=-443;
UPDATE creature_ai_texts SET content_default='你快要没时间了!' WHERE entry=-444;
UPDATE creature_ai_texts SET content_default='不胜即亡!' WHERE entry=-445;
UPDATE creature_ai_texts SET content_default='没有人阻挡的了我们!' WHERE entry=-446;
UPDATE creature_ai_texts SET content_default='巫师将会倒下!' WHERE entry=-447;
UPDATE creature_ai_texts SET content_default='%s发出了一声尖叫。' WHERE entry=-448;
UPDATE creature_ai_texts SET content_default='是哪个$R在这里多管闲事?让斯塔文的传说和你一起消亡吧!' WHERE entry=-449;
UPDATE creature_ai_texts SET content_default='不要多管闲事，$N!' WHERE entry=-450;
UPDATE creature_ai_texts SET content_default='为什麽暴风城的卫兵还没有来?' WHERE entry=-451;
UPDATE creature_ai_texts SET content_default='圣光似乎遗弃了我们。' WHERE entry=-452;
UPDATE creature_ai_texts SET content_default='从暴风城来的消息似乎不太妙……' WHERE entry=-453;
UPDATE creature_ai_texts SET content_default='不断的争论只会一事无成。我们需要采取行动。' WHERE entry=-454;
UPDATE creature_ai_texts SET content_default='我们需要暴风城更多地采取行动。我们的家园正在被亡灵攻占。' WHERE entry=-455;
UPDATE creature_ai_texts SET content_default='恐怕黑暗正在向我们逼近。' WHERE entry=-456;
UPDATE creature_ai_texts SET content_default='暴风城的耳朵就像是城墙一样聋，跟本听不进我们说的话。' WHERE entry=-457;
UPDATE creature_ai_texts SET content_default='夜色镇的人民更多的期待理事会。我们不能让他们忍受这种在我们中传播的愤怒。' WHERE entry=-458;
UPDATE creature_ai_texts SET content_default='亡灵到处都是。暴风城的军队都哪去了？' WHERE entry=-459;
UPDATE creature_ai_texts SET content_default='等等……你不是我的丈夫。但肯定是他派你来的。你看起来……很可口!' WHERE entry=-460;
UPDATE creature_ai_texts SET content_default='亚伯?是你吗?啊……我很饿，亚伯!我饿啊!!' WHERE entry=-461;
UPDATE creature_ai_texts SET content_default='暮色森林的议会必须行动起来了。这里已经充满了邪恶。' WHERE entry=-462;
UPDATE creature_ai_texts SET content_default='我将会很快结束......' WHERE entry=-463;
UPDATE creature_ai_texts SET content_default='我们将战斗到死！' WHERE entry=-464;
UPDATE creature_ai_texts SET content_default='猛兽！听我的命令！立刻杀死他们！' WHERE entry=-465;
UPDATE creature_ai_texts SET content_default='嗯...完成...' WHERE entry=-466;
UPDATE creature_ai_texts SET content_default='看招!' WHERE entry=-467;
UPDATE creature_ai_texts SET content_default='已经完成了。' WHERE entry=-468;
UPDATE creature_ai_texts SET content_default='你无法阻止被遗忘者， $R。黑暗女王将会让你感受到痛苦和恐惧。' WHERE entry=-469;
UPDATE creature_ai_texts SET content_default='你听好了，在我杀死你之后，你的身体将为我所用， $R.' WHERE entry=-470;
UPDATE creature_ai_texts SET content_default='%s 开始破解，破解。' WHERE entry=-471;
UPDATE creature_ai_texts SET content_default='%s的力量随着石块断裂迅速衰减。' WHERE entry=-472;
UPDATE creature_ai_texts SET content_default='%s几乎都成了碎块，但仍然继续战斗。' WHERE entry=-473;
UPDATE creature_ai_texts SET content_default='邪恶的 $R入侵者。死吧!' WHERE entry=-474;
UPDATE creature_ai_texts SET content_default='如果鲁诺克恢复了他的力量，我们就死定了!' WHERE entry=-475;
UPDATE creature_ai_texts SET content_default='爸爸！' WHERE entry=-476;
UPDATE creature_ai_texts SET content_default='呣，更多的魔精。' WHERE entry=-477;
UPDATE creature_ai_texts SET content_default='不~~~~…!' WHERE entry=-478;
UPDATE creature_ai_texts SET content_default='我看到你了，害虫!靠近一点。' WHERE entry=-479;
UPDATE creature_ai_texts SET content_default='我们的血管中燃烧着野性诸神的力量，没有人，即使是巫妖王，也不能挡住我的去路!' WHERE entry=-480;
UPDATE creature_ai_texts SET content_default='他们胆敢攻击我们?那些蠢货!难道他们不知道我们现在无所不能了吗?!' WHERE entry=-481;
UPDATE creature_ai_texts SET content_default='解决他，接着我们就能向南挺进杀掉他们的同胞了!' WHERE entry=-482;
UPDATE creature_ai_texts SET content_default='我会消灭银白十字军!我会击碎天谴军!' WHERE entry=-483;
UPDATE creature_ai_texts SET content_default='把这些胆敢污染我们祭坛的入侵者杀掉!' WHERE entry=-484;
UPDATE creature_ai_texts SET content_default='深饮一口吧兄弟!' WHERE entry=-485;
UPDATE creature_ai_texts SET content_default='司瑟拉图斯的魔精现在是我们的啦。现在，所有人都将被德拉克瑞的力量给击碎!' WHERE entry=-486;
UPDATE creature_ai_texts SET content_default='等等…别再打了!' WHERE entry=-487;
UPDATE creature_ai_texts SET content_default='我…我投降。只要沸滚同意不要煮沸我的池子，我同意休战。' WHERE entry=-488;
UPDATE creature_ai_texts SET content_default='马上从我面前滚开。要是你识相就不要在我眼前出现。' WHERE entry=-489;
UPDATE creature_ai_texts SET content_default='我的背疼得要命。' WHERE entry=-490;
UPDATE creature_ai_texts SET content_default='如果我挂了，拿上我的邮袋。确保送到大将军手上。' WHERE entry=-491;
UPDATE creature_ai_texts SET content_default='我感觉到危险的存在。' WHERE entry=-492;
UPDATE creature_ai_texts SET content_default='死亡将只是你的酷刑的开始。' WHERE entry=-493;
UPDATE creature_ai_texts SET content_default='我的爪子将撕碎你的弱小的身体, $r.' WHERE entry=-494;
UPDATE creature_ai_texts SET content_default='我是钥匙大师。 你是守门人吗?' WHERE entry=-495;
UPDATE creature_ai_texts SET content_default='你的死期很快就会来临了……' WHERE entry=-496;
UPDATE creature_ai_texts SET content_default='你们阻止不了我们全部!' WHERE entry=-497;
UPDATE creature_ai_texts SET content_default='谁不敢？' WHERE entry=-498;
UPDATE creature_ai_texts SET content_default='住手!' WHERE entry=-499;
UPDATE creature_ai_texts SET content_default='告诉英波里安，我会考虑停止敌对的态度。但是，首先，翻涌必须停止他波涛般的入侵，来阻止我现身!' WHERE entry=-500;
UPDATE creature_ai_texts SET content_default='你让我感到厌烦了，滚!' WHERE entry=-501;
UPDATE creature_ai_texts SET content_default='我猜你带来了好消息?' WHERE entry=-502;
UPDATE creature_ai_texts SET content_default='事情会按照计划，主福尔肯克雷。我向你保证，这只是一个时间问题' WHERE entry=-503;
UPDATE creature_ai_texts SET content_default='...滚吧，不想嘲笑你两次!' WHERE entry=-504;
UPDATE creature_ai_texts SET content_default='要立刻塞满囚犯，不然玛里苟斯会知道的!' WHERE entry=-505;
UPDATE creature_ai_texts SET content_default='把更多的囚犯带下去!在彻底净化艾泽拉斯所有莽撞的魔法使用者之前，片刻都不得休息!' WHERE entry=-506;
UPDATE creature_ai_texts SET content_default='这场骚动有何含意?!' WHERE entry=-507;
UPDATE creature_ai_texts SET content_default='谁那麽大胆干扰我工作!?现身吧，懦夫!' WHERE entry=-508;
UPDATE creature_ai_texts SET content_default='啊！他来对了!' WHERE entry=-509;
UPDATE creature_ai_texts SET content_default='卡加尼舒!' WHERE entry=-510;
UPDATE creature_ai_texts SET content_default='你跑不了太远的!' WHERE entry=-511;
UPDATE creature_ai_texts SET content_default='我的力量是伟大的!哈哈...' WHERE entry=-512;
UPDATE creature_ai_texts SET content_default='你要震聋我?真可悲…等等…那是什麽声响?' WHERE entry=-513;
UPDATE creature_ai_texts SET content_default='我肯定老赫米特一定可以用你的骨头来做点什麽!' WHERE entry=-514;
UPDATE creature_ai_texts SET content_default='杀杀杀!!!!!!!' WHERE entry=-515;
UPDATE creature_ai_texts SET content_default='现在「这」才是竞技活动!' WHERE entry=-516;
UPDATE creature_ai_texts SET content_default='不会吧!犀牛头盔帽只要三十颗犀牛头的超低价?那我要两顶!' WHERE entry=-517;
UPDATE creature_ai_texts SET content_default='只要再50多个蹄子，我就可以有新枪了!' WHERE entry=-518;
UPDATE creature_ai_texts SET content_default='放弃，小野兽！' WHERE entry=-519;
UPDATE creature_ai_texts SET content_default='他只要这样继续搞下去，奈辛瓦里就会破产啦!兰恩根本不清楚他在做什麽!' WHERE entry=-520;
UPDATE creature_ai_texts SET content_default='晚上有小牛肉吃了!' WHERE entry=-521;
UPDATE creature_ai_texts SET content_default='我不知道奈辛瓦里为什幺告诉我你躲在这！' WHERE entry=-522;
UPDATE creature_ai_texts SET content_default='%s 开始召唤 黑手恐怖法师！' WHERE entry=-523;
UPDATE creature_ai_texts SET content_default='%s 开始召唤在黑手老兵！' WHERE entry=-524;
UPDATE creature_ai_texts SET content_default='%s召唤黑手恐法师来帮助他！' WHERE entry=-525;
UPDATE creature_ai_texts SET content_default='%s 召唤在黑手老兵来帮助他！' WHERE entry=-526;
UPDATE creature_ai_texts SET content_default='他将粉碎你！' WHERE entry=-527;
UPDATE creature_ai_texts SET content_default='死！你不会释放密斯赖尔！' WHERE entry=-528;
UPDATE creature_ai_texts SET content_default='站稳了，兄弟。别担心，他就在我们身边！' WHERE entry=-529;
UPDATE creature_ai_texts SET content_default='不，离开我们！我们必须完成我们的任务！' WHERE entry=-530;
UPDATE creature_ai_texts SET content_default='接招吧！我们必胜！' WHERE entry=-531;
UPDATE creature_ai_texts SET content_default='住手!愚蠢的 $C，我们不能让你召唤密斯赖尔' WHERE entry=-532;
UPDATE creature_ai_texts SET content_default='警告！警告！入侵者警报！入侵者警报！' WHERE entry=-536;
UPDATE creature_ai_texts SET content_default='您已被侦测到。你会被同化或消灭。' WHERE entry=-537;
UPDATE creature_ai_texts SET content_default='启动反措施。击退入侵者。' WHERE entry=-538;
UPDATE creature_ai_texts SET content_default='%s非常饿!' WHERE entry=-539;
UPDATE creature_ai_texts SET content_default='%s变得非常饿!' WHERE entry=-540;
UPDATE creature_ai_texts SET content_default='为银月城！为逐日者！' WHERE entry=-541;
UPDATE creature_ai_texts SET content_default='你的死，是对国王的敬意！' WHERE entry=-542;
UPDATE creature_ai_texts SET content_default='你的钱或你的生活！实际上，你的生命将尽...' WHERE entry=-543;
UPDATE creature_ai_texts SET content_default='死亡看守者辛瑞克集中精力于 $T' WHERE entry=-544;
UPDATE creature_ai_texts SET content_default='扫描生命形式的目标没有找到....' WHERE entry=-545;
UPDATE creature_ai_texts SET content_default='目标搜索模式恢复失去....' WHERE entry=-546;
UPDATE creature_ai_texts SET content_default='未知生命形式的评估检测 .... …' WHERE entry=-547;
UPDATE creature_ai_texts SET content_default='Arrrhhh...Guards!' WHERE entry=-548;
UPDATE creature_ai_texts SET content_default='Guards!' WHERE entry=-549;
UPDATE creature_ai_texts SET content_default='%s看到朋友在战斗中倒下，变得非常愤怒!' WHERE entry=-550;
UPDATE creature_ai_texts SET content_default='%s大声呼救!' WHERE entry=-551;
UPDATE creature_ai_texts SET content_default='问候公民。' WHERE entry=-552;
UPDATE creature_ai_texts SET content_default='胆敢破坏神圣的埃德萨拉斯? 面对我吧，懦夫！' WHERE entry=-553;
UPDATE creature_ai_texts SET content_default='我的灵魂终于可以安息了……哦，亲爱的塞瑞利恩……' WHERE entry=-554;
UPDATE creature_ai_texts SET content_default='我会告诉你一切！请住手！' WHERE entry=-555;
UPDATE creature_ai_texts SET content_default='我们...我们只说"赤色黎明"是一次觉醒。你看，光讲到高一般。它是光...' WHERE entry=-556;
UPDATE creature_ai_texts SET content_default='光是指引我们。你来之前，运动是设置在议案中...我们...按告诉我们，我们就去做。这是我们必须做些什么。' WHERE entry=-557;
UPDATE creature_ai_texts SET content_default='我知道其他很少......高一般选择谁可能去的人必须留下。有没有别的... ...你一定要相信我！' WHERE entry=-558;
UPDATE creature_ai_texts SET content_default='不！请住手！有一件事我忘了提及... ...一个快递来...从壁炉。它... ...' WHERE entry=-559;
UPDATE creature_ai_texts SET content_default='你会被吊在绞刑架不久，天灾恶魔！' WHERE entry=-560;
UPDATE creature_ai_texts SET content_default='你必须要杀死我，怪物！我什么也不会说！' WHERE entry=-561;
UPDATE creature_ai_texts SET content_default='你打得像个女人。老实说。那是你能做的最好吗？' WHERE entry=-562;
UPDATE creature_ai_texts SET content_default='你烧我最后的好战袍！' WHERE entry=-563;
UPDATE creature_ai_texts SET content_default='疼痛...当我收到我在文法学校，但孩子的鞭打的痛苦几乎是难以承受的。' WHERE entry=-564;
UPDATE creature_ai_texts SET content_default='你的痛苦，对我来说是一个正常的的午后！' WHERE entry=-565;
UPDATE creature_ai_texts SET content_default='谁干扰了我的冥想?' WHERE entry=-566;
UPDATE creature_ai_texts SET content_default='睡吧...' WHERE entry=-567;
UPDATE creature_ai_texts SET content_default='尘归尘，土归土' WHERE entry=-568;
UPDATE creature_ai_texts SET content_default='阿库麦尔死了!我终于可以离开这块伤心地了。' WHERE entry=-569;
UPDATE creature_ai_texts SET content_default='我会让你痛苦的死去。' WHERE entry=-570;
UPDATE creature_ai_texts SET content_default='你的死将是痛苦的。' WHERE entry=-571;
UPDATE creature_ai_texts SET content_default='你被标记了' WHERE entry=-572;
UPDATE creature_ai_texts SET content_default='你算什麽东西!' WHERE entry=-573;
UPDATE creature_ai_texts SET content_default='可悲的家伙！' WHERE entry=-574;
UPDATE creature_ai_texts SET content_default='Shaza-Kiel!' WHERE entry=-575;
UPDATE creature_ai_texts SET content_default='以索瑞森的胡须的名义!杀了他们!' WHERE entry=-576;
UPDATE creature_ai_texts SET content_default='我，格瑞姆洛克，我是国王!' WHERE entry=-577;
UPDATE creature_ai_texts SET content_default='去死！去死！' WHERE entry=-578;
UPDATE creature_ai_texts SET content_default='不！没有，你必须这样做！' WHERE entry=-579;
UPDATE creature_ai_texts SET content_default='死，凡人!


' WHERE entry=-580;
UPDATE creature_ai_texts SET content_default='%s 开始计入战斗!' WHERE entry=-581;
UPDATE creature_ai_texts SET content_default='比修知道宝藏被藏在哪儿了。' WHERE entry=-582;
UPDATE creature_ai_texts SET content_default='发牢骚！ *咳嗽咳嗽* * *我要戒菸！' WHERE entry=-583;
UPDATE creature_ai_texts SET content_default='问基布勒关于珍惜！发牢骚！' WHERE entry=-584;
UPDATE creature_ai_texts SET content_default='他们都到石塔，但从来没有回来 ...就像比茹。' WHERE entry=-585;
UPDATE creature_ai_texts SET content_default='Opus要科尔戈的黄金... 与蠕虫.' WHERE entry=-586;
UPDATE creature_ai_texts SET content_default='基布雷尔正在调查G.E.T.A.' WHERE entry=-587;
UPDATE creature_ai_texts SET content_default='我们什麽时候才能再吃东西?' WHERE entry=-588;
UPDATE creature_ai_texts SET content_default='感觉…………不太好。' WHERE entry=-589;
UPDATE creature_ai_texts SET content_default='哈尔……' WHERE entry=-590;
UPDATE creature_ai_texts SET content_default='是吗，纳特?' WHERE entry=-591;
UPDATE creature_ai_texts SET content_default='昨晚又再次的梦到那个梦……' WHERE entry=-592;
UPDATE creature_ai_texts SET content_default='哪一个?' WHERE entry=-593;
UPDATE creature_ai_texts SET content_default='那个梦 ...疯狂的那个。还记得吗？' WHERE entry=-594;
UPDATE creature_ai_texts SET content_default='塔伦米尔被一些疯狂的力量摧毁，成为敌人的南岸。' WHERE entry=-595;
UPDATE creature_ai_texts SET content_default='难道亚想像这样的事情，哈尔？可亚？' WHERE entry=-596;
UPDATE creature_ai_texts SET content_default='不可能!' WHERE entry=-597;
UPDATE creature_ai_texts SET content_default='那个地方，成千上万的人从天空注视着我们...' WHERE entry=-598;
UPDATE creature_ai_texts SET content_default='我们很喜欢他们的傀儡 - 我们跳舞，哭泣，战斗，并说无聊的事情供他们的娱乐。' WHERE entry=-599;
UPDATE creature_ai_texts SET content_default='正义得到伸张！' WHERE entry=-600;
UPDATE creature_ai_texts SET content_default='让处决开始！' WHERE entry=-601;
UPDATE creature_ai_texts SET content_default='这沙漠是我的！' WHERE entry=-602;
UPDATE creature_ai_texts SET content_default='Sandfury至高无上！' WHERE entry=-603;
UPDATE creature_ai_texts SET content_default='感受沙子的愤怒！' WHERE entry=-604;
UPDATE creature_ai_texts SET content_default='你怎么敢进我的圣地！' WHERE entry=-605;
UPDATE creature_ai_texts SET content_default='午餐已经到来我美丽的孩子。把他们撕成碎片！' WHERE entry=-606;
UPDATE creature_ai_texts SET content_default='Soulflayer来了！' WHERE entry=-607;
UPDATE creature_ai_texts SET content_default='加入我们！' WHERE entry=-608;
UPDATE creature_ai_texts SET content_default='我会在你的骨头堆里大吃！' WHERE entry=-609;
UPDATE creature_ai_texts SET content_default='嗯，他回到国王身边假装一切都很好，然后拔出他的剑，并抵住国王，刺进……你知道的……当场杀死他。' WHERE entry=-610;
UPDATE creature_ai_texts SET content_default='起来 Ata''lai, 起来!' WHERE entry=-611;
UPDATE creature_ai_texts SET content_default='哇哈哈哈' WHERE entry=-612;
UPDATE creature_ai_texts SET content_default='如果那还不够疯狂，他们决定结束冰淇淋的生意，并成为冒险者 ...他们走遍各地，最终消失在一些传送点。我醒来后一身冷汗...' WHERE entry=-613;
UPDATE creature_ai_texts SET content_default='我在敦霍尔德那里的那次，那个布拉克摩尔的私人奴隶逃跑……' WHERE entry=-614;
UPDATE creature_ai_texts SET content_default='他最后毁灭整个堡垒，释放关在营地的所有兽人，并且成为兽人的国王……大酋长还是甚麽的。' WHERE entry=-615;
UPDATE creature_ai_texts SET content_default='很疯狂，不是吗?' WHERE entry=-616;
UPDATE creature_ai_texts SET content_default='不行。' WHERE entry=-617;
UPDATE creature_ai_texts SET content_default='它永远不会发生，奈特。' WHERE entry=-618;
UPDATE creature_ai_texts SET content_default='你把什麽纳特你该管的？' WHERE entry=-619;
UPDATE creature_ai_texts SET content_default='保持你的声音了，赫尔库拉。陌生人比比皆是…' WHERE entry=-620;
UPDATE creature_ai_texts SET content_default='招魂。这就是所谓招魂。是的，我有它在我的权力来保佑你这个礼物。' WHERE entry=-621;
UPDATE creature_ai_texts SET content_default='这不是你要关心的，赫尔库拉，因为你既不是祈伦托，也不是巫师。' WHERE entry=-622;
UPDATE creature_ai_texts SET content_default='但要做到完全坦诚，我也不在乎什麽祈伦托的想法！他们是傻瓜，设定在古老的方式。' WHERE entry=-623;
UPDATE creature_ai_texts SET content_default='在适当的时候，赫尔库拉 ...所有在适当的时候 …' WHERE entry=-624;
UPDATE creature_ai_texts SET content_default='所以，你能教我这个 ...这个 …' WHERE entry=-625;
UPDATE creature_ai_texts SET content_default='同时祈伦托？他们有什麽要说这个巫术？' WHERE entry=-626;
UPDATE creature_ai_texts SET content_default='然后教我，科尔苏加德。教你知道我的一切…' WHERE entry=-627;
UPDATE creature_ai_texts SET content_default='什麽? 这是哪..? 不要只是站着发呆，小伙子上前杀敌!' WHERE entry=-628;
UPDATE creature_ai_texts SET content_default='这才像话!' WHERE entry=-629;
UPDATE creature_ai_texts SET content_default='你们……不过如……此……' WHERE entry=-630;
UPDATE creature_ai_texts SET content_default='那是什麽?(兽人语)攻击敌人!杀死他们!' WHERE entry=-631;
UPDATE creature_ai_texts SET content_default='我们的任务尚未完成!' WHERE entry=-632;
UPDATE creature_ai_texts SET content_default='嘎……' WHERE entry=-633;
UPDATE creature_ai_texts SET content_default='这个王国属于天谴军团! 只有亡者才能进入。' WHERE entry=-634;
UPDATE creature_ai_texts SET content_default='阴影…将你吞没。' WHERE entry=-635;
UPDATE creature_ai_texts SET content_default='黑暗...消耗...所有' WHERE entry=-636;
UPDATE creature_ai_texts SET content_default='这船…是空的。' WHERE entry=-637;
UPDATE creature_ai_texts SET content_default='没有...生活' WHERE entry=-638;
UPDATE creature_ai_texts SET content_default='虚空…招手。' WHERE entry=-639;
UPDATE creature_ai_texts SET content_default='激怒我是不明智的。' WHERE entry=-640;
UPDATE creature_ai_texts SET content_default='啊…那多好。' WHERE entry=-641;
UPDATE creature_ai_texts SET content_default='啊…正是我要的。' WHERE entry=-642;
UPDATE creature_ai_texts SET content_default='完全无效。就像其他人一样。' WHERE entry=-643;
UPDATE creature_ai_texts SET content_default='你选择了错误的对手。' WHERE entry=-644;
UPDATE creature_ai_texts SET content_default='我要把你撕成碎片！' WHERE entry=-645;
UPDATE creature_ai_texts SET content_default='(虫族语)脆弱的肉体!' WHERE entry=-646;
UPDATE creature_ai_texts SET content_default='现在我真的…生气了…' WHERE entry=-647;
UPDATE creature_ai_texts SET content_default='%s 发出低沉的轰鸣声，提醒附近的盟友！' WHERE entry=-648;
UPDATE creature_ai_texts SET content_default='%s 进入醉酒怒气！' WHERE entry=-649;
UPDATE creature_ai_texts SET content_default='我是红字的冲击。我们不出卖我们的领袖！' WHERE entry=-650;
UPDATE creature_ai_texts SET content_default='我不知道元帅在哪里。去死吧。' WHERE entry=-651;
UPDATE creature_ai_texts SET content_default='警卫！' WHERE entry=-652;
UPDATE creature_ai_texts SET content_default='大主教必须知道！啊.....！' WHERE entry=-653;
UPDATE creature_ai_texts SET content_default='斯尼维尔在此!冷齿矿坑是斯尼维尔的!' WHERE entry=-654;
UPDATE creature_ai_texts SET content_default='告诉我们!你们的领导者躲在哪?' WHERE entry=-655;
UPDATE creature_ai_texts SET content_default='拜托!我一定要立刻吃点东西……一个法力水晶……一个裂片……任何东西都好!我不能再忍受这种痛苦了!' WHERE entry=-656;
UPDATE creature_ai_texts SET content_default='你不说的话是不会得到任何东西的，人渣!' WHERE entry=-657;
UPDATE creature_ai_texts SET content_default='我的同伴的数量减少，女神，和自己的力量很快就不足以阻止费伍德森林的恶魔。' WHERE entry=-658;
UPDATE creature_ai_texts SET content_default='女神，请给予我力量让我征服我的敌人！听我说，我快要绝望了，我的所做的是正义的！' WHERE entry=-659;
UPDATE creature_ai_texts SET content_default='什麽...这是什麽？难道这是我的祈祷回答呢？ 艾露尼已授予我的武器 - 这镰刀 - 战胜恶魔。' WHERE entry=-660;
UPDATE creature_ai_texts SET content_default='安娜雅……?我的双眼没有欺骗我吗?真的是你吗?' WHERE entry=-661;
UPDATE creature_ai_texts SET content_default='命运是如此残酷，它让我们在分别了数千年之后才能重逢……' WHERE entry=-662;
UPDATE creature_ai_texts SET content_default='我的爱人，你恨我吗?我在万般无奈之下摧毁了你的躯壳，因为只有这样才能让你从痛苦中永久地解脱。' WHERE entry=-663;
UPDATE creature_ai_texts SET content_default='不!安娜雅……安娜雅!请不要离开我!不……' WHERE entry=-664;
UPDATE creature_ai_texts SET content_default='怎麽办，我的爱人?没有你，我怎麽办……没有你……我如何有勇气在这个世界上生存……' WHERE entry=-665;
UPDATE creature_ai_texts SET content_default='岁月对我和你都很残酷，我的爱人……但最后我们还是重逢了。' WHERE entry=-666;
UPDATE creature_ai_texts SET content_default='亲爱的，不要为此而感到内疚。你使我从无尽的苦楚和折磨中解脱了出来，我只会为此而更加爱你。' WHERE entry=-667;
UPDATE creature_ai_texts SET content_default='但是，即使是这经过数千年的分离才换来的重逢也是如此短暂……我和这个世界的联结正在逐渐减弱，我正在慢慢地离开它……离开你……' WHERE entry=-668;
UPDATE creature_ai_texts SET content_default='再见了，塞瑞利恩，我的爱人。我们终能再见……' WHERE entry=-669;
UPDATE creature_ai_texts SET content_default='%s那柔和的声音在薄雾中轻轻回响，「你要知道我永远爱你……」' WHERE entry=-670;
UPDATE creature_ai_texts SET content_default='你们这些无能的蠢蛋们!奥齐顿将成为我们的了……看看你们就像是一群过街老鼠!' WHERE entry=-671;
UPDATE creature_ai_texts SET content_default='这个世界是我们的！' WHERE entry=-672;
UPDATE creature_ai_texts SET content_default='你在那里！密切留意这些城墙，入侵者可以在任何时间的方法！' WHERE entry=-673;
UPDATE creature_ai_texts SET content_default='为了卡加斯!为了胜利!' WHERE entry=-674;
UPDATE creature_ai_texts SET content_default='你怎幺能就这样离开我吗？' WHERE entry=-675;
UPDATE creature_ai_texts SET content_default='救救我！请救救我！' WHERE entry=-676;
UPDATE creature_ai_texts SET content_default='请问痛苦结束的时候？' WHERE entry=-677;
UPDATE creature_ai_texts SET content_default='协助我，奴隶!' WHERE entry=-678;
UPDATE creature_ai_texts SET content_default='快点!你动作越慢，我就会让你越痛!' WHERE entry=-679;
UPDATE creature_ai_texts SET content_default='醒来!快起来回去工作!' WHERE entry=-680;
UPDATE creature_ai_texts SET content_default='太快了!你太快就懈怠了!' WHERE entry=-681;
UPDATE creature_ai_texts SET content_default='嘿！在这里！是啊，在这里 ...我在这个笼子！' WHERE entry=-682;
UPDATE creature_ai_texts SET content_default='这真是糟糕……我打你们这些懒惰的苦工打的手都痠了!' WHERE entry=-683;
UPDATE creature_ai_texts SET content_default='快回去工作吧你!' WHERE entry=-684;
UPDATE creature_ai_texts SET content_default='这是什麽?!你爸妈都没教你一点东西吗?!' WHERE entry=-685;
UPDATE creature_ai_texts SET content_default='%s开始大量的治疗!' WHERE entry=-686;
UPDATE creature_ai_texts SET content_default='是谁胆敢杀了我卡加斯的指挥官?你会为此付出……血债血偿!' WHERE entry=-687;
UPDATE creature_ai_texts SET content_default='不!' WHERE entry=-688;
UPDATE creature_ai_texts SET content_default='ZZZ...ZZZ!' WHERE entry=-689;
UPDATE creature_ai_texts SET content_default='你给我站住！不...你给我站住。' WHERE entry=-690;
UPDATE creature_ai_texts SET content_default='我不害怕！' WHERE entry=-691;
UPDATE creature_ai_texts SET content_default='不要杀我！' WHERE entry=-692;
UPDATE creature_ai_texts SET content_default='你不需要…我！' WHERE entry=-693;
UPDATE creature_ai_texts SET content_default='%s 芯片和碎片！' WHERE entry=-694;
UPDATE creature_ai_texts SET content_default='没人可以窃取这个！' WHERE entry=-695;
UPDATE creature_ai_texts SET content_default='德雷德国王伸出了他的鹰爪进行致命一击！' WHERE entry=-696;
UPDATE creature_ai_texts SET content_default='国王德莱德呼叫鹰鹫！' WHERE entry=-697;
UPDATE creature_ai_texts SET content_default='沙漠的沙，挡住了太阳！' WHERE entry=-698;
UPDATE creature_ai_texts SET content_default='你被终结了。' WHERE entry=-699;
UPDATE creature_ai_texts SET content_default='我…失败。' WHERE entry=-700;
UPDATE creature_ai_texts SET content_default='厚颜无耻的傻瓜！我要亲手杀了你！' WHERE entry=-701;
UPDATE creature_ai_texts SET content_default='勇士！队长！继续战斗！' WHERE entry=-702;
UPDATE creature_ai_texts SET content_default='你不值得我花时间, $n.' WHERE entry=-703;
UPDATE creature_ai_texts SET content_default='%s 回避使他更痛苦。' WHERE entry=-704;
UPDATE creature_ai_texts SET content_default='%s呻吟.' WHERE entry=-705;
UPDATE creature_ai_texts SET content_default='%s 可怜的啜泣.' WHERE entry=-706;
UPDATE creature_ai_texts SET content_default='愿圣光保佑你.' WHERE entry=-707;
UPDATE creature_ai_texts SET content_default='你的伤口很严重，但是你会活下来。' WHERE entry=-708;
UPDATE creature_ai_texts SET content_default='现在休息，你今天打得不错。' WHERE entry=-709;
UPDATE creature_ai_texts SET content_default='午饭时间到了，我的孩子。把他们撕成碎片！' WHERE entry=-710;
UPDATE creature_ai_texts SET content_default='站出来保卫你的主人！' WHERE entry=-711;
UPDATE creature_ai_texts SET content_default='孩子们扎会保护他们的主人。苏利萨斯会再度崛起！' WHERE entry=-712;
UPDATE creature_ai_texts SET content_default='伊利法尔，你的主人在召唤你!' WHERE entry=-713;
UPDATE creature_ai_texts SET content_default='让溷沌之火将你吞噬吧!' WHERE entry=-714;
UPDATE creature_ai_texts SET content_default='面对我的勇士吧，凡人!' WHERE entry=-715;
UPDATE creature_ai_texts SET content_default='为自己准备一个永恒的痛苦和折磨 - 我的报复，应 …' WHERE entry=-716;
UPDATE creature_ai_texts SET content_default='你要做到最好，现在试下！巨魔啤酒！！' WHERE entry=-717;
UPDATE creature_ai_texts SET content_default='嘿，你！酿造饮料怪物！让你成为大国和强国！' WHERE entry=-718;
UPDATE creature_ai_texts SET content_default='你想喝点什麽吗？我们的一起喝！' WHERE entry=-719;
UPDATE creature_ai_texts SET content_default='离开我，爱德华兹，免得你斩首。' WHERE entry=-720;
UPDATE creature_ai_texts SET content_default='我不会离开你的，我的仆从。' WHERE entry=-721;
UPDATE creature_ai_texts SET content_default='你别再让我看到你，你这个猥琐的家伙。小心我杀了你！' WHERE entry=-722;
UPDATE creature_ai_texts SET content_default='尊敬的$C，也…也许，你需要更多的尸尘…？' WHERE entry=-723;
UPDATE creature_ai_texts SET content_default='尊敬的$C 我可以擦…擦亮你的盔甲 ...?' WHERE entry=-724;
UPDATE creature_ai_texts SET content_default='尊敬的$C 我可以帮你洗马？' WHERE entry=-725;
UPDATE creature_ai_texts SET content_default='我是您忠实的仆人，我的主人。' WHERE entry=-726;
UPDATE creature_ai_texts SET content_default='门徒的血，你努力掌握控制你的敌人。' WHERE entry=-727;
UPDATE creature_ai_texts SET content_default='它的刀片或咒语，血液为我们提供攻击和削弱敌人的力量。' WHERE entry=-728;
UPDATE creature_ai_texts SET content_default='真正的大师，学会使用血液服务自己的战斗。' WHERE entry=-729;
UPDATE creature_ai_texts SET content_default='剥离我们敌人，双方的战斗和堕落，让我们坚持。' WHERE entry=-730;
UPDATE creature_ai_texts SET content_default='每一个敌人，能源消耗和被盗，只有进一步的攻击。' WHERE entry=-731;
UPDATE creature_ai_texts SET content_default='如主人的血，战斗无止境...' WHERE entry=-732;
UPDATE creature_ai_texts SET content_default='我们知道饥饿永不熄灭…' WHERE entry=-733;
UPDATE creature_ai_texts SET content_default='我们知道权力从未被克服...' WHERE entry=-734;
UPDATE creature_ai_texts SET content_default='作为主人的血，为我们的主人生死。反对我们的，甚至希望放弃生命.' WHERE entry=-735;
UPDATE creature_ai_texts SET content_default='%s开始产生动力的暗能量!' WHERE entry=-736;
UPDATE creature_ai_texts SET content_default='我的宝贝！你偷塔尔特克的东西，真是愚蠢的事。' WHERE entry=-737;
UPDATE creature_ai_texts SET content_default='%s 尖叫着愤怒和赶往救助她的婴儿.' WHERE entry=-738;
UPDATE creature_ai_texts SET content_default='你的母亲是和你父亲一样的暴人！' WHERE entry=-739;
UPDATE creature_ai_texts SET content_default='你不能轻松地击败我们，入侵者！' WHERE entry=-740;
UPDATE creature_ai_texts SET content_default='我的死亡只会加速你的死亡。' WHERE entry=-741;
UPDATE creature_ai_texts SET content_default='不可能！' WHERE entry=-742;
UPDATE creature_ai_texts SET content_default='如此的脆弱和无力！' WHERE entry=-743;
UPDATE creature_ai_texts SET content_default='肉…这样一个障碍。' WHERE entry=-744;
UPDATE creature_ai_texts SET content_default='你寻找奥杜尔的秘密？然后拿走他们！' WHERE entry=-745;
UPDATE creature_ai_texts SET content_default='本次钢铁议会休会！' WHERE entry=-746;
UPDATE creature_ai_texts SET content_default='无论是世界上最伟大的蚊子还是世界上最伟大的英雄，你终究只是个凡人。' WHERE entry=-747;
UPDATE creature_ai_texts SET content_default='镰布隆迪尔开始超负荷！' WHERE entry=-748;
UPDATE creature_ai_texts SET content_default='站着，看着光！' WHERE entry=-749;
UPDATE creature_ai_texts SET content_default='风暴的生命力量…' WHERE entry=-750;
UPDATE creature_ai_texts SET content_default='你轻率的疯狂之口！' WHERE entry=-751;
UPDATE creature_ai_texts SET content_default='一个仁慈的杀死！' WHERE entry=-752;
UPDATE creature_ai_texts SET content_default='哈!' WHERE entry=-753;
UPDATE creature_ai_texts SET content_default='本次会议休会！' WHERE entry=-754;
UPDATE creature_ai_texts SET content_default='让暴风云的上升和雨从天而降的死神！' WHERE entry=-755;
UPDATE creature_ai_texts SET content_default='没有总抽取就够了！' WHERE entry=-756;
UPDATE creature_ai_texts SET content_default='风暴的遗产不被撤消…' WHERE entry=-757;
UPDATE creature_ai_texts SET content_default='你能从我的失败中得到什幺？你没有那幺淡定，凡人…' WHERE entry=-758;
UPDATE creature_ai_texts SET content_default='破解这！' WHERE entry=-759;
UPDATE creature_ai_texts SET content_default='面对雷电浪涌！' WHERE entry=-760;
UPDATE creature_ai_texts SET content_default='世界上遭受另一个微不足道的损失！' WHERE entry=-761;
UPDATE creature_ai_texts SET content_default='傲慢的代价是死亡。' WHERE entry=-762;
UPDATE creature_ai_texts SET content_default='本次会议休会！' WHERE entry=-763;
UPDATE creature_ai_texts SET content_default='离开这个地方！' WHERE entry=-764;
UPDATE creature_ai_texts SET content_default='死亡的入侵者！' WHERE entry=-765;
UPDATE creature_ai_texts SET content_default='你控制不了我，弱小的 $r!' WHERE entry=-766;
UPDATE creature_ai_texts SET content_default='你阻止不了我们！' WHERE entry=-768;
UPDATE creature_ai_texts SET content_default='用我的死亡! 召唤你!' WHERE entry=-769;
UPDATE creature_ai_texts SET content_default='我被召唤来！入侵者，来到我的帐篷，面对你的死亡！' WHERE entry=-770;
UPDATE creature_ai_texts SET content_default='站起来，再次战斗！' WHERE entry=-771;
UPDATE creature_ai_texts SET content_default='为领主！为洛肯！' WHERE entry=-772;
UPDATE creature_ai_texts SET content_default='战斗，我的孩子！对敌人毫无怜悯！' WHERE entry=-773;
UPDATE creature_ai_texts SET content_default='构建，保卫首都的所有费用！' WHERE entry=-774;
UPDATE creature_ai_texts SET content_default='好吧！我们投降…放低你的武器，我会合作' WHERE entry=-775;
UPDATE creature_ai_texts SET content_default='%s仍掉在地上。' WHERE entry=-776;
UPDATE creature_ai_texts SET content_default='你在这里不受欢迎，怪物！' WHERE entry=-777;
UPDATE creature_ai_texts SET content_default='开始清洗！' WHERE entry=-778;
UPDATE creature_ai_texts SET content_default='十字军东征将胜利！' WHERE entry=-779;
UPDATE creature_ai_texts SET content_default='可怜的...' WHERE entry=-780;
UPDATE creature_ai_texts SET content_default='他们竟然嘲笑我们对血色十字军无能为力，是时候给他们审判的时候了！' WHERE entry=-781;
UPDATE creature_ai_texts SET content_default='天空本身以痛苦的征服！' WHERE entry=-782;
UPDATE creature_ai_texts SET content_default='眼睛睁大点。哥哥姐姐，弟弟妹妹。! GAZE UPON APOCALYPSE!' WHERE entry=-783;
UPDATE creature_ai_texts SET content_default='一个敌人被杀，我们的实力增长！我们决不能手软！' WHERE entry=-784;
UPDATE creature_ai_texts SET content_default='血色舰队在破坏后分离的海岸！' WHERE entry=-785;
UPDATE creature_ai_texts SET content_default='尸体的那些尝试只能养活我们的扩展宿主！' WHERE entry=-786;
UPDATE creature_ai_texts SET content_default='没有幸存者在你醒来，兄弟姐妹！' WHERE entry=-787;
UPDATE creature_ai_texts SET content_default='所有的人…必须…死' WHERE entry=-788;
UPDATE creature_ai_texts SET content_default='巫妖王和每一个人说！再反响你一次！' WHERE entry=-789;
UPDATE creature_ai_texts SET content_default='混沌！' WHERE entry=-790;
UPDATE creature_ai_texts SET content_default='让这些血色的傀儡见识我们恐怖的力量！' WHERE entry=-791;
UPDATE creature_ai_texts SET content_default='没有怜悯弱者！' WHERE entry=-792;
UPDATE creature_ai_texts SET content_default='杀光他们，死亡骑士！' WHERE entry=-793;
UPDATE creature_ai_texts SET content_default='死亡降临！结束了，血色十字军，你们将面对天灾军团的怒火。为了巫妖王！冲锋！' WHERE entry=-794;
UPDATE creature_ai_texts SET content_default='破坏的！' WHERE entry=-795;
UPDATE creature_ai_texts SET content_default='你敢来挑战胡鲁斯加王？' WHERE entry=-796;
UPDATE creature_ai_texts SET content_default='%s 把他的俱乐部，开始疯狂地摆动！' WHERE entry=-797;
UPDATE creature_ai_texts SET content_default='我认为是我做！' WHERE entry=-798;
UPDATE creature_ai_texts SET content_default='我欠你的，朋友。' WHERE entry=-799;
UPDATE creature_ai_texts SET content_default='我的同伴正在减少，女神，而且我自己的力量很快就会不足以阻挡费伍德森林的恶魔。' WHERE entry=-800;
UPDATE creature_ai_texts SET content_default='女神，赐予我力量，让我征服的敌人！听我说，我要绝望了，我所做的正义的！' WHERE entry=-801;
UPDATE creature_ai_texts SET content_default='什么...这是什么？难道这是我的祈祷回应吗？艾露尼已授予我武器 - 这把镰刀 - 去战胜恶魔。' WHERE entry=-802;
UPDATE creature_ai_texts SET content_default='安娜雅...? 我的眼睛没有欺骗我吧?真的是你吗?' WHERE entry=-803;
UPDATE creature_ai_texts SET content_default='命运如此残酷。千年之后我们只能如此...' WHERE entry=-804;
UPDATE creature_ai_texts SET content_default='你恨我吗，我的爱人？我是被迫毁掉你活着的样子，从而使你的精神从不愉快的束缚中得到释放。' WHERE entry=-805;
UPDATE creature_ai_texts SET content_default='不! 安娜雅。。。安娜雅，请不要离开我。。。' WHERE entry=-806;
UPDATE creature_ai_texts SET content_default='怎样才能...我的爱，我怎样才能面对没有你在我身旁陪伴的时光……' WHERE entry=-807;
UPDATE creature_ai_texts SET content_default='岁月对你我如此残酷，我的爱，但放心，我们终将团聚。' WHERE entry=-808;
UPDATE creature_ai_texts SET content_default='请不要费心了，亲爱的。您已经使我摆脱了奴役，我只会更加爱你。' WHERE entry=-809;
UPDATE creature_ai_texts SET content_default='可悲的是，这如此短暂...我和这个世界的连接正在削弱，拉我远走...' WHERE entry=-810;
UPDATE creature_ai_texts SET content_default='永别了，Cerellean，直到我们再次加入...' WHERE entry=-811;
UPDATE creature_ai_texts SET content_default='安纳亚的温柔的声音消失在迷雾小径，“要知道，我永远爱你...”' WHERE entry=-812;
UPDATE creature_ai_texts SET content_default='交易。' WHERE entry=-813;
UPDATE creature_ai_texts SET content_default='利润！' WHERE entry=-814;
UPDATE creature_ai_texts SET content_default='这…是一个不可恢复的…损失。' WHERE entry=-815;
UPDATE creature_ai_texts SET content_default='不要低估其它空灵的贪婪。' WHERE entry=-816;
UPDATE creature_ai_texts SET content_default='So or''manley fi siame Dim fus siame yudo' WHERE entry=-817;
UPDATE creature_ai_texts SET content_default='IMan atuad fi ting caang' WHERE entry=-818;
UPDATE creature_ai_texts SET content_default='回头！不醒的梦！' WHERE entry=-819;
UPDATE creature_ai_texts SET content_default='你不知道你在做什幺！我们必须毁灭自己' WHERE entry=-820;
UPDATE creature_ai_texts SET content_default='The shield be down! Rise up Atal''ai! Rise up!' WHERE entry=-821;
UPDATE creature_ai_texts SET content_default='The Soulflayer comes!' WHERE entry=-822;
UPDATE creature_ai_texts SET content_default='Join us!' WHERE entry=-823;
UPDATE creature_ai_texts SET content_default='哈卡将再次重生！' WHERE entry=-824;
UPDATE creature_ai_texts SET content_default='这个邪恶的不被允许进入这个世界！我的孩子！' WHERE entry=-825;
UPDATE creature_ai_texts SET content_default='你，死！' WHERE entry=-826;
UPDATE creature_ai_texts SET content_default='不，你不能比星海强！不！' WHERE entry=-827;
UPDATE creature_ai_texts SET content_default='%s 攻击卡拉恩的旌旗！' WHERE entry=-828;
UPDATE creature_ai_texts SET content_default='%s 掌管！' WHERE entry=-829;
UPDATE creature_ai_texts SET content_default='%s 在成为无形资产。' WHERE entry=-830;
UPDATE creature_ai_texts SET content_default='嘿，harbringer，怎样的研究来？有可能是一个ultra-kinetic华夫铁在为你如果你及时的知道结果！' WHERE entry=-831;
UPDATE creature_ai_texts SET content_default='它来到一起。你没有一个产品演示做什幺的？' WHERE entry=-832;
UPDATE creature_ai_texts SET content_default='是第一个难以置信的静电冲击波！' WHERE entry=-833;
UPDATE creature_ai_texts SET content_default='从新分析破碎残阳的军事技术，让它远离爆炸污渍！' WHERE entry=-834;
UPDATE creature_ai_texts SET content_default='酒渍，草地上的污渍，甚至宠物污渍，冲击波！' WHERE entry=-835;
UPDATE creature_ai_texts SET content_default='不要等待！现在为了获得我的ultra-kinetic的任何额外费用！' WHERE entry=-836;
UPDATE creature_ai_texts SET content_default='嘿, $G 女士？给些钱？我有五个孩子要养活' WHERE entry=-837;
UPDATE creature_ai_texts SET content_default='铜板，夫人？' WHERE entry=-838;
UPDATE creature_ai_texts SET content_default='请不要忽视我…' WHERE entry=-839;
UPDATE creature_ai_texts SET content_default='凉爽的微风轻抚你的脸。柔和的旋律哼唱。' WHERE entry=-840;
UPDATE creature_ai_texts SET content_default='游戏时间！' WHERE entry=-841;
UPDATE creature_ai_texts SET content_default='新玩具！' WHERE entry=-842;
UPDATE creature_ai_texts SET content_default='真无聊！' WHERE entry=-843;
UPDATE creature_ai_texts SET content_default='为什幺你不走了？' WHERE entry=-844;
UPDATE creature_ai_texts SET content_default='起来！我还没有做好！' WHERE entry=-845;
UPDATE creature_ai_texts SET content_default='这不好玩…' WHERE entry=-846;
UPDATE creature_ai_texts SET content_default='你太晚了，洛丹伦的战士。将迎来他们死亡的一天。' WHERE entry=-847;
UPDATE creature_ai_texts SET content_default='啊，已抵达！' WHERE entry=-848;
UPDATE creature_ai_texts SET content_default='好戏才刚刚开始！' WHERE entry=-849;
UPDATE creature_ai_texts SET content_default='啊，优质的材料！' WHERE entry=-850;
UPDATE creature_ai_texts SET content_default='别担心，我会好好利用你。' WHERE entry=-851;
UPDATE creature_ai_texts SET content_default='向我的朋友问好。' WHERE entry=-852;
UPDATE creature_ai_texts SET content_default='来，斯坦索姆的公民！满足你的救世主。' WHERE entry=-853;
UPDATE creature_ai_texts SET content_default='繁荣的！哈哈哈哈哈…' WHERE entry=-854;
UPDATE creature_ai_texts SET content_default='血…破坏的…令人兴奋的！' WHERE entry=-855;
UPDATE creature_ai_texts SET content_default='我想要一个样品…' WHERE entry=-856;
UPDATE creature_ai_texts SET content_default='这种力量…它必须属于我！' WHERE entry=-857;
UPDATE creature_ai_texts SET content_default='你的身体背叛了你。' WHERE entry=-858;
UPDATE creature_ai_texts SET content_default='你只是推进…主人的计划…' WHERE entry=-859;
UPDATE creature_ai_texts SET content_default='阿尔塞斯米奈希尔王子，在这一天，一个强大的黑暗主宰了你的灵魂。死亡注定是你命运，这一天是你自己的。' WHERE entry=-860;
UPDATE creature_ai_texts SET content_default='我们会看到这位年轻的王子。' WHERE entry=-861;
UPDATE creature_ai_texts SET content_default='滴答，滴答滴答…' WHERE entry=-862;
UPDATE creature_ai_texts SET content_default='不够快！' WHERE entry=-863;
UPDATE creature_ai_texts SET content_default='结束吧。' WHERE entry=-864;
UPDATE creature_ai_texts SET content_default='在没有你的未来。' WHERE entry=-865;
UPDATE creature_ai_texts SET content_default='这是我们最伟大的胜利时刻！' WHERE entry=-866;
UPDATE creature_ai_texts SET content_default='你将注定要失败。' WHERE entry=-867;
UPDATE creature_ai_texts SET content_default='是的，这是开始。我一直在等你，年轻的王子。我是玛尔甘尼斯。' WHERE entry=-868;
UPDATE creature_ai_texts SET content_default='如你所见，你的人民现在是属于我的。我现在要把这城，一户一户，直到生命的火焰已经永远被扼杀。' WHERE entry=-869;
UPDATE creature_ai_texts SET content_default='你的旅程刚刚开始，年轻的王子。聚集你的军队，并满足我在北极诺森德大陆的需求。我们将决一胜负。这是你真正的命运。' WHERE entry=-870;
UPDATE creature_ai_texts SET content_default='这将是一个很好的测试，阿尔塞斯王子。' WHERE entry=-871;
UPDATE creature_ai_texts SET content_default='没时间了。' WHERE entry=-872;
UPDATE creature_ai_texts SET content_default='你看上去很累。' WHERE entry=-873;
UPDATE creature_ai_texts SET content_default='太容易了。' WHERE entry=-874;
UPDATE creature_ai_texts SET content_default='黑魔王不高兴你干扰。' WHERE entry=-875;
UPDATE creature_ai_texts SET content_default='我想要阿尔塞斯王子，不是你。' WHERE entry=-876;
UPDATE creature_ai_texts SET content_default='每个人都得了流行病！' WHERE entry=-877;
UPDATE creature_ai_texts SET content_default='士兵们散布恐慌谣言。邻居指责有毒药。该市将陷入混乱！' WHERE entry=-878;
UPDATE creature_ai_texts SET content_default='似乎没有办法工作，整个城市已患病…' WHERE entry=-879;
UPDATE creature_ai_texts SET content_default='我不知所措。简单的面对灾难？' WHERE entry=-880;
UPDATE creature_ai_texts SET content_default='我怎幺可能帮助该市，在这样一个危机时刻？' WHERE entry=-881;
UPDATE creature_ai_texts SET content_default='我祈祷我感觉是由于…' WHERE entry=-882;
UPDATE creature_ai_texts SET content_default='你好。弗里亚斯主人不在。请明天再来！哔哔声！' WHERE entry=-883;
UPDATE creature_ai_texts SET content_default='我活过来了，像重生一样！' WHERE entry=-884;
UPDATE creature_ai_texts SET content_default='但…但…我是完美的！' WHERE entry=-885;
UPDATE creature_ai_texts SET content_default='我在哪里？好奇怪的感觉？' WHERE entry=-886;
UPDATE creature_ai_texts SET content_default='我重生了！谢谢！' WHERE entry=-887;
UPDATE creature_ai_texts SET content_default='我知道你会来。' WHERE entry=-888;
UPDATE creature_ai_texts SET content_default='你的格斗，给我留下了深刻的印象。' WHERE entry=-889;
UPDATE creature_ai_texts SET content_default='欢迎世界各地的亡灵！' WHERE entry=-890;
UPDATE creature_ai_texts SET content_default='打得好…' WHERE entry=-891;
UPDATE creature_ai_texts SET content_default='我知道你为什幺来——那些愚蠢的马格纳托平原上干涉设法参与。你喜欢为他们的狗？' WHERE entry=-892;
UPDATE creature_ai_texts SET content_default='你寻求他们的领袖…小事情，你发动战争。不要急于赶死。' WHERE entry=-893;
UPDATE creature_ai_texts SET content_default='哈！就是这样！吹号角的马格纳托领导的环火把南蓝龙殿围绕。实现和平，您的神…格罗姆萨尔会来。' WHERE entry=-894;
UPDATE creature_ai_texts SET content_default='你们是逃不了的。十字军东征应当销毁所有天灾的污点。' WHERE entry=-895;
UPDATE creature_ai_texts SET content_default='你带着这污点，准备进入扭曲虚空。' WHERE entry=-896;
UPDATE creature_ai_texts SET content_default='谴责所有罪恶,现在你会死！' WHERE entry=-897;
UPDATE creature_ai_texts SET content_default='真遗憾你死在这里。' WHERE entry=-902;
UPDATE creature_ai_texts SET content_default='我们不允许你离开这个山谷！' WHERE entry=-903;
UPDATE creature_ai_texts SET content_default='我希望你安静下来。' WHERE entry=-904;
UPDATE creature_ai_texts SET content_default='你不带我活着，浮渣！' WHERE entry=-905;
UPDATE creature_ai_texts SET content_default='该注射过的奈斯特灌木林枭兽不喜欢刚才发生的。' WHERE entry=-906;
UPDATE creature_ai_texts SET content_default='奈斯特灌木林枭兽看起来很迷惘。' WHERE entry=-907;
UPDATE creature_ai_texts SET content_default='奈斯特灌木林枭兽赞赏地点头。' WHERE entry=-908;
UPDATE creature_ai_texts SET content_default='奈斯特灌木林枭兽不喜欢看到影响。' WHERE entry=-909;
UPDATE creature_ai_texts SET content_default='奈斯特灌木林枭兽似乎很高兴。' WHERE entry=-910;
UPDATE creature_ai_texts SET content_default='<Sobbing> 我讨厌墓地。这幺多死人。我的luhanaa.....' WHERE entry=-911;
UPDATE creature_ai_texts SET content_default='它应该是我！' WHERE entry=-912;
UPDATE creature_ai_texts SET content_default='安静，我亲爱的Luhanaa.' WHERE entry=-913;
UPDATE creature_ai_texts SET content_default='我永远不会忘记你，我的爱。' WHERE entry=-914;
UPDATE creature_ai_texts SET content_default='如果我能找到那些…！' WHERE entry=-915;
UPDATE creature_ai_texts SET content_default='我们不应该来。' WHERE entry=-916;
UPDATE creature_ai_texts SET content_default='为什幺，luhanaa？为什幺？' WHERE entry=-917;
UPDATE creature_ai_texts SET content_default='我非常想念你。' WHERE entry=-918;
UPDATE creature_ai_texts SET content_default='你会一直在这里，和我。' WHERE entry=-919;
UPDATE creature_ai_texts SET content_default='德莱尼送葬者轻轻地哭泣。' WHERE entry=-920;
UPDATE creature_ai_texts SET content_default='德莱尼送葬者低头叹息。' WHERE entry=-921;
UPDATE creature_ai_texts SET content_default='德莱尼送葬者倒下了。' WHERE entry=-922;
UPDATE creature_ai_texts SET content_default='德莱尼送葬者在沉默标记之前刻刀。' WHERE entry=-923;
UPDATE creature_ai_texts SET content_default='代理更多的集团，我敢打赌！你不会收回它…或南岸！' WHERE entry=-924;
UPDATE creature_ai_texts SET content_default='该园现在贫瘠和生命为我腐烂的外壳。一旦这些树木开花，但现在只有腐烂。' WHERE entry=-925;
UPDATE creature_ai_texts SET content_default='我花了我的整个生命照顾这些树。修剪和培育他们…他们与我一起死亡。' WHERE entry=-926;
UPDATE creature_ai_texts SET content_default='入侵者！攻击入侵者！' WHERE entry=-927;
UPDATE creature_ai_texts SET content_default='用南海镇的血来还债！' WHERE entry=-928;
UPDATE creature_ai_texts SET content_default='复活！' WHERE entry=-929;
UPDATE creature_ai_texts SET content_default='复仇！' WHERE entry=-930;
UPDATE creature_ai_texts SET content_default='你灵魂不死的盛宴, $N.' WHERE entry=-931;
UPDATE creature_ai_texts SET content_default='帮帮我！救命啊！刺客在山上！武器！武器！' WHERE entry=-932;
UPDATE creature_ai_texts SET content_default='守卫你的职位！他必须被保护！他们可能来自任何地方！' WHERE entry=-933;
UPDATE creature_ai_texts SET content_default='%s 抓住他的脖子后面，他的眼睛睁大。' WHERE entry=-934;
UPDATE creature_ai_texts SET content_default='刺客…救…' WHERE entry=-935;
UPDATE creature_ai_texts SET content_default='你走开, $N.' WHERE entry=-936;
UPDATE creature_ai_texts SET content_default='向前走, $c.' WHERE entry=-937;
UPDATE creature_ai_texts SET content_default='不要逼它的公民！' WHERE entry=-938;
UPDATE creature_ai_texts SET content_default='不需要任何物资的巨魔？任何巨魔都会。' WHERE entry=-939;
UPDATE creature_ai_texts SET content_default='我不明白为什幺我们的盟友是肮脏的臭巨魔？唯一的好巨魔已经死了' WHERE entry=-940;
UPDATE creature_ai_texts SET content_default='如果我只有奶酪下酒…' WHERE entry=-941;
UPDATE creature_ai_texts SET content_default='为什幺不选择其他母亲奉献自己？蛋糕，糕点，面包-除了奶酪' WHERE entry=-942;
UPDATE creature_ai_texts SET content_default='哦，多幺可怕的工作！一天，包围的脚臭味。' WHERE entry=-943;
UPDATE creature_ai_texts SET content_default='是…这一切都是梦吗？简！简，你在哪里！' WHERE entry=-944;
UPDATE creature_ai_texts SET content_default='我就在这里，爸爸。你已经一天没睡了。你一定很累了！' WHERE entry=-945;
UPDATE creature_ai_texts SET content_default='啊，美妙。它只是一个梦…' WHERE entry=-946;
UPDATE creature_ai_texts SET content_default='疼痛……需要……我要更多…' WHERE entry=-947;
UPDATE creature_ai_texts SET content_default='这是什幺？我认识你时，我杀了他. 你必须这样 $n 每个人都害怕.' WHERE entry=-948;
UPDATE creature_ai_texts SET content_default='你别担心我，男孩。恰恰相反，我盼望杀死你和你的朋友。现在辛托加没有什幺可以阻止我！' WHERE entry=-949;
UPDATE creature_ai_texts SET content_default='可惜，现在你虽然掌握真理，但你是一个凡人。你不能打败我' WHERE entry=-950;
UPDATE creature_ai_texts SET content_default='你不过是外来入侵者。准备死！' WHERE entry=-951;
UPDATE creature_ai_texts SET content_default='什幺? HAR′KOA?' WHERE entry=-952;
UPDATE creature_ai_texts SET content_default='很好，小猫。你必然灭亡。我盼望与你交易，只要我完成这些！' WHERE entry=-953;
UPDATE creature_ai_texts SET content_default='不，我会杀了你！' WHERE entry=-954;
UPDATE creature_ai_texts SET content_default='先知！' WHERE entry=-955;
UPDATE creature_ai_texts SET content_default='你把你的脏手从他们身上挪开！' WHERE entry=-956;
UPDATE creature_ai_texts SET content_default='我想不。你会放弃你的免疫力，停止你的仪式现在释放他们！' WHERE entry=-957;
UPDATE creature_ai_texts SET content_default='谢谢。你又一次救了我们大家。我们辛托加再见。' WHERE entry=-958;
UPDATE creature_ai_texts SET content_default='入侵检测！威胁！' WHERE entry=-959;
UPDATE creature_ai_texts SET content_default='我喜欢闻虚空的早晨。' WHERE entry=-960;
UPDATE creature_ai_texts SET content_default='它闻起来像…' WHERE entry=-961;
UPDATE creature_ai_texts SET content_default='胜利。' WHERE entry=-962;
UPDATE creature_ai_texts SET content_default='今天看来是错误的一天…' WHERE entry=-963;
UPDATE creature_ai_texts SET content_default='我认为我为此而做！' WHERE entry=-10000;
UPDATE creature_ai_texts SET content_default='Of course I was the one Chosen to summon a demon for the competitors. I am Wilfred Fizzlebang, master summoner! Demons quail before the mere thought of being under my will!' WHERE entry=-10019;
UPDATE creature_ai_texts SET content_default='我欠你的，朋友。' WHERE entry=-10001;
UPDATE creature_ai_texts SET content_default='呃……' WHERE entry=-10002;
UPDATE creature_ai_texts SET content_default='有人射击，蝙蝠！' WHERE entry=-10003;
UPDATE creature_ai_texts SET content_default='It was awful.. I dreamt I was fighting against my friends' WHERE entry=-10005;
UPDATE creature_ai_texts SET content_default='终于结束了... 我可以休息了。' WHERE entry=-10006;
UPDATE creature_ai_texts SET content_default='I can''t hear the screams anymore. Is this the end?' WHERE entry=-10007;
UPDATE creature_ai_texts SET content_default='I''m so tired. Just let me rest for a moment' WHERE entry=-10008;
UPDATE creature_ai_texts SET content_default='我的噩梦，终于结束了吗？' WHERE entry=-10009;
UPDATE creature_ai_texts SET content_default='Your offering has come too late, little one. Can you feel the mist closing in upon you? The Kvaldir return...' WHERE entry=-10010;
UPDATE creature_ai_texts SET content_default='你没有逃生机会。十字军不得不杀死所有被亡灵天灾污染过的人。' WHERE entry=-10011;
UPDATE creature_ai_texts SET content_default='你被亡灵天灾污染过。准备进入扭曲虚空。' WHERE entry=-10012;
UPDATE creature_ai_texts SET content_default='圣光惩罚所有为恶魔效力的人。现在你就要死了！' WHERE entry=-10013;
UPDATE creature_ai_texts SET content_default='So the oracIe has decided to aid you, outlander. Very well, I will offer you what i know.' WHERE entry=-10014;
UPDATE creature_ai_texts SET content_default='Your companion seeks the shardhorn patriarch Farunn, who holds himself aloof from his brothers.' WHERE entry=-10015;
UPDATE creature_ai_texts SET content_default='Farunn walks the lands north of what your people call the Bittertide Falls. You will find him alone, but you will see her requires no defenders.' WHERE entry=-10016;
UPDATE creature_ai_texts SET content_default='Return to your companion. Tell him to go forth and claim his prize in Farunn.' WHERE entry=-10017;
UPDATE creature_ai_texts SET content_default='Once he has done so, tell him to leave this land in peace. He does not belong here.' WHERE entry=-10018;
UPDATE creature_ai_texts SET content_default='救命啊。我的眼睛！' WHERE entry=-10004;
UPDATE creature_ai_texts SET content_default='You''ve come for the doctor''s plans! You''ll only find death!' WHERE entry=-10020;
UPDATE creature_ai_texts SET content_default='The doctor entrusted me with the plans to Nergeld! I will not fall!' WHERE entry=-10021;
UPDATE creature_ai_texts SET content_default='相当好。我们必须集中我们的精力清洗纳格兰！' WHERE entry=-964;
UPDATE creature_ai_texts SET content_default='裂谷的力量是我们的！' WHERE entry=-965;
UPDATE creature_ai_texts SET content_default='核心过载检测。故障检测系统…' WHERE entry=-966;
UPDATE creature_ai_texts SET content_default='你不能杀... 我!' WHERE entry=-7033;
UPDATE creature_ai_texts SET content_default='我没有恐惧! 额...! 不要杀我!' WHERE entry=-7034;
UPDATE creature_ai_texts SET content_default='不要阻拦我! 不... 不要阻挡我。' WHERE entry=-7035;
UPDATE creature_ai_texts SET content_default='It''s been so long since a traveler has come here bearing flowers.' WHERE entry=-7012;
UPDATE creature_ai_texts SET content_default='The lake has been too lonely these past years. The travelers stopped coming and evil came to these waters.' WHERE entry=-7011;

