UPDATE areatrigger_teleport SET name='血色修道院西(墓地)副本起点' WHERE id=45;
UPDATE areatrigger_teleport SET name='死亡矿井(副本)A-西部荒野' WHERE id=78;
UPDATE areatrigger_teleport SET name='暴风城监狱-(副本)入口' WHERE id=101;
UPDATE areatrigger_teleport SET name='暴风城地窑' WHERE id=107;
UPDATE areatrigger_teleport SET name='暴风城地窑' WHERE id=109;
UPDATE areatrigger_teleport SET name='死亡矿井A门口-西部荒野' WHERE id=119;
UPDATE areatrigger_teleport SET name='死亡矿井B出口-西部荒野' WHERE id=121;
UPDATE areatrigger_teleport SET name='影牙城堡(副本)-银松森林' WHERE id=145;
UPDATE areatrigger_teleport SET name='影牙城堡 -入口' WHERE id=194;
UPDATE areatrigger_teleport SET name='哀嚎洞穴门口-贫瘠之地' WHERE id=226;
UPDATE areatrigger_teleport SET name='哀嚎洞穴(副本)-贫瘠之地' WHERE id=228;
UPDATE areatrigger_teleport SET name='剃刀沼泽门口-贫瘠之地' WHERE id=242;
UPDATE areatrigger_teleport SET name='剃刀沼泽(副本)-贫瘠之地' WHERE id=244;
UPDATE areatrigger_teleport SET name='黑暗深渊(副本)-灰谷' WHERE id=257;
UPDATE areatrigger_teleport SET name='黑暗深渊门口-灰谷' WHERE id=259;
UPDATE areatrigger_teleport SET name='奥达曼(副本)A-荒芜之地' WHERE id=286;
UPDATE areatrigger_teleport SET name='奥达曼门口' WHERE id=288;
UPDATE areatrigger_teleport SET name='诺莫瑞根门口A-丹莫罗' WHERE id=322;
UPDATE areatrigger_teleport SET name='诺莫瑞根(副本)A-丹莫罗' WHERE id=324;
UPDATE areatrigger_teleport SET name='剃刀高地(副本)-贫瘠之地' WHERE id=442;
UPDATE areatrigger_teleport SET name='剃刀高地门口-贫瘠之地' WHERE id=444;
UPDATE areatrigger_teleport SET name='阿塔哈卡神庙(副本)-悲伤沼泽' WHERE id=446;
UPDATE areatrigger_teleport SET name='阿塔哈卡神庙门口-悲伤沼泽' WHERE id=448;
UPDATE areatrigger_teleport SET name='暴风城监狱-门口' WHERE id=503;
UPDATE areatrigger_teleport SET name='诺莫瑞根(副本)B-丹莫罗' WHERE id=523;
UPDATE areatrigger_teleport SET name='诺莫瑞根门口B-丹莫罗' WHERE id=525;
UPDATE areatrigger_teleport SET name='泰达希尔-鲁瑟兰村' WHERE id=527;
UPDATE areatrigger_teleport SET name='泰达希尔-达纳苏斯' WHERE id=542;
UPDATE areatrigger_teleport SET name='血色修道院西(墓地)门口' WHERE id=602;
UPDATE areatrigger_teleport SET name='血色修道院西(大教堂)门口' WHERE id=604;
UPDATE areatrigger_teleport SET name='血色修道院东(军械库)门口' WHERE id=606;
UPDATE areatrigger_teleport SET name='血色修道院东(图书馆)门口' WHERE id=608;
UPDATE areatrigger_teleport SET name='血色修道院西(大教堂)副本起点' WHERE id=610;
UPDATE areatrigger_teleport SET name='血色修道院东(军械库)副本起点' WHERE id=612;
UPDATE areatrigger_teleport SET name='血色修道院东(图书馆)副本起点' WHERE id=614;
UPDATE areatrigger_teleport SET name='暴风城-巫师圣殿' WHERE id=702;
UPDATE areatrigger_teleport SET name='暴风城-巫师圣殿入口' WHERE id=704;
UPDATE areatrigger_teleport SET name='奥达曼门口B-荒芜之地' WHERE id=882;
UPDATE areatrigger_teleport SET name='奥达曼(副本)B-荒芜之地' WHERE id=902;
UPDATE areatrigger_teleport SET name='祖尔法拉克门口-塔纳利斯' WHERE id=922;
UPDATE areatrigger_teleport SET name='祖尔法拉克(副本)-塔纳利斯' WHERE id=924;
UPDATE areatrigger_teleport SET name='奥妮克希亚的巢穴门口-尘泥沼泽' WHERE id=1064;
UPDATE areatrigger_teleport SET name='黑石深渊(副本)-黑石山' WHERE id=1466;
UPDATE areatrigger_teleport SET name='黑石塔-灼热峡谷黑手大厅' WHERE id=1468;
UPDATE areatrigger_teleport SET name='黑石塔-灼热峡谷熔岩之桥' WHERE id=1470;
UPDATE areatrigger_teleport SET name='黑石深渊门口-黑石山' WHERE id=1472;
UPDATE areatrigger_teleport SET name='矿道地铁-铁炉堡' WHERE id=2166;
UPDATE areatrigger_teleport SET name='矿道地铁-暴风城' WHERE id=2171;
UPDATE areatrigger_teleport SET name='矿道地铁-暴风城' WHERE id=2173;
UPDATE areatrigger_teleport SET name='矿道地铁-铁炉堡' WHERE id=2175;
UPDATE areatrigger_teleport SET name='斯坦索姆(副本)B-东瘟疫之地' WHERE id=2214;
UPDATE areatrigger_teleport SET name='斯坦索姆-东瘟疫之地出口A2' WHERE id=2216;
UPDATE areatrigger_teleport SET name='斯坦索姆-东瘟疫之地出口A1' WHERE id=2217;
UPDATE areatrigger_teleport SET name='斯坦索姆门口B-东瘟疫之地' WHERE id=2221;
UPDATE areatrigger_teleport SET name='怒焰裂谷门口-奥格瑞玛' WHERE id=2226;
UPDATE areatrigger_teleport SET name='怒焰裂谷(副本)-奥格瑞玛' WHERE id=2230;
UPDATE areatrigger_teleport SET name='俄特加德要塞- 出口' WHERE id=4743;
UPDATE areatrigger_teleport SET name='奥格瑞玛-(勇者大厅)入口' WHERE id=2530;
UPDATE areatrigger_teleport SET name='暴风城-(勇士大厅)入口' WHERE id=2534;
UPDATE areatrigger_teleport SET name='通灵学院(副本)-西瘟疫之地' WHERE id=2567;
UPDATE areatrigger_teleport SET name='通灵学院门口-西瘟疫之地' WHERE id=2568;
UPDATE areatrigger_teleport SET name='PVP1奥托兰克山谷-部落入口' WHERE id=2606;
UPDATE areatrigger_teleport SET name='PVP1奥托兰克山谷-联盟入口' WHERE id=2608;
UPDATE areatrigger_teleport SET name='奥妮克希亚的巢穴(副本)-尘泥沼泽' WHERE id=2848;
UPDATE areatrigger_teleport SET name='熔火之桥' WHERE id=2886;
UPDATE areatrigger_teleport SET name='熔火之心 - 入口, 里面' WHERE id=2890;
UPDATE areatrigger_teleport SET name='迈拉顿门口B-凄凉之地' WHERE id=3126;
UPDATE areatrigger_teleport SET name='迈拉顿门口A-凄凉之地' WHERE id=3131;
UPDATE areatrigger_teleport SET name='迈拉顿(副本)A-凄凉之地' WHERE id=3133;
UPDATE areatrigger_teleport SET name='迈拉顿(副本)B-凄凉之地' WHERE id=3134;
UPDATE areatrigger_teleport SET name='厄运之槌东A(副本)-菲拉斯' WHERE id=3183;
UPDATE areatrigger_teleport SET name='厄运之槌东B(副本)-菲拉斯' WHERE id=3184;
UPDATE areatrigger_teleport SET name='厄运之槌东C(副本)-菲拉斯' WHERE id=3185;
UPDATE areatrigger_teleport SET name='厄运之槌西B(副本)-菲拉斯' WHERE id=3186;
UPDATE areatrigger_teleport SET name='厄运之槌西A(副本)-菲拉斯' WHERE id=3187;
UPDATE areatrigger_teleport SET name='厄运之槌北(副本)-菲拉斯' WHERE id=3189;
UPDATE areatrigger_teleport SET name='厄运之槌西B门口-菲拉斯' WHERE id=3190;
UPDATE areatrigger_teleport SET name='厄运之槌西A门口-菲拉斯' WHERE id=3191;
UPDATE areatrigger_teleport SET name='厄运之槌北门口-菲拉斯' WHERE id=3193;
UPDATE areatrigger_teleport SET name='厄运之槌东A门口-菲拉斯' WHERE id=3194;
UPDATE areatrigger_teleport SET name='厄运之槌东B门口-菲拉斯' WHERE id=3195;
UPDATE areatrigger_teleport SET name='厄运之槌东C门口-菲拉斯' WHERE id=3196;
UPDATE areatrigger_teleport SET name='厄运之槌东D门口-菲拉斯' WHERE id=3197;
UPDATE areatrigger_teleport SET name='熔火之心之窗 (熔岩) 入口' WHERE id=3529;
UPDATE areatrigger_teleport SET name='黑翼之巢入口-灼热峡谷-燃烧平原-东部王国' WHERE id=3726;
UPDATE areatrigger_teleport SET name='黑翼之巢出口-黑石山-东部王国' WHERE id=3728;
UPDATE areatrigger_teleport SET name='祖尔格拉布(副本)-荆棘谷' WHERE id=3928;
UPDATE areatrigger_teleport SET name='祖尔格拉布门口-荆棘谷' WHERE id=3930;
UPDATE areatrigger_teleport SET name='PVP4阿拉希盆地联盟出口' WHERE id=3948;
UPDATE areatrigger_teleport SET name='PVP4落锤镇部落入口' WHERE id=3949;
UPDATE areatrigger_teleport SET name='熔火之心之窗 入口' WHERE id=3528;
UPDATE areatrigger_teleport SET name='安其拉废墟门口-希利苏斯' WHERE id=4006;
UPDATE areatrigger_teleport SET name='安其拉废墟(副本)-希利苏斯' WHERE id=4008;
UPDATE areatrigger_teleport SET name='安其拉神殿(副本)-希利苏斯' WHERE id=4010;
UPDATE areatrigger_teleport SET name='安其拉神殿门口-希利苏斯' WHERE id=4012;
UPDATE areatrigger_teleport SET name='俄特加德要塞- 入口' WHERE id=4745;
UPDATE areatrigger_teleport SET name='卡拉赞门楼(入口处)' WHERE id=4131;
UPDATE areatrigger_teleport SET name='碎裂大厅出口' WHERE id=4145;
UPDATE areatrigger_teleport SET name='蒸汽洞窟出口' WHERE id=4147;
UPDATE areatrigger_teleport SET name='玛瑟里顿的巢穴出口' WHERE id=4149;
UPDATE areatrigger_teleport SET name='地狱火壁垒' WHERE id=4150;
UPDATE areatrigger_teleport SET name='破碎大厅' WHERE id=4151;
UPDATE areatrigger_teleport SET name='蒸汽洞窟' WHERE id=4152;
UPDATE areatrigger_teleport SET name='玛瑟里顿的巢穴' WHERE id=4153;
UPDATE areatrigger_teleport SET name='纳克萨玛斯(副本出口)' WHERE id=4156;
UPDATE areatrigger_teleport SET name='地狱火壁垒出口' WHERE id=4297;
UPDATE areatrigger_teleport SET name='到海家尔人类营地之门' WHERE id=4311;
UPDATE areatrigger_teleport SET name='从海家尔到部落营地之门' WHERE id=4312;
UPDATE areatrigger_teleport SET name='从海家尔到暗夜精灵村庄生命之树之门' WHERE id=4313;
UPDATE areatrigger_teleport SET name='海家尔山峰入口' WHERE id=4319;
UPDATE areatrigger_teleport SET name='黑色沼泽出口' WHERE id=4320;
UPDATE areatrigger_teleport SET name='时光之穴出口' WHERE id=4321;
UPDATE areatrigger_teleport SET name='黑色沼泽出口' WHERE id=4322;
UPDATE areatrigger_teleport SET name='从海家尔到CoT 主门' WHERE id=4323;
UPDATE areatrigger_teleport SET name='时光之穴入口' WHERE id=4324;
UPDATE areatrigger_teleport SET name='外域到黑暗之门' WHERE id=4352;
UPDATE areatrigger_teleport SET name='黑暗之门到外域' WHERE id=4354;
UPDATE areatrigger_teleport SET name='沼泽洞穴入口' WHERE id=4363;
UPDATE areatrigger_teleport SET name='蒸汽洞窟入口' WHERE id=4364;
UPDATE areatrigger_teleport SET name='奴隶围栏入口' WHERE id=4365;
UPDATE areatrigger_teleport SET name='蒸汽洞窟出口' WHERE id=4366;
UPDATE areatrigger_teleport SET name='沼泽洞穴出口' WHERE id=4367;
UPDATE areatrigger_teleport SET name='奴隶围栏出口' WHERE id=4379;
UPDATE areatrigger_teleport SET name='逐日岛到东瘟疫之地' WHERE id=4386;
UPDATE areatrigger_teleport SET name='暗影迷宫出口' WHERE id=4397;
UPDATE areatrigger_teleport SET name='塞泰克大厅出口' WHERE id=4399;
UPDATE areatrigger_teleport SET name='法力坟墓出口' WHERE id=4401;
UPDATE areatrigger_teleport SET name='奥金顿墓穴出口' WHERE id=4403;
UPDATE areatrigger_teleport SET name='奥金顿墓穴入口' WHERE id=4404;
UPDATE areatrigger_teleport SET name='法力坟墓入口' WHERE id=4405;
UPDATE areatrigger_teleport SET name='塞泰克大厅入口' WHERE id=4406;
UPDATE areatrigger_teleport SET name='暗影迷宫入口' WHERE id=4407;
UPDATE areatrigger_teleport SET name='东瘟疫之地到逐日岛' WHERE id=4409;
UPDATE areatrigger_teleport SET name='盘牙洞穴入口' WHERE id=4416;
UPDATE areatrigger_teleport SET name='卡拉赞门房 (出口)' WHERE id=4436;
UPDATE areatrigger_teleport SET name='拱廊区出口' WHERE id=4455;
UPDATE areatrigger_teleport SET name='凤凰大厅出口' WHERE id=4457;
UPDATE areatrigger_teleport SET name='秘术区出口' WHERE id=4459;
UPDATE areatrigger_teleport SET name='机械区出口' WHERE id=4461;
UPDATE areatrigger_teleport SET name='秘术区入口' WHERE id=4467;
UPDATE areatrigger_teleport SET name='拱廊区入口' WHERE id=4468;
UPDATE areatrigger_teleport SET name='机械区入口' WHERE id=4469;
UPDATE areatrigger_teleport SET name='凤凰大厅入口' WHERE id=4470;
UPDATE areatrigger_teleport SET name='海家尔峰出口' WHERE id=4487;
UPDATE areatrigger_teleport SET name='格鲁尔巢穴出口' WHERE id=4534;
UPDATE areatrigger_teleport SET name='格鲁尔巢穴入口' WHERE id=4535;
UPDATE areatrigger_teleport SET name='黑暗神庙' WHERE id=4598;
UPDATE areatrigger_teleport SET name='黑暗神庙出口' WHERE id=4619;
UPDATE areatrigger_teleport SET name='盘牙洞穴出口' WHERE id=4418;
UPDATE areatrigger_teleport SET name='索克雷萨出口' WHERE id=4523;
UPDATE areatrigger_teleport SET name='祖阿曼入口' WHERE id=4738;
UPDATE areatrigger_teleport SET name='祖阿曼出口' WHERE id=4739;
UPDATE areatrigger_teleport SET name='信仰的飞跃 - 秋季结束' WHERE id=943;
UPDATE areatrigger_teleport SET name='侵略点:灾难 (回归)' WHERE id=4561;
UPDATE areatrigger_teleport SET name='侵略点:灾难 (回归)' WHERE id=4562;
UPDATE areatrigger_teleport SET name='卡拉赞上层' WHERE id=4135;
UPDATE areatrigger_teleport SET name='魔班主任平台出口' WHERE id=4885;
UPDATE areatrigger_teleport SET name='魔班主任平台入口' WHERE id=4887;
UPDATE areatrigger_teleport SET name='太阳之井高地入口' WHERE id=4889;
UPDATE areatrigger_teleport SET name='太阳之井高地出口' WHERE id=4891;
UPDATE areatrigger_teleport SET name='俄特加德要塞- 出口' WHERE id=4747;
UPDATE areatrigger_teleport SET name='俄特加德要塞- 出口' WHERE id=4741;
UPDATE areatrigger_teleport SET name='奈萨斯 70 入口' WHERE id=4983;
UPDATE areatrigger_teleport SET name='奈萨斯 70 出口' WHERE id=4981;
UPDATE areatrigger_teleport SET name='永恒之眼 - 入口' WHERE id=5246;
UPDATE areatrigger_teleport SET name='纳克萨玛斯 - 入口 4' WHERE id=5191;
UPDATE areatrigger_teleport SET name='纳克萨玛斯 - 入口 2' WHERE id=5192;
UPDATE areatrigger_teleport SET name='纳克萨玛斯 - 入口 3' WHERE id=5193;
UPDATE areatrigger_teleport SET name='纳克萨玛斯 - 入口 1' WHERE id=5194;
UPDATE areatrigger_teleport SET name='纳克萨玛斯 - 出口 4' WHERE id=5196;
UPDATE areatrigger_teleport SET name='纳克萨玛斯 - 出口 2' WHERE id=5197;
UPDATE areatrigger_teleport SET name='纳克萨玛斯 - 出口 3' WHERE id=5198;
UPDATE areatrigger_teleport SET name='纳克萨玛斯 - 出口 1' WHERE id=5199;
UPDATE areatrigger_teleport SET name='往事启动 入口' WHERE id=5150;
UPDATE areatrigger_teleport SET name='斯坦索姆的抉择 (出口)' WHERE id=5181;
UPDATE areatrigger_teleport SET name='紫罗兰堡 - 入口' WHERE id=5209;
UPDATE areatrigger_teleport SET name='紫罗兰堡 - 出口' WHERE id=5211;
UPDATE areatrigger_teleport SET name='刚德拉克 - 入口' WHERE id=5206;
UPDATE areatrigger_teleport SET name='刚德拉克 - 入口' WHERE id=5205;
UPDATE areatrigger_teleport SET name='刚德拉克 - 出口 04' WHERE id=5277;
UPDATE areatrigger_teleport SET name='刚德拉克 - 出口 02' WHERE id=5231;
UPDATE areatrigger_teleport SET name='雷光大厅 - 入口' WHERE id=5093;
UPDATE areatrigger_teleport SET name='雷光大厅 - 出口' WHERE id=5091;
UPDATE areatrigger_teleport SET name='奥杜亚, 石之大厅 (入口)' WHERE id=5010;
UPDATE areatrigger_teleport SET name='石之大厅 - 出口' WHERE id=5012;
UPDATE areatrigger_teleport SET name='阿兹欧-奈幽 (入口)' WHERE id=5117;
UPDATE areatrigger_teleport SET name='阿兹欧-奈幽 (出口)' WHERE id=5115;
UPDATE areatrigger_teleport SET name='阿兹欧-奈幽 - 出口?' WHERE id=5113;
UPDATE areatrigger_teleport SET name='阿兹欧-奈幽: 安卡罕特:古王国 - 入口' WHERE id=5215;
UPDATE areatrigger_teleport SET name='古王国 - 出口' WHERE id=5213;
UPDATE areatrigger_teleport SET name='守护巨龙之间, 黑曜圣所 (入口)' WHERE id=5243;
UPDATE areatrigger_teleport SET name='守护巨龙之间, 黑曜圣所 (出口)' WHERE id=5241;
UPDATE areatrigger_teleport SET name='德拉克萨隆 入口' WHERE id=4998;
UPDATE areatrigger_teleport SET name='德拉克萨隆 出口' WHERE id=5000;
UPDATE areatrigger_teleport SET name='永恒之眼 (入口)' WHERE id=5290;
UPDATE areatrigger_teleport SET name='奥核之眼 - 出口' WHERE id=5001;
UPDATE areatrigger_teleport SET name='卡拉赞, 广场 (出口)' WHERE id=4520;
UPDATE areatrigger_teleport SET name='奥杜亚团队 入口' WHERE id=5379;
UPDATE areatrigger_teleport SET name='奥杜亚团队 出口' WHERE id=5381;
UPDATE areatrigger_teleport SET name='亚夏梵穹殿 (出口)' WHERE id=5262;
UPDATE areatrigger_teleport SET name='亚夏梵穹殿 (入口)' WHERE id=5258;
UPDATE areatrigger_teleport SET name='达拉然水井' WHERE id=5273;
UPDATE areatrigger_teleport SET name='十字军试炼 (出口)' WHERE id=5508;
UPDATE areatrigger_teleport SET name='十字军试炼 (入口)' WHERE id=5503;
UPDATE areatrigger_teleport SET name='勇士试炼 (入口)' WHERE id=5505;
UPDATE areatrigger_teleport SET name='勇士试炼 (出口)' WHERE id=5510;
UPDATE areatrigger_teleport SET name='寒冰皇冠城塞 (入口)' WHERE id=5670;
UPDATE areatrigger_teleport SET name='寒冰皇冠城塞 (出口)' WHERE id=5668;
UPDATE areatrigger_teleport SET name='众魂熔炉 (入口)' WHERE id=5635;
UPDATE areatrigger_teleport SET name='倒影大厅 (入口)' WHERE id=5636;
UPDATE areatrigger_teleport SET name='萨伦之渊 (入口)' WHERE id=5637;
UPDATE areatrigger_teleport SET name='众魂熔炉 (出口)' WHERE id=5642;
UPDATE areatrigger_teleport SET name='萨伦之渊 (出口)' WHERE id=5643;
UPDATE areatrigger_teleport SET name='倒影大厅 (出口)' WHERE id=5646;
UPDATE areatrigger_teleport SET name='萨伦之渊 (出口) 倒影大厅 (入口)' WHERE id=5683;
UPDATE areatrigger_teleport SET name='众魂熔炉 (出口) 萨伦之渊 (入口)' WHERE id=5688;
UPDATE areatrigger_teleport SET name='q12710:1楼' WHERE id=5051;
UPDATE areatrigger_teleport SET name='q12710: 2楼' WHERE id=5079;
UPDATE areatrigger_teleport SET name='晶红圣殿 (入口)' WHERE id=5869;
UPDATE areatrigger_teleport SET name='晶红圣殿 (出口)' WHERE id=5872;
UPDATE areatrigger_teleport SET name='刚德拉克 - 出口 03' WHERE id=5276;
UPDATE areatrigger_teleport SET name='刚德拉克 - 出口 01' WHERE id=5233;
UPDATE areatrigger_teleport SET name='域门【环形山至盆地】' WHERE id=5046;
UPDATE areatrigger_teleport SET name='域门【盆地至环形山】' WHERE id=5047;

