UPDATE creature_ai_texts SET content_default='我看到修道院的那帮笨蛋给我们送来新鲜的肉了。 ' WHERE entry=-1;
UPDATE creature_ai_texts SET content_default='兄弟会不能容忍你的行为。 ' WHERE entry=-2;
UPDATE creature_ai_texts SET content_default='啊！一个使用这把崭新的锐利之刃的机会。 ' WHERE entry=-3;
UPDATE creature_ai_texts SET content_default='感受兄弟会的力量吧！ ' WHERE entry=-4;
UPDATE creature_ai_texts SET content_default='有更多的骨头可以啃啦……！ ' WHERE entry=-5;
UPDATE creature_ai_texts SET content_default='啊啊啊……新鲜的肉！！ ' WHERE entry=-6;
UPDATE creature_ai_texts SET content_default='你休想拿走我的蜡烛! ' WHERE entry=-7;
UPDATE creature_ai_texts SET content_default='哎呀! 我得逃跑!. ' WHERE entry=-8;
UPDATE creature_ai_texts SET content_default='为了胜利！为阿迦玛甘！ ' WHERE entry=-18;
UPDATE creature_ai_texts SET content_default='范克里夫会为你的脑袋出个好价钱的! ' WHERE entry=-22;
UPDATE creature_ai_texts SET content_default='你不属于这里 ！古人，攻打这些入侵者 ！ ' WHERE entry=-28;
UPDATE creature_ai_texts SET content_default='你没资格挑战我！我将永远为王！ ' WHERE entry=-29;
UPDATE creature_ai_texts SET content_default='%s的血喷入空气！ ' WHERE entry=-30;
UPDATE creature_ai_texts SET content_default='%s血溅成河！ ' WHERE entry=-31;
UPDATE creature_ai_texts SET content_default='电动正义！ ' WHERE entry=-32;
UPDATE creature_ai_texts SET content_default='警告！警告！入侵者警报！入侵者警报！ ' WHERE entry=-33;
UPDATE creature_ai_texts SET content_default='加入我们吧， $C。 ' WHERE entry=-42;
UPDATE creature_ai_texts SET content_default='愤怒吧 ' WHERE entry=-46;
UPDATE creature_ai_texts SET content_default='%s恐惧的想要逃走！ ' WHERE entry=-47;
UPDATE creature_ai_texts SET content_default='好黑... ' WHERE entry=-73;
UPDATE creature_ai_texts SET content_default='啊啊啊! 差一点就跑掉了. ' WHERE entry=-74;
UPDATE creature_ai_texts SET content_default='你不能唤醒沉睡者! ' WHERE entry=-99;
UPDATE creature_ai_texts SET content_default='%s发出了高声的尖叫，寻求帮助! ' WHERE entry=-100;
UPDATE creature_ai_texts SET content_default='为了龙喉！ ' WHERE entry=-101;
UPDATE creature_ai_texts SET content_default='龙喉万岁！你的死毫无价值 $R! ' WHERE entry=-102;
UPDATE creature_ai_texts SET content_default='脑子…… ' WHERE entry=-103;
UPDATE creature_ai_texts SET content_default='这片土地属于黑铁矮人。准备看来世， $C! ' WHERE entry=-104;
UPDATE creature_ai_texts SET content_default='你将会被我踩在脚下，$R! ' WHERE entry=-105;
UPDATE creature_ai_texts SET content_default='%s进入狂暴! ' WHERE entry=-106;
UPDATE creature_ai_texts SET content_default='我是毒蛇之王!我无所不能! ' WHERE entry=-123;
UPDATE creature_ai_texts SET content_default='麻烦的小龙。我会教你干涉！ ' WHERE entry=-133;
UPDATE creature_ai_texts SET content_default='我们的新盟友将为我们报仇！ ' WHERE entry=-134;
UPDATE creature_ai_texts SET content_default='你会为侵占我们的土地付出代价！ ' WHERE entry=-135;
UPDATE creature_ai_texts SET content_default='呸！这是我的规则！ ' WHERE entry=-136;
UPDATE creature_ai_texts SET content_default='我会重生，凡人！ 主人会让我从这些灰烬中复活！ ' WHERE entry=-137;
UPDATE creature_ai_texts SET content_default='死亡的力量会彻底摧毁你! ' WHERE entry=-140;
UPDATE creature_ai_texts SET content_default='在巨大的悲痛中，亚米萨兰的恐怖笼罩了大地，生存的希望淼小。 ' WHERE entry=-142;
UPDATE creature_ai_texts SET content_default='主人来到我们身边，他用法术保护我们不受伤害。 ' WHERE entry=-143;
UPDATE creature_ai_texts SET content_default='当晃动停止，显露了他的真实动机。我们被困，他慢慢地耗尽我们的力量。 ' WHERE entry=-144;
UPDATE creature_ai_texts SET content_default='哇喔!谢啦! ' WHERE entry=-148;
UPDATE creature_ai_texts SET content_default='$r...很快会像我一样的死去。 ' WHERE entry=-161;
UPDATE creature_ai_texts SET content_default='嗯……我喜欢南海镇的美酒。 ' WHERE entry=-162;
UPDATE creature_ai_texts SET content_default='杀了他们，我的兄弟!为了天灾军团! ' WHERE entry=-163;
UPDATE creature_ai_texts SET content_default='我们统治整个贫瘠之地！ ' WHERE entry=-164;
UPDATE creature_ai_texts SET content_default='我们将奴役野猪人！ ' WHERE entry=-165;
UPDATE creature_ai_texts SET content_default='很快，天灾军团就会统治世界！ ' WHERE entry=-166;
UPDATE creature_ai_texts SET content_default='杀!!! ' WHERE entry=-167;
UPDATE creature_ai_texts SET content_default='谁敢打扰我?去死吧， $N! ' WHERE entry=-168;
UPDATE creature_ai_texts SET content_default='没有人能与兄弟会抗衡! ' WHERE entry=-169;
UPDATE creature_ai_texts SET content_default='受死吧! ' WHERE entry=-170;
UPDATE creature_ai_texts SET content_default='你们都只是会摇尾巴的小狗! ' WHERE entry=-171;
UPDATE creature_ai_texts SET content_default='笨蛋!我们的理想是正当的! ' WHERE entry=-172;
UPDATE creature_ai_texts SET content_default='兄弟会必将获得最终的胜利! ' WHERE entry=-173;
UPDATE creature_ai_texts SET content_default=' 你不能拿走我的蜡烛！  ' WHERE entry=-174;
UPDATE creature_ai_texts SET content_default='You land lovers are tougher then I thought! I will need to improvise ' WHERE entry=-175;
UPDATE creature_ai_texts SET content_default='$N!你现在让我很生气! ' WHERE entry=-176;
UPDATE creature_ai_texts SET content_default='我要把你的皮当作便服来穿!长靴呢?你得将它们从那儿撬下来!!!! ' WHERE entry=-177;
UPDATE creature_ai_texts SET content_default='寻找这些吗？？？你不会有时间？！ ' WHERE entry=-178;
UPDATE creature_ai_texts SET content_default='我的!我的!我的!吉兹洛克是这片领域的统治者!你绝对不能泄漏我的行踪! ' WHERE entry=-182;
UPDATE creature_ai_texts SET content_default='什麽?哦，好吧，我不在乎你说什麽。我只是喜欢虐待你。 ' WHERE entry=-183;
UPDATE creature_ai_texts SET content_default='你终究是要说的，还不如现在就说了。 ' WHERE entry=-184;
UPDATE creature_ai_texts SET content_default='坦白交待了，我们就放你走。 ' WHERE entry=-185;
UPDATE creature_ai_texts SET content_default='这儿有活人! ' WHERE entry=-186;
UPDATE creature_ai_texts SET content_default='USURPERS!!! GNOMEREGAN IS MINE!!! ' WHERE entry=-188;
UPDATE creature_ai_texts SET content_default='My machines are the future! They’ll destroy you all! ' WHERE entry=-189;
UPDATE creature_ai_texts SET content_default='Explosions! MORE explosions! I’ve got to have more explosions! ' WHERE entry=-190;
UPDATE creature_ai_texts SET content_default='...and stay dead! He got served! ' WHERE entry=-191;
UPDATE creature_ai_texts SET content_default='它可以在这里非常热的荒地。但至少这是一个干热。 ' WHERE entry=-192;
UPDATE creature_ai_texts SET content_default='小玩意儿 ...检查。 Doothingies ...检查。 Wizzers ...检查。 ' WHERE entry=-193;
UPDATE creature_ai_texts SET content_default='总有一天我要成为一个真正的男孩。 ' WHERE entry=-194;
UPDATE creature_ai_texts SET content_default='啪嗒……咔咔…… ' WHERE entry=-195;
UPDATE creature_ai_texts SET content_default='主人，这里很危险。但我要去帮你站岗放哨。 ' WHERE entry=-196;
UPDATE creature_ai_texts SET content_default='我们能让它变得更好，更强，更快。我们不仅拥有技术，而且拥有强大的魔法。 ' WHERE entry=-197;
UPDATE creature_ai_texts SET content_default='你们不该来这里!杀了他们! ' WHERE entry=-198;
UPDATE creature_ai_texts SET content_default='你会很容易被捕食，$C. ' WHERE entry=-200;
UPDATE creature_ai_texts SET content_default='我的魔爪会切碎泥弱小的身躯，$R。 ' WHERE entry=-201;
UPDATE creature_ai_texts SET content_default='你的头会是一个很好的战利品，$R。 ' WHERE entry=-202;
UPDATE creature_ai_texts SET content_default='不!!! 把它放在篮子下面或者吃一槌子！ ' WHERE entry=-203;
UPDATE creature_ai_texts SET content_default='新鲜的面包啦! ' WHERE entry=-204;
UPDATE creature_ai_texts SET content_default='新鲜出炉的面包! ' WHERE entry=-205;
UPDATE creature_ai_texts SET content_default='擦亮你的装甲？ ' WHERE entry=-206;
UPDATE creature_ai_texts SET content_default='帮助一个贫穷的家伙呢？ ' WHERE entry=-207;
UPDATE creature_ai_texts SET content_default='一些硬币吗？ ' WHERE entry=-208;
UPDATE creature_ai_texts SET content_default='我有一个特别的消息要交给一个名叫 $N 的家伙。那就是:你死定了! ' WHERE entry=-209;
UPDATE creature_ai_texts SET content_default='让我送你一程吧，没用的 $C!你可以准备后事了! ' WHERE entry=-210;
UPDATE creature_ai_texts SET content_default='为艾德温·范克里夫而战! ' WHERE entry=-211;
UPDATE creature_ai_texts SET content_default='啊啊啊! ' WHERE entry=-212;
UPDATE creature_ai_texts SET content_default='粉碎! ' WHERE entry=-213;
UPDATE creature_ai_texts SET content_default='杀死! ' WHERE entry=-214;
UPDATE creature_ai_texts SET content_default='摧毁! ' WHERE entry=-215;
UPDATE creature_ai_texts SET content_default='我会让你成为魔咒! ' WHERE entry=-228;
UPDATE creature_ai_texts SET content_default='杀你很容易. ' WHERE entry=-229;
UPDATE creature_ai_texts SET content_default='你将要死了! ' WHERE entry=-230;
UPDATE creature_ai_texts SET content_default='我将消灭你! ' WHERE entry=-231;
UPDATE creature_ai_texts SET content_default='The Brotherhood will not be hampered by insects. ' WHERE entry=-232;
UPDATE creature_ai_texts SET content_default='事情太多，时间太少! ' WHERE entry=-233;
UPDATE creature_ai_texts SET content_default='%s 看起来很弱足以捕捉。 ' WHERE entry=-274;
UPDATE creature_ai_texts SET content_default='这比上一个好一点。不管怎幺说，它像其它的一样受制于脆弱骨头结构。当你召唤其中的一个，你就走上了正确的道路。 ' WHERE entry=-311;
UPDATE creature_ai_texts SET content_default='沙漠会将你吞噬! ' WHERE entry=-320;
UPDATE creature_ai_texts SET content_default='Iman m t’ief fu Fus’obeah italaf ' WHERE entry=-321;
UPDATE creature_ai_texts SET content_default='Dim wha Siame cyaa fi so yudo ' WHERE entry=-322;
UPDATE creature_ai_texts SET content_default='So ju weh siame is fus nehjo skam worl Uptfeel ' WHERE entry=-323;
UPDATE creature_ai_texts SET content_default='是猛攻的时后了! ' WHERE entry=-324;
UPDATE creature_ai_texts SET content_default='%s从阴影中跳了出来! ' WHERE entry=-341;
UPDATE creature_ai_texts SET content_default='%s从阴影中叫出了更多的同伴。 ' WHERE entry=-342;
UPDATE creature_ai_texts SET content_default='让我帮帮你吧。 ' WHERE entry=-343;
UPDATE creature_ai_texts SET content_default='把这个喝了，它对你有好处。 ' WHERE entry=-344;
UPDATE creature_ai_texts SET content_default='你会好起来的。 ' WHERE entry=-345;
UPDATE creature_ai_texts SET content_default='%s开始呼唤增援! ' WHERE entry=-346;
UPDATE creature_ai_texts SET content_default='我没从$c跑掉，和你一样! ' WHERE entry=-353;
UPDATE creature_ai_texts SET content_default='嘢！我杀！ ' WHERE entry=-354;
UPDATE creature_ai_texts SET content_default='最好的 $R 就是死掉的 $R! ' WHERE entry=-355;
UPDATE creature_ai_texts SET content_default='没用的 $C!你无法对抗碎石怪部族! ' WHERE entry=-356;
UPDATE creature_ai_texts SET content_default='感觉一下黑铁矮人的力量! ' WHERE entry=-357;
UPDATE creature_ai_texts SET content_default='是时后解决你了，$C! ' WHERE entry=-358;
UPDATE creature_ai_texts SET content_default='我会粉碎你! ' WHERE entry=-359;
UPDATE creature_ai_texts SET content_default='我们将粉碎你！你就要死了！ ' WHERE entry=-360;
UPDATE creature_ai_texts SET content_default='啊啊啊r!!!我们撕碎 $R! ' WHERE entry=-361;
UPDATE creature_ai_texts SET content_default='麦格尼·铜须是个白痴而且还是个骗子! ' WHERE entry=-362;
UPDATE creature_ai_texts SET content_default='巨石水坝将会被摧毁!拉格纳罗斯万岁! ' WHERE entry=-363;
UPDATE creature_ai_texts SET content_default='哇哈哈! 你像我一样倒下了! ' WHERE entry=-364;
UPDATE creature_ai_texts SET content_default='我听厌了这些废话!准备受死吧! ' WHERE entry=-365;
UPDATE creature_ai_texts SET content_default='啊啊啊! ' WHERE entry=-366;
UPDATE creature_ai_texts SET content_default='嗯? 那是什麽? ' WHERE entry=-367;
UPDATE creature_ai_texts SET content_default='这个 $R 看起来很好吃! ' WHERE entry=-368;
UPDATE creature_ai_texts SET content_default='扁它! ' WHERE entry=-369;
UPDATE creature_ai_texts SET content_default='一个叫做$C 的 $N?你应该是一顿不错的早餐! ' WHERE entry=-370;
UPDATE creature_ai_texts SET content_default='死吧 $R! 这块土地属于碎石穴居部落! ' WHERE entry=-371;
UPDATE creature_ai_texts SET content_default='这个湖现在属于碎石穴居部落，$N! 死吧! ' WHERE entry=-372;
UPDATE creature_ai_texts SET content_default='以拉格纳罗斯之名，去死吧! ' WHERE entry=-373;
UPDATE creature_ai_texts SET content_default='[矮人语] Dum mos ' WHERE entry=-374;
UPDATE creature_ai_texts SET content_default='%s的眼睛变得通红，一边狂笑一边点燃了火药! ' WHERE entry=-375;
UPDATE creature_ai_texts SET content_default='[兽人语] Ogg kaz ko zugas kil mog Tov’nokaz Kagg ' WHERE entry=-376;
UPDATE creature_ai_texts SET content_default='[兽人语] Tago mog regas gi mog Tov’nokaz Kagg ' WHERE entry=-377;
UPDATE creature_ai_texts SET content_default='不值一提! ' WHERE entry=-388;
UPDATE creature_ai_texts SET content_default='我不能让你进入圣殿！我要摧毁你的货物！ ' WHERE entry=-404;
UPDATE creature_ai_texts SET content_default='%s看起来已经平静不少了。现在他已经吃下了$N的残骸 ' WHERE entry=-405;
UPDATE creature_ai_texts SET content_default='不要放过一个黑铁，$C. ' WHERE entry=-406;
UPDATE creature_ai_texts SET content_default='我会放干你的血，$C! ' WHERE entry=-407;
UPDATE creature_ai_texts SET content_default='有人想休息一下？太糟糕了！必须接着工作！ ' WHERE entry=-408;
UPDATE creature_ai_texts SET content_default='向下移动这部分，让它靠近船！ ' WHERE entry=-409;
UPDATE creature_ai_texts SET content_default='嗯，这一个看起来也就比风铃好一些。做好记录同学们……这不是在战斗激烈的时候你们想要召唤的东西。 ' WHERE entry=-410;
UPDATE creature_ai_texts SET content_default='今天的汉堡我会很高兴地在星期二那天付钱给你。 ' WHERE entry=-411;
UPDATE creature_ai_texts SET content_default='给我这个可怜的瞎子一点零钱吧?……你说我不是瞎子是什麽意思?……我真的不瞎了!我看的见了!!这真是一个奇迹! ' WHERE entry=-412;
UPDATE creature_ai_texts SET content_default='这都是他们的错，愚蠢的联盟军队。刚在我的农场后面建立自己的水塔。 ' WHERE entry=-413;
UPDATE creature_ai_texts SET content_default='如果被上尉发现，我就死定了。 ' WHERE entry=-414;
UPDATE creature_ai_texts SET content_default='他们一定是得到了某些人的帮助。 ' WHERE entry=-415;
UPDATE creature_ai_texts SET content_default='突然之间，到处都是那帮家伙了。 ' WHERE entry=-416;
UPDATE creature_ai_texts SET content_default='想想我开始穿车辙的铺路石。 ' WHERE entry=-423;
UPDATE creature_ai_texts SET content_default='杰克和吉尔我的皱纹 patoot！我所有的水卢金轮在这里。 ' WHERE entry=-424;
UPDATE creature_ai_texts SET content_default='我一天要走好多趟到水井那边去打水，现在的年轻人啊…… ' WHERE entry=-425;
UPDATE creature_ai_texts SET content_default='有水吗，艾玛?去弄点水，艾玛?你要是再不去打水，我都快忘了水是什麽样的了…… ' WHERE entry=-426;
UPDATE creature_ai_texts SET content_default='我这麽多年来好像都没干过比打水更有意义的事情似的! ' WHERE entry=-427;
UPDATE creature_ai_texts SET content_default='我只是在自言自语罢了，和这里的其他人说话的时候，我总是得不到应有的尊重。 ' WHERE entry=-428;
UPDATE creature_ai_texts SET content_default='还没到吗? ' WHERE entry=-429;
UPDATE creature_ai_texts SET content_default='我腿疼! ' WHERE entry=-430;
UPDATE creature_ai_texts SET content_default='真的吗?运河里真的有鳄鱼吗? ' WHERE entry=-431;
UPDATE creature_ai_texts SET content_default='我们为什麽要走这条路? ' WHERE entry=-432;
UPDATE creature_ai_texts SET content_default='我们要去哪里? ' WHERE entry=-433;
UPDATE creature_ai_texts SET content_default='我要去看法师塔。 ' WHERE entry=-434;
UPDATE creature_ai_texts SET content_default='不要召唤这样的东西。它如此脆弱，用棒敲击就能使它粉身碎骨。 ' WHERE entry=-435;
UPDATE creature_ai_texts SET content_default='看起来你要继续前进，棘轮，告诉他，我已经破坏了碎纸机。 ' WHERE entry=-436;
UPDATE creature_ai_texts SET content_default='我会留下来，警惕的残骸。快点！希望没有人会发现烟 … ' WHERE entry=-437;
UPDATE creature_ai_texts SET content_default='我们被出卖了! ' WHERE entry=-438;
UPDATE creature_ai_texts SET content_default='%s发出了一声尖叫。 ' WHERE entry=-448;
UPDATE creature_ai_texts SET content_default='是哪个$R在这里多管闲事?让斯塔文的传说和你一起消亡吧! ' WHERE entry=-449;
UPDATE creature_ai_texts SET content_default='不要多管闲事，$N! ' WHERE entry=-450;
UPDATE creature_ai_texts SET content_default='为什麽暴风城的卫兵还没有来? ' WHERE entry=-451;
UPDATE creature_ai_texts SET content_default='圣光似乎遗弃了我们。 ' WHERE entry=-452;
UPDATE creature_ai_texts SET content_default='从暴风城来的消息似乎不太妙…… ' WHERE entry=-453;
UPDATE creature_ai_texts SET content_default='不断的争论只会一事无成。我们需要采取行动。 ' WHERE entry=-454;
UPDATE creature_ai_texts SET content_default='我们需要暴风城更多地采取行动。我们的家园正在被亡灵攻占。 ' WHERE entry=-455;
UPDATE creature_ai_texts SET content_default='恐怕黑暗正在向我们逼近。 ' WHERE entry=-456;
UPDATE creature_ai_texts SET content_default='暴风城的耳朵就像是城墙一样聋，跟本听不进我们说的话。 ' WHERE entry=-457;
UPDATE creature_ai_texts SET content_default='夜色镇的人民更多的期待理事会。我们不能让他们忍受这种在我们中传播的愤怒。 ' WHERE entry=-458;
UPDATE creature_ai_texts SET content_default='亡灵到处都是。暴风城的军队都哪去了？ ' WHERE entry=-459;
UPDATE creature_ai_texts SET content_default='等等……你不是我的丈夫。但肯定是他派你来的。你看起来……很可口! ' WHERE entry=-460;
UPDATE creature_ai_texts SET content_default='亚伯?是你吗?啊……我很饿，亚伯!我饿啊!! ' WHERE entry=-461;
UPDATE creature_ai_texts SET content_default='暮色森林的议会必须行动起来了。这里已经充满了邪恶。 ' WHERE entry=-462;
UPDATE creature_ai_texts SET content_default='你无法阻止被遗忘者， $R。黑暗女王将会让你感受到痛苦和恐惧。 ' WHERE entry=-469;
UPDATE creature_ai_texts SET content_default='你听好了，在我杀死你之后，你的身体将为我所用， $R. ' WHERE entry=-470;
UPDATE creature_ai_texts SET content_default='%s 开始破解，破解。 ' WHERE entry=-471;
UPDATE creature_ai_texts SET content_default='%s的力量随着石块断裂迅速衰减。 ' WHERE entry=-472;
UPDATE creature_ai_texts SET content_default='%s几乎都成了碎块，但仍然继续战斗。 ' WHERE entry=-473;
UPDATE creature_ai_texts SET content_default='我的背疼得要命。 ' WHERE entry=-490;
UPDATE creature_ai_texts SET content_default='如果我挂了，拿上我的邮袋。确保送到大将军手上。 ' WHERE entry=-491;
UPDATE creature_ai_texts SET content_default='我感觉到危险的存在。 ' WHERE entry=-492;
UPDATE creature_ai_texts SET content_default='我的爪子将撕碎你的弱小的身体, $r. ' WHERE entry=-494;
UPDATE creature_ai_texts SET content_default='我猜你带来了好消息? ' WHERE entry=-502;
UPDATE creature_ai_texts SET content_default='事情会按照计划，主福尔肯克雷。我向你保证，这只是一个时间问题 ' WHERE entry=-503;
UPDATE creature_ai_texts SET content_default='%s 开始召唤 黑手恐怖法师！ ' WHERE entry=-523;
UPDATE creature_ai_texts SET content_default='%s 开始召唤在黑手老兵！ ' WHERE entry=-524;
UPDATE creature_ai_texts SET content_default='%s召唤黑手恐法师来帮助他！ ' WHERE entry=-525;
UPDATE creature_ai_texts SET content_default='%s 召唤在黑手老兵来帮助他！ ' WHERE entry=-526;
UPDATE creature_ai_texts SET content_default='他将粉碎你！ ' WHERE entry=-527;
UPDATE creature_ai_texts SET content_default='死！你不会释放密斯赖尔！ ' WHERE entry=-528;
UPDATE creature_ai_texts SET content_default='站稳了，兄弟。别担心，他就在我们身边！ ' WHERE entry=-529;
UPDATE creature_ai_texts SET content_default='不，离开我们！我们必须完成我们的任务！ ' WHERE entry=-530;
UPDATE creature_ai_texts SET content_default='接招吧！我们必胜！ ' WHERE entry=-531;
UPDATE creature_ai_texts SET content_default='住手!愚蠢的 $C，我们不能让你召唤密斯赖尔 ' WHERE entry=-532;
UPDATE creature_ai_texts SET content_default='%s非常饿! ' WHERE entry=-539;
UPDATE creature_ai_texts SET content_default='%s变得非常饿! ' WHERE entry=-540;
UPDATE creature_ai_texts SET content_default='扫描生命形式的目标没有找到.... ' WHERE entry=-545;
UPDATE creature_ai_texts SET content_default='目标搜索模式恢复失去.... ' WHERE entry=-546;
UPDATE creature_ai_texts SET content_default='未知生命形式的评估检测 .... … ' WHERE entry=-547;
UPDATE creature_ai_texts SET content_default='Arrrhhh...Guards! ' WHERE entry=-548;
UPDATE creature_ai_texts SET content_default='Guards! ' WHERE entry=-549;
UPDATE creature_ai_texts SET content_default='%s看到朋友在战斗中倒下，变得非常愤怒! ' WHERE entry=-550;
UPDATE creature_ai_texts SET content_default='%s大声呼救! ' WHERE entry=-551;
UPDATE creature_ai_texts SET content_default='问候公民。 ' WHERE entry=-552;
UPDATE creature_ai_texts SET content_default='胆敢破坏神圣的埃德萨拉斯? 面对我吧，懦夫！ ' WHERE entry=-553;
UPDATE creature_ai_texts SET content_default='我的灵魂终于可以安息了……哦，亲爱的塞瑞利恩…… ' WHERE entry=-554;
UPDATE creature_ai_texts SET content_default='谁干扰了我的冥想? ' WHERE entry=-566;
UPDATE creature_ai_texts SET content_default='睡吧... ' WHERE entry=-567;
UPDATE creature_ai_texts SET content_default='尘归尘，土归土 ' WHERE entry=-568;
UPDATE creature_ai_texts SET content_default='阿库麦尔死了!我终于可以离开这块伤心地了。 ' WHERE entry=-569;
UPDATE creature_ai_texts SET content_default='以索瑞森的胡须的名义!杀了他们! ' WHERE entry=-576;
UPDATE creature_ai_texts SET content_default='我，格瑞姆洛克，我是国王! ' WHERE entry=-577;
UPDATE creature_ai_texts SET content_default='去死！去死！ ' WHERE entry=-578;
UPDATE creature_ai_texts SET content_default='不！没有，你必须这样做！ ' WHERE entry=-579;
UPDATE creature_ai_texts SET content_default='"死，凡人!" ' WHERE entry=-580;
UPDATE creature_ai_texts SET content_default='%s 开始计入战斗! ' WHERE entry=-581;
UPDATE creature_ai_texts SET content_default='比修知道宝藏被藏在哪儿了。 ' WHERE entry=-582;
UPDATE creature_ai_texts SET content_default='发牢骚！ *咳嗽咳嗽* * *我要戒菸！ ' WHERE entry=-583;
UPDATE creature_ai_texts SET content_default='问基布勒关于珍惜！发牢骚！ ' WHERE entry=-584;
UPDATE creature_ai_texts SET content_default='他们都到石塔，但从来没有回来 ...就像比茹。 ' WHERE entry=-585;
UPDATE creature_ai_texts SET content_default='Opus要科尔戈的黄金... 与蠕虫. ' WHERE entry=-586;
UPDATE creature_ai_texts SET content_default='基布雷尔正在调查G.E.T.A. ' WHERE entry=-587;
UPDATE creature_ai_texts SET content_default='%s 发出低沉的轰鸣声，提醒附近的盟友！ ' WHERE entry=-648;
UPDATE creature_ai_texts SET content_default='%s 进入醉酒怒气！ ' WHERE entry=-649;
UPDATE creature_ai_texts SET content_default='斯尼维尔在此!冷齿矿坑是斯尼维尔的! ' WHERE entry=-654;
UPDATE creature_ai_texts SET content_default='我的同伴的数量减少，女神，和自己的力量很快就不足以阻止费伍德森林的恶魔。 ' WHERE entry=-658;
UPDATE creature_ai_texts SET content_default='女神，请给予我力量让我征服我的敌人！听我说，我快要绝望了，我的所做的是正义的！ ' WHERE entry=-659;
UPDATE creature_ai_texts SET content_default='什麽...这是什麽？难道这是我的祈祷回答呢？ 艾露尼已授予我的武器 - 这镰刀 - 战胜恶魔。 ' WHERE entry=-660;
UPDATE creature_ai_texts SET content_default='安娜雅……?我的双眼没有欺骗我吗?真的是你吗? ' WHERE entry=-661;
UPDATE creature_ai_texts SET content_default='命运是如此残酷，它让我们在分别了数千年之后才能重逢…… ' WHERE entry=-662;
UPDATE creature_ai_texts SET content_default='我的爱人，你恨我吗?我在万般无奈之下摧毁了你的躯壳，因为只有这样才能让你从痛苦中永久地解脱。 ' WHERE entry=-663;
UPDATE creature_ai_texts SET content_default='不!安娜雅……安娜雅!请不要离开我!不…… ' WHERE entry=-664;
UPDATE creature_ai_texts SET content_default='怎麽办，我的爱人?没有你，我怎麽办……没有你……我如何有勇气在这个世界上生存…… ' WHERE entry=-665;
UPDATE creature_ai_texts SET content_default='岁月对我和你都很残酷，我的爱人……但最后我们还是重逢了。 ' WHERE entry=-666;
UPDATE creature_ai_texts SET content_default='亲爱的，不要为此而感到内疚。你使我从无尽的苦楚和折磨中解脱了出来，我只会为此而更加爱你。 ' WHERE entry=-667;
UPDATE creature_ai_texts SET content_default='%s 芯片和碎片！ ' WHERE entry=-694;
UPDATE creature_ai_texts SET content_default='没人可以窃取这个！ ' WHERE entry=-695;
UPDATE creature_ai_texts SET content_default='沙漠的沙，挡住了太阳！ ' WHERE entry=-698;
UPDATE creature_ai_texts SET content_default='你被终结了。 ' WHERE entry=-699;
UPDATE creature_ai_texts SET content_default='我…失败。 ' WHERE entry=-700;
UPDATE creature_ai_texts SET content_default='厚颜无耻的傻瓜！我要亲手杀了你！ ' WHERE entry=-701;
UPDATE creature_ai_texts SET content_default='勇士！队长！继续战斗！ ' WHERE entry=-702;
UPDATE creature_ai_texts SET content_default='你不值得我花时间, $n. ' WHERE entry=-703;
UPDATE creature_ai_texts SET content_default='%s 回避使他更痛苦。 ' WHERE entry=-704;
UPDATE creature_ai_texts SET content_default='%s呻吟. ' WHERE entry=-705;
UPDATE creature_ai_texts SET content_default='%s 可怜的啜泣. ' WHERE entry=-706;
UPDATE creature_ai_texts SET content_default='午饭时间到了，我的孩子。把他们撕成碎片！ ' WHERE entry=-710;
UPDATE creature_ai_texts SET content_default='站出来保卫你的主人！ ' WHERE entry=-711;
UPDATE creature_ai_texts SET content_default='孩子们扎会保护他们的主人。苏利萨斯会再度崛起！ ' WHERE entry=-712;
UPDATE creature_ai_texts SET content_default='伊利法尔，你的主人在召唤你! ' WHERE entry=-713;
UPDATE creature_ai_texts SET content_default='让溷沌之火将你吞噬吧! ' WHERE entry=-714;
UPDATE creature_ai_texts SET content_default='面对我的勇士吧，凡人! ' WHERE entry=-715;
UPDATE creature_ai_texts SET content_default='为自己准备一个永恒的痛苦和折磨 - 我的报复，应 … ' WHERE entry=-716;
UPDATE creature_ai_texts SET content_default='离开这个地方！ ' WHERE entry=-764;
UPDATE creature_ai_texts SET content_default='用我的死亡! 召唤你! ' WHERE entry=-769;
UPDATE creature_ai_texts SET content_default='我被召唤来！入侵者，来到我的帐篷，面对你的死亡！ ' WHERE entry=-770;
UPDATE creature_ai_texts SET content_default='好吧！我们投降…放低你的武器，我会合作 ' WHERE entry=-775;
UPDATE creature_ai_texts SET content_default='%s 把他的俱乐部，开始疯狂地摆动！ ' WHERE entry=-797;
UPDATE creature_ai_texts SET content_default='怎样才能...我的爱，我怎样才能面对没有你在我身旁陪伴的时光…… ' WHERE entry=-807;
UPDATE creature_ai_texts SET content_default='岁月对你我如此残酷，我的爱，但放心，我们终将团聚。 ' WHERE entry=-808;
UPDATE creature_ai_texts SET content_default='请不要费心了，亲爱的。您已经使我摆脱了奴役，我只会更加爱你。 ' WHERE entry=-809;
UPDATE creature_ai_texts SET content_default='So or’manley fi siame Dim fus siame yudo ' WHERE entry=-817;
UPDATE creature_ai_texts SET content_default='回头！不醒的梦！ ' WHERE entry=-819;
UPDATE creature_ai_texts SET content_default='你不知道你在做什幺！我们必须毁灭自己 ' WHERE entry=-820;
UPDATE creature_ai_texts SET content_default='The Soulflayer comes! ' WHERE entry=-822;
UPDATE creature_ai_texts SET content_default='Join us! ' WHERE entry=-823;
UPDATE creature_ai_texts SET content_default='哈卡将再次重生！ ' WHERE entry=-824;
UPDATE creature_ai_texts SET content_default='这个邪恶的不被允许进入这个世界！我的孩子！ ' WHERE entry=-825;
UPDATE creature_ai_texts SET content_default='你，死！ ' WHERE entry=-826;
UPDATE creature_ai_texts SET content_default='不，你不能比星海强！不！ ' WHERE entry=-827;
UPDATE creature_ai_texts SET content_default='%s 攻击卡拉恩的旌旗！ ' WHERE entry=-828;
UPDATE creature_ai_texts SET content_default='%s 掌管！ ' WHERE entry=-829;
UPDATE creature_ai_texts SET content_default='你们是逃不了的。十字军东征应当销毁所有天灾的污点。 ' WHERE entry=-895;
UPDATE creature_ai_texts SET content_default='你带着这污点，准备进入扭曲虚空。 ' WHERE entry=-896;
UPDATE creature_ai_texts SET content_default='谴责所有罪恶,现在你会死！ ' WHERE entry=-897;
UPDATE creature_ai_texts SET content_default='代理更多的集团，我敢打赌！你不会收回它…或南岸！ ' WHERE entry=-924;
UPDATE creature_ai_texts SET content_default='该园现在贫瘠和生命为我腐烂的外壳。一旦这些树木开花，但现在只有腐烂。 ' WHERE entry=-925;
UPDATE creature_ai_texts SET content_default='我花了我的整个生命照顾这些树。修剪和培育他们…他们与我一起死亡。 ' WHERE entry=-926;
UPDATE creature_ai_texts SET content_default='入侵者！攻击入侵者！ ' WHERE entry=-927;
UPDATE creature_ai_texts SET content_default='用南海镇的血来还债！ ' WHERE entry=-928;
UPDATE creature_ai_texts SET content_default='复活！ ' WHERE entry=-929;
UPDATE creature_ai_texts SET content_default='复仇！ ' WHERE entry=-930;
UPDATE creature_ai_texts SET content_default='你灵魂不死的盛宴, $N. ' WHERE entry=-931;
UPDATE creature_ai_texts SET content_default='帮帮我！救命啊！刺客在山上！武器！武器！ ' WHERE entry=-932;
UPDATE creature_ai_texts SET content_default='守卫你的职位！他必须被保护！他们可能来自任何地方！ ' WHERE entry=-933;
UPDATE creature_ai_texts SET content_default='%s 抓住他的脖子后面，他的眼睛睁大。 ' WHERE entry=-934;
UPDATE creature_ai_texts SET content_default='刺客…救… ' WHERE entry=-935;
UPDATE creature_ai_texts SET content_default='Thieves! Scallywags! Rapscallions! Come face me gigantic pillas! ' WHERE entry=-974;
UPDATE creature_ai_texts SET content_default='Are They all.... Dead? ' WHERE entry=-981;
UPDATE creature_ai_texts SET content_default='Is someone there? Tirion my old friend, is that you? Have you come to save us? ' WHERE entry=-982;
UPDATE creature_ai_texts SET content_default='You dare! Now feel my wrath! ' WHERE entry=-983;
UPDATE creature_ai_texts SET content_default='Who dares?! I will destroy you! ' WHERE entry=-984;
UPDATE creature_ai_texts SET content_default='Mistress!! They seek to destroy your work! ' WHERE entry=-985;
UPDATE creature_ai_texts SET content_default='You be too scared! Me find you! ' WHERE entry=-986;
UPDATE creature_ai_texts SET content_default='What? No you can’t beat me! Me will return! ' WHERE entry=-987;
UPDATE creature_ai_texts SET content_default='Mommy! ' WHERE entry=-990;
UPDATE creature_ai_texts SET content_default='This will teach you to lay off the herb, $r. ' WHERE entry=-1019;
UPDATE creature_ai_texts SET content_default='Step right up! Step right up! Greetings my friend. I’m Silas Darkmoon and I want to welcome you to the greatest show on Azeroth! It’s the Darkmoon Faire friend, and it’s your lucky day! Sparing no expense, we’ve gathered wonders and treats from around the world for your delight. Whether you’re young or old, rich or poor, the Darkmoon Faire has it all! ' WHERE entry=-1020;
UPDATE creature_ai_texts SET content_default='Amaze at the wonders that the Darkmoon Faire has uncovered in this vast and mysterious world! We have spared no expense in bringing you excitement that children of all ages will delight in! ' WHERE entry=-1021;
UPDATE creature_ai_texts SET content_default='We have it all... delicious food, strong drink, exotic artifacts, fortunes read, amazing prizes and excitement without end! ' WHERE entry=-1022;
UPDATE creature_ai_texts SET content_default='And, don’t forget to turn in your Darkmoon Faire Prize Tickets! All it takes is five or more and you’re on your way to the most wondrous prizes on all of Azeroth. Everybody is a winner! ' WHERE entry=-1023;
UPDATE creature_ai_texts SET content_default='Step right up! Get your Red Hot Wings right here! ' WHERE entry=-1024;
UPDATE creature_ai_texts SET content_default='You’ve got money and we’ve got food. What are you waiting for? ' WHERE entry=-1025;
UPDATE creature_ai_texts SET content_default='Darkmoon Dogs fresh off the grill. Come and get em while they’re hot! ' WHERE entry=-1026;
UPDATE creature_ai_texts SET content_default='For a limited time only, Crunchy Frog available exclusively here at the Darkmoon Faire. ' WHERE entry=-1027;
UPDATE creature_ai_texts SET content_default='The Scarlet Crusade shall smite the wicked and drive evil from these lands! ' WHERE entry=-1028;
UPDATE creature_ai_texts SET content_default='You carry the taint of the scourge.  Prepare to enter the twisting nether. ' WHERE entry=-1029;
UPDATE creature_ai_texts SET content_default='The Scarlet Crusade shall not fail in it’s mission! ' WHERE entry=-1030;
UPDATE creature_ai_texts SET content_default='These undead atrocities will be destroyed! ' WHERE entry=-1031;
UPDATE creature_ai_texts SET content_default='These lands shall be cleansed! ' WHERE entry=-1032;
UPDATE creature_ai_texts SET content_default='Here to visit the family? Die, fool! ' WHERE entry=-1033;
UPDATE creature_ai_texts SET content_default='The Agamand Mills is held by the Scourge, $c. Join us! ' WHERE entry=-1034;
UPDATE creature_ai_texts SET content_default='This desert be mine! ' WHERE entry=-1035;
UPDATE creature_ai_texts SET content_default='The Sandfury reign supreme! ' WHERE entry=-1036;
UPDATE creature_ai_texts SET content_default='Feel the fury of the sands! ' WHERE entry=-1037;
UPDATE creature_ai_texts SET content_default='Die, outlander! ' WHERE entry=-1038;
UPDATE creature_ai_texts SET content_default='Let the executions begin! ' WHERE entry=-1039;
UPDATE creature_ai_texts SET content_default='Justice is done! ' WHERE entry=-1040;
UPDATE creature_ai_texts SET content_default='Tell the Warden this prison is ours now! ' WHERE entry=-1041;
UPDATE creature_ai_texts SET content_default='I’ll crush your skull beneath my boot! ' WHERE entry=-1042;
UPDATE creature_ai_texts SET content_default='Death to the Warden’s men! ' WHERE entry=-1043;
UPDATE creature_ai_texts SET content_default='Fresh meat! ' WHERE entry=-1044;
UPDATE creature_ai_texts SET content_default='More of the Warden’s errand boys! ' WHERE entry=-1045;
UPDATE creature_ai_texts SET content_default='How dare you enter my sanctum! ' WHERE entry=-1047;
UPDATE creature_ai_texts SET content_default='You are in the presence of a god! ' WHERE entry=-1048;
UPDATE creature_ai_texts SET content_default='%s collapses but the broken body rises again! ' WHERE entry=-1054;
UPDATE creature_ai_texts SET content_default='No tampering with the mail! ' WHERE entry=-1055;
UPDATE creature_ai_texts SET content_default='That’s our treasure, you lubber! ' WHERE entry=-1056;
UPDATE creature_ai_texts SET content_default='Hey!  Get away from our treasure! ' WHERE entry=-1057;
UPDATE creature_ai_texts SET content_default='%s seems to no longer be able to cast spells... ' WHERE entry=-1058;
UPDATE creature_ai_texts SET content_default='Kill $N! ' WHERE entry=-1119;
UPDATE creature_ai_texts SET content_default='For Kalimdor! ' WHERE entry=-1133;
UPDATE creature_ai_texts SET content_default='Endudi Rifa! ' WHERE entry=-1134;
UPDATE creature_ai_texts SET content_default='None can stand against the serpent lords! ' WHERE entry=-1135;
UPDATE creature_ai_texts SET content_default='Anudora! ' WHERE entry=-1136;
UPDATE creature_ai_texts SET content_default='WHO IS BOTHERING ME? ' WHERE entry=-1137;
UPDATE creature_ai_texts SET content_default='Ahh, a new chew toy for my dogs! ' WHERE entry=-1138;
UPDATE creature_ai_texts SET content_default='Come, $n. See what the Nightmare brings... ' WHERE entry=-1139;
UPDATE creature_ai_texts SET content_default='The Nightmare cannot be stopped! ' WHERE entry=-1140;
UPDATE creature_ai_texts SET content_default='%s squeezes the last bit of life out of $n and swallows their soul. ' WHERE entry=-1141;
UPDATE creature_ai_texts SET content_default='I crush weaklings like you every day! Bring it on! ' WHERE entry=-1142;
UPDATE creature_ai_texts SET content_default='You will not harm Emperor Thaurissan! ' WHERE entry=-1143;
UPDATE creature_ai_texts SET content_default='Curse you! One day, vengeance will be mine! ' WHERE entry=-1145;
UPDATE creature_ai_texts SET content_default='Ach! Thank you so much I’m free! Finally! ' WHERE entry=-1146;
UPDATE creature_ai_texts SET content_default='%s ’s death cry has stirred the nearby silithid hive ' WHERE entry=-1147;
UPDATE creature_ai_texts SET content_default='You asked for it. ' WHERE entry=-1148;
UPDATE creature_ai_texts SET content_default='I hate resorting to violence! ' WHERE entry=-1149;
UPDATE creature_ai_texts SET content_default='Your time has come! ' WHERE entry=-1150;
UPDATE creature_ai_texts SET content_default='Lok’Narosh! ' WHERE entry=-1151;
UPDATE creature_ai_texts SET content_default='For Doomhammer! ' WHERE entry=-1152;
UPDATE creature_ai_texts SET content_default='You make big mistake, mon. ' WHERE entry=-1153;
UPDATE creature_ai_texts SET content_default='Here come the voodoo! ' WHERE entry=-1154;
UPDATE creature_ai_texts SET content_default='For the Darkspear tribe! ' WHERE entry=-1155;
UPDATE creature_ai_texts SET content_default='Taste blade, mongrel! ' WHERE entry=-1156;
UPDATE creature_ai_texts SET content_default='Please tell me that you didn’t just do what I think you just did. Please tell me that I’m not going to have to hurt you... ' WHERE entry=-1157;
UPDATE creature_ai_texts SET content_default='As if we don’t have enough problems, you go and create more! ' WHERE entry=-1158;
UPDATE creature_ai_texts SET content_default='Is that the best you can do? ' WHERE entry=-1159;
UPDATE creature_ai_texts SET content_default='Ah ken see very well through this haze, but I’d know tha’ smell anywhere! Die ye foul ogre! ' WHERE entry=-1160;
UPDATE creature_ai_texts SET content_default='Ooooooooh... $B To the plaguelands went old Duggan, ta’send them Scourge back inta’th’ groun’. $B Where th’scent of death is on th’wind and everythin’ is mostly brown. $B An’ when he did arrive there, what’d his dwarf eyes see? $B A hundred crates of barley there ta’ be makin’ inta’ mead! $B But tha’ mead was cursed with th’ plague o’death, and now old Duggan, too. $B An’ surrounded by the Lich King’s beasts, what could old Duggan do? $B But though I feel the plague within, my hopes ’ave not yet sunk. $B If’n I’m gonna be Scourge anyway, I might as well be drunk! ' WHERE entry=-1161;
UPDATE creature_ai_texts SET content_default='Emperor Thaurissan does not wish to be disturbed! Turn back now or face your doom, weak mortals! ' WHERE entry=-1194;
UPDATE creature_ai_texts SET content_default='Prepare to be Malowned! ' WHERE entry=-1195;
UPDATE creature_ai_texts SET content_default='You just got MALOWNED! ' WHERE entry=-1196;
UPDATE creature_ai_texts SET content_default='TIMMY! ' WHERE entry=-1197;
UPDATE creature_ai_texts SET content_default='Tell me... tell me everything! ' WHERE entry=-1198;
UPDATE creature_ai_texts SET content_default='Naughty secrets! ' WHERE entry=-1199;
UPDATE creature_ai_texts SET content_default='I’ll rip the secrets from your flesh! ' WHERE entry=-1200;
UPDATE creature_ai_texts SET content_default='Purged by pain! ' WHERE entry=-1201;
UPDATE creature_ai_texts SET content_default='We hunger for vengeance. ' WHERE entry=-1202;
UPDATE creature_ai_texts SET content_default='No rest, for the angry dead. ' WHERE entry=-1203;
UPDATE creature_ai_texts SET content_default='More... More souls. ' WHERE entry=-1204;
UPDATE creature_ai_texts SET content_default='Release the hounds! ' WHERE entry=-1205;
UPDATE creature_ai_texts SET content_default='SMOTTS, I HAVE YOUR LITTLE BELT....COME GET IT! ' WHERE entry=-1206;
UPDATE creature_ai_texts SET content_default='SMOTTS! HEY, SMOTTS! COME OUT AND PLAY! ' WHERE entry=-1207;
UPDATE creature_ai_texts SET content_default='DON’T LET THIS STATUE BE MY ONLY COMPANY, COME OUT AND PLAY! ' WHERE entry=-1208;
UPDATE creature_ai_texts SET content_default='COME OUT TO JANEIRO’S POINT. I’M WAITING FOR YOU, SMOTTS... ' WHERE entry=-1209;
UPDATE creature_ai_texts SET content_default='I PROMISE I WON’T KILL YOUR CREW THIS TIME. HAH! BUT MY BROTHER MIGHT EAT THEM! ' WHERE entry=-1210;
UPDATE creature_ai_texts SET content_default='HAVE YOU RUN OUT OF SHIPS TO SEND? WHERE IS YOUR COURAGE? ' WHERE entry=-1211;
UPDATE creature_ai_texts SET content_default='YOU WERE SUCH GOOD SPORT THE LAST TIME...COME OUT! ' WHERE entry=-1212;
UPDATE creature_ai_texts SET content_default='I HAVE YOUR LITTLE BELT TIED AROUND MY FINGER, SMOTTS. DON’T YOU WANT IT BACK? ' WHERE entry=-1213;
UPDATE creature_ai_texts SET content_default='You’ll never leave this place... alive. ' WHERE entry=-1221;
UPDATE creature_ai_texts SET content_default='To me, my servants! ' WHERE entry=-1222;
UPDATE creature_ai_texts SET content_default='Come, spirits, attend your master! ' WHERE entry=-1223;
UPDATE creature_ai_texts SET content_default='I am the hand of the Lich King! ' WHERE entry=-1224;
UPDATE creature_ai_texts SET content_default='Too...easy! ' WHERE entry=-1225;
UPDATE creature_ai_texts SET content_default='Oh now you’ve gone and angered me! Time to see the true force of the Stone of Tides! ' WHERE entry=-1226;
UPDATE creature_ai_texts SET content_default='Intruders have breached the hatchery! Sound the alarm! Protect the eggs at all costs! ' WHERE entry=-1294;
UPDATE creature_ai_texts SET content_default='Foolish mortal, you serve me now! ' WHERE entry=-1295;
UPDATE creature_ai_texts SET content_default='The power of the light is truly great and merciful. ' WHERE entry=-1296;
UPDATE creature_ai_texts SET content_default='We shall be reunited once more, my love... ' WHERE entry=-1297;
UPDATE creature_ai_texts SET content_default='At last, it ends... ' WHERE entry=-1298;
UPDATE creature_ai_texts SET content_default='Stranger, find the fallen Prince Menethil and end his reign of terror. ' WHERE entry=-1299;
UPDATE creature_ai_texts SET content_default='Should I live through this, I shall make it my life’s sole ambition to destroy Arthas... ' WHERE entry=-1300;
UPDATE creature_ai_texts SET content_default='I won’t make it... go... go on without me... ' WHERE entry=-1301;
UPDATE creature_ai_texts SET content_default='Death take me! I cannot go on! I have nothing left... ' WHERE entry=-1302;
UPDATE creature_ai_texts SET content_default='The light condemns all who harbor evil.  Now you will die! ' WHERE entry=-1305;
UPDATE creature_ai_texts SET content_default='You carry the taint of the scourge.  Prepare to enter the twisting nether. ' WHERE entry=-1306;
UPDATE creature_ai_texts SET content_default='There is no escape for you.  The Crusade shall destroy all who carry the scourge’s taint. ' WHERE entry=-1307;
UPDATE creature_ai_texts SET content_default='The Scarlet Crusade shall smite the wicked and drive evil from these lands! ' WHERE entry=-1308;
UPDATE creature_ai_texts SET content_default='Welcome to flavor country! ' WHERE entry=-1310;
UPDATE creature_ai_texts SET content_default='I can’t believe dad won’t let me keep your sister. ' WHERE entry=-1312;
UPDATE creature_ai_texts SET content_default='Can anyone give my adorable, extra little kitty a home? ' WHERE entry=-1313;
UPDATE creature_ai_texts SET content_default='What does allergic mean anyway? And what does it have to do with either of my kitties? ' WHERE entry=-1314;
UPDATE creature_ai_texts SET content_default='Will someone please give my little kitten a good home? ' WHERE entry=-1315;
UPDATE creature_ai_texts SET content_default='Don’t worry, I’ll find a good home for ya. ' WHERE entry=-1316;
UPDATE creature_ai_texts SET content_default='Silithid Creeper lays an egg! ' WHERE entry=-1317;
UPDATE creature_ai_texts SET content_default='Silithid Creeper Egg begins to crack and open... ' WHERE entry=-1318;
UPDATE creature_ai_texts SET content_default='Silithid Creeper Egg splits open! ' WHERE entry=-1319;
UPDATE creature_ai_texts SET content_default='%s splits into two new Lava Spawns! ' WHERE entry=-1320;
UPDATE creature_ai_texts SET content_default='If you’re here, then it means you are prepared to begin the study of summoning demonic cohorts to do your bidding. We will start with the lowliest creatures you will be able to call and continue from there. Let us begin. ' WHERE entry=-1411;
UPDATE creature_ai_texts SET content_default='The easiest creature for you to summon is the imp. You should already be able to bring forth this minion but for completeness’ sake I will start with him. ' WHERE entry=-1412;
UPDATE creature_ai_texts SET content_default='This foul little beast is the imp. It is small and weak, making it almost useless as a meatshield, and its damage output is mediocre at best. This creature is best used for support of a larger group. ' WHERE entry=-1413;
UPDATE creature_ai_texts SET content_default='Now that you have had a chance to study imp, let us move on the next minion you will be able to summon, the voidwalker. ' WHERE entry=-1414;
UPDATE creature_ai_texts SET content_default='This demonic entity is known as the Voidwalker. Its strength and endurance are significant, making it ideal for defense. Send it to attack your enemy, then use it as a shield while you use your spells and abilities to drain away your opponent’s life. ' WHERE entry=-1415;
UPDATE creature_ai_texts SET content_default='If you’ve never seen one, it is a sight to behold. A very impressive creature both on and off the field of battle. Next, let us take a look at what I am sure all you male students have been waiting for. The succubus. ' WHERE entry=-1416;
UPDATE creature_ai_texts SET content_default='All right now. Aside from the obvious distractions a minion like this will provide against your more masculine foes, she is also capable of dealing out impressive amounts of damage. However, her fragile endurance makes her almost useless as a shield. ' WHERE entry=-1417;
UPDATE creature_ai_texts SET content_default='Study hard and you might one day be able to summon one on your own, but for now it’s time to move on to the felhunter. ' WHERE entry=-1418;
UPDATE creature_ai_texts SET content_default='What you see before you is a felhunter. This creature’s natural talents include spell lock and other abilities which make it unequalled when facing a magically attuned opponent. ' WHERE entry=-1419;
UPDATE creature_ai_texts SET content_default='When facing a spellcaster of any kind, this feral beast will be your best friend. Now, let us take a look at something a bit different. This next creature will aid your travels and make your future journeys much easier. Let’s take a look at a felsteed. ' WHERE entry=-1420;
UPDATE creature_ai_texts SET content_default='I doubt you have had much occasion to see such a creature. These demonic equines will make your travels much faster by acting as your mount as long as you control them. However, they are difficult to control, so be sure you are ready before attempting it. ' WHERE entry=-1421;
UPDATE creature_ai_texts SET content_default='There you have it. Our lesson on summoning has come to an end. A new class will begin shortly, so if you wish to brush up, feel free to stay around. ' WHERE entry=-1422;