UPDATE db_script_string SET content_default='威胁结束！ $N 是 萨文是我们所有的！' WHERE entry=2000000009;
UPDATE db_script_string SET content_default='你有多少埋怨，我需要送回的妈妈和爸爸在一个运尸袋里包着，是军团头杀死的还是自杀?你不要向我点你的头骨,尽管你知道我废话!' WHERE entry=2000000010;
UPDATE db_script_string SET content_default='好吧，那就行动。 现在来，回到商店完成我们的事业！' WHERE entry=2000000011;
UPDATE db_script_string SET content_default='跟着我，好＄$C. 艾尔文烈啤酒你竟然比我更快速地喝完了。 Mmmm。。。 烈啤酒。' WHERE entry=2000000012;
UPDATE db_script_string SET content_default='向万能者鞠躬！ 在我的地狱主宰之前弯腰。。。 小鸡？' WHERE entry=2000000013;
UPDATE db_script_string SET content_default='往后站！站开！地狱者将会需要有一个宽的船位！' WHERE entry=2000000014;
UPDATE db_script_string SET content_default='沉默,仆人!此仇不报非君子!死亡暴风城!死鸡!' WHERE entry=2000000015;
UPDATE db_script_string SET content_default='谢谢你伟大的灵魂。谢谢你!' WHERE entry=2000000016;
UPDATE db_script_string SET content_default='你被解雇了,
你被解雇了,
你被解雇了,$N.' WHERE entry=2000000017;
UPDATE db_script_string SET content_default='空军指挥官布拉克，$n他会与我们的装甲翼龙驱逐舰一同和你战斗。而且，祝你好运！' WHERE entry=2000000018;
UPDATE db_script_string SET content_default='要由耐心 $N. 火炬几乎都是完整的.' WHERE entry=2000000019;
UPDATE db_script_string SET content_default='这很有趣......' WHERE entry=2000000020;
UPDATE db_script_string SET content_default='可爱的歌曲，不是吗？' WHERE entry=2000000021;
UPDATE db_script_string SET content_default='$N 看看它残暴与凶猛!' WHERE entry=2000000102;
UPDATE db_script_string SET content_default='战斗即将开始了!' WHERE entry=2000000103;
UPDATE db_script_string SET content_default='精神的水,我赞美你,我求你帮个忙。你有听到$N的请求,我信任他是高贵的。请你帮助我们?' WHERE entry=2000000026;
UPDATE db_script_string SET content_default='这是后勒的帐篷，但是后勒在哪？' WHERE entry=2000000029;
UPDATE db_script_string SET content_default='它也没在这，奇怪了，它在哪？' WHERE entry=2000000030;
UPDATE db_script_string SET content_default='得到在戒指里的血,$ N。战斗就要开始了!' WHERE entry=2000000104;
UPDATE db_script_string SET content_default='噢，热热热！如果它不是在你的脚下炸开，我都没发现！' WHERE entry=2000000033;
UPDATE db_script_string SET content_default='来吧, $N. 等着主人的怒火吧.' WHERE entry=2000000034;
UPDATE db_script_string SET content_default='There''s nothing like some scalding mornbrew on a chilly Dun Morogh day to get things started right!' WHERE entry=2000000035;
UPDATE db_script_string SET content_default='从桌上拿一块石头。你的任务会需要它。' WHERE entry=2000000036;
UPDATE db_script_string SET content_default='请救救我！' WHERE entry=2000000037;
UPDATE db_script_string SET content_default='你是我的英雄！' WHERE entry=2000000038;
UPDATE db_script_string SET content_default='感谢你的帮助！' WHERE entry=2000000039;
UPDATE db_script_string SET content_default='好的，我们走！' WHERE entry=2000000040;
UPDATE db_script_string SET content_default='你们听着,里斯的居住者!请让人们知道 $n 是崇高的成员。铁匠的荣誉、奉献和无限的耐心。为$n欢呼三次！' WHERE entry=2000000041;
UPDATE db_script_string SET content_default='和平和耐性和你在一起,$N。总是保持强劲。' WHERE entry=2000000042;
UPDATE db_script_string SET content_default='直到我们再次见面,勇敢的人。
直到我们再次见面,勇敢的人。' WHERE entry=2000000043;
UPDATE db_script_string SET content_default='你必须保护我,谁敢生活在这片森林里!' WHERE entry=2000000044;
UPDATE db_script_string SET content_default='这片森林对我们非常危险。我们必须留心!' WHERE entry=2000000045;
UPDATE db_script_string SET content_default='杀了两个怪物,他们留在附近的植物,我收集了一些' WHERE entry=2000000046;
UPDATE db_script_string SET content_default='我再搜集一些植物，这得需要一些时间' WHERE entry=2000000047;
UPDATE db_script_string SET content_default='现在我可以把这些种到我的庄园里' WHERE entry=2000000048;
UPDATE db_script_string SET content_default='再次感谢你 $N，这对于地球和我的实验都非常有利' WHERE entry=2000000049;
UPDATE db_script_string SET content_default='恩，好吧，我现在派人，我们必须找到并救他' WHERE entry=2000000050;
UPDATE db_script_string SET content_default='你知道他在哪？' WHERE entry=2000000051;
UPDATE db_script_string SET content_default='他不见了?' WHERE entry=2000000052;
UPDATE db_script_string SET content_default='发生什么事？' WHERE entry=2000000053;
UPDATE db_script_string SET content_default='方法,新手!' WHERE entry=2000000054;
UPDATE db_script_string SET content_default='嗯...你看起来不算太差！' WHERE entry=2000000055;
UPDATE db_script_string SET content_default='这里是灯塔，$n保持自给，如果您找到我们需要的东西。' WHERE entry=2000000056;
UPDATE db_script_string SET content_default='请，凡人，请与奥术师在达拉然进行谈判。' WHERE entry=2000000057;
UPDATE db_script_string SET content_default='谢谢你的伟大精神。非常感谢！' WHERE entry=2000000058;
UPDATE db_script_string SET content_default='我在此销毁这些文书的邪恶！为了部落！' WHERE entry=2000000059;
UPDATE db_script_string SET content_default='这些足迹肯定属于它。' WHERE entry=2000000060;
UPDATE db_script_string SET content_default='这些是它的足迹。' WHERE entry=2000000061;
UPDATE db_script_string SET content_default='跟着我' WHERE entry=2000000062;
UPDATE db_script_string SET content_default='请，凡人，在达拉然寻找魔导师。他可以与银色盟约谈判。' WHERE entry=2000000063;
UPDATE db_script_string SET content_default='这一切意味着什么呢？住手！我会付你工资的两倍了！' WHERE entry=2000000064;
UPDATE db_script_string SET content_default='你是什么意思，他说“我的时间已经到来”？我就当场杀了你！' WHERE entry=2000000065;
UPDATE db_script_string SET content_default='你如果不能真正记住，我是不会一直沉默的 | 3-6 ($ c)!' WHERE entry=2000000066;
UPDATE db_script_string SET content_default='一定要读一遍我的值日里的笔记。你会发现他们是在克服塔的防御


' WHERE entry=2000000067;
UPDATE db_script_string SET content_default='呼叫声!


' WHERE entry=2000000068;
UPDATE db_script_string SET content_default='那是有趣的。。。' WHERE entry=2000000069;
UPDATE db_script_string SET content_default='我需要请教霍雷肖。' WHERE entry=2000000070;
UPDATE db_script_string SET content_default='我找到你的原因了。' WHERE entry=2000000071;
UPDATE db_script_string SET content_default='要有耐心$ N。火炬几乎是完整的。' WHERE entry=2000000072;
UPDATE db_script_string SET content_default='它正在做....' WHERE entry=2000000073;
UPDATE db_script_string SET content_default='快点我的朋友' WHERE entry=2000000074;
UPDATE db_script_string SET content_default='不，别，请别杀我！' WHERE entry=2000000075;
UPDATE db_script_string SET content_default='你好。' WHERE entry=2000000076;
UPDATE db_script_string SET content_default='Poor Dorius. If I ever get my hands on those Dark Irons, so help me...' WHERE entry=2000005000;
UPDATE db_script_string SET content_default='Opus wants some Cuergo''s Gold... with worm.' WHERE entry=2000005001;
UPDATE db_script_string SET content_default='Bijou lost! SQUAWK! *cough' WHERE entry=2000005002;
UPDATE db_script_string SET content_default='Kibler is being investigated by G.E.T.A.' WHERE entry=2000005003;
UPDATE db_script_string SET content_default='Bijou knows where treasures are hidden.' WHERE entry=2000005004;
UPDATE db_script_string SET content_default='Dragons controlling orcs!? SQUAWK!' WHERE entry=2000005005;
UPDATE db_script_string SET content_default='They all go to the Spire but none never come back... just like Bijou.' WHERE entry=2000005006;
UPDATE db_script_string SET content_default='Ask Kibler about the treasure! SQUAWK!' WHERE entry=2000005007;
UPDATE db_script_string SET content_default='SQUAWK!! *cough* *cough* I need to quit smoking!' WHERE entry=2000005008;
UPDATE db_script_string SET content_default='Well done, soldiers! At ease!' WHERE entry=2000005009;
UPDATE db_script_string SET content_default='呵呵! 很乐意为你效劳!' WHERE entry=2000005010;
UPDATE db_script_string SET content_default='Yes right away momma!' WHERE entry=2000005011;
UPDATE db_script_string SET content_default='Mysterious hoofprints, scorched shields, stray badges... how do we make sense of all this?' WHERE entry=2000005012;
UPDATE db_script_string SET content_default='I don''t think Drazzit''s going to have any luck finding anyone to kill this raptor. I mean, he''s already raised the reward twice...' WHERE entry=2000005013;
UPDATE db_script_string SET content_default='But this the only building that fit Brogg! Goblins make buildings too small!' WHERE entry=2000005014;
UPDATE db_script_string SET content_default='I thought we talked about this, Brogg. You can''t stay in this building. Sure, it can house you, but there''s no room for anyone else!' WHERE entry=2000005015;
UPDATE db_script_string SET content_default='Yes, we said you can stay here, but this building is our headquarters! All of our manuals and blueprints are stored here!' WHERE entry=2000005016;
UPDATE db_script_string SET content_default='I''m inclined to say they made ogres too big! I can see I''m not going to convince you to move now, but don''t think this is permanent!' WHERE entry=2000005017;
UPDATE db_script_string SET content_default='Ah, this must be him now... no?' WHERE entry=2000005018;
UPDATE db_script_string SET content_default='You might wanna stand back. Fish guttin'' is a dirty job.' WHERE entry=2000005019;
UPDATE db_script_string SET content_default='It''s good to see you defending Theramore with pride, friend.' WHERE entry=2000005020;
UPDATE db_script_string SET content_default='When you''re off duty, let''s go to the inn. I''ll buy a round and we can reminisce about the good old days.' WHERE entry=2000005021;
UPDATE db_script_string SET content_default='Wouldn''t you like to bring those days back? I have some friends who know just the way to do that.' WHERE entry=2000005022;
UPDATE db_script_string SET content_default='Every item that I have for sale I acquired myself. You have my personal guarantee of authenticity.' WHERE entry=2000005023;
UPDATE db_script_string SET content_default='它越来越远了!' WHERE entry=2000005024;
UPDATE db_script_string SET content_default='Prizes! Get your prizes right here! Get over here and turn in your Darkmoon Faire Prize Tickets for valuable prizes!' WHERE entry=2000005025;
UPDATE db_script_string SET content_default='Come speak with me, and what once was cloudy shall become crystal clear.' WHERE entry=2000005026;
UPDATE db_script_string SET content_default='The Lich King''s forces are building. It is imperative that our timetable supports his plans.' WHERE entry=2000005027;
UPDATE db_script_string SET content_default='Tomorrow we will begin training of our promising dragons, so don''t forget your chew toys.' WHERE entry=2000005028;
UPDATE db_script_string SET content_default='Our oldest clutch of dragons are still far from maturity, but with patience and study, we are confident the dragons will soon be ready.' WHERE entry=2000005029;
UPDATE db_script_string SET content_default='If you wait to come see me, there may be nothing left!' WHERE entry=2000005030;
UPDATE db_script_string SET content_default='I come from the land down under... where women plague and men sunder.' WHERE entry=2000005031;
UPDATE db_script_string SET content_default='...And then the tauren said, "13 INCHES!"' WHERE entry=2000005032;
UPDATE db_script_string SET content_default='Come one, come all! Welcome to the Darkmoon Faire! Do you crave adventure? Do you seek exotic and mysterious treasures? Then look no further! You, my friend, have come to the right place! Dive right in and take part in all that the Faire has to offer! We''' WHERE entry=2000005033;
UPDATE db_script_string SET content_default='Welcome one and all to the Darkmoon Faire, the greatest event in all the worlds! We have it all... delicious food, strong drinks, exotic artifacts, fortunes read, amazing prizes and excitement without end! Don''t forget to turn in your Darkmoon Faire Prize' WHERE entry=2000005034;
UPDATE db_script_string SET content_default='它越来越远了!' WHERE entry=2000005035;
UPDATE db_script_string SET content_default='求求你了!我一定要立刻吃点东西……一个法力水晶……一个裂片……任何东西都好!我不能再忍受这种痛苦了!' WHERE entry=2000005036;
UPDATE db_script_string SET content_default='I might just have to go hunting for that Wretched beast now that there''s a bounty on his head.' WHERE entry=2000005037;
UPDATE db_script_string SET content_default='Tell us! Where does you leader hide?' WHERE entry=2000005038;
UPDATE db_script_string SET content_default='The wind speaks of our enemies'' movements, Ashyen. The Naga will attack again.' WHERE entry=2000005039;
UPDATE db_script_string SET content_default='Very well. When that decision is made, I will be ready. Let us hope it won''t be too late.' WHERE entry=2000005040;
UPDATE db_script_string SET content_default='I will do my best to take care of the children, Grandmother.' WHERE entry=2000005041;
UPDATE db_script_string SET content_default='New posting up! Adventurers and heroes, gather round the bulletin board!' WHERE entry=2000005042;
UPDATE db_script_string SET content_default='我会摧毁所有的生物！' WHERE entry=2000005043;
UPDATE db_script_string SET content_default='这里已经不再和平了！' WHERE entry=2000005044;
UPDATE db_script_string SET content_default='告诉我们!你们的头目躲在哪里?' WHERE entry=2000005045;
UPDATE db_script_string SET content_default='这是一个好机会?' WHERE entry=2000005048;
UPDATE db_script_string SET content_default='I have another reading from the nether.' WHERE entry=2000005049;
UPDATE db_script_string SET content_default='Well hand it overand let''s see what you got!' WHERE entry=2000005050;
UPDATE db_script_string SET content_default='伟大的加兹鲁维！' WHERE entry=2000005051;
UPDATE db_script_string SET content_default='嘿，朋友。想要一些糖果吗？' WHERE entry=2000005052;
UPDATE db_script_string SET content_default='嘣！' WHERE entry=2000005053;
UPDATE db_script_string SET content_default='嘣！' WHERE entry=2000005054;
UPDATE db_script_string SET content_default='嘣！' WHERE entry=2000005055;
UPDATE db_script_string SET content_default='Right. We just busted our tails to haul all of this stuff up here, and you want us to work more?' WHERE entry=2000005056;
UPDATE db_script_string SET content_default='爱哭鬼！爱哭鬼！' WHERE entry=2000005057;
UPDATE db_script_string SET content_default='宝宝想要她的多莉!' WHERE entry=2000005058;
UPDATE db_script_string SET content_default='我不知道你的洋娃娃会游泳！' WHERE entry=2000005059;
UPDATE db_script_string SET content_default='哈哈！我有贝齐！' WHERE entry=2000005060;
UPDATE db_script_string SET content_default='宝宝希望得到她的洋娃娃！' WHERE entry=2000005061;
UPDATE db_script_string SET content_default='我有你的洋娃娃！尼亚尼亚！' WHERE entry=2000005062;
UPDATE db_script_string SET content_default='爱哭鬼！爱哭鬼！' WHERE entry=2000005063;
UPDATE db_script_string SET content_default='宝宝希望得到她的洋娃娃！' WHERE entry=2000005064;
UPDATE db_script_string SET content_default='我不知道你的洋娃娃会游泳！' WHERE entry=2000005065;
UPDATE db_script_string SET content_default='哈哈！我有贝齐！' WHERE entry=2000005066;
UPDATE db_script_string SET content_default='宝宝希望得到她的洋娃娃！' WHERE entry=2000005067;
UPDATE db_script_string SET content_default='我有你的洋娃娃！尼亚尼亚！' WHERE entry=2000005068;
UPDATE db_script_string SET content_default='爱哭鬼！爱哭鬼！' WHERE entry=2000005069;
UPDATE db_script_string SET content_default='宝宝希望得到她的洋娃娃！' WHERE entry=2000005070;
UPDATE db_script_string SET content_default='我不知道你的洋娃娃会游泳！' WHERE entry=2000005071;
UPDATE db_script_string SET content_default='哈哈！我有贝齐！' WHERE entry=2000005072;
UPDATE db_script_string SET content_default='宝宝希望得到她的洋娃娃！' WHERE entry=2000005073;
UPDATE db_script_string SET content_default='我有你的洋娃娃！尼亚尼亚！' WHERE entry=2000005074;
UPDATE db_script_string SET content_default='爱哭鬼！爱哭鬼！' WHERE entry=2000005075;
UPDATE db_script_string SET content_default='宝宝希望得到她的洋娃娃！' WHERE entry=2000005076;
UPDATE db_script_string SET content_default='我不知道你的洋娃娃会游泳！' WHERE entry=2000005077;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005078;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005079;
UPDATE db_script_string SET content_default='不要伤害贝齐，你个小气鬼！' WHERE entry=2000005080;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005081;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005082;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005083;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005084;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005085;
UPDATE db_script_string SET content_default='不要伤害贝齐，你个小气鬼！' WHERE entry=2000005086;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005087;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005088;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005089;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005090;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005091;
UPDATE db_script_string SET content_default='不要伤害贝齐，你个小气鬼！' WHERE entry=2000005092;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005093;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005094;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005095;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005096;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005097;
UPDATE db_script_string SET content_default='不要伤害贝齐，你个小气鬼！' WHERE entry=2000005098;
UPDATE db_script_string SET content_default='新鲜面包出售' WHERE entry=2000005099;
UPDATE db_script_string SET content_default='我能感觉到它的炙热。' WHERE entry=2000005100;
UPDATE db_script_string SET content_default='刚出炉的面包。您需要看看吗？' WHERE entry=2000005101;
UPDATE db_script_string SET content_default='我能感觉到它的炙热。' WHERE entry=2000005102;
UPDATE db_script_string SET content_default='Jack and Jill my wrinkled patoot! I do all the water luggin round here.' WHERE entry=2000005103;
UPDATE db_script_string SET content_default='Wheres the water Emma? Get the water Emma? Ifn it werent fer me that lot wouldnt know what water looks like.' WHERE entry=2000005104;
UPDATE db_script_string SET content_default='Of Course Im talking to myself. Only way to get a decent conversation in this city.' WHERE entry=2000005105;
UPDATE db_script_string SET content_default='As if I dont have better things to do in my old age than carry buckets of water.' WHERE entry=2000005106;
UPDATE db_script_string SET content_default='Seems like a hundred times a day I walk all the way to get more water. No respect for their elders I tell ya.' WHERE entry=2000005107;
UPDATE db_script_string SET content_default='Deja vu. For a moment I thought I was back home... before the plague...' WHERE entry=2000005108;
UPDATE db_script_string SET content_default='他们说，有时他可以变成乌鸦。' WHERE entry=2000005109;
UPDATE db_script_string SET content_default='他们说，有时他可以变成乌鸦。' WHERE entry=2000005110;
UPDATE db_script_string SET content_default='And then the rabbit just bit his head off... I swear.' WHERE entry=2000005111;
UPDATE db_script_string SET content_default='I swear, people have actualy seen them. Pandaren really do exist!!' WHERE entry=2000005112;
UPDATE db_script_string SET content_default='You know why Orcs eyes glow red? It''s because they drink blood!' WHERE entry=2000005113;
UPDATE db_script_string SET content_default='I dont think there''s any fish in these canals.' WHERE entry=2000005114;
UPDATE db_script_string SET content_default='And that''s how Lother killed thirty six orcs with his bare hands!' WHERE entry=2000005115;
UPDATE db_script_string SET content_default='额...这并不是一条鱼！' WHERE entry=2000005116;
UPDATE db_script_string SET content_default='I got worm guts on my shoes.' WHERE entry=2000005117;
UPDATE db_script_string SET content_default='我觉得我应该看看这些.' WHERE entry=2000005118;
UPDATE db_script_string SET content_default='额...这并不是一条鱼！' WHERE entry=2000005119;
UPDATE db_script_string SET content_default='我觉得我应该看看这些.' WHERE entry=2000005120;
UPDATE db_script_string SET content_default='我希望这是一条鱼！' WHERE entry=2000005121;
UPDATE db_script_string SET content_default='Worm goes on the hook, hook goes in the water, Fish is in the water, our fish.' WHERE entry=2000005122;
UPDATE db_script_string SET content_default='你能想象的到吗？' WHERE entry=2000005123;
UPDATE db_script_string SET content_default='真的吗？' WHERE entry=2000005124;
UPDATE db_script_string SET content_default='哇。' WHERE entry=2000005125;
UPDATE db_script_string SET content_default='我父亲说，这只是一个故事。' WHERE entry=2000005126;
UPDATE db_script_string SET content_default='真的吗？' WHERE entry=2000005127;
UPDATE db_script_string SET content_default='哇。' WHERE entry=2000005128;
UPDATE db_script_string SET content_default='真整齐.' WHERE entry=2000005129;
UPDATE db_script_string SET content_default='哇。' WHERE entry=2000005130;
UPDATE db_script_string SET content_default='真的吗？' WHERE entry=2000005131;
UPDATE db_script_string SET content_default='Look alive, dogs! We got an operation to run here!' WHERE entry=2000005132;
UPDATE db_script_string SET content_default='有一个好时机吗？' WHERE entry=2000005133;
UPDATE db_script_string SET content_default='Here we have the Cathedral of Light, the center of spiritual enlightenment here in Stormwind.' WHERE entry=2000005134;
UPDATE db_script_string SET content_default='Yes, that is true. Paladins and Priests alike train their skills and research great truths behind the walls of the Cathedral.' WHERE entry=2000005135;
UPDATE db_script_string SET content_default='Children if you would please follow me, we will now be going to see the keep where King Anduin Wrynn himself sits on this throne.' WHERE entry=2000005136;
UPDATE db_script_string SET content_default='Here we have Stormwind Keep. Built upon the ruins of Stormwind Castle, which was destroyed by the Horde in the first Great War.' WHERE entry=2000005137;
UPDATE db_script_string SET content_default='When the Horde was shattered, men returned here and began to rebuild the once great city as a testament to our own survival.' WHERE entry=2000005138;
UPDATE db_script_string SET content_default='Yes, well...let''s head on to the monument dedicated to the heroes of the two Great Wars, the Valley of Heroes. Follow Me.' WHERE entry=2000005139;
UPDATE db_script_string SET content_default='Isn''t it amazing, children? All who enter the city must walk beneath the watchful eyes of the greatest heroes of our lands.' WHERE entry=2000005140;
UPDATE db_script_string SET content_default='Breathtaking. Children, when we return to the school, you will each give an oral report on one of these legendary people.' WHERE entry=2000005141;
UPDATE db_script_string SET content_default='Now, take another long look before we make our way to the Holy District and the great Cathedral of Light.' WHERE entry=2000005142;
UPDATE db_script_string SET content_default='This will never do..' WHERE entry=2000005143;
UPDATE db_script_string SET content_default='这必须是固定的！' WHERE entry=2000005144;
UPDATE db_script_string SET content_default='怎么能就这样生活下去！' WHERE entry=2000005145;
UPDATE db_script_string SET content_default='鸭子！' WHERE entry=2000005146;
UPDATE db_script_string SET content_default='Don''t go close to the lake! It''s haunted!' WHERE entry=2000005147;
UPDATE db_script_string SET content_default='把12个中心的焦点汇聚,以形成更多的魔法能量、多渠道增加必要的稳定性。' WHERE entry=2000005148;
UPDATE db_script_string SET content_default='至少我们不能来把它收拾干净。' WHERE entry=2000005149;
UPDATE db_script_string SET content_default='只有我们不遵循正确的初始化过程。' WHERE entry=2000005150;
UPDATE db_script_string SET content_default='虽然最终的能量将会消失,这可能会导致一个能量流,会让你头痛几个星期。' WHERE entry=2000005151;
UPDATE db_script_string SET content_default='只有我们不遵循正确的初始化过程。' WHERE entry=2000005152;
UPDATE db_script_string SET content_default='只有我们不遵循正确的初始化过程。' WHERE entry=2000005153;
UPDATE db_script_string SET content_default='至少我们不能来把它收拾干净。' WHERE entry=2000005154;
UPDATE db_script_string SET content_default='但是,这不是他娴熟的神奇配方引起的初值问题?' WHERE entry=2000005155;
UPDATE db_script_string SET content_default='我想这才能行得通,如果我们有二十人赶出它。' WHERE entry=2000005156;
UPDATE db_script_string SET content_default='但是由此产生的多普勒频移是发送的魔法反馈流吗?' WHERE entry=2000005157;
UPDATE db_script_string SET content_default='对齐时碰撞与积极能量带负电荷的能量,他们不排斥彼此。' WHERE entry=2000005158;
UPDATE db_script_string SET content_default='那不平衡的神奇焦点,显然,和一种反向的振动有关。' WHERE entry=2000005159;
UPDATE db_script_string SET content_default='但那不意味着要穿越小溪吗?那真不好办了?
' WHERE entry=2000005160;
UPDATE db_script_string SET content_default='为什么我们不能只改变数组通量差异？' WHERE entry=2000005161;
UPDATE db_script_string SET content_default='但是，这不正是造成神奇公式与Adept Syleria初期问题的原因吗？' WHERE entry=2000005162;
UPDATE db_script_string SET content_default='我想不会，我需要再被炸上天了。' WHERE entry=2000005163;
UPDATE db_script_string SET content_default='主人说，扭曲而引起正面能量交流电流向实际上就是建立一个更加稳定的流量。' WHERE entry=2000005164;
UPDATE db_script_string SET content_default='但是，那不就意味着要穿过风暴？这真的很不好？' WHERE entry=2000005165;
UPDATE db_script_string SET content_default='但是，这不正是造成神奇公式与Adept Syleria初期问题的原因吗？' WHERE entry=2000005166;
UPDATE db_script_string SET content_default='这是真的，骑士坐骑在这里？' WHERE entry=2000005167;
UPDATE db_script_string SET content_default='我们为什么要学习这些莫名其妙的东西？?' WHERE entry=2000005168;
UPDATE db_script_string SET content_default='如果我们扭转这一本质流动也许我们能改变极性。' WHERE entry=2000005169;
UPDATE db_script_string SET content_default='如果我们用三个重点在Tyrean模式?应该能解决它。' WHERE entry=2000005170;
UPDATE db_script_string SET content_default='哇,这一切为了一份爱情药剂。希望他是值得的。' WHERE entry=2000005171;
UPDATE db_script_string SET content_default='如果我们使用适当的顺序，应该没问题。在我们开始前将会带走一些重要的研究。' WHERE entry=2000005172;
UPDATE db_script_string SET content_default='传送门转移的效果。在这里,如果你施放一个有约束力的法术，你就会把地方具体化。' WHERE entry=2000005173;
UPDATE db_script_string SET content_default='哇,这一切为了一份爱情药剂。希望他是值得的。' WHERE entry=2000005174;
UPDATE db_script_string SET content_default='但如果我们能稳定能量固定点，它应该就能工作了。' WHERE entry=2000005175;
UPDATE db_script_string SET content_default='如果我们用三个重点在Tyrean模式?应该能解决它。' WHERE entry=2000005176;
UPDATE db_script_string SET content_default='如果我们使用适当的顺序，应该没问题。在我们开始前将会带走一些重要的研究。' WHERE entry=2000005177;
UPDATE db_script_string SET content_default='但如果我们能稳定能量固定点，它应该就能工作了。' WHERE entry=2000005178;
UPDATE db_script_string SET content_default='哇,这一切为了一份爱情药剂。希望他是值得的。' WHERE entry=2000005179;
UPDATE db_script_string SET content_default='Hello, Charys. I have my list, could you get me all of that, especially the last ingredient.' WHERE entry=2000005180;
UPDATE db_script_string SET content_default='Sure Paige. Just be gentle.' WHERE entry=2000005181;
UPDATE db_script_string SET content_default='Thanks, Charys. C''mon Paige, sweetie.' WHERE entry=2000005182;
UPDATE db_script_string SET content_default='Mommy? Can I pet Fizzles?' WHERE entry=2000005183;
UPDATE db_script_string SET content_default='Fizzles used to be a great wizard. But got turned into a rabbit when one of his spells went bad.' WHERE entry=2000005184;
UPDATE db_script_string SET content_default='学习魔法强化你的大脑?放松!' WHERE entry=2000005185;
UPDATE db_script_string SET content_default='在暴风城最好的饮料!' WHERE entry=2000005186;
UPDATE db_script_string SET content_default='蓝色的隐居者在上头。在那里所有的人都知道你的名字!' WHERE entry=2000005187;
UPDATE db_script_string SET content_default='感觉忧郁?快点下来和蓝色的隐居者过一段美好时光!' WHERE entry=2000005188;
UPDATE db_script_string SET content_default='在暴风城最好的饮料!' WHERE entry=2000005189;
UPDATE db_script_string SET content_default='学习魔法强化你的大脑?放松!' WHERE entry=2000005190;
UPDATE db_script_string SET content_default='问我你如何才能得到从蓝色隐居者手中获得一杯免费饮料!' WHERE entry=2000005191;
UPDATE db_script_string SET content_default='蓝色的隐居者在上头。在那里所有的人都知道你的名字!' WHERE entry=2000005192;
UPDATE db_script_string SET content_default='来自于蓝色隐居者的免费饮料!
来自于蓝色隐居者的免费饮料!' WHERE entry=2000005193;
UPDATE db_script_string SET content_default='感觉忧郁?快点下来和蓝色的隐居者过一段美好时光!' WHERE entry=2000005194;
UPDATE db_script_string SET content_default='学习魔法强化你的大脑?放松!' WHERE entry=2000005195;
UPDATE db_script_string SET content_default='在暴风城最好的饮料!' WHERE entry=2000005196;
UPDATE db_script_string SET content_default='问我你如何才能得到从蓝色隐居者手中获得一杯免费饮料!' WHERE entry=2000005197;
UPDATE db_script_string SET content_default='蓝色的隐居者在上头。在那里所有的人都知道你的名字!' WHERE entry=2000005198;
UPDATE db_script_string SET content_default='在暴风城最好的饮料!' WHERE entry=2000005199;
UPDATE db_script_string SET content_default='冲锋!' WHERE entry=2000005200;
UPDATE db_script_string SET content_default='冲锋!' WHERE entry=2000005201;
UPDATE db_script_string SET content_default='Ahh, my precious Ameenah! How wonderful to see you again.' WHERE entry=2000005202;
UPDATE db_script_string SET content_default='Yer wearin down, princess, I can sense it!' WHERE entry=2000005203;
UPDATE db_script_string SET content_default='Hmm, don''t mind if I do!' WHERE entry=2000005204;
UPDATE db_script_string SET content_default='It''s coming along, Wafflefry. Haven''t you got a product demonstration to do or something?' WHERE entry=2000005205;
UPDATE db_script_string SET content_default='Be the first on your block to own the incredible Electrostatic Maculation Blaster!' WHERE entry=2000005206;
UPDATE db_script_string SET content_default='Derived from cutting edge Shattered Hand Offensive military technology, it blasts away stubborn stains with ease!' WHERE entry=2000005207;
UPDATE db_script_string SET content_default='Wine stains, grass stains, even pet stains are no match for the Electrostatic Maculation Blaster!' WHERE entry=2000005208;
UPDATE db_script_string SET content_default='Don''t wait! Order now and receive my Ultra-Kinetic Waffle Iron at no additional charge!' WHERE entry=2000005209;
UPDATE db_script_string SET content_default='I''ll never stop. Never...' WHERE entry=2000005210;
UPDATE db_script_string SET content_default='所以,我们会看到…如果我没弄错的话,它…嗯…' WHERE entry=2000000077;
UPDATE db_script_string SET content_default='啊，是的。洛肯我知道的很清楚。' WHERE entry=2000000078;
UPDATE db_script_string SET content_default='这的确是一个神秘的过去!但也是未来的一个关键!' WHERE entry=2000000079;
UPDATE db_script_string SET content_default='这他在他们的战争中命令了铁的儿子反对我们。' WHERE entry=2000000080;
UPDATE db_script_string SET content_default='从他的藏身之地，他看了一场战争，其目的是破坏石巨人的筹备工作。' WHERE entry=2000000081;
UPDATE db_script_string SET content_default='这些大火已经燃烧好几年了。巨魔不寻常的奉献。' WHERE entry=2000005237;
UPDATE db_script_string SET content_default='奇怪…这些马赛克不像任何已知的巨魔的传统。' WHERE entry=2000005238;
UPDATE db_script_string SET content_default='是的,是的,我确信这代表了铸锭的实体。令人着迷。' WHERE entry=2000005239;
UPDATE db_script_string SET content_default='通过研究显示其能学习一种文化。' WHERE entry=2000005240;
UPDATE db_script_string SET content_default='呃。聚集的头发,羽毛、残骨,部分烧毁的资料-也许还有服装?' WHERE entry=2000005241;
UPDATE db_script_string SET content_default='正如将我们所有。' WHERE entry=2000000093;
UPDATE db_script_string SET content_default='隐形白酒已经为你准备好了,$ N。' WHERE entry=2000000094;
UPDATE db_script_string SET content_default='跛脚乔不问！但是 -是的，我知道洛肯。' WHERE entry=2000000082;
UPDATE db_script_string SET content_default='他要我抢！如果我在你的地方是这里的旅客。你永远不知道他是如何躲在树下！' WHERE entry=2000000083;
UPDATE db_script_string SET content_default='你太晚了，$N另一名达拉然的游客来到后，都在同一个巨龙叶片上获取信息' WHERE entry=2000000084;
UPDATE db_script_string SET content_default='从你的描述而言，我肯定，我借给的书可以让旅客轻松识别你的武器。' WHERE entry=2000000085;
UPDATE db_script_string SET content_default='我们不能容忍任何恶魔的仆人在我们的家园出现!' WHERE entry=2000000090;
UPDATE db_script_string SET content_default='Ribbit ! 不! ! !这是绝对不可能…ribbit…!你骗我…. ribbit……你的诡计!Ribbit !' WHERE entry=2000000091;
UPDATE db_script_string SET content_default='“嘿,Belm !给我一个马克杯的雷声,一袋啤酒给我的好朋友!' WHERE entry=2000000092;
UPDATE db_script_string SET content_default='我怕你不得不问--当然，也许卡雷苟斯会帮助。' WHERE entry=2000000086;
UPDATE db_script_string SET content_default='我们走了!谢谢!' WHERE entry=2000000087;
UPDATE db_script_string SET content_default='嘿，我希望你帮帮我！' WHERE entry=2000000088;
UPDATE db_script_string SET content_default='从群星之中!一种精神已经被召唤出来的!' WHERE entry=2000000089;
UPDATE db_script_string SET content_default='这是它！ 这真的它－－大乌鸦的帐本！' WHERE entry=2000000004;
UPDATE db_script_string SET content_default='一旦我们的敌人转而反对我们，我们强大的武器。是什么让你觉得棱形刀片将有什么不同？' WHERE entry=2000000105;
UPDATE db_script_string SET content_default='如你愿意，我的皇后。我不会站在他们的对面，但我会继续密切留意。' WHERE entry=2000000106;
UPDATE db_script_string SET content_default='西部荒野的人民敬礼,$N,一个自由的勇敢的防御者。' WHERE entry=2000000028;
UPDATE db_script_string SET content_default='$N 可能已经找到了一个棱柱形叶片，卡雷苟斯依然存在。是否会提供给予您协助的旅客？' WHERE entry=2000000095;
UPDATE db_script_string SET content_default='你相信我们的盟友将无法控制的剑的力量？' WHERE entry=2000000096;
UPDATE db_script_string SET content_default='致命的冠军们长期使用这些武器，打击邪恶。我认为没有理由不让他们在这场战斗用剑。' WHERE entry=2000000097;
UPDATE db_script_string SET content_default='你必须保护我履行我的命运!' WHERE entry=2000000098;
UPDATE db_script_string SET content_default='这不会花很长时间…
这不会花很长时间…' WHERE entry=2000000099;
UPDATE db_script_string SET content_default='你肯定你应该帮助他们对剑的追求这些凡人？' WHERE entry=2000000100;
UPDATE db_script_string SET content_default='这些刀片，克拉苏斯...他们在很久以前，事情就不同了。' WHERE entry=2000000101;
UPDATE db_script_string SET content_default='We really should fix this fence soon.' WHERE entry=2000005400;
UPDATE db_script_string SET content_default='*sigh* It''s about time to check on the cemetary again-- Ill be back in a few minutes.' WHERE entry=2000005401;
UPDATE db_script_string SET content_default='How long can it take to pick a handful of weeds?' WHERE entry=2000005402;
UPDATE db_script_string SET content_default='At this rate I could have gathered them myself!' WHERE entry=2000005403;
UPDATE db_script_string SET content_default='Ah, this must be him now... no? Bah!' WHERE entry=2000005404;
UPDATE db_script_string SET content_default='As if I had all eternity.' WHERE entry=2000005405;
UPDATE db_script_string SET content_default='We''re running low on iron, lads! I don''t want to see a single bar go to waste, ye hear me now?' WHERE entry=2000005406;
UPDATE db_script_string SET content_default='Not bad. Try that trick I told you about when you temper the steel.' WHERE entry=2000005407;
UPDATE db_script_string SET content_default='当我的变化出现...我的妻子和孩子们…' WHERE entry=2000000138;
UPDATE db_script_string SET content_default='Stonemasons. . .errr. . Defias be warned:  The rusty anchor sinks tonight.' WHERE entry=2000005408;
UPDATE db_script_string SET content_default='%s calls upon the mighty armies of the Scourge!' WHERE entry=2000005409;
UPDATE db_script_string SET content_default='Armies of the Scourge, hear my call! The scarlet apocalypse has begun! Tear this land asunder and leave only death in your wake!' WHERE entry=2000005410;
UPDATE db_script_string SET content_default='它会花数年在没有你的情况下找大乌鸦的帐本，年轻的雀鹰和我们感谢的心情伴随你回到你的家。' WHERE entry=2000000005;
UPDATE db_script_string SET content_default='他们是跟随我，$R!  很快地，在我们被发现之前告诉我你为什么在这里！ 如果他们决定抓我，它将会意味着我和你一起死亡！' WHERE entry=2000000006;
UPDATE db_script_string SET content_default='你－－你不是他们的其中之一！ 在他们找到我们之前，让我们离开这里！快！' WHERE entry=2000000007;
UPDATE db_script_string SET content_default='你正在亚瑟的王国做什么？无营业执照者！我叫道，离开我们！ 你的货物在这里不受欢迎！' WHERE entry=2000000008;
UPDATE db_script_string SET content_default='[PH]你好, $N.' WHERE entry=2000000107;
UPDATE db_script_string SET content_default='检查炮弹...' WHERE entry=2000000108;

