SET NAMES 'utf8';
UPDATE game_event SET description='仲夏火焰节' WHERE entry=1;
UPDATE game_event SET description='冬幕节' WHERE entry=2;
UPDATE game_event SET description='除夕' WHERE entry=6;
UPDATE game_event SET description='春节' WHERE entry=7;
UPDATE game_event SET description='情人节' WHERE entry=8;
UPDATE game_event SET description='冬幕节 - 礼物' WHERE entry=9;
UPDATE game_event SET description='儿童周' WHERE entry=10;
UPDATE game_event SET description='收获节' WHERE entry=11;
UPDATE game_event SET description='万圣节' WHERE entry=12;
UPDATE game_event SET description='元素入侵-火' WHERE entry=13;
UPDATE game_event SET description='元素入侵-气' WHERE entry=14;
UPDATE game_event SET description='元素入侵-土' WHERE entry=15;
UPDATE game_event SET description='古拉巴什竞技场战斗' WHERE entry=16;
UPDATE game_event SET description='天灾入侵' WHERE entry=17;
UPDATE game_event SET description='战斗的召唤：奥特兰克山谷' WHERE entry=18;
UPDATE game_event SET description='战斗的召唤：战歌峡谷' WHERE entry=19;
UPDATE game_event SET description='战斗的召唤：阿拉希盆地' WHERE entry=20;
UPDATE game_event SET description='战斗的召唤：风暴之眼' WHERE entry=21;
UPDATE game_event SET description='安其拉之战' WHERE entry=22;
UPDATE game_event SET description='焚木村 - 夜幕天灾诅咒' WHERE entry=23;
UPDATE game_event SET description='暴风城 - 监狱越狱' WHERE entry=24;
UPDATE game_event SET description='美酒节' WHERE entry=26;
UPDATE game_event SET description='夜幕' WHERE entry=27;
UPDATE game_event SET description='复活节' WHERE entry=28;
UPDATE game_event SET description='祖尔格拉布 - 疯狂之缘(格里雷克)' WHERE entry=29;
UPDATE game_event SET description='祖尔格拉布 - 疯狂之缘(哈扎拉尔)' WHERE entry=30;
UPDATE game_event SET description='祖尔格拉布 - 疯狂之缘(雷纳塔基)' WHERE entry=31;
UPDATE game_event SET description='祖尔格拉布 - 疯狂之缘(乌苏雷)' WHERE entry=32;
UPDATE game_event SET description='竞技场评级赛' WHERE entry=33;
UPDATE game_event SET description='荆棘谷钓鱼大赛 - 通告' WHERE entry=34;
UPDATE game_event SET description='荆棘谷钓鱼大赛' WHERE entry=35;
UPDATE game_event SET description='荆棘谷钓鱼大赛 - 上缴' WHERE entry=36;
UPDATE game_event SET description='暗月马戏团(莫高雷) - 建设阶段1' WHERE entry=39;
UPDATE game_event SET description='暗月马戏团(莫高雷) - 建设阶段2' WHERE entry=40;
UPDATE game_event SET description='海盗节' WHERE entry=44;
UPDATE game_event SET description='竞技场评级赛第1季' WHERE entry=53;
UPDATE game_event SET description='竞技场评级赛第2季' WHERE entry=54;
UPDATE game_event SET description='竞技场评级赛第3季' WHERE entry=55;
UPDATE game_event SET description='竞技场评级赛第4季' WHERE entry=56;
UPDATE game_event SET description='世界的尽头小酒馆 - 派瑞·加奈尔通告' WHERE entry=57;
UPDATE game_event SET description='世界的尽头小酒馆 -  派瑞·加奈尔喜剧' WHERE entry=58;
UPDATE game_event SET description='世界的尽头小酒馆 - L70ETC音乐会通告' WHERE entry=59;
UPDATE game_event SET description='世界的尽头小酒馆 - L70ETC音乐会' WHERE entry=60;
UPDATE game_event SET description='黑铁酒吧 - L70ETC音乐会排练' WHERE entry=61;
UPDATE game_event SET description='黑铁酒吧 - L70ETC音乐会' WHERE entry=62;
UPDATE game_event SET description='L70ETC 音乐会 - 泰罗卡森林(暴雪嘉年华)' WHERE entry=63;
UPDATE game_event SET description='美酒俱乐部 - 一月' WHERE entry=64;
UPDATE game_event SET description='美酒俱乐部 - 二月' WHERE entry=65;
UPDATE game_event SET description='美酒俱乐部 - 三月' WHERE entry=66;
UPDATE game_event SET description='美酒俱乐部 - 四月' WHERE entry=67;
UPDATE game_event SET description='美酒俱乐部 - 五月' WHERE entry=68;
UPDATE game_event SET description='美酒俱乐部 - 六月' WHERE entry=69;
UPDATE game_event SET description='美酒俱乐部 - 七月' WHERE entry=70;
UPDATE game_event SET description='美酒俱乐部 - 八月' WHERE entry=71;
UPDATE game_event SET description='美酒俱乐部 - 九月' WHERE entry=72;
UPDATE game_event SET description='美酒俱乐部 - 十月' WHERE entry=73;
UPDATE game_event SET description='美酒俱乐部 - 十一月' WHERE entry=74;
UPDATE game_event SET description='美酒俱乐部 - 十二月' WHERE entry=75;
UPDATE game_event SET description='暗月马戏团(泰罗卡森林) - June 2018 - Building Stage 1' WHERE entry=76;
UPDATE game_event SET description='暗月马戏团(泰罗卡森林) - June 2018 - Building Stage 2' WHERE entry=77;
UPDATE game_event SET description='暗月马戏团(泰罗卡森林) - June 2018 - Darkmoon Faire Open' WHERE entry=78;
UPDATE game_event SET description='暗月马戏团(莫高雷) - July 2018 - Building Stage 1' WHERE entry=79;
UPDATE game_event SET description='暗月马戏团(莫高雷) - July 2018 - Building Stage 2' WHERE entry=80;
UPDATE game_event SET description='暗月马戏团(莫高雷) - July 2018 - Darkmoon Faire Open' WHERE entry=81;
UPDATE game_event SET description='暗月马戏团(艾尔文森林) - August 2018 - Building Stage 1' WHERE entry=82;
UPDATE game_event SET description='暗月马戏团(艾尔文森林) - August 2018 - Building Stage 2' WHERE entry=83;
UPDATE game_event SET description='暗月马戏团(艾尔文森林) - August 2018 - Darkmoon Faire Open' WHERE entry=84;
UPDATE game_event SET description='暗月马戏团(泰罗卡森林) - September 2018 - Building Stage 1' WHERE entry=85;
UPDATE game_event SET description='暗月马戏团(泰罗卡森林) - September 2018 - Building Stage 2' WHERE entry=86;
UPDATE game_event SET description='暗月马戏团(泰罗卡森林) - September 2018 - Darkmoon Faire Open' WHERE entry=87;
UPDATE game_event SET description='暗月马戏团(莫高雷) - October 2018 - Building Stage 1' WHERE entry=88;
UPDATE game_event SET description='暗月马戏团(莫高雷) - October 2018 - Building Stage 2' WHERE entry=89;
UPDATE game_event SET description='暗月马戏团(莫高雷) - October 2018 - Darkmoon Faire Open' WHERE entry=90;
UPDATE game_event SET description='暗月马戏团(艾尔文森林) - November 2018 - Building Stage 1' WHERE entry=91;
UPDATE game_event SET description='暗月马戏团(艾尔文森林) - November 2018 - Building Stage 2' WHERE entry=92;
UPDATE game_event SET description='暗月马戏团(艾尔文森林) - November 2018 - Darkmoon Faire Open' WHERE entry=93;
UPDATE game_event SET description='暗月马戏团(泰罗卡森林) - December 2018 - Building Stage 1' WHERE entry=94;
UPDATE game_event SET description='暗月马戏团(泰罗卡森林) - December 2018 - Building Stage 2' WHERE entry=95;
UPDATE game_event SET description='暗月马戏团(泰罗卡森林) - December 2018 - Darkmoon Faire Open' WHERE entry=96;
UPDATE game_event SET description='暗月马戏团(莫高雷) - January 2019 - Building Stage 1' WHERE entry=97;
UPDATE game_event SET description='暗月马戏团(莫高雷) - January 2019 - Building Stage 2' WHERE entry=98;
UPDATE game_event SET description='暗月马戏团(莫高雷) - January 2019 - Darkmoon Faire Open' WHERE entry=99;
UPDATE game_event SET description='暗月马戏团(艾尔文森林) - February 2019 - Building Stage 1' WHERE entry=100;
UPDATE game_event SET description='暗月马戏团(艾尔文森林) - February 2019 - Building Stage 2' WHERE entry=101;
UPDATE game_event SET description='暗月马戏团(艾尔文森林) - February 2019 - Darkmoon Faire Open' WHERE entry=102;
UPDATE game_event SET description='暗月马戏团(泰罗卡森林) - March 2018 - Building Stage 1' WHERE entry=103;
UPDATE game_event SET description='暗月马戏团(泰罗卡森林) - March 2018 - Building Stage 2' WHERE entry=104;
UPDATE game_event SET description='暗月马戏团(泰罗卡森林) - March 2018 - Darkmoon Faire Open' WHERE entry=105;
UPDATE game_event SET description='暗月马戏团(莫高雷) - April 2018 - Building Stage 1' WHERE entry=106;
UPDATE game_event SET description='暗月马戏团(莫高雷) - April 2018 - Building Stage 2' WHERE entry=107;
UPDATE game_event SET description='暗月马戏团(莫高雷) - April 2018 - Darkmoon Faire Open' WHERE entry=108;
UPDATE game_event SET description='暗月马戏团(艾尔文森林) - May 2018 - Building Stage 1' WHERE entry=109;
UPDATE game_event SET description='暗月马戏团(艾尔文森林) - May 2018 - Building Stage 2' WHERE entry=110;
UPDATE game_event SET description='暗月马戏团(艾尔文森林) - May 2018 - Darkmoon Faire Open' WHERE entry=111;
UPDATE game_event SET description='万圣节 - 稻草人余烬' WHERE entry=112;
UPDATE game_event SET description='万圣节 - 希尔瓦娜丝' WHERE entry=113;
UPDATE game_event SET description='随机日常副本 - 悬赏: 禁魔监狱斥候' WHERE entry=1000;
UPDATE game_event SET description='随机日常副本 - 悬赏: 盘牙侍从' WHERE entry=1001;
UPDATE game_event SET description='随机日常副本 - 悬赏: 恶毒导师' WHERE entry=1002;
UPDATE game_event SET description='随机日常副本 - 悬赏: 裂隙领主' WHERE entry=1003;
UPDATE game_event SET description='随机日常副本 - 悬赏: 碎手百夫长' WHERE entry=1004;
UPDATE game_event SET description='随机日常副本 - 悬赏: 寻日者导魔者' WHERE entry=1005;
UPDATE game_event SET description='随机日常副本 - 悬赏: 风暴锻铸摧毁者' WHERE entry=1006;
UPDATE game_event SET description='随机日常副本 - 悬赏: 痛苦妖女' WHERE entry=1007;
UPDATE game_event SET description='随机日常英雄 - 悬赏: 纳杉的骑鞭' WHERE entry=1008;
UPDATE game_event SET description='随机日常英雄 - 悬赏: 黑色阔步者的卵' WHERE entry=1009;
UPDATE game_event SET description='随机日常英雄 - 悬赏: 扭木碎片' WHERE entry=1010;
UPDATE game_event SET description='随机日常英雄 - 悬赏: 埃欧努斯的沙漏' WHERE entry=1011;
UPDATE game_event SET description='随机日常英雄 - 悬赏: 刃拳的印记' WHERE entry=1012;
UPDATE game_event SET description='随机日常英雄 - 悬赏: 克里丹的羽饰法杖' WHERE entry=1013;
UPDATE game_event SET description='随机日常英雄 - 悬赏: 摩摩尔的低语' WHERE entry=1014;
UPDATE game_event SET description='随机日常英雄 - 悬赏: 帕萨雷恩的投影仪' WHERE entry=1015;
UPDATE game_event SET description='随机日常英雄 - 悬赏: 沙法尔的精致饰物' WHERE entry=1016;
UPDATE game_event SET description='随机日常英雄 - 悬赏: 时空猎手的徽记' WHERE entry=1017;
UPDATE game_event SET description='随机日常英雄 - 悬赏: 主教的灵魂宝钻' WHERE entry=1018;
UPDATE game_event SET description='随机日常英雄 - 悬赏: 艾吉斯的冠羽' WHERE entry=1019;
UPDATE game_event SET description='随机日常英雄 - 悬赏: 夸格米拉之心' WHERE entry=1020;
UPDATE game_event SET description='随机日常英雄 - 悬赏: 斯克瑞斯的卷轴' WHERE entry=1021;
UPDATE game_event SET description='随机日常英雄 - 悬赏: 督军的论文' WHERE entry=1022;
UPDATE game_event SET description='随机日常英雄 - 悬赏: 凯尔萨斯王子的徽记之戒' WHERE entry=1023;
UPDATE game_event SET description='钟声(每个小时) ' WHERE entry=1024;
UPDATE game_event SET description='随机日常PVP - 战斗的召唤: 阿拉希盆地' WHERE entry=1025;
UPDATE game_event SET description='随机日常PVP - 战斗的召唤: 奥特兰克山谷' WHERE entry=1026;
UPDATE game_event SET description='随机日常PVP - 战斗的召唤: 风暴之眼' WHERE entry=1027;
UPDATE game_event SET description='随机日常PVP - 战斗的召唤: 战歌峡谷' WHERE entry=1028;
UPDATE game_event SET description='烹饪-随机日常-甜美的复仇' WHERE entry=1127;
UPDATE game_event SET description='烹饪-随机日常-超级美味烧烤' WHERE entry=1128;
UPDATE game_event SET description='烹饪-随机日常-魔法美味' WHERE entry=1129;
UPDATE game_event SET description='烹饪-随机日常-灵魂之汤' WHERE entry=1130;
UPDATE game_event SET description='钓鱼-随机日常-城中的鳄鱼' WHERE entry=1131;
UPDATE game_event SET description='钓鱼-随机日常-黑鳞镖鲈' WHERE entry=1132;
UPDATE game_event SET description='钓鱼-随机日常-世界上最大的泥鱼' WHERE entry=1133;
UPDATE game_event SET description='钓鱼-随机日常-巨型淡水虾' WHERE entry=1134;
UPDATE game_event SET description='钓鱼-随机日常-魔血鲷鱼' WHERE entry=1135;
