UPDATE mangos_string SET content_loc4='你需要选择一个玩家角色或者生物' WHERE entry=1;
UPDATE mangos_string SET content_loc4='你需要选择一个生物' WHERE entry=2;
UPDATE mangos_string SET content_loc4='|cffff0000[系统消息]: %s|r' WHERE entry=3;
UPDATE mangos_string SET content_loc4='|cffff0000[事件消息]: %s|r' WHERE entry=4;
UPDATE mangos_string SET content_loc4='没有此指令的帮助信息' WHERE entry=5;
UPDATE mangos_string SET content_loc4='该指令不存在' WHERE entry=6;
UPDATE mangos_string SET content_loc4='没有此类子指令' WHERE entry=7;
UPDATE mangos_string SET content_loc4='指令的 %s 子指令有:' WHERE entry=8;
UPDATE mangos_string SET content_loc4='你可以使用的指令有:' WHERE entry=9;
UPDATE mangos_string SET content_loc4='指令语法格式错误.' WHERE entry=10;
UPDATE mangos_string SET content_loc4='你的账号级别是: %i' WHERE entry=11;
UPDATE mangos_string SET content_loc4='在线人数: %u (最多: %u)' WHERE entry=12;
UPDATE mangos_string SET content_loc4='服务器正常运行时间: %s' WHERE entry=13;
UPDATE mangos_string SET content_loc4='玩家数据保存成功.' WHERE entry=14;
UPDATE mangos_string SET content_loc4='保存所有玩家数据成功.' WHERE entry=15;
UPDATE mangos_string SET content_loc4='当前在线管理员:' WHERE entry=16;
UPDATE mangos_string SET content_loc4='当前没有管理员在线.' WHERE entry=17;
UPDATE mangos_string SET content_loc4='飞行时不能那样做.' WHERE entry=18;
UPDATE mangos_string SET content_loc4='战场中不能那样做.' WHERE entry=19;
UPDATE mangos_string SET content_loc4='目标在飞行状态中，你不能那样做.' WHERE entry=20;
UPDATE mangos_string SET content_loc4='%s 在飞行状态中, 指令无效.' WHERE entry=21;
UPDATE mangos_string SET content_loc4='没有上马，因此你不能下马.' WHERE entry=22;
UPDATE mangos_string SET content_loc4='战斗中不能那样做.' WHERE entry=23;
UPDATE mangos_string SET content_loc4='你最近刚使用过.' WHERE entry=24;
UPDATE mangos_string SET content_loc4='密码修改失败(未知错误)!' WHERE entry=25;
UPDATE mangos_string SET content_loc4='密码已经修改' WHERE entry=26;
UPDATE mangos_string SET content_loc4='旧密码是错误的' WHERE entry=27;
UPDATE mangos_string SET content_loc4='你的帐号已被锁定' WHERE entry=28;
UPDATE mangos_string SET content_loc4='你的账号取消锁定' WHERE entry=29;
UPDATE mangos_string SET content_loc4=', 等级 ' WHERE entry=30;
UPDATE mangos_string SET content_loc4=' [学会]' WHERE entry=31;
UPDATE mangos_string SET content_loc4=' [学习]' WHERE entry=32;
UPDATE mangos_string SET content_loc4=' [被动]' WHERE entry=33;
UPDATE mangos_string SET content_loc4=' [天赋]' WHERE entry=34;
UPDATE mangos_string SET content_loc4=' [激活]' WHERE entry=35;
UPDATE mangos_string SET content_loc4=' [完成]' WHERE entry=36;
UPDATE mangos_string SET content_loc4=' (离线)' WHERE entry=37;
UPDATE mangos_string SET content_loc4='开启' WHERE entry=38;
UPDATE mangos_string SET content_loc4='关闭' WHERE entry=39;
UPDATE mangos_string SET content_loc4='你是: %s' WHERE entry=40;
UPDATE mangos_string SET content_loc4='显示' WHERE entry=41;
UPDATE mangos_string SET content_loc4='隐藏' WHERE entry=42;
UPDATE mangos_string SET content_loc4='完成' WHERE entry=43;
UPDATE mangos_string SET content_loc4='你' WHERE entry=44;
UPDATE mangos_string SET content_loc4=' <未知> ' WHERE entry=45;
UPDATE mangos_string SET content_loc4='<错误>' WHERE entry=46;
UPDATE mangos_string SET content_loc4='<玩家不存在>' WHERE entry=47;
UPDATE mangos_string SET content_loc4='未知' WHERE entry=48;
UPDATE mangos_string SET content_loc4='你至少需要%u级才能进入.' WHERE entry=49;
UPDATE mangos_string SET content_loc4='你至少需要%u级并且拥有道具%s才能进入.' WHERE entry=50;
UPDATE mangos_string SET content_loc4='你好！准备好接受训练了吗？' WHERE entry=51;
UPDATE mangos_string SET content_loc4='Invaid item count (%u) for item %u' WHERE entry=52;
UPDATE mangos_string SET content_loc4='Mail can\'t have more %u item stacks' WHERE entry=53;
UPDATE mangos_string SET content_loc4='新旧密码不匹配' WHERE entry=54;
UPDATE mangos_string SET content_loc4='你的密码长度不能超过16个字符（客户端限制），密码未更改!' WHERE entry=55;
UPDATE mangos_string SET content_loc4='今日消息：%s' WHERE entry=56;
UPDATE mangos_string SET content_loc4='世界数据库: %s' WHERE entry=57;
UPDATE mangos_string SET content_loc4='脚本库' WHERE entry=58;
UPDATE mangos_string SET content_loc4='生物EventAI: %s' WHERE entry=59;
UPDATE mangos_string SET content_loc4='用户名: ' WHERE entry=61;
UPDATE mangos_string SET content_loc4='密码: ' WHERE entry=62;
UPDATE mangos_string SET content_loc4='接受悄悄话' WHERE entry=63;
UPDATE mangos_string SET content_loc4='不接受悄悄话' WHERE entry=64;
UPDATE mangos_string SET content_loc4='脚本库：<未知脚本库>' WHERE entry=65;
UPDATE mangos_string SET content_loc4='脚本库：<不存在脚本库>' WHERE entry=66;
UPDATE mangos_string SET content_loc4='全体注意：' WHERE entry=100;
UPDATE mangos_string SET content_loc4='地图: %u (%s) 区域: %u (%s) 地区: %u (%s)\r\nX: %f Y: %f Z: %f Orientation: %f\r\ngrid[%u,%u]cell[%u,%u] InstanceID: %u\r\n ZoneX: %f ZoneY: %f\r\nGroundZ: %f FloorZ: %f Have height data (Map: %u VMap: %u)' WHERE entry=101;
UPDATE mangos_string SET content_loc4='%s正在被传送中.' WHERE entry=102;
UPDATE mangos_string SET content_loc4='只有对方在你的队伍中并且你是队长才能召唤他到你附近.' WHERE entry=103;
UPDATE mangos_string SET content_loc4='你无法传送到玩家的副本，你们不在同一队伍.' WHERE entry=104;
UPDATE mangos_string SET content_loc4='传送到不是同一队伍的玩家的副本需要开启ＧＭ模式.' WHERE entry=105;
UPDATE mangos_string SET content_loc4='你无法传送到玩家 %s 从副本到副本.' WHERE entry=106;
UPDATE mangos_string SET content_loc4='你不能召唤这个玩家 %s 从副本到副本.' WHERE entry=107;
UPDATE mangos_string SET content_loc4='你正在召唤 %s%s.' WHERE entry=108;
UPDATE mangos_string SET content_loc4='你正在被 %s 召唤中.' WHERE entry=109;
UPDATE mangos_string SET content_loc4='你正在传送  %s%s 到 %s.' WHERE entry=110;
UPDATE mangos_string SET content_loc4='你正在被 %s 传送.' WHERE entry=111;
UPDATE mangos_string SET content_loc4='玩家 (%s) 不存在.' WHERE entry=112;
UPDATE mangos_string SET content_loc4='出现在 %s 的位置.' WHERE entry=113;
UPDATE mangos_string SET content_loc4='%s 出现在你的位置.' WHERE entry=114;
UPDATE mangos_string SET content_loc4='无效参数.' WHERE entry=115;
UPDATE mangos_string SET content_loc4='没有选择角色.' WHERE entry=116;
UPDATE mangos_string SET content_loc4='%s不在一个队伍中.' WHERE entry=117;
UPDATE mangos_string SET content_loc4='你改变 %s 的血量值到 %i/%i.' WHERE entry=118;
UPDATE mangos_string SET content_loc4='%s 改变你的血量值到 %i/%i.' WHERE entry=119;
UPDATE mangos_string SET content_loc4='你改变 %s 的魔法值到 %i/%i.' WHERE entry=120;
UPDATE mangos_string SET content_loc4='%s 改变你的魔法值到 %i/%i.' WHERE entry=121;
UPDATE mangos_string SET content_loc4='你改变 %s 的能量值到 %i/%i.' WHERE entry=122;
UPDATE mangos_string SET content_loc4='%s 改变你的能量值到 %i/%i.' WHERE entry=123;
UPDATE mangos_string SET content_loc4='当前的能量: %u' WHERE entry=124;
UPDATE mangos_string SET content_loc4='你改变 %s 的怒气值到 %i/%i.' WHERE entry=125;
UPDATE mangos_string SET content_loc4='%s 改变你的怒气值到 %i/%i.' WHERE entry=126;
UPDATE mangos_string SET content_loc4='你改变 %s 的等级到 %i.' WHERE entry=127;
UPDATE mangos_string SET content_loc4='GUID %i, faction is %i, flags is %i, npcflag is %i, DY flag is %i' WHERE entry=128;
UPDATE mangos_string SET content_loc4='错误的阵营: %u (factiontemplate.dbc不存在该阵营).' WHERE entry=129;
UPDATE mangos_string SET content_loc4='You changed GUID=%i \'s Faction to %i, flags to %i, npcflag to %i, dyflag to %i.' WHERE entry=130;
UPDATE mangos_string SET content_loc4='You changed the %s spellmod %u to value %i for spell with family bit %u for %s.' WHERE entry=131;
UPDATE mangos_string SET content_loc4='%s changed your spellmod %u to value %i for spell with family bit %u.' WHERE entry=132;
UPDATE mangos_string SET content_loc4='%s 获得了所有的飞行节点 (直到注销).' WHERE entry=133;
UPDATE mangos_string SET content_loc4='%s 现在不能显示所有飞行节点(仅显示已开通的).' WHERE entry=134;
UPDATE mangos_string SET content_loc4='%s 改变了你所有的飞行节点 (直到注销).' WHERE entry=135;
UPDATE mangos_string SET content_loc4='%s 已取消所有飞行节点(仅显示已开通的).' WHERE entry=136;
UPDATE mangos_string SET content_loc4='你设置所有的速度到 %2.2f 从基础值 %s.' WHERE entry=137;
UPDATE mangos_string SET content_loc4='%s 设置你所有的速度到 %2.2f 从基础值.' WHERE entry=138;
UPDATE mangos_string SET content_loc4='你设置移动速度到 %2.2f 从基础值 %s.' WHERE entry=139;
UPDATE mangos_string SET content_loc4='%s 设置你的移动速度到 %2.2f 从基础值.' WHERE entry=140;
UPDATE mangos_string SET content_loc4='你设置游泳速度到 %2.2f 从基础值 %s.' WHERE entry=141;
UPDATE mangos_string SET content_loc4='%s 设置你的游泳速度到 %2.2f 从基础值.' WHERE entry=142;
UPDATE mangos_string SET content_loc4='你设置后退速度到 %2.2f 从基础值 %s.' WHERE entry=143;
UPDATE mangos_string SET content_loc4='%s 设置你的后退速度到 %2.2f 从基础值.' WHERE entry=144;
UPDATE mangos_string SET content_loc4='你设置飞行速度到 %2.2f 从基础值 %s.' WHERE entry=145;
UPDATE mangos_string SET content_loc4='%s 设置你的飞行速度到 %2.2f 从基础值.' WHERE entry=146;
UPDATE mangos_string SET content_loc4='你设置模型大小 %2.2f 到 %s.' WHERE entry=147;
UPDATE mangos_string SET content_loc4='%s 设置你的模型大小到 %2.2f' WHERE entry=148;
UPDATE mangos_string SET content_loc4='没有此类坐骑.' WHERE entry=149;
UPDATE mangos_string SET content_loc4='你把一个坐骑.送给 %s.' WHERE entry=150;
UPDATE mangos_string SET content_loc4='%s 送给你一个坐骑.' WHERE entry=151;
UPDATE mangos_string SET content_loc4='用户1: %i, 添加: %i, 结果: %i' WHERE entry=152;
UPDATE mangos_string SET content_loc4='你拿走了所有的铜币从 %s.' WHERE entry=153;
UPDATE mangos_string SET content_loc4='%s 拿走了你所有的铜币.' WHERE entry=154;
UPDATE mangos_string SET content_loc4='你拿走了 %i 铜币从 %s.' WHERE entry=155;
UPDATE mangos_string SET content_loc4='%s 拿走了 %i 铜币从你这里.' WHERE entry=156;
UPDATE mangos_string SET content_loc4='你把 %i 铜币给了 %s.' WHERE entry=157;
UPDATE mangos_string SET content_loc4='%s 给你 %i  铜币.' WHERE entry=158;
UPDATE mangos_string SET content_loc4='你听到声音 %u.' WHERE entry=159;
UPDATE mangos_string SET content_loc4='用户2: %i, 添加: %i, 结果: %i' WHERE entry=160;
UPDATE mangos_string SET content_loc4='Removed bit %i in field %i.' WHERE entry=161;
UPDATE mangos_string SET content_loc4='Set bit %i in field %i.' WHERE entry=162;
UPDATE mangos_string SET content_loc4='传送地点表是空的!' WHERE entry=163;
UPDATE mangos_string SET content_loc4='传送地点没被发现!' WHERE entry=164;
UPDATE mangos_string SET content_loc4='需要搜索参数.' WHERE entry=165;
UPDATE mangos_string SET content_loc4='没有传送地点匹配您的请求.' WHERE entry=166;
UPDATE mangos_string SET content_loc4='发现地点是: %s' WHERE entry=168;
UPDATE mangos_string SET content_loc4='邮件寄给 %s' WHERE entry=169;
UPDATE mangos_string SET content_loc4='你试着听声音 %u 但是它并不存在.' WHERE entry=170;
UPDATE mangos_string SET content_loc4='你不能传送自己!' WHERE entry=171;
UPDATE mangos_string SET content_loc4='服务器控制台指令' WHERE entry=172;
UPDATE mangos_string SET content_loc4='Liquid level: %f, ground: %f, type flags %u, status: %d.' WHERE entry=175;
UPDATE mangos_string SET content_loc4='没有选择.' WHERE entry=200;
UPDATE mangos_string SET content_loc4='Object GUID is: %s' WHERE entry=201;
UPDATE mangos_string SET content_loc4='这个名字长度超过了 %i 字符.' WHERE entry=202;
UPDATE mangos_string SET content_loc4='错误,名字只能包含字符 A-Z 和 a-z.' WHERE entry=203;
UPDATE mangos_string SET content_loc4='次级名字太长超过了 %i 字符.' WHERE entry=204;
UPDATE mangos_string SET content_loc4='未能改变' WHERE entry=205;
UPDATE mangos_string SET content_loc4='物品 ’%i’ ’%s’以加入到列表且最大数 ’%i’刷新时间 ’%i’ 额外费用 \'%i\'' WHERE entry=206;
UPDATE mangos_string SET content_loc4='物品 ’%i’ 在数据库里没有找到.' WHERE entry=207;
UPDATE mangos_string SET content_loc4='物品 ’%i’ ’%s’ 已经从商人列表中删除.' WHERE entry=208;
UPDATE mangos_string SET content_loc4='物品 ’%i’ 在商人的列表里不存在.' WHERE entry=209;
UPDATE mangos_string SET content_loc4='物品 ’%i’ 已存在于商人的列表里.' WHERE entry=210;
UPDATE mangos_string SET content_loc4='法术 %s 重置.' WHERE entry=211;
UPDATE mangos_string SET content_loc4='法术 %s 将在下次登陆时重置.' WHERE entry=212;
UPDATE mangos_string SET content_loc4='天赋 %s 重置.' WHERE entry=213;
UPDATE mangos_string SET content_loc4='天赋 %s 将在下次登陆时重置.' WHERE entry=214;
UPDATE mangos_string SET content_loc4='你的技能已经重置了.' WHERE entry=215;
UPDATE mangos_string SET content_loc4='你的天赋已经重置了.' WHERE entry=216;
UPDATE mangos_string SET content_loc4='未知的参数  ’%s’ 为 .resetall 命令. 键入完整的正确参数名字.' WHERE entry=217;
UPDATE mangos_string SET content_loc4='设置所有玩家在重新登录后重置法术, 建议重新登录!' WHERE entry=218;
UPDATE mangos_string SET content_loc4='设置所有玩家在重新登录后重置天赋, 建议重新登录!' WHERE entry=219;
UPDATE mangos_string SET content_loc4='Cannot find waypoint id %u for %s (in path %i, loaded from %s)' WHERE entry=220;
UPDATE mangos_string SET content_loc4='Last Waypoint not found for %s' WHERE entry=221;
UPDATE mangos_string SET content_loc4='%s has no path or path empty, path-id %i (loaded from %s)' WHERE entry=222;
UPDATE mangos_string SET content_loc4='Creature (GUID: %u) No waypoints found - This is a MaNGOS db problem (single float).' WHERE entry=223;
UPDATE mangos_string SET content_loc4='Cannot access %s on map, maybe you are too far away from its spawn location' WHERE entry=224;
UPDATE mangos_string SET content_loc4='生物 (GUID: %u) 没有找到.' WHERE entry=225;
UPDATE mangos_string SET content_loc4='您必须选择一个路径点.' WHERE entry=226;
UPDATE mangos_string SET content_loc4='没有找到路径点.' WHERE entry=227;
UPDATE mangos_string SET content_loc4='不能与生物ID: %d 创建路径点' WHERE entry=228;
UPDATE mangos_string SET content_loc4='清理所有路径点.' WHERE entry=229;
UPDATE mangos_string SET content_loc4='Could not add waypoint %u to %s (pathId %i stored by %s)' WHERE entry=230;
UPDATE mangos_string SET content_loc4='没有设置GUID.' WHERE entry=231;
UPDATE mangos_string SET content_loc4='没有设置路径点.' WHERE entry=232;
UPDATE mangos_string SET content_loc4='需要参数 \'%s\'.' WHERE entry=233;
UPDATE mangos_string SET content_loc4='Added Waypoint %u to %s (PathId %i, path stored by %s)' WHERE entry=234;
UPDATE mangos_string SET content_loc4='未使用' WHERE entry=235;
UPDATE mangos_string SET content_loc4='路径点已改变.' WHERE entry=236;
UPDATE mangos_string SET content_loc4='路径点 %s 已修改.' WHERE entry=237;
UPDATE mangos_string SET content_loc4='路径点修改成功.' WHERE entry=238;
UPDATE mangos_string SET content_loc4='数据库里未发现路径点.' WHERE entry=239;
UPDATE mangos_string SET content_loc4='文件输入.' WHERE entry=240;
UPDATE mangos_string SET content_loc4='路径点删除.' WHERE entry=241;
UPDATE mangos_string SET content_loc4='未使用' WHERE entry=242;
UPDATE mangos_string SET content_loc4='未使用' WHERE entry=243;
UPDATE mangos_string SET content_loc4='未使用' WHERE entry=244;
UPDATE mangos_string SET content_loc4='未使用' WHERE entry=245;
UPDATE mangos_string SET content_loc4='Waypoint %u for %s (from pathId %i, stored by %s)' WHERE entry=246;
UPDATE mangos_string SET content_loc4=' 等待时间: %d' WHERE entry=247;
UPDATE mangos_string SET content_loc4=' 方向: %f' WHERE entry=248;
UPDATE mangos_string SET content_loc4=' 脚本ID: %u' WHERE entry=249;
UPDATE mangos_string SET content_loc4='ScriptID set to non-existing id %u, add it to DBScriptsEngine and reload the table.' WHERE entry=250;
UPDATE mangos_string SET content_loc4='未使用' WHERE entry=251;
UPDATE mangos_string SET content_loc4='AI脚本名称: %s' WHERE entry=252;
UPDATE mangos_string SET content_loc4='强制修改玩家名 %s, 将于下次登录时生效.' WHERE entry=253;
UPDATE mangos_string SET content_loc4='强制修改玩家名 %s (GUID #%u), 将于下次登录时生效.' WHERE entry=254;
UPDATE mangos_string SET content_loc4='路径点-生物 (GUID: %u) 没有找到.' WHERE entry=255;
UPDATE mangos_string SET content_loc4='不能查找NPC...' WHERE entry=256;
UPDATE mangos_string SET content_loc4='生物运动方式设置为 ’%s’, 路径点删除 (如果存在).' WHERE entry=257;
UPDATE mangos_string SET content_loc4='生物运动方式设置为 ’%s’, 路径点不删除.' WHERE entry=258;
UPDATE mangos_string SET content_loc4='错误值, 请用 on 或 off' WHERE entry=259;
UPDATE mangos_string SET content_loc4='设置已保存.' WHERE entry=260;
UPDATE mangos_string SET content_loc4='设置已保存, 你可能需要重新清理你的客户缓存.' WHERE entry=261;
UPDATE mangos_string SET content_loc4='区域触发(传送门) ID %u 没有发现! ' WHERE entry=262;
UPDATE mangos_string SET content_loc4='目标地图或坐标无效 (X: %f Y: %f 地图Id: %u)' WHERE entry=263;
UPDATE mangos_string SET content_loc4='区域传送门无效 (X: %f Y: %f 地区Id: %u)' WHERE entry=264;
UPDATE mangos_string SET content_loc4='Zone %u (%s) is part of instanceable map %u (%s)' WHERE entry=265;
UPDATE mangos_string SET content_loc4='不存在!' WHERE entry=266;
UPDATE mangos_string SET content_loc4='对象不存在!' WHERE entry=267;
UPDATE mangos_string SET content_loc4='生物不存在!' WHERE entry=268;
UPDATE mangos_string SET content_loc4='生物已经移除' WHERE entry=270;
UPDATE mangos_string SET content_loc4='生物已经迁移.' WHERE entry=271;
UPDATE mangos_string SET content_loc4='生物 (GUID:%u) 必须与玩家在同样的地图!' WHERE entry=272;
UPDATE mangos_string SET content_loc4='游戏物体 (GUID: %u) 不存在.' WHERE entry=273;
UPDATE mangos_string SET content_loc4='Game Object (GUID: %u) has references in not found owner %s GO list, can\'t be deleted.' WHERE entry=274;
UPDATE mangos_string SET content_loc4='游戏物体 (GUID: %u) 删除.' WHERE entry=275;
UPDATE mangos_string SET content_loc4='游戏物体 |cffffffff|Hgameobject:%d|h[%s]|h|r (GUID: %u) 转向.' WHERE entry=276;
UPDATE mangos_string SET content_loc4='游戏物体 |cffffffff|Hgameobject:%d|h[%s]|h|r (GUID: %u) 迁移.' WHERE entry=277;
UPDATE mangos_string SET content_loc4='你必须选择一个商人' WHERE entry=278;
UPDATE mangos_string SET content_loc4='你必须使用物品的id' WHERE entry=279;
UPDATE mangos_string SET content_loc4='商人设置太多的物品 (最多128)' WHERE entry=280;
UPDATE mangos_string SET content_loc4='你不能踢出你自己，可以注销.' WHERE entry=281;
UPDATE mangos_string SET content_loc4='玩家 %s 被踢出' WHERE entry=282;
UPDATE mangos_string SET content_loc4='接受悄悄话: %s' WHERE entry=284;
UPDATE mangos_string SET content_loc4='接受悄悄话: 开启' WHERE entry=285;
UPDATE mangos_string SET content_loc4='接受悄悄话: 关闭' WHERE entry=286;
UPDATE mangos_string SET content_loc4='生物 (GUID: %u) 不存在' WHERE entry=287;
UPDATE mangos_string SET content_loc4='标签数量: %i 出示新的标签: %s ' WHERE entry=288;
UPDATE mangos_string SET content_loc4='新标签开始于 %s' WHERE entry=289;
UPDATE mangos_string SET content_loc4='标签属于 %s (上次更新: %s):\n%s' WHERE entry=290;
UPDATE mangos_string SET content_loc4='新标签显示: 开启' WHERE entry=291;
UPDATE mangos_string SET content_loc4='新标签显示: 关闭' WHERE entry=292;
UPDATE mangos_string SET content_loc4='标签 %i 不存在.' WHERE entry=293;
UPDATE mangos_string SET content_loc4='所有标签已删除.' WHERE entry=294;
UPDATE mangos_string SET content_loc4='角色 %s 标签已删除.' WHERE entry=295;
UPDATE mangos_string SET content_loc4='标签已删除.' WHERE entry=296;
UPDATE mangos_string SET content_loc4='刷新时间间隔改变为: %i' WHERE entry=297;
UPDATE mangos_string SET content_loc4='刷新时间改变为: %i' WHERE entry=298;
UPDATE mangos_string SET content_loc4='%s 的荣誉被设置到 %u!' WHERE entry=299;
UPDATE mangos_string SET content_loc4='你被禁言%u分钟.' WHERE entry=300;
UPDATE mangos_string SET content_loc4='你对 %s 禁言%u分钟.' WHERE entry=301;
UPDATE mangos_string SET content_loc4='玩家的禁言已经解除.' WHERE entry=302;
UPDATE mangos_string SET content_loc4='你的禁言已经解除.' WHERE entry=303;
UPDATE mangos_string SET content_loc4='你已经解除了%s的禁言.' WHERE entry=304;
UPDATE mangos_string SET content_loc4='阵营 %s (%u) 的声望 %s 设置为 %5d!' WHERE entry=305;
UPDATE mangos_string SET content_loc4='%s 的竞技场点数设置为 %u!' WHERE entry=306;
UPDATE mangos_string SET content_loc4='阵营不存在!' WHERE entry=307;
UPDATE mangos_string SET content_loc4='阵营 %i 未知!' WHERE entry=308;
UPDATE mangos_string SET content_loc4='无效的参数 %s' WHERE entry=309;
UPDATE mangos_string SET content_loc4='增加量两必须介于 0 和 %d (包括)之间' WHERE entry=310;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|Hfaction:%d|h[%s]|h|r' WHERE entry=311;
UPDATE mangos_string SET content_loc4=' [显示]' WHERE entry=312;
UPDATE mangos_string SET content_loc4=' [战斗]' WHERE entry=313;
UPDATE mangos_string SET content_loc4=' [强制和平]' WHERE entry=314;
UPDATE mangos_string SET content_loc4=' [隐藏]' WHERE entry=315;
UPDATE mangos_string SET content_loc4=' [强制隐藏]' WHERE entry=316;
UPDATE mangos_string SET content_loc4=' [离开]' WHERE entry=317;
UPDATE mangos_string SET content_loc4='仇恨' WHERE entry=318;
UPDATE mangos_string SET content_loc4='敌对' WHERE entry=319;
UPDATE mangos_string SET content_loc4='冷淡' WHERE entry=320;
UPDATE mangos_string SET content_loc4='中立' WHERE entry=321;
UPDATE mangos_string SET content_loc4='友善' WHERE entry=322;
UPDATE mangos_string SET content_loc4='尊敬' WHERE entry=323;
UPDATE mangos_string SET content_loc4='崇敬' WHERE entry=324;
UPDATE mangos_string SET content_loc4='崇拜' WHERE entry=325;
UPDATE mangos_string SET content_loc4='阵营 %s (%u) 不能获得声望.' WHERE entry=326;
UPDATE mangos_string SET content_loc4=' [无荣誉]' WHERE entry=327;
UPDATE mangos_string SET content_loc4='角色帐号 %s (Id: %u)' WHERE entry=328;
UPDATE mangos_string SET content_loc4='  %s (GUID %u)' WHERE entry=329;
UPDATE mangos_string SET content_loc4='玩家不存在!' WHERE entry=330;
UPDATE mangos_string SET content_loc4='额外出售%u 不存在' WHERE entry=331;
UPDATE mangos_string SET content_loc4='GM 模式开启' WHERE entry=332;
UPDATE mangos_string SET content_loc4='GM 模式关闭' WHERE entry=333;
UPDATE mangos_string SET content_loc4='GM 聊条前缀开启' WHERE entry=334;
UPDATE mangos_string SET content_loc4='GM 聊条前缀关闭' WHERE entry=335;
UPDATE mangos_string SET content_loc4='你修复了所有%s的物品.' WHERE entry=336;
UPDATE mangos_string SET content_loc4='%s修复了你的所有物品.' WHERE entry=337;
UPDATE mangos_string SET content_loc4='你设置水上行走模式%s为%s.' WHERE entry=338;
UPDATE mangos_string SET content_loc4='你的水上行走模式%s为%s.' WHERE entry=339;
UPDATE mangos_string SET content_loc4='%s正在跟踪你.' WHERE entry=340;
UPDATE mangos_string SET content_loc4='%s没有跟踪你.' WHERE entry=341;
UPDATE mangos_string SET content_loc4='%s现在没有跟踪你.' WHERE entry=342;
UPDATE mangos_string SET content_loc4='生物 (Entry: %u) 不能被驯服.' WHERE entry=343;
UPDATE mangos_string SET content_loc4='你已拥有宠物.' WHERE entry=344;
UPDATE mangos_string SET content_loc4='找不到出租车节点ID!' WHERE entry=347;
UPDATE mangos_string SET content_loc4='Game Object (Entry: %u) have invalid data and can\'t be spawned' WHERE entry=348;
UPDATE mangos_string SET content_loc4='%d (idx:%d) - |cffffffff|Htitle:%d|h[%s %s]|h|r %s %s ' WHERE entry=349;
UPDATE mangos_string SET content_loc4='%d (idx:%d) - [%s %s] %s %s ' WHERE entry=350;
UPDATE mangos_string SET content_loc4='标题不存在!' WHERE entry=351;
UPDATE mangos_string SET content_loc4='无效的标题 id: %u' WHERE entry=352;
UPDATE mangos_string SET content_loc4='Title %u (%s) added to known titles list for player %s.' WHERE entry=353;
UPDATE mangos_string SET content_loc4='Title %u (%s) removed from known titles list for player %s.' WHERE entry=354;
UPDATE mangos_string SET content_loc4='Title %u (%s) set as current selected title for player %s.' WHERE entry=355;
UPDATE mangos_string SET content_loc4='Current selected title for player %s reset as not known now.' WHERE entry=356;
UPDATE mangos_string SET content_loc4='区域传送门%u没有坐标!' WHERE entry=357;
UPDATE mangos_string SET content_loc4='没有发现区域传送门!' WHERE entry=358;
UPDATE mangos_string SET content_loc4='%s|cffffffff|Hareatrigger_target:%u|h[Trigger target %u]|h|r Map %u X:%f Y:%f Z:%f%s' WHERE entry=359;
UPDATE mangos_string SET content_loc4='%s[Trigger target %u] Map %u X:%f Y:%f Z:%f' WHERE entry=360;
UPDATE mangos_string SET content_loc4='|cffffffff|Hareatrigger:%u|h[Trigger %u]|h|r Map %u X:%f Y:%f Z:%f%s%s%s' WHERE entry=361;
UPDATE mangos_string SET content_loc4='[Trigger %u] Map %u X:%f Y:%f Z:%f%s%s' WHERE entry=362;
UPDATE mangos_string SET content_loc4=' (距离 %f)' WHERE entry=363;
UPDATE mangos_string SET content_loc4=' [旅店]' WHERE entry=364;
UPDATE mangos_string SET content_loc4=' [任务]' WHERE entry=365;
UPDATE mangos_string SET content_loc4='查询任务:' WHERE entry=366;
UPDATE mangos_string SET content_loc4='需要等级: %u' WHERE entry=367;
UPDATE mangos_string SET content_loc4='需要物品:' WHERE entry=368;
UPDATE mangos_string SET content_loc4='需要任务:' WHERE entry=369;
UPDATE mangos_string SET content_loc4='需要英雄钥匙:' WHERE entry=370;
UPDATE mangos_string SET content_loc4='结果:\r\n%s ' WHERE entry=373;
UPDATE mangos_string SET content_loc4='标签总数: %i\n' WHERE entry=374;
UPDATE mangos_string SET content_loc4='玩家 %s 标签不存在.' WHERE entry=375;
UPDATE mangos_string SET content_loc4='%u - |cffffffff|Hpool:%u|h[%s]|h|r AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u' WHERE entry=376;
UPDATE mangos_string SET content_loc4='当前地图鱼池不存在 \'%s\' (Id:%u)' WHERE entry=377;
UPDATE mangos_string SET content_loc4='You can\'t use this command at non-instanceable map \'%s\' (Id:%u). Use .lookup pool command instead' WHERE entry=378;
UPDATE mangos_string SET content_loc4='You can\'t use this command without args at non-instanceable map \'%s\' (Id' WHERE entry=379;
UPDATE mangos_string SET content_loc4='%d%s - |cffffffff|Hcreature:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r Chance:%f %s' WHERE entry=380;
UPDATE mangos_string SET content_loc4='%d%s - [%s] X:%f Y:%f Z:%f MapId:%d Chance:%f %s' WHERE entry=381;
UPDATE mangos_string SET content_loc4='%d%s - |cffffffff|Hcreature:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r %s' WHERE entry=382;
UPDATE mangos_string SET content_loc4='%d%s - [%s] X:%f Y:%f Z:%f MapId:%d %s' WHERE entry=383;
UPDATE mangos_string SET content_loc4='%d%s - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r Chance:%f %s' WHERE entry=384;
UPDATE mangos_string SET content_loc4='%d%s - [%s] X:%f Y:%f Z:%f MapId:%d Chance:%f %s' WHERE entry=385;
UPDATE mangos_string SET content_loc4='%d%s - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r %s' WHERE entry=386;
UPDATE mangos_string SET content_loc4='%d%s - [%s] X:%f Y:%f Z:%f MapId:%d %s' WHERE entry=387;
UPDATE mangos_string SET content_loc4='Creatures with explicitly chance:' WHERE entry=388;
UPDATE mangos_string SET content_loc4='Creatures with equal chance:' WHERE entry=389;
UPDATE mangos_string SET content_loc4='Gameobjects with explicitly chance:' WHERE entry=390;
UPDATE mangos_string SET content_loc4='Gameobjects with equal chance:' WHERE entry=391;
UPDATE mangos_string SET content_loc4='Pool %u - Mother pool: %u |cffffffff|Hpool:%u|h[%s]|h|r AutoSpawn: %u MaxLimit: %u' WHERE entry=392;
UPDATE mangos_string SET content_loc4='Pool %u - Mother pool: %u [%s] AutoSpawn: %u MaxLimit: %u' WHERE entry=393;
UPDATE mangos_string SET content_loc4='Pool %u - Mother pool: none AutoSpawn: %u MaxLimit: %u' WHERE entry=394;
UPDATE mangos_string SET content_loc4='没有发现鱼池' WHERE entry=395;
UPDATE mangos_string SET content_loc4='%u - [%s] AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u' WHERE entry=396;
UPDATE mangos_string SET content_loc4='Pools with explicitly chance:' WHERE entry=397;
UPDATE mangos_string SET content_loc4='Pools with equal chance:' WHERE entry=398;
UPDATE mangos_string SET content_loc4='%u - |cffffffff|Hpool:%u|h[%s]|h|r AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u Chance: %f %s' WHERE entry=399;
UPDATE mangos_string SET content_loc4='|cffff0000[系统消息]:|r脚本已经重载' WHERE entry=400;
UPDATE mangos_string SET content_loc4='你改变了 %s 的帐号权限等级为 %i.' WHERE entry=401;
UPDATE mangos_string SET content_loc4='%s 改变了你的帐号权限等级为 %i.' WHERE entry=402;
UPDATE mangos_string SET content_loc4='你的帐号权限等级不足.' WHERE entry=403;
UPDATE mangos_string SET content_loc4='生物移动点取消.' WHERE entry=404;
UPDATE mangos_string SET content_loc4='生物移动点生效.' WHERE entry=405;
UPDATE mangos_string SET content_loc4='这个区域的天气不能被更改.' WHERE entry=406;
UPDATE mangos_string SET content_loc4='服务器天气系统取消.' WHERE entry=407;
UPDATE mangos_string SET content_loc4='%s 被禁止的为 %s. 操作: %s.' WHERE entry=408;
UPDATE mangos_string SET content_loc4='%s 被永久禁止的为 %s.' WHERE entry=409;
UPDATE mangos_string SET content_loc4='%s %s 不存在.' WHERE entry=410;
UPDATE mangos_string SET content_loc4='%s 已解除禁止.' WHERE entry=411;
UPDATE mangos_string SET content_loc4='出现错误取消禁令 %s.' WHERE entry=412;
UPDATE mangos_string SET content_loc4='帐户不存在: %s' WHERE entry=413;
UPDATE mangos_string SET content_loc4='角色不能存在.' WHERE entry=414;
UPDATE mangos_string SET content_loc4='禁止列表不存在这样的IP.' WHERE entry=415;
UPDATE mangos_string SET content_loc4='账号 %s 从未被禁止.' WHERE entry=416;
UPDATE mangos_string SET content_loc4='历史禁止帐户 %s:' WHERE entry=417;
UPDATE mangos_string SET content_loc4='禁止日期: %s 禁止时间: %s 激活间隔: %s  原因: %s 操作者: %s' WHERE entry=418;
UPDATE mangos_string SET content_loc4='信息.' WHERE entry=419;
UPDATE mangos_string SET content_loc4='从未' WHERE entry=420;
UPDATE mangos_string SET content_loc4='是' WHERE entry=421;
UPDATE mangos_string SET content_loc4='否' WHERE entry=422;
UPDATE mangos_string SET content_loc4='禁止IP: %s\r\n禁止日期: %s\r\n禁止时间: %s\r\n剩余: %s\r\n原因: %s\r\n操作者: %s' WHERE entry=423;
UPDATE mangos_string SET content_loc4='没有匹配的IP禁止地址.' WHERE entry=424;
UPDATE mangos_string SET content_loc4='没有匹配的帐户.' WHERE entry=425;
UPDATE mangos_string SET content_loc4='没有禁用的账号与其相匹配.' WHERE entry=426;
UPDATE mangos_string SET content_loc4='下面的IP地址符合您的匹配:' WHERE entry=427;
UPDATE mangos_string SET content_loc4='以下帐户匹配您的查询:' WHERE entry=428;
UPDATE mangos_string SET content_loc4='你学会了全部法术或技能.' WHERE entry=429;
UPDATE mangos_string SET content_loc4='你已经学会了所有的会职业法术.' WHERE entry=430;
UPDATE mangos_string SET content_loc4='你已经学会了所有的本职业天赋.' WHERE entry=431;
UPDATE mangos_string SET content_loc4='你已经学会了所有的语言.' WHERE entry=432;
UPDATE mangos_string SET content_loc4='你学会了所有手工艺技能和食谱.' WHERE entry=433;
UPDATE mangos_string SET content_loc4='不能查找 ’%s’' WHERE entry=434;
UPDATE mangos_string SET content_loc4='无效的物品id: %u' WHERE entry=435;
UPDATE mangos_string SET content_loc4='物品不存在!' WHERE entry=436;
UPDATE mangos_string SET content_loc4='无效的物体id: %u' WHERE entry=437;
UPDATE mangos_string SET content_loc4='找到物品 %u: %u ( 库存 %u 邮箱 %u 拍卖 %u guild %u)' WHERE entry=438;
UPDATE mangos_string SET content_loc4='找到物体%u: %u' WHERE entry=439;
UPDATE mangos_string SET content_loc4='无效的生物id: %u' WHERE entry=440;
UPDATE mangos_string SET content_loc4='找到生物%u: %u' WHERE entry=441;
UPDATE mangos_string SET content_loc4='地区不存在!' WHERE entry=442;
UPDATE mangos_string SET content_loc4='物品套装不存在!' WHERE entry=443;
UPDATE mangos_string SET content_loc4='技能不存在!' WHERE entry=444;
UPDATE mangos_string SET content_loc4='法术不存在!' WHERE entry=445;
UPDATE mangos_string SET content_loc4='任务不存在!' WHERE entry=446;
UPDATE mangos_string SET content_loc4='生物不存在!' WHERE entry=447;
UPDATE mangos_string SET content_loc4='物体不存在!' WHERE entry=448;
UPDATE mangos_string SET content_loc4='墓地 #%u 不存在.' WHERE entry=449;
UPDATE mangos_string SET content_loc4='墓地 #%u 已经连接到区域 #%u (当前).' WHERE entry=450;
UPDATE mangos_string SET content_loc4='墓地 #%u 连接到区域 #%u (当前).' WHERE entry=451;
UPDATE mangos_string SET content_loc4='墓地 #%u 不能连接到子区域或不存在的区域 #%u (内部错误).' WHERE entry=452;
UPDATE mangos_string SET content_loc4='没有阵营在墓地且 id= #%u , 请修复你的DB数据库' WHERE entry=454;
UPDATE mangos_string SET content_loc4='无效的团队, 请修复你的数据库' WHERE entry=455;
UPDATE mangos_string SET content_loc4='任何' WHERE entry=456;
UPDATE mangos_string SET content_loc4='联盟' WHERE entry=457;
UPDATE mangos_string SET content_loc4='部落' WHERE entry=458;
UPDATE mangos_string SET content_loc4='墓地ID #%u (阵营: %s) 是最近的距此区域ID #%u.' WHERE entry=459;
UPDATE mangos_string SET content_loc4='区域 #%u 没有一个连接的墓地.' WHERE entry=460;
UPDATE mangos_string SET content_loc4='区域 #%u 没有一个连接的墓地为阵营: %s.' WHERE entry=461;
UPDATE mangos_string SET content_loc4='传送地点已经存在!' WHERE entry=462;
UPDATE mangos_string SET content_loc4='传送地点增加.' WHERE entry=463;
UPDATE mangos_string SET content_loc4='传送地点增加失败: 数据库错误.' WHERE entry=464;
UPDATE mangos_string SET content_loc4='传送地点被删除.' WHERE entry=465;
UPDATE mangos_string SET content_loc4='没有发现骑乘飞行节点!' WHERE entry=466;
UPDATE mangos_string SET content_loc4='目标单位有 %d 光环:' WHERE entry=467;
UPDATE mangos_string SET content_loc4='id: %d eff: %d type: %d duration: %d maxduration: %d name: %s%s%s caster: %s' WHERE entry=468;
UPDATE mangos_string SET content_loc4='Target unit has %d auras of type %d:' WHERE entry=469;
UPDATE mangos_string SET content_loc4='id: %d eff: %d name: %s%s%s caster: %s' WHERE entry=470;
UPDATE mangos_string SET content_loc4='任务 %u 不存在.' WHERE entry=471;
UPDATE mangos_string SET content_loc4='任务 %u 由物品触发. 为正确工作, 请添加物品到库里并且开始这个任务的正常方式: .additem %u' WHERE entry=472;
UPDATE mangos_string SET content_loc4='任务清除.' WHERE entry=473;
UPDATE mangos_string SET content_loc4=' [奖励]' WHERE entry=474;
UPDATE mangos_string SET content_loc4=' [完成]' WHERE entry=475;
UPDATE mangos_string SET content_loc4=' [激活]' WHERE entry=476;
UPDATE mangos_string SET content_loc4='%s 飞行模式 %s' WHERE entry=477;
UPDATE mangos_string SET content_loc4='操作代码 %u 发送到 %s' WHERE entry=478;
UPDATE mangos_string SET content_loc4='角色加载成功!' WHERE entry=479;
UPDATE mangos_string SET content_loc4='加载角色失败!' WHERE entry=480;
UPDATE mangos_string SET content_loc4='卸载角色成功!' WHERE entry=481;
UPDATE mangos_string SET content_loc4='卸载角色失败!' WHERE entry=482;
UPDATE mangos_string SET content_loc4='法术 %u 禁止，并且不允许使用或学习!' WHERE entry=483;
UPDATE mangos_string SET content_loc4='技能值 %u (%s) 为角色 %s 设置到 %u 并且当前最大设置到 %u (没有固定(天赋)奖励).' WHERE entry=484;
UPDATE mangos_string SET content_loc4='角色 %s 必须拥有技能 %u (%s) 在使用这个命令之前.' WHERE entry=485;
UPDATE mangos_string SET content_loc4='错误的技能id (%u)' WHERE entry=486;
UPDATE mangos_string SET content_loc4='你学会了ＧＭ默认的法术和技能.' WHERE entry=487;
UPDATE mangos_string SET content_loc4='你已经学了这个法术' WHERE entry=488;
UPDATE mangos_string SET content_loc4='目标(%s) 已经学习了那些法术.' WHERE entry=489;
UPDATE mangos_string SET content_loc4='%s 不能学习那些法术.' WHERE entry=490;
UPDATE mangos_string SET content_loc4='您已经忘却了那个法术.' WHERE entry=491;
UPDATE mangos_string SET content_loc4='所有的法术冷却清除 %s.' WHERE entry=492;
UPDATE mangos_string SET content_loc4='法术 %u 冷却清除 %s.' WHERE entry=493;
UPDATE mangos_string SET content_loc4='指令 : Additem, itemId = %i, amount = %i' WHERE entry=494;
UPDATE mangos_string SET content_loc4='指令 : Additemset, itemsetId = %i' WHERE entry=495;
UPDATE mangos_string SET content_loc4='移除 itemID = %i, amount = %i from %s' WHERE entry=496;
UPDATE mangos_string SET content_loc4='不能创建物品\'%i\' (数量: %i)' WHERE entry=497;
UPDATE mangos_string SET content_loc4='你需要提供一个公会名字!' WHERE entry=498;
UPDATE mangos_string SET content_loc4='角色不存在!' WHERE entry=499;
UPDATE mangos_string SET content_loc4='玩家已经加入了一个公会！' WHERE entry=500;
UPDATE mangos_string SET content_loc4='公会未被创建! (是否已经存在?)' WHERE entry=501;
UPDATE mangos_string SET content_loc4='物品套装 \'%u\' 不存在.' WHERE entry=502;
UPDATE mangos_string SET content_loc4='The distance is: (3D) %f (2D) %f - (3D, point-to-point) %f yards.' WHERE entry=503;
UPDATE mangos_string SET content_loc4='物品 ’%i’ ’%s’ 背包 %i' WHERE entry=504;
UPDATE mangos_string SET content_loc4='物品 ’%i’不存在.' WHERE entry=505;
UPDATE mangos_string SET content_loc4='物品 ’%i’ ’%s’ 已添加到背包 %i' WHERE entry=506;
UPDATE mangos_string SET content_loc4='物品保存失败!' WHERE entry=507;
UPDATE mangos_string SET content_loc4='%d - 队长: %s (索引: %u 帐号: %u ) %s' WHERE entry=508;
UPDATE mangos_string SET content_loc4='%d - 发件人: %s (索引: %u 帐号: %u ) 收件人: %s (索引: %u 帐号: %u ) %s' WHERE entry=509;
UPDATE mangos_string SET content_loc4='%d - 队长: %s (索引: %u 帐号: %u ) %s' WHERE entry=510;
UPDATE mangos_string SET content_loc4='错误链接类型!' WHERE entry=511;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|Hitem:%d:0:0:0:0:0:0:0|h[%s]|h|r %s' WHERE entry=512;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|Hquest:%d:%d|h[%s]|h|r %s' WHERE entry=513;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|Hcreature_entry:%d|h[%s]|h|r ' WHERE entry=514;
UPDATE mangos_string SET content_loc4='%d%s - |cffffffff|Hcreature:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ' WHERE entry=515;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|Hgameobject_entry:%d|h[%s]|h|r ' WHERE entry=516;
UPDATE mangos_string SET content_loc4='%d%s, Entry %d - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r' WHERE entry=517;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|Hitemset:%d|h[%s %s]|h|r ' WHERE entry=518;
UPDATE mangos_string SET content_loc4='|cffffffff|Htele:%s|h[%s]|h|r ' WHERE entry=519;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|Hspell:%d|h[%s]|h|r ' WHERE entry=520;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|Hskill:%d|h[%s %s]|h|r %s %s' WHERE entry=521;
UPDATE mangos_string SET content_loc4='物体(Entry: %u) 不存在' WHERE entry=522;
UPDATE mangos_string SET content_loc4='>> Game Object %s (GUID: %u) at %f %f %f. Orientation %f.' WHERE entry=523;
UPDATE mangos_string SET content_loc4='Selected object:\n|cffffffff|Hgameobject:%d|h[%s]|h|r GUID: %u ID: %u\nX: %f Y: %f Z: %f MapId: %u\nOrientation: %f' WHERE entry=524;
UPDATE mangos_string SET content_loc4='>> Add Game Object \'%i\' (%s) (GUID: %i) added at \'%f %f %f\'.' WHERE entry=525;
UPDATE mangos_string SET content_loc4='%s (lowguid: %u) movement generators stack:' WHERE entry=526;
UPDATE mangos_string SET content_loc4='   空闲' WHERE entry=527;
UPDATE mangos_string SET content_loc4='   随机' WHERE entry=528;
UPDATE mangos_string SET content_loc4='   路径' WHERE entry=529;
UPDATE mangos_string SET content_loc4='   随机移动' WHERE entry=530;
UPDATE mangos_string SET content_loc4='   困惑' WHERE entry=531;
UPDATE mangos_string SET content_loc4='   目标角色 %s (lowguid %u)' WHERE entry=532;
UPDATE mangos_string SET content_loc4='   目标生物 %s (lowguid %u)' WHERE entry=533;
UPDATE mangos_string SET content_loc4='   目标为 <空>' WHERE entry=534;
UPDATE mangos_string SET content_loc4='   Home movement to (X:%f Y:%f Z:%f)' WHERE entry=535;
UPDATE mangos_string SET content_loc4='   Home movement used for player?!?' WHERE entry=536;
UPDATE mangos_string SET content_loc4='   出租飞行' WHERE entry=537;
UPDATE mangos_string SET content_loc4='   未知的运动触发器(%u)' WHERE entry=538;
UPDATE mangos_string SET content_loc4='Player selected: %s.\nFaction: %u.\nnpcFlags: %u.\nEntry: %u.\nDisplayID: %u (Native: %u).' WHERE entry=539;
UPDATE mangos_string SET content_loc4='等级: %u.' WHERE entry=540;
UPDATE mangos_string SET content_loc4='生命值 (基础): %u. (最大): %u. (当前): %u.' WHERE entry=541;
UPDATE mangos_string SET content_loc4='单位标志: %u.\r\n动态标志: %u.\r\n阵营模版: %u.' WHERE entry=542;
UPDATE mangos_string SET content_loc4='掉落物品: %u 偷窃: %u 剥皮: %u\'' WHERE entry=543;
UPDATE mangos_string SET content_loc4='位置: %f %f %f.' WHERE entry=544;
UPDATE mangos_string SET content_loc4='*** 是一个供应商!' WHERE entry=545;
UPDATE mangos_string SET content_loc4='*** 是一个训练师!' WHERE entry=546;
UPDATE mangos_string SET content_loc4='副本ID: %u' WHERE entry=547;
UPDATE mangos_string SET content_loc4='玩家%s %s (guid: %u) 帐号: %s (id: %u) GM等级: %u 最后IP: %s 最后登陆: %s 延迟: %ums' WHERE entry=548;
UPDATE mangos_string SET content_loc4='玩家已在线时间: %s 等级: %u 金钱: %ug%us%uc' WHERE entry=549;
UPDATE mangos_string SET content_loc4='命令提示：命令 .pinfo 不支持  ’rep’ 选择玩家不在线.' WHERE entry=550;
UPDATE mangos_string SET content_loc4='%s 探索了所有地区' WHERE entry=551;
UPDATE mangos_string SET content_loc4='%s 没有更多的探索区.' WHERE entry=552;
UPDATE mangos_string SET content_loc4='%s 你探索了所有区域.' WHERE entry=553;
UPDATE mangos_string SET content_loc4='%s 你掩藏了所有区域.' WHERE entry=554;
UPDATE mangos_string SET content_loc4='%s 的等级提高 (%i)' WHERE entry=557;
UPDATE mangos_string SET content_loc4='%s 的等级下降 (%i)' WHERE entry=558;
UPDATE mangos_string SET content_loc4='%s 重置了你的等级.' WHERE entry=559;
UPDATE mangos_string SET content_loc4='该地区已被设置为探索.' WHERE entry=560;
UPDATE mangos_string SET content_loc4='该地区已被设置为未探索.' WHERE entry=561;
UPDATE mangos_string SET content_loc4='The value index %u is too big to %s (count: %u).' WHERE entry=564;
UPDATE mangos_string SET content_loc4='Set for %s field:%u to uint32 value:%u' WHERE entry=565;
UPDATE mangos_string SET content_loc4='You set for %s field:%u to uint32 value: %u' WHERE entry=566;
UPDATE mangos_string SET content_loc4='Set for %s field:%u to to float value:%f' WHERE entry=567;
UPDATE mangos_string SET content_loc4='You set for %s field:%u to float value: %f' WHERE entry=568;
UPDATE mangos_string SET content_loc4='Get %s uint32 value:[FIELD]:%u [VALUE]:%u' WHERE entry=569;
UPDATE mangos_string SET content_loc4='%s has uint32 value:[FIELD]:%u [VALUE]:%u' WHERE entry=570;
UPDATE mangos_string SET content_loc4='Get %s float value:[FIELD]:%u [VALUE]:%f' WHERE entry=571;
UPDATE mangos_string SET content_loc4='%s has float value:[FIELD]:%u [VALUE]:%f' WHERE entry=572;
UPDATE mangos_string SET content_loc4='Modify %s uint32 field:%u to sum with:%i = %u (%i)' WHERE entry=575;
UPDATE mangos_string SET content_loc4='You modify for %s uint32 field:%u to sum with:%i = %u (%i)' WHERE entry=576;
UPDATE mangos_string SET content_loc4='你现在处于隐身状态.' WHERE entry=577;
UPDATE mangos_string SET content_loc4='你现在处于可见状态.' WHERE entry=578;
UPDATE mangos_string SET content_loc4='Selected player or creature not have victim.' WHERE entry=579;
UPDATE mangos_string SET content_loc4='Player %s learned all default spells for race/class and completed quests rewarded spells.' WHERE entry=580;
UPDATE mangos_string SET content_loc4='Found near gameobjects (distance %f): %u ' WHERE entry=581;
UPDATE mangos_string SET content_loc4='SpawnTime: Full:%s Remain:%s' WHERE entry=582;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|Hgameevent:%d|h[%s]|h|r%s' WHERE entry=583;
UPDATE mangos_string SET content_loc4='没有事件被找到!' WHERE entry=584;
UPDATE mangos_string SET content_loc4='事件不存在!' WHERE entry=585;
UPDATE mangos_string SET content_loc4='事件 %u: %s%s\r\n开始: %s 结束: %s 发生: %s 全程: %s\r\n下一次状态改变: %s' WHERE entry=586;
UPDATE mangos_string SET content_loc4='事件 %u 已经开始!' WHERE entry=587;
UPDATE mangos_string SET content_loc4='事件 %u 已经结束!' WHERE entry=588;
UPDATE mangos_string SET content_loc4='   点移动到(X:%f Y:%f Z:%f)' WHERE entry=589;
UPDATE mangos_string SET content_loc4='   恐惧移动' WHERE entry=590;
UPDATE mangos_string SET content_loc4='   混乱移动' WHERE entry=591;
UPDATE mangos_string SET content_loc4='你已经学会了所有的法术: %s' WHERE entry=592;
UPDATE mangos_string SET content_loc4='目前禁用的帐户:' WHERE entry=593;
UPDATE mangos_string SET content_loc4='|    帐户    |   禁止日期   |   禁止时间   |   操作员   |   禁止理由  | ' WHERE entry=594;
UPDATE mangos_string SET content_loc4='目前禁止IP:' WHERE entry=595;
UPDATE mangos_string SET content_loc4='|    地址    |   禁止日期   |   禁止时间   |   操作员   |   禁止理由  |' WHERE entry=596;
UPDATE mangos_string SET content_loc4='目前游戏管理员:' WHERE entry=597;
UPDATE mangos_string SET content_loc4='|    帐户    |  管理员  |' WHERE entry=598;
UPDATE mangos_string SET content_loc4='游戏管理员不存在.' WHERE entry=599;
UPDATE mangos_string SET content_loc4='联盟获得胜利!' WHERE entry=600;
UPDATE mangos_string SET content_loc4='部落获得胜利!' WHERE entry=601;
UPDATE mangos_string SET content_loc4='战歌峡谷的战斗将在1分内钟开始.' WHERE entry=602;
UPDATE mangos_string SET content_loc4='战歌峡谷的战斗在30秒后开始，大家做好准备!' WHERE entry=603;
UPDATE mangos_string SET content_loc4='战歌峡谷的战斗开始了！' WHERE entry=604;
UPDATE mangos_string SET content_loc4='$N夺取了部落的旗帜！' WHERE entry=605;
UPDATE mangos_string SET content_loc4='$N夺取了联盟的旗帜！' WHERE entry=606;
UPDATE mangos_string SET content_loc4='部落的旗帜被$N丢下了！' WHERE entry=607;
UPDATE mangos_string SET content_loc4='联盟的旗帜被$N丢下了！' WHERE entry=608;
UPDATE mangos_string SET content_loc4='$N归还了联盟的旗帜！' WHERE entry=609;
UPDATE mangos_string SET content_loc4='$N归还了部落的旗帜！' WHERE entry=610;
UPDATE mangos_string SET content_loc4='部落的旗帜被$N拿起了！' WHERE entry=611;
UPDATE mangos_string SET content_loc4='联盟的旗帜被$N拿起了！' WHERE entry=612;
UPDATE mangos_string SET content_loc4='旗帜被放置在了各自的基地中.' WHERE entry=613;
UPDATE mangos_string SET content_loc4='联盟的旗帜回到了基地中.' WHERE entry=614;
UPDATE mangos_string SET content_loc4='部落的旗帜回到了基地中.' WHERE entry=615;
UPDATE mangos_string SET content_loc4='暴风之眼的战斗将在1分钟内开始.' WHERE entry=636;
UPDATE mangos_string SET content_loc4='暴风之眼的战斗将在30秒内开始，请做好准备！' WHERE entry=637;
UPDATE mangos_string SET content_loc4='暴风之眼的战斗开始了！' WHERE entry=638;
UPDATE mangos_string SET content_loc4='联盟' WHERE entry=650;
UPDATE mangos_string SET content_loc4='部落' WHERE entry=651;
UPDATE mangos_string SET content_loc4='马厩' WHERE entry=652;
UPDATE mangos_string SET content_loc4='铁匠' WHERE entry=653;
UPDATE mangos_string SET content_loc4='农场' WHERE entry=654;
UPDATE mangos_string SET content_loc4='伐木场' WHERE entry=655;
UPDATE mangos_string SET content_loc4='矿洞' WHERE entry=656;
UPDATE mangos_string SET content_loc4='%s控制了%s' WHERE entry=657;
UPDATE mangos_string SET content_loc4='$N成功防守了%s' WHERE entry=658;
UPDATE mangos_string SET content_loc4='$N突袭了%s' WHERE entry=659;
UPDATE mangos_string SET content_loc4='$N占领了%s！如果不采取行动, %s将在1分钟后控制它！' WHERE entry=660;
UPDATE mangos_string SET content_loc4='阿拉希盆地的战斗将在1分钟内开始.' WHERE entry=661;
UPDATE mangos_string SET content_loc4='阿拉希盆地的战斗将在30秒内开始，请做好准备！' WHERE entry=662;
UPDATE mangos_string SET content_loc4='阿拉希盆地的战斗开始了！' WHERE entry=663;
UPDATE mangos_string SET content_loc4='联盟已经收集了$1776W的资源,离胜利已经不远了！' WHERE entry=664;
UPDATE mangos_string SET content_loc4='部落已经收集了$1777W的资源,离胜利已经不远了！' WHERE entry=665;
UPDATE mangos_string SET content_loc4='你在最近的 %s 战斗之后,我们努力想为你颁发一个荣誉标志却没有成功,结束后你会发现这个荣誉标志的,但不是此刻,感谢你在 %s 的战斗.' WHERE entry=666;
UPDATE mangos_string SET content_loc4='联盟夺取了法师塔的控制权！' WHERE entry=667;
UPDATE mangos_string SET content_loc4='部落夺取了法师塔的控制权！' WHERE entry=668;
UPDATE mangos_string SET content_loc4='联盟夺取了德莱尼废墟的控制权！' WHERE entry=669;
UPDATE mangos_string SET content_loc4='部落夺取了德莱尼废墟的控制权！' WHERE entry=670;
UPDATE mangos_string SET content_loc4='联盟夺取了血精灵塔的控制权！' WHERE entry=671;
UPDATE mangos_string SET content_loc4='部落夺取了血精灵塔的控制权！' WHERE entry=672;
UPDATE mangos_string SET content_loc4='联盟夺取了魔能机甲废墟的控制权！' WHERE entry=673;
UPDATE mangos_string SET content_loc4='部落夺取了魔能机甲废墟的控制权！' WHERE entry=674;
UPDATE mangos_string SET content_loc4='联盟失去了法师塔的控制权！' WHERE entry=675;
UPDATE mangos_string SET content_loc4='部落失去了法师塔的控制权！' WHERE entry=676;
UPDATE mangos_string SET content_loc4='联盟失去了德莱尼废墟的控制权！' WHERE entry=677;
UPDATE mangos_string SET content_loc4='部落失去了德莱尼废墟的控制权！' WHERE entry=678;
UPDATE mangos_string SET content_loc4='联盟失去了血精灵塔的控制权！' WHERE entry=679;
UPDATE mangos_string SET content_loc4='部落失去了血精灵塔的控制权！' WHERE entry=680;
UPDATE mangos_string SET content_loc4='联盟失去了魔能机甲废墟的控制权！' WHERE entry=681;
UPDATE mangos_string SET content_loc4='部落失去了魔能机甲废墟的控制权！' WHERE entry=682;
UPDATE mangos_string SET content_loc4='%s 已夺取旗帜!' WHERE entry=683;
UPDATE mangos_string SET content_loc4='联盟夺得了旗帜！' WHERE entry=684;
UPDATE mangos_string SET content_loc4='部落夺得了旗帜！' WHERE entry=685;
UPDATE mangos_string SET content_loc4='旗帜已失去.' WHERE entry=686;
UPDATE mangos_string SET content_loc4='旗帜已被重置.' WHERE entry=687;
UPDATE mangos_string SET content_loc4='你必须达到等级%u才能进入竞技场' WHERE entry=700;
UPDATE mangos_string SET content_loc4='竞技场战斗将在一分钟后开始！' WHERE entry=701;
UPDATE mangos_string SET content_loc4='竞技场战斗将在三十秒后开始！' WHERE entry=702;
UPDATE mangos_string SET content_loc4='竞技场战斗将在十五秒后开始！' WHERE entry=703;
UPDATE mangos_string SET content_loc4='竞技场战斗开始了！' WHERE entry=704;
UPDATE mangos_string SET content_loc4='你必须等待%s才能再次发言.' WHERE entry=705;
UPDATE mangos_string SET content_loc4='这些道具在装备/存放中出现一个问题.' WHERE entry=706;
UPDATE mangos_string SET content_loc4='%s现在不想被打扰: %s' WHERE entry=707;
UPDATE mangos_string SET content_loc4='%s现在不在电脑旁: %s' WHERE entry=708;
UPDATE mangos_string SET content_loc4='请勿打扰' WHERE entry=709;
UPDATE mangos_string SET content_loc4='离开' WHERE entry=710;
UPDATE mangos_string SET content_loc4='队列状态 %s (等级: %u 至 %u)\n联盟队列: %u (至少需要 %u more)\n部落队列: %u (至少需要 %u more)' WHERE entry=711;
UPDATE mangos_string SET content_loc4='|cffff0000[战场召唤]:|r %s -- [%u-%u] 联盟人数: %u/%u, 部落人数: %u/%u|r' WHERE entry=712;
UPDATE mangos_string SET content_loc4='你的等级必须达到%u才能加入一个竞技场队伍!' WHERE entry=713;
UPDATE mangos_string SET content_loc4='你还没有达到战场要求的等级!' WHERE entry=715;
UPDATE mangos_string SET content_loc4='|cffff0000[战场召唤]:|r %s -- [%u-%u] 开始了！|r' WHERE entry=717;
UPDATE mangos_string SET content_loc4='|cffff0000[竞技场召唤]:|r All Arenas -- Joined : %ux%u : %u|r' WHERE entry=718;
UPDATE mangos_string SET content_loc4='|cffff0000[竞技场召唤]:|r All Arenas -- Left : %ux%u : %u|r' WHERE entry=719;
UPDATE mangos_string SET content_loc4='你的团队成员太多,无法加入战场. 请重新加入.' WHERE entry=720;
UPDATE mangos_string SET content_loc4='你的团队成员太多,不适合这个竞技场. 请重新加入.' WHERE entry=721;
UPDATE mangos_string SET content_loc4='你的团队成员不在你的竞技场队伍中. 请重新加入.' WHERE entry=722;
UPDATE mangos_string SET content_loc4='你们组没有足够的角色参加这场比赛.' WHERE entry=723;
UPDATE mangos_string SET content_loc4='金色队获得胜利！' WHERE entry=724;
UPDATE mangos_string SET content_loc4='绿色队获得胜利！' WHERE entry=725;
UPDATE mangos_string SET content_loc4='你的队伍中有离线成员，请移除后再加入。' WHERE entry=727;
UPDATE mangos_string SET content_loc4='你的队伍中有对立阵营的玩家。不能以队伍形式加入战场。' WHERE entry=728;
UPDATE mangos_string SET content_loc4='你的队伍中有玩家在其它战场中。不能以队伍形式加入。' WHERE entry=729;
UPDATE mangos_string SET content_loc4='你的团队中已经有人在这个战场队列中。他（她）必须先退出队列才能以队伍形式加入。' WHERE entry=730;
UPDATE mangos_string SET content_loc4='你的团队中有战场逃亡者。不能以队伍形式加入。' WHERE entry=731;
UPDATE mangos_string SET content_loc4='你的团队中已经有人在3个战场队列中。不能以队伍形式加入。' WHERE entry=732;
UPDATE mangos_string SET content_loc4='你不能传送到战场或竞技场地图。' WHERE entry=733;
UPDATE mangos_string SET content_loc4='你不能召唤玩家到战场或竞技场地图。' WHERE entry=734;
UPDATE mangos_string SET content_loc4='你必须在GM模式才能传送到战场的玩家身边.' WHERE entry=735;
UPDATE mangos_string SET content_loc4='你不能传送到另一个战场. 请先离开现在的战场.' WHERE entry=736;
UPDATE mangos_string SET content_loc4='调试竞技场开启.战场设置 1V1 不能组队加入.' WHERE entry=737;
UPDATE mangos_string SET content_loc4='竞技场模式已更改为正常状态.' WHERE entry=738;
UPDATE mangos_string SET content_loc4='调试战场开启.战场设置 1V0.' WHERE entry=739;
UPDATE mangos_string SET content_loc4='战场模式已更改为正常状态.' WHERE entry=740;
UPDATE mangos_string SET content_loc4='Flushing Arena points based on team ratings, this may take a few minutes. Please stand by...' WHERE entry=741;
UPDATE mangos_string SET content_loc4='分配玩家竞技场点数…' WHERE entry=742;
UPDATE mangos_string SET content_loc4='设置线玩家竞技场点数.' WHERE entry=743;
UPDATE mangos_string SET content_loc4='Modifying played count, arena points etc. for loaded arena teams, sending updated stats to online players...' WHERE entry=744;
UPDATE mangos_string SET content_loc4='修改完成.' WHERE entry=745;
UPDATE mangos_string SET content_loc4='完成竞技场点数更新.' WHERE entry=746;
UPDATE mangos_string SET content_loc4='没有足够的玩家. 这个战场将在%u分钟后关闭.' WHERE entry=750;
UPDATE mangos_string SET content_loc4='没有足够的玩家. 该战场将在%u秒后关闭.' WHERE entry=751;
UPDATE mangos_string SET content_loc4='只有联盟才能用这个入口' WHERE entry=752;
UPDATE mangos_string SET content_loc4='只有部落才能用这个入口' WHERE entry=753;
UPDATE mangos_string SET content_loc4='%s被%s摧毁了！' WHERE entry=759;
UPDATE mangos_string SET content_loc4='%s遭到攻击！如果不采取行动, %s将会摧毁它！' WHERE entry=760;
UPDATE mangos_string SET content_loc4='%s被%s占领了！' WHERE entry=761;
UPDATE mangos_string SET content_loc4='%s被%s占领了！' WHERE entry=762;
UPDATE mangos_string SET content_loc4='%s被%s占领了！' WHERE entry=763;
UPDATE mangos_string SET content_loc4='%s遭到攻击！如果不采取行动，%s将会夺取它！' WHERE entry=764;
UPDATE mangos_string SET content_loc4='%s占领了%s！它的物资将被用于增援！' WHERE entry=765;
UPDATE mangos_string SET content_loc4='深铁矿洞' WHERE entry=766;
UPDATE mangos_string SET content_loc4='冷齿矿洞' WHERE entry=767;
UPDATE mangos_string SET content_loc4='雷矛急救站' WHERE entry=768;
UPDATE mangos_string SET content_loc4='丹巴尔达南部碉堡' WHERE entry=769;
UPDATE mangos_string SET content_loc4='丹巴尔达北部碉堡' WHERE entry=770;
UPDATE mangos_string SET content_loc4='雷矛墓地' WHERE entry=771;
UPDATE mangos_string SET content_loc4='冰翼碉堡' WHERE entry=772;
UPDATE mangos_string SET content_loc4='石炉墓地' WHERE entry=773;
UPDATE mangos_string SET content_loc4='石炉碉堡' WHERE entry=774;
UPDATE mangos_string SET content_loc4='雪落墓地' WHERE entry=775;
UPDATE mangos_string SET content_loc4='冰血哨塔' WHERE entry=776;
UPDATE mangos_string SET content_loc4='冰血墓地' WHERE entry=777;
UPDATE mangos_string SET content_loc4='哨塔高地' WHERE entry=778;
UPDATE mangos_string SET content_loc4='霜狼墓地' WHERE entry=779;
UPDATE mangos_string SET content_loc4='东部霜狼哨塔' WHERE entry=780;
UPDATE mangos_string SET content_loc4='西部霜狼哨塔' WHERE entry=781;
UPDATE mangos_string SET content_loc4='霜狼急救站' WHERE entry=782;
UPDATE mangos_string SET content_loc4='奥特兰克山谷的战斗将在1分钟后开始.' WHERE entry=784;
UPDATE mangos_string SET content_loc4='奥特兰克山谷的战斗将在30秒后开始，请做好准备！' WHERE entry=785;
UPDATE mangos_string SET content_loc4='奥特兰克山谷的战斗开始了！' WHERE entry=786;
UPDATE mangos_string SET content_loc4='联盟的部队正在增援！' WHERE entry=787;
UPDATE mangos_string SET content_loc4='部落的部队正在增援！' WHERE entry=788;
UPDATE mangos_string SET content_loc4='霜狼将军死了！' WHERE entry=789;
UPDATE mangos_string SET content_loc4='雷矛将军死了！' WHERE entry=790;
UPDATE mangos_string SET content_loc4='你没有足够的金币' WHERE entry=801;
UPDATE mangos_string SET content_loc4='你没有足够的栏位' WHERE entry=802;
UPDATE mangos_string SET content_loc4='你的同伴没有足够的背包空间' WHERE entry=803;
UPDATE mangos_string SET content_loc4='你没有执行该函数的权限' WHERE entry=804;
UPDATE mangos_string SET content_loc4='未知语言' WHERE entry=805;
UPDATE mangos_string SET content_loc4='你不会这种语言' WHERE entry=806;
UPDATE mangos_string SET content_loc4='请提供角色名称' WHERE entry=807;
UPDATE mangos_string SET content_loc4='玩家%s找不到或不在线' WHERE entry=808;
UPDATE mangos_string SET content_loc4='角色 %s 的帐号为找到' WHERE entry=809;
UPDATE mangos_string SET content_loc4='会长' WHERE entry=811;
UPDATE mangos_string SET content_loc4='官员' WHERE entry=812;
UPDATE mangos_string SET content_loc4='老兵' WHERE entry=813;
UPDATE mangos_string SET content_loc4='会员' WHERE entry=814;
UPDATE mangos_string SET content_loc4='新兵' WHERE entry=815;
UPDATE mangos_string SET content_loc4='你的身体太疲惫无法复活.' WHERE entry=816;
UPDATE mangos_string SET content_loc4='你不能进入黑色沼泽直到你在敦霍尔德城堡拯救萨尔后。' WHERE entry=818;
UPDATE mangos_string SET content_loc4='退出程序...' WHERE entry=1000;
UPDATE mangos_string SET content_loc4='删除帐号: %s' WHERE entry=1001;
UPDATE mangos_string SET content_loc4='帐户%s删除失败 (可能更新了SQL文件格式)' WHERE entry=1002;
UPDATE mangos_string SET content_loc4='帐号%s删除失败 (未知错误)' WHERE entry=1003;
UPDATE mangos_string SET content_loc4='创建帐号: %s' WHERE entry=1004;
UPDATE mangos_string SET content_loc4='帐号名称不能超过16个字符（客户端限制），不能创建帐号！' WHERE entry=1005;
UPDATE mangos_string SET content_loc4='此帐号名称已经存在！' WHERE entry=1006;
UPDATE mangos_string SET content_loc4='创建帐号失败%s（可能更新了SQL文件格式）' WHERE entry=1007;
UPDATE mangos_string SET content_loc4='创建帐号失败%s（未知错误）' WHERE entry=1008;
UPDATE mangos_string SET content_loc4='角色 %s (Guid: %u) 帐号 %s (Id: %u) 删除.' WHERE entry=1009;
UPDATE mangos_string SET content_loc4='| ID         |    Account    |       Character      |       IP        | GM | Expansion |' WHERE entry=1010;
UPDATE mangos_string SET content_loc4='========================================================================================' WHERE entry=1012;
UPDATE mangos_string SET content_loc4='| %10u |%15s| %20s | %15s |%4d| %9d |' WHERE entry=1013;
UPDATE mangos_string SET content_loc4='没有在线角色.' WHERE entry=1014;
UPDATE mangos_string SET content_loc4='只能从远程管理控制台退出或退出命令未完全输入(退出).' WHERE entry=1015;
UPDATE mangos_string SET content_loc4='| GUID       | Name                 | Account                      | Delete Date         |' WHERE entry=1016;
UPDATE mangos_string SET content_loc4='| %10u | %20s | %15s (%10u) | %19s |' WHERE entry=1017;
UPDATE mangos_string SET content_loc4='==========================================================================================' WHERE entry=1018;
UPDATE mangos_string SET content_loc4='角色不存在.' WHERE entry=1019;
UPDATE mangos_string SET content_loc4='恢复以下角色:' WHERE entry=1020;
UPDATE mangos_string SET content_loc4='删除以下角色:' WHERE entry=1021;
UPDATE mangos_string SET content_loc4='错误: 你只能选择单个角色设置新名称!' WHERE entry=1022;
UPDATE mangos_string SET content_loc4='角色 \'%s\' (GUID: %u Account %u) 无法恢复: 帐号不能存在!' WHERE entry=1023;
UPDATE mangos_string SET content_loc4='角色 \'%s\' (GUID: %u Account %u) 无法恢复: 帐号角色列表已满!' WHERE entry=1024;
UPDATE mangos_string SET content_loc4='角色 \'%s\' (GUID: %u Account %u) 无法恢复: 名称已被使用!' WHERE entry=1025;
UPDATE mangos_string SET content_loc4='GUID: %u 名称: %s 帐号: %s (%u) 日期: %s' WHERE entry=1026;
UPDATE mangos_string SET content_loc4='日志过滤状态:' WHERE entry=1027;
UPDATE mangos_string SET content_loc4='全部日志过滤设置为: %s' WHERE entry=1028;
UPDATE mangos_string SET content_loc4='只能从远程管理控制台调用指令.' WHERE entry=1029;
UPDATE mangos_string SET content_loc4='帐户 %s (Id: %u) 已被授予 %u 版本权限.' WHERE entry=1100;
UPDATE mangos_string SET content_loc4='今日消息更改为:\r\n%s' WHERE entry=1101;
UPDATE mangos_string SET content_loc4='发送消息到%s: %s' WHERE entry=1102;
UPDATE mangos_string SET content_loc4='%d - %s %s' WHERE entry=1103;
UPDATE mangos_string SET content_loc4='%d - %s' WHERE entry=1104;
UPDATE mangos_string SET content_loc4='%d - %s %s' WHERE entry=1105;
UPDATE mangos_string SET content_loc4='%d - %s %s' WHERE entry=1106;
UPDATE mangos_string SET content_loc4='%d - %s' WHERE entry=1107;
UPDATE mangos_string SET content_loc4='%d - %s %s' WHERE entry=1108;
UPDATE mangos_string SET content_loc4='%d - %s %s %s %s' WHERE entry=1109;
UPDATE mangos_string SET content_loc4='%d%s - %s X:%f Y:%f Z:%f MapId:%d' WHERE entry=1110;
UPDATE mangos_string SET content_loc4='%d%s - %s X:%f Y:%f Z:%f MapId:%d' WHERE entry=1111;
UPDATE mangos_string SET content_loc4='打开文件失败: %s' WHERE entry=1112;
UPDATE mangos_string SET content_loc4='帐号 %s (%u) 已经达到最大角色限制 (客户端限制)' WHERE entry=1113;
UPDATE mangos_string SET content_loc4='转储文件有损坏的数据！' WHERE entry=1114;
UPDATE mangos_string SET content_loc4='无效的角色名称！' WHERE entry=1115;
UPDATE mangos_string SET content_loc4='无效的公会名称！' WHERE entry=1116;
UPDATE mangos_string SET content_loc4='公会名称%u已被使用!' WHERE entry=1117;
UPDATE mangos_string SET content_loc4='%d - guild: %s (guid: %u) %s' WHERE entry=1118;
UPDATE mangos_string SET content_loc4='你必须使用男性或女性作为性别.' WHERE entry=1119;
UPDATE mangos_string SET content_loc4='你改变%s的性别为%s.' WHERE entry=1120;
UPDATE mangos_string SET content_loc4='你的性别%s更改为%s.' WHERE entry=1121;
UPDATE mangos_string SET content_loc4='(%u/%u +perm %u +temp %u)' WHERE entry=1122;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|Htaxinode:%u|h[%s %s]|h|r (Map:%u X:%f Y:%f Z:%f)' WHERE entry=1128;
UPDATE mangos_string SET content_loc4='%d - %s %s (Map:%u X:%f Y:%f Z:%f)' WHERE entry=1129;
UPDATE mangos_string SET content_loc4='事件启用 %u \"%s\"' WHERE entry=1130;
UPDATE mangos_string SET content_loc4='事件停止 %u \"%s\"' WHERE entry=1131;
UPDATE mangos_string SET content_loc4='   跟随玩家 %s (lowguid %u)' WHERE entry=1132;
UPDATE mangos_string SET content_loc4='   跟随生物 %s (lowguid %u)' WHERE entry=1133;
UPDATE mangos_string SET content_loc4='   跟随<空>' WHERE entry=1134;
UPDATE mangos_string SET content_loc4='已学习天赋列表:' WHERE entry=1135;
UPDATE mangos_string SET content_loc4='   (发现天赋: %u 使用的天赋点数: %u)' WHERE entry=1136;
UPDATE mangos_string SET content_loc4='%d%s - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ' WHERE entry=1137;
UPDATE mangos_string SET content_loc4='=================================================================================' WHERE entry=1138;
UPDATE mangos_string SET content_loc4='| GUID       | Name                 | Race            | Class           | Level |' WHERE entry=1139;
UPDATE mangos_string SET content_loc4='| %10u | %20s | %15s | %15s | %5u |' WHERE entry=1140;
UPDATE mangos_string SET content_loc4='%u - |cffffffff|Hplayer:%s|h[%s]|h|r %s %s %u' WHERE entry=1141;
UPDATE mangos_string SET content_loc4='%u - %s (在线:%s 地址:%s 管理员:%u 版本:%u)' WHERE entry=1142;
UPDATE mangos_string SET content_loc4='Spawned by event %u (%s)' WHERE entry=1143;
UPDATE mangos_string SET content_loc4='Despawned by event %u (%s)' WHERE entry=1144;
UPDATE mangos_string SET content_loc4='部分鱼池 %u' WHERE entry=1145;
UPDATE mangos_string SET content_loc4='Part of pool %u, top pool %u' WHERE entry=1146;
UPDATE mangos_string SET content_loc4='The (top)pool %u is spawned by event %u (%s)' WHERE entry=1147;
UPDATE mangos_string SET content_loc4='The (top)pool %u is despawned by event %u (%s)' WHERE entry=1148;
UPDATE mangos_string SET content_loc4=' (鱼池 %u)' WHERE entry=1149;
UPDATE mangos_string SET content_loc4='(事件 %i)' WHERE entry=1150;
UPDATE mangos_string SET content_loc4=' (鱼池 %u 事件 %i)' WHERE entry=1151;
UPDATE mangos_string SET content_loc4='[使用]' WHERE entry=1152;
UPDATE mangos_string SET content_loc4='Get %s bitstr value:[FIELD]:%u [VALUE]:%s' WHERE entry=1153;
UPDATE mangos_string SET content_loc4='%s has bitstr value:[FIELD]:%u [VALUE]:%s' WHERE entry=1154;
UPDATE mangos_string SET content_loc4='Get %s hex value:[FIELD]:%u [VALUE]:%x' WHERE entry=1155;
UPDATE mangos_string SET content_loc4='%s has hex value:[FIELD]:%u [VALUE]:%x' WHERE entry=1156;
UPDATE mangos_string SET content_loc4='Modify %s hex field:%u %s %x = %x (hex)' WHERE entry=1157;
UPDATE mangos_string SET content_loc4='You modify for %s hex field:%u %s %x = %x (hex)' WHERE entry=1158;
UPDATE mangos_string SET content_loc4='Modify %s float field:%u to sum with:%f = %f' WHERE entry=1159;
UPDATE mangos_string SET content_loc4='You modify for %s float field:%u to sum with:%f = %f' WHERE entry=1160;
UPDATE mangos_string SET content_loc4='法术 %u 没有光环.' WHERE entry=1165;
UPDATE mangos_string SET content_loc4='脚本库不存在或者不可访问.' WHERE entry=1166;
UPDATE mangos_string SET content_loc4='脚本库有错误的列表函数(过时了?).' WHERE entry=1167;
UPDATE mangos_string SET content_loc4='脚本库重载.' WHERE entry=1168;
UPDATE mangos_string SET content_loc4='脚本库版本不匹配.' WHERE entry=1169;
UPDATE mangos_string SET content_loc4='玩家选择: %s.\n阵营: %u.\nnpcFlags: %u.\nBase Entry: %u, Spawned Entry %u (Difficulty %u).\nDisplayID: %u (Native: %u).' WHERE entry=1170;
UPDATE mangos_string SET content_loc4='拍卖行机器人配置文件加载所有配置.' WHERE entry=1171;
UPDATE mangos_string SET content_loc4='错误尝试重新加载拍卖行机器人配置.' WHERE entry=1172;
UPDATE mangos_string SET content_loc4='==========================================================' WHERE entry=1173;
UPDATE mangos_string SET content_loc4='|--------------------------------------------------------|' WHERE entry=1174;
UPDATE mangos_string SET content_loc4='|           |   联盟   |   部落   |   中立   |    总数   |' WHERE entry=1175;
UPDATE mangos_string SET content_loc4='          联盟/部落/中立/总数' WHERE entry=1176;
UPDATE mangos_string SET content_loc4='| %-10s | %8u | %8u | %8u | %8u |' WHERE entry=1177;
UPDATE mangos_string SET content_loc4='%-10s = %6u / %6u / %6u / %6u' WHERE entry=1178;
UPDATE mangos_string SET content_loc4='总数' WHERE entry=1179;
UPDATE mangos_string SET content_loc4='物品大小' WHERE entry=1180;
UPDATE mangos_string SET content_loc4='|           |   联盟   |   部落   |   中立   |    数量   |' WHERE entry=1181;
UPDATE mangos_string SET content_loc4='          联盟/部落/中立/数量' WHERE entry=1182;
UPDATE mangos_string SET content_loc4='灰色' WHERE entry=1183;
UPDATE mangos_string SET content_loc4='白色' WHERE entry=1184;
UPDATE mangos_string SET content_loc4='绿色' WHERE entry=1185;
UPDATE mangos_string SET content_loc4='蓝色' WHERE entry=1186;
UPDATE mangos_string SET content_loc4='紫色' WHERE entry=1187;
UPDATE mangos_string SET content_loc4='橙色' WHERE entry=1188;
UPDATE mangos_string SET content_loc4='黄色' WHERE entry=1189;
UPDATE mangos_string SET content_loc4='数量 %s 装备设置为 %u.' WHERE entry=1190;
UPDATE mangos_string SET content_loc4='Items ratio for %s is set to %u.' WHERE entry=1191;
UPDATE mangos_string SET content_loc4='Effect movement' WHERE entry=1192;
UPDATE mangos_string SET content_loc4='当前状态信息: GOState %u, LootState %u. Collision %s' WHERE entry=1194;
UPDATE mangos_string SET content_loc4='当前状态信息: GOState %u, LootState %u. Collision %s, (door %s by default)' WHERE entry=1195;
UPDATE mangos_string SET content_loc4='You try to view cinemitic %u but it doesn\'t exist.' WHERE entry=1200;
UPDATE mangos_string SET content_loc4='Spell %u %s = %f (*1.88 = %f) DB = %f AP = %f' WHERE entry=1202;
UPDATE mangos_string SET content_loc4='直接治愈' WHERE entry=1203;
UPDATE mangos_string SET content_loc4='直接伤害' WHERE entry=1204;
UPDATE mangos_string SET content_loc4='持续治愈' WHERE entry=1205;
UPDATE mangos_string SET content_loc4='持续伤害' WHERE entry=1206;
UPDATE mangos_string SET content_loc4='%u - [%s] AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u Chance: %f %s' WHERE entry=1500;
UPDATE mangos_string SET content_loc4='%u - |cffffffff|Hpool:%u|h[%s]|h|r AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u %s' WHERE entry=1501;
UPDATE mangos_string SET content_loc4='%u - [%s] AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u %s' WHERE entry=1502;
UPDATE mangos_string SET content_loc4='Cannot add spawn because no free guids for static spawn in reserved guids range. Server restart is required before command can be used. Also look GuidReserveSize.* config options.' WHERE entry=1503;
UPDATE mangos_string SET content_loc4='AI-Information for Npc Entry %u' WHERE entry=1504;
UPDATE mangos_string SET content_loc4='AI名称: %s (%s) 脚本名称: %s' WHERE entry=1505;
UPDATE mangos_string SET content_loc4='当前阶段 = %u' WHERE entry=1506;
UPDATE mangos_string SET content_loc4='战斗移动 %s' WHERE entry=1507;
UPDATE mangos_string SET content_loc4='近战攻击 %s' WHERE entry=1508;
UPDATE mangos_string SET content_loc4='鱼池 %u 未找到 (最大鱼池 entry %u)' WHERE entry=1509;
UPDATE mangos_string SET content_loc4='|cffffff00北地哨塔被部落占领了！|r' WHERE entry=1600;
UPDATE mangos_string SET content_loc4='|cffffff00北地哨塔被联盟占领了！|r' WHERE entry=1601;
UPDATE mangos_string SET content_loc4='|cffffff00皇冠哨塔被部落占领了！|r' WHERE entry=1602;
UPDATE mangos_string SET content_loc4='|cffffff00皇冠哨塔被联盟占领了！|r' WHERE entry=1603;
UPDATE mangos_string SET content_loc4='|cffffff00东墙哨塔被部落占领了！|r' WHERE entry=1604;
UPDATE mangos_string SET content_loc4='|cffffff00东墙哨塔被联盟占领了！|r' WHERE entry=1605;
UPDATE mangos_string SET content_loc4='|cffffff00病木林哨塔被部落占领了！|r' WHERE entry=1606;
UPDATE mangos_string SET content_loc4='|cffffff00病木林哨塔被联盟占领了！|r' WHERE entry=1607;
UPDATE mangos_string SET content_loc4='|cffffff00部落占领了瞭望台！|r' WHERE entry=1608;
UPDATE mangos_string SET content_loc4='|cffffff00联盟占领了瞭望台！|r' WHERE entry=1609;
UPDATE mangos_string SET content_loc4='|cffffff00部落占领了竞赛场！|r' WHERE entry=1610;
UPDATE mangos_string SET content_loc4='|cffffff00联盟占领了竞赛场！|r' WHERE entry=1611;
UPDATE mangos_string SET content_loc4='|cffffff00部落占领了碎石岭！|r' WHERE entry=1612;
UPDATE mangos_string SET content_loc4='|cffffff00联盟占领了碎石岭！|r' WHERE entry=1613;
UPDATE mangos_string SET content_loc4='|cffffff00部落夺取了东部灯塔的控制权！|r' WHERE entry=1614;
UPDATE mangos_string SET content_loc4='|cffffff00联盟夺取了东部灯塔的控制权！|r' WHERE entry=1615;
UPDATE mangos_string SET content_loc4='|cffffff00部落夺取了西部灯塔的控制权！|r' WHERE entry=1616;
UPDATE mangos_string SET content_loc4='|cffffff00联盟夺取了西部灯塔的控制权！|r' WHERE entry=1617;
UPDATE mangos_string SET content_loc4='|cffffff00部落夺取了东部灯塔和西部灯塔的控制权！|r' WHERE entry=1618;
UPDATE mangos_string SET content_loc4='|cffffff00联盟夺取了东部灯塔和西部灯塔的控制权！|r' WHERE entry=1619;
UPDATE mangos_string SET content_loc4='|cffffff00部落战地斥候正在发放军旗。|r' WHERE entry=1620;
UPDATE mangos_string SET content_loc4='|cffffff00联盟战地斥候正在发放军旗。|r' WHERE entry=1621;
UPDATE mangos_string SET content_loc4='|cffffff00部落夺取了双塔废墟的控制权！|r' WHERE entry=1622;
UPDATE mangos_string SET content_loc4='|cffffff00联盟夺取了双塔废墟的控制权！|r' WHERE entry=1623;
UPDATE mangos_string SET content_loc4='|cffffff00部落夺取了一座灵魂塔的控制权！|r' WHERE entry=1624;
UPDATE mangos_string SET content_loc4='|cffffff00联盟夺取了一座灵魂塔的控制权！|r' WHERE entry=1625;
UPDATE mangos_string SET content_loc4='|cffffff00部落失去了一座灵魂塔的控制权！|r' WHERE entry=1626;
UPDATE mangos_string SET content_loc4='|cffffff00联盟失去了一座灵魂塔的控制权！|r' WHERE entry=1627;
UPDATE mangos_string SET content_loc4='|cffffff00部落夺取了白骨荒野的控制权！|r' WHERE entry=1628;
UPDATE mangos_string SET content_loc4='|cffffff00联盟夺取了白骨荒野的控制权！|r' WHERE entry=1629;
UPDATE mangos_string SET content_loc4='|cffffff00部落正在夺取哈兰的控制权！|r' WHERE entry=1630;
UPDATE mangos_string SET content_loc4='|cffffff00联盟正在夺取哈兰的控制权！|r' WHERE entry=1631;
UPDATE mangos_string SET content_loc4='|cffffff00部落占领了哈兰！|r' WHERE entry=1632;
UPDATE mangos_string SET content_loc4='|cffffff00联盟占领了哈兰！|r' WHERE entry=1633;
UPDATE mangos_string SET content_loc4='|cffffff00哈兰的防御力量被消灭了！|r' WHERE entry=1634;
UPDATE mangos_string SET content_loc4='|cffffff00部落已经收集了200个希利苏斯水晶尘！|r' WHERE entry=1635;
UPDATE mangos_string SET content_loc4='|cffffff00联盟已经收集了200个希利苏斯水晶尘！|' WHERE entry=1636;
UPDATE mangos_string SET content_loc4='RAF system ok.' WHERE entry=1700;
UPDATE mangos_string SET content_loc4='RAF system error.' WHERE entry=1701;
UPDATE mangos_string SET content_loc4='角色 |cffff0000%s|r [GUID: %u] 有 |cffff0000%f|r 仇恨' WHERE entry=1702;
UPDATE mangos_string SET content_loc4='显示仇恨 %s [Entry %u]' WHERE entry=1703;
UPDATE mangos_string SET content_loc4='排队玩家: %u (最大: %u)' WHERE entry=1704;
UPDATE mangos_string SET content_loc4='特殊玩家: %u' WHERE entry=1705;
