UPDATE creature_text SET text='For Khaz''Modan!' WHERE entry=2784;
UPDATE creature_text SET text='Feel the fury of the mountain!' WHERE entry=2784;
UPDATE creature_text SET text='小心，$N! 看西边!' WHERE entry=3389;
UPDATE creature_text SET text='一个防卫者倒下了!' WHERE entry=3389;
UPDATE creature_text SET text='太感谢了,亲爱的 $C, 你把我复活了!' WHERE entry=6172;
UPDATE creature_text SET text='太感谢了,亲爱的 $C, 你把我复活了!' WHERE entry=6177;
UPDATE creature_text SET text='Grid yourself, $N. The demon in this orb is a fel beast.' WHERE entry=6546;
UPDATE creature_text SET text='The Kolkar are the strongest!' WHERE entry=9456;
UPDATE creature_text SET text='Defend the bunkers!' WHERE entry=9458;
UPDATE creature_text SET text='Our foes will fail!' WHERE entry=9458;
UPDATE creature_text SET text='为了部落!' WHERE entry=9458;
UPDATE creature_text SET text='%s goes into a frenzy!' WHERE entry=9461;
UPDATE creature_text SET text='Kolkar Invader charges!' WHERE entry=9524;
UPDATE creature_text SET text='Killing you be easy!' WHERE entry=11339;
UPDATE creature_text SET text='Troll mojo da strongest mojo!' WHERE entry=11339;
UPDATE creature_text SET text='Your skull gonna decorate our ritual altars!' WHERE entry=11339;
UPDATE creature_text SET text='I gonna make you into mojo!' WHERE entry=11339;
UPDATE creature_text SET text='Feel da big bad voodoo!' WHERE entry=11339;
UPDATE creature_text SET text='My weapon be thirsty!' WHERE entry=11339;
UPDATE creature_text SET text='You be dead soon!' WHERE entry=11339;
UPDATE creature_text SET text='Killing you be easy!' WHERE entry=11340;
UPDATE creature_text SET text='Troll mojo da strongest mojo!' WHERE entry=11340;
UPDATE creature_text SET text='Your skull gonna decorate our ritual altars!' WHERE entry=11340;
UPDATE creature_text SET text='I gonna make you into mojo!' WHERE entry=11340;
UPDATE creature_text SET text='Feel da big bad voodoo!' WHERE entry=11340;
UPDATE creature_text SET text='My weapon be thirsty!' WHERE entry=11340;
UPDATE creature_text SET text='You be dead soon!' WHERE entry=11340;
UPDATE creature_text SET text='%s goes into a frenzy!' WHERE entry=11350;
UPDATE creature_text SET text='Killing you be easy!' WHERE entry=11350;
UPDATE creature_text SET text='Troll mojo da strongest mojo!' WHERE entry=11350;
UPDATE creature_text SET text='Your skull gonna decorate our ritual altars!' WHERE entry=11350;
UPDATE creature_text SET text='I gonna make you into mojo!' WHERE entry=11350;
UPDATE creature_text SET text='Feel da big bad voodoo!' WHERE entry=11350;
UPDATE creature_text SET text='My weapon be thirsty!' WHERE entry=11350;
UPDATE creature_text SET text='You be dead soon!' WHERE entry=11350;
UPDATE creature_text SET text='Killing you be easy!' WHERE entry=11351;
UPDATE creature_text SET text='Troll mojo da strongest mojo!' WHERE entry=11351;
UPDATE creature_text SET text='Your skull gonna decorate our ritual altars!' WHERE entry=11351;
UPDATE creature_text SET text='I gonna make you into mojo!' WHERE entry=11351;
UPDATE creature_text SET text='Feel da big bad voodoo!' WHERE entry=11351;
UPDATE creature_text SET text='My weapon be thirsty!' WHERE entry=11351;
UPDATE creature_text SET text='You be dead soon!' WHERE entry=11351;
UPDATE creature_text SET text='%s goes into a frenzy!' WHERE entry=11352;
UPDATE creature_text SET text='%s becomes enraged!' WHERE entry=11355;
UPDATE creature_text SET text='Killing you be easy!' WHERE entry=11356;
UPDATE creature_text SET text='Troll mojo da strongest mojo!' WHERE entry=11356;
UPDATE creature_text SET text='Your skull gonna decorate our ritual altars!' WHERE entry=11356;
UPDATE creature_text SET text='I gonna make you into mojo!' WHERE entry=11356;
UPDATE creature_text SET text='Feel da big bad voodoo!' WHERE entry=11356;
UPDATE creature_text SET text='My weapon be thirsty!' WHERE entry=11356;
UPDATE creature_text SET text='You be dead soon!' WHERE entry=11356;
UPDATE creature_text SET text='%s goes into a frenzy!' WHERE entry=11359;
UPDATE creature_text SET text='Killing you be easy!' WHERE entry=11830;
UPDATE creature_text SET text='Troll mojo da strongest mojo!' WHERE entry=11830;
UPDATE creature_text SET text='Your skull gonna decorate our ritual altars!' WHERE entry=11830;
UPDATE creature_text SET text='I gonna make you into mojo!' WHERE entry=11830;
UPDATE creature_text SET text='Feel da big bad voodoo!' WHERE entry=11830;
UPDATE creature_text SET text='My weapon be thirsty!' WHERE entry=11830;
UPDATE creature_text SET text='You be dead soon!' WHERE entry=11830;
UPDATE creature_text SET text='Killing you be easy!' WHERE entry=11831;
UPDATE creature_text SET text='Troll mojo da strongest mojo!' WHERE entry=11831;
UPDATE creature_text SET text='Your skull gonna decorate our ritual altars!' WHERE entry=11831;
UPDATE creature_text SET text='I gonna make you into mojo!' WHERE entry=11831;
UPDATE creature_text SET text='Feel da big bad voodoo!' WHERE entry=11831;
UPDATE creature_text SET text='My weapon be thirsty!' WHERE entry=11831;
UPDATE creature_text SET text='You be dead soon!' WHERE entry=11831;
UPDATE creature_text SET text='If you want the key, you''ll have to catch me!' WHERE entry=14354;
UPDATE creature_text SET text='Chase me if you dare! I run without a care!' WHERE entry=14354;
UPDATE creature_text SET text='Why would you ever want to harm me!? Come. Friends we can be!' WHERE entry=14354;
UPDATE creature_text SET text='DIE?! You make Pusillin cry!' WHERE entry=14354;
UPDATE creature_text SET text='Say hello to my little friends!' WHERE entry=14354;
UPDATE creature_text SET text='让复仇的毒蛇吞噬你们吧!' WHERE entry=14507;
UPDATE creature_text SET text='Ssserenity..at lassst!' WHERE entry=14507;
UPDATE creature_text SET text='%s fully engulfs in flame and a maddened look appears in his eyes!' WHERE entry=14750;
UPDATE creature_text SET text='%s becomes enraged!' WHERE entry=14821;
UPDATE creature_text SET text='The strands of LIFE have been severed! The Dreamers must be avenged!' WHERE entry=14887;
UPDATE creature_text SET text='Come forth, ye Dreamers - and claim your vengeance!' WHERE entry=14887;
UPDATE creature_text SET text='I can sense the SHADOW on your hearts. There can be no rest for the wicked!' WHERE entry=14888;
UPDATE creature_text SET text='Your wicked souls shall feed my power!' WHERE entry=14888;
UPDATE creature_text SET text='Hope is a DISEASE of the soul! This land shall wither and die!' WHERE entry=14889;
UPDATE creature_text SET text='Taste your world''s corruption!' WHERE entry=14889;
UPDATE creature_text SET text='Peace is but a fleeting dream! Let the NIGHTMARE reign!' WHERE entry=14890;
UPDATE creature_text SET text='Children of Madness - I release you upon this world!' WHERE entry=14890;
UPDATE creature_text SET text='Your treachery only speeds your doom. This world will fall to darkness!' WHERE entry=15203;
UPDATE creature_text SET text='Your treachery only speeds your doom. This world will fall to darkness!' WHERE entry=15204;
UPDATE creature_text SET text='Your treachery only speeds your doom. This world will fall to darkness!' WHERE entry=15205;
UPDATE creature_text SET text='What? Such a small, frail thing beckons me? This will not do unpunished!' WHERE entry=15206;
UPDATE creature_text SET text='What? Such a small, frail thing beckons me? This will not do unpunished!' WHERE entry=15207;
UPDATE creature_text SET text='What? Such a small, frail thing beckons me? This will not do unpunished!' WHERE entry=15208;
UPDATE creature_text SET text='The Abyssal Council does not tolerate deceit! Feel our wrath, little human!' WHERE entry=15209;
UPDATE creature_text SET text='The Abyssal Council does not tolerate deceit! Feel our wrath, little human!' WHERE entry=15211;
UPDATE creature_text SET text='The Abyssal Council does not tolerate deceit! Feel our wrath, little human!' WHERE entry=15212;
UPDATE creature_text SET text='What? Such a small, frail thing beckons me? This will not do unpunished!' WHERE entry=15220;
UPDATE creature_text SET text='Your treachery only speeds your doom. This world will fall to darkness!' WHERE entry=15305;
UPDATE creature_text SET text='The Abyssal Council does not tolerate deceit! Feel our wrath, little human!' WHERE entry=15307;
UPDATE creature_text SET text='非常不错. 咱们到里面看看能有什么好东西, $N.' WHERE entry=15420;
UPDATE creature_text SET text='没看到你说的那些好东西, $r? 你可不要忽悠我，我会让你付出代价的！' WHERE entry=15420;
UPDATE creature_text SET text='嗯？这是... 你怎么会有我们的密信. 看来必须得干掉你了.死吧！你这个杂碎！为了联盟！' WHERE entry=15420;
UPDATE creature_text SET text='我遗憾的向你说再见了!' WHERE entry=15481;
UPDATE creature_text SET text='Th... thank you.  I thought I was going to die.' WHERE entry=16206;
UPDATE creature_text SET text='Thanks, I should''ve never left Silverpine Forest.' WHERE entry=16208;
UPDATE creature_text SET text='非常感谢你!' WHERE entry=16209;
UPDATE creature_text SET text='The %s seems overjoyed.' WHERE entry=16518;
UPDATE creature_text SET text='The %s seems disoriented.' WHERE entry=16518;
UPDATE creature_text SET text='The %s doesn''t look like it minds the crystal''s effects.' WHERE entry=16518;
UPDATE creature_text SET text='The %s didn''t like what just happened.' WHERE entry=16518;
UPDATE creature_text SET text='The %s looks confused.' WHERE entry=16518;
UPDATE creature_text SET text='The %s nods appreciatively.' WHERE entry=16518;
UPDATE creature_text SET text='%s becomes enraged!' WHERE entry=16878;
UPDATE creature_text SET text='入侵者闯入了内室。加紧毁掉那条绿龙！留下龙筋龙骨用来复生！' WHERE entry=16980;
UPDATE creature_text SET text='I think I can make it to Brackenwall on my own. They''ve got the cargo at the top of the tower. Be careful!' WHERE entry=17119;
UPDATE creature_text SET text='停止前进,否则你们将被消灭.' WHERE entry=17711;
UPDATE creature_text SET text='地面破坏程序启动.' WHERE entry=17711;
UPDATE creature_text SET text='范围确认,释放.' WHERE entry=17711;
UPDATE creature_text SET text='轨道锁定.' WHERE entry=17711;
UPDATE creature_text SET text='提升至最高速度.' WHERE entry=17711;
UPDATE creature_text SET text='威胁等级:0.' WHERE entry=17711;
UPDATE creature_text SET text='指令完成.' WHERE entry=17711;
UPDATE creature_text SET text='目标已歼灭.' WHERE entry=17711;
UPDATE creature_text SET text='系统崩溃倒计时,5、4……' WHERE entry=17711;
UPDATE creature_text SET text='%s goes into a frenzy!' WHERE entry=18069;
UPDATE creature_text SET text='Dat was poop! Mogor could put up much better fight den dat!' WHERE entry=18069;
UPDATE creature_text SET text='Mogor not impressed! Skra''gath wuz made of da air and shadow! Soft like da squishy orcies!' WHERE entry=18069;
UPDATE creature_text SET text='Now you face da true champion! I give you chance to run away little one. Run away now before Mogor decim... destyor... Run away before Mogor KILL!' WHERE entry=18069;
UPDATE creature_text SET text='No more chances! Now you pay da ogre!' WHERE entry=18069;
UPDATE creature_text SET text='No more nice ogre! You hurt Mogor!' WHERE entry=18069;
UPDATE creature_text SET text='WUT!? UNPOSSIBLE!! You fight Mogor now! Mogor destroy!' WHERE entry=18069;
UPDATE creature_text SET text='Obey the laws of Silvermoon. Failure to do so will result in termination.' WHERE entry=18103;
UPDATE creature_text SET text='Maintain order within these walls.' WHERE entry=18103;
UPDATE creature_text SET text='Look out!' WHERE entry=18209;
UPDATE creature_text SET text='Don''t let them escape! Kill the strong one first!' WHERE entry=18209;
UPDATE creature_text SET text='More of them are coming! Watch out!' WHERE entry=18209;
UPDATE creature_text SET text='Where do you think you''re going? Kill them all!' WHERE entry=18209;
UPDATE creature_text SET text='Ride the lightning, filth!' WHERE entry=18209;
UPDATE creature_text SET text='FROST SHOCK!' WHERE entry=18209;
UPDATE creature_text SET text='Up ahead is the road to Telaar. We will split up when we reach the fork as they will surely send more Murkblood after us. Hopefully one of us makes it back to Telaar alive.' WHERE entry=18209;
UPDATE creature_text SET text='Look out!' WHERE entry=18210;
UPDATE creature_text SET text='Don''t let them escape! Kill the strong one first!' WHERE entry=18210;
UPDATE creature_text SET text='More of them are coming! Watch out!' WHERE entry=18210;
UPDATE creature_text SET text='Where do you think you''re going? Kill them all!' WHERE entry=18210;
UPDATE creature_text SET text='Ride the lightning, filth!' WHERE entry=18210;
UPDATE creature_text SET text='FROST SHOCK!' WHERE entry=18210;
UPDATE creature_text SET text='It is best that we split up now, in case they send more after us. Hopefully one of us will make it back to Garrosh. Farewell, stranger.' WHERE entry=18210;
UPDATE creature_text SET text='In Nagrand, food hunt ogre!' WHERE entry=18351;
UPDATE creature_text SET text='You taste good with maybe a little salt and pepper.' WHERE entry=18351;
UPDATE creature_text SET text='OK, OK! Lump give up!' WHERE entry=18351;
UPDATE creature_text SET text='Blue brothers reign supreme!' WHERE entry=18399;
UPDATE creature_text SET text='ROKDAR SMASH PUNY %t!' WHERE entry=18400;
UPDATE creature_text SET text='Closer... Come closer... See what the void brings!' WHERE entry=18401;
UPDATE creature_text SET text='Piece by piece I will tear this challenger apart... PIECE BY PIECE!' WHERE entry=18402;
UPDATE creature_text SET text='Death to the ogres!' WHERE entry=18428;
UPDATE creature_text SET text='Many thanks, hero!' WHERE entry=18428;
UPDATE creature_text SET text='One day, a hero will rise and lift the orcs up to their former glory.' WHERE entry=18428;
UPDATE creature_text SET text='Spirits watch over you, $r!' WHERE entry=18428;
UPDATE creature_text SET text='Thank you, $r! Your service to the Mag''har will not be forgotten.' WHERE entry=18428;
UPDATE creature_text SET text='Get in the Ring of Blood, $N. The fight is about to start!' WHERE entry=18471;
UPDATE creature_text SET text='The battle is about to begin! $N versus the ferocious clefthoof, Brokentoe!' WHERE entry=18471;
UPDATE creature_text SET text='$N has defeated Brokentoe!' WHERE entry=18471;
UPDATE creature_text SET text='The battle is about to begin! The unmerciful Murkblood twins versus $N!' WHERE entry=18471;
UPDATE creature_text SET text='Unbelievable! $N has defeated the Murkblood Twins!' WHERE entry=18471;
UPDATE creature_text SET text='Hailing from the mountains of Blade''s Edge comes Rokdar the Sundered Lord! $N is in for the fight of $g his:her;
 life.' WHERE entry=18471;
UPDATE creature_text SET text='$N is victorious once more!' WHERE entry=18471;
UPDATE creature_text SET text='From parts unkown: Skra''gath! Can $N possibly survive the onslaught of void energies?' WHERE entry=18471;
UPDATE creature_text SET text='$N is victorious once more!' WHERE entry=18471;
UPDATE creature_text SET text='This is the moment we''ve all been waiting for! The Warmaul champion is about to make $g his:her;
 first showing at the Ring of Blood in weeks! Will $N go down in defeat as easily as the champion''s other opponents? We shall see...' WHERE entry=18471;
UPDATE creature_text SET text='$N is victorious once more!' WHERE entry=18471;
UPDATE creature_text SET text='Mogor has challenged you. You have to accept! Get in the ring if you are ready to fight.' WHERE entry=18471;
UPDATE creature_text SET text='Ancestors watch over you, kind one...' WHERE entry=18688;
UPDATE creature_text SET text='Cease your crying! STOP!' WHERE entry=18688;
UPDATE creature_text SET text='I remember everything...' WHERE entry=18688;
UPDATE creature_text SET text='It cannot be...' WHERE entry=18688;
UPDATE creature_text SET text='It comes for you...' WHERE entry=18688;
UPDATE creature_text SET text='The spirits call... I am consumed.' WHERE entry=18688;
UPDATE creature_text SET text='Cannot control... It draws me in... The void grows...' WHERE entry=18688;
UPDATE creature_text SET text='It is dying. It is dying. It is dying.' WHERE entry=18688;
UPDATE creature_text SET text='The cold embrace awaits...' WHERE entry=18688;
UPDATE creature_text SET text='The pain is unbearable.' WHERE entry=18688;
UPDATE creature_text SET text='What is happening to me?' WHERE entry=18688;
UPDATE creature_text SET text='What is this trickery? I... ARGH...' WHERE entry=18688;
UPDATE creature_text SET text='What will become of us when it falls?' WHERE entry=18688;
UPDATE creature_text SET text='我仍然清晰的记得,三次战争败北的耻辱,我等待复仇的机会,已经等得太久了,现在,军团的阴影将重新笼罩这个世界,你们彻底毁灭的日子,已经不远了!' WHERE entry=18728;
UPDATE creature_text SET text='军团将会征服一切!' WHERE entry=18728;
UPDATE creature_text SET text='所有的凡人都将灭亡!' WHERE entry=18728;
UPDATE creature_text SET text='所有的生命,都将被根除!' WHERE entry=18728;
UPDATE creature_text SET text='我要把你们生吞活剥!' WHERE entry=18728;
UPDATE creature_text SET text='Kirel Narak!' WHERE entry=18728;
UPDATE creature_text SET text='可笑的蠢货!' WHERE entry=18728;
UPDATE creature_text SET text='宇宙将获得新生!' WHERE entry=18728;
UPDATE creature_text SET text='军团……永远不会……失败……' WHERE entry=18728;
UPDATE creature_text SET text='%s goes into a frenzy!' WHERE entry=18728;
UPDATE creature_text SET text='Invaders, you dangle upon the precipice of oblivion! The Burning Legion comes and with it comes your end.' WHERE entry=18728;
UPDATE creature_text SET text='Impudent whelps, you only delay the inevitable. Where one has fallen, ten shall rise. Such is the will of Kazzak...' WHERE entry=18728;
UPDATE creature_text SET text='Arrrhhh...Guards!' WHERE entry=18930;
UPDATE creature_text SET text='Thank you for freeing me, $N! I''m going to make my way to Shattrath!' WHERE entry=18956;
UPDATE creature_text SET text='Hey, did you read the bounty on this wanted poster?' WHERE entry=18999;
UPDATE creature_text SET text='The Bone Wastes! I don''t care what''s being offered as a reward, I''m not going into the Bone Wastes!' WHERE entry=18999;
UPDATE creature_text SET text='This wanted poster says that they''re offering gold to these so-called adventurers to go kill things. Isn''t that what we do? I don''t think I''m being paid enough!' WHERE entry=18999;
UPDATE creature_text SET text='You want to go do the bounty off of this wanted poster after the shift is over?' WHERE entry=18999;
UPDATE creature_text SET text='This poster has a bounty on bonelashers. You think I should do that?' WHERE entry=18999;
UPDATE creature_text SET text='Is that wanted poster all that you''re going to talk about today?' WHERE entry=18999;
UPDATE creature_text SET text='I''m up to looking into that bounty after this shift.' WHERE entry=18999;
UPDATE creature_text SET text='I could use the extra money.' WHERE entry=18999;
UPDATE creature_text SET text='I don''t know and I don''t care.' WHERE entry=18999;
UPDATE creature_text SET text='The bonelashers of the wastes are no laughing matter. I hear they carry diseases!' WHERE entry=18999;
UPDATE creature_text SET text='Oh sweet, delicious, spotted eggs - you will be mine...' WHERE entry=19035;
UPDATE creature_text SET text='If only I could get this blasted machine working!' WHERE entry=19035;
UPDATE creature_text SET text='They look so delicious...' WHERE entry=19035;
UPDATE creature_text SET text='Emote blabla' WHERE entry=19055;
UPDATE creature_text SET text='What good does this violence serve?  What is done is done.  I have failed my people.' WHERE entry=19456;
UPDATE creature_text SET text='Haven''t you done enough harm?  Must you also disturb my slumber?' WHERE entry=19456;
UPDATE creature_text SET text='What... What have I become? Arrrgghhh...' WHERE entry=19480;
UPDATE creature_text SET text='A tradesman, perhaps? You need look no further than I for supplies. My prices are quite fair, friend. These items were difficult to acquire, but what does the source matter, eh? You''ll have what you need.' WHERE entry=19533;
UPDATE creature_text SET text='The creatures of this place are strong, wayfarer. You''ll need ample ammunition if you hope to survive. You''re in luck - I am well-stocked with fine arrows, bullets, and throwing weapons. The price is reasonable, considering circumstances.' WHERE entry=19534;
UPDATE creature_text SET text='If you think I''ll betray my friend that easily, think again!  Face me, you scoundrel!' WHERE entry=20159;
UPDATE creature_text SET text='Spare my life!  I will tell you about Arelion''s secret.' WHERE entry=20159;
UPDATE creature_text SET text='The best selection of smuggled goods is available right here, $N.  Great for the whole family!  Avoid goblin taxation and naaru prohibition - the Consortium is here to fill your every shopping need!' WHERE entry=20242;
UPDATE creature_text SET text='%s calls for the aid of a nearby male!' WHERE entry=20610;
UPDATE creature_text SET text='%s seems to have weakened.' WHERE entry=20610;
UPDATE creature_text SET text='%s goes into a frenzy!' WHERE entry=20774;
UPDATE creature_text SET text='%s seems to have weakened.' WHERE entry=20777;
UPDATE creature_text SET text='%s goes into a frenzy!' WHERE entry=20983;
UPDATE creature_text SET text='I''m through asking nicely, fish-man.' WHERE entry=21291;
UPDATE creature_text SET text='Where is the Cipher of Damnation? I know a third of it is in this village.' WHERE entry=21291;
UPDATE creature_text SET text='No... Of course not. What was I thinking? Why would you have a third of the Cipher of Damnation?' WHERE entry=21291;
UPDATE creature_text SET text='I feel so stupid. Maybe I should unchain you and set you free?' WHERE entry=21291;
UPDATE creature_text SET text='DO I HONESTLY LOOK THAT STUPID TO YOU, NAGA? NOW YOU FEEL PAIN!' WHERE entry=21291;
UPDATE creature_text SET text='%s spits on the Coilskar naga.' WHERE entry=21291;
UPDATE creature_text SET text='GET UP YOU ROTTEN PIECE OF TRASH! GET UP BEFORE I END YOU!' WHERE entry=21291;
UPDATE creature_text SET text='I''m listening...' WHERE entry=21291;
UPDATE creature_text SET text='Whhaaat... are you sssspeaking of, ssssoft-sskin?' WHERE entry=21295;
UPDATE creature_text SET text='The naga do nottt... have thissss... cipherrr...' WHERE entry=21295;
UPDATE creature_text SET text='Yesss... Yesss... Ssset me freee...' WHERE entry=21295;
UPDATE creature_text SET text='%s regains consciousness.' WHERE entry=21295;
UPDATE creature_text SET text='Do not beat the Coilsssskaarrr commander anymore, orc! I will tell you! The cipherrr... It is hidden in one of the chests at Coilssskarrr Point... The naga there hold the keysss...' WHERE entry=21295;
UPDATE creature_text SET text='COILSSSKARRR!' WHERE entry=21295;
UPDATE creature_text SET text='Your body is mine! Our fates are forever intertwined!' WHERE entry=21797;
UPDATE creature_text SET text='More Minions of Terokk are coming!' WHERE entry=22373;
UPDATE creature_text SET text='The invaders persist! Hold them off!' WHERE entry=22373;
UPDATE creature_text SET text='An Avatar of Terokk!! To arms!' WHERE entry=22373;
UPDATE creature_text SET text='The Avatar of Terokk has been defeated! Death to Terokk! Death to Skettis!' WHERE entry=22373;
UPDATE creature_text SET text='Chill Nymph appears weak!' WHERE entry=23678;
UPDATE creature_text SET text='I knew Lurielle would send help! Thank you friend, and give Lurielle my thanks as well!' WHERE entry=23678;
UPDATE creature_text SET text='Where am I? What happened to me? You... you freed me?' WHERE entry=23678;
UPDATE creature_text SET text='Thank you. I thought I would die without seeing my sisters again!' WHERE entry=23678;
UPDATE creature_text SET text='Thank you! There''s no telling what those brutes would''ve done to me.' WHERE entry=23720;
UPDATE creature_text SET text='Guards!' WHERE entry=23859;
UPDATE creature_text SET text='The darkness... the corruption... they came too quickly for anyone to know...' WHERE entry=23861;
UPDATE creature_text SET text='It is too late for us, living one. Take yourself and your friend away from here before you both are... claimed...' WHERE entry=23861;
UPDATE creature_text SET text='Go away, whoever you are! Witch Hill is mine... mine!' WHERE entry=23861;
UPDATE creature_text SET text='The darkness will consume all... all the living...' WHERE entry=23861;
UPDATE creature_text SET text='The manor... someone else... will soon be consumed...' WHERE entry=23861;
UPDATE creature_text SET text='Why have you come here, outsider? You will only find pain! Our fate will be yours...' WHERE entry=23861;
UPDATE creature_text SET text='It was... terrible... the demon...' WHERE entry=23861;
UPDATE creature_text SET text='Fire grant me vision...' WHERE entry=23975;
UPDATE creature_text SET text='Water grant me serenity...' WHERE entry=23975;
UPDATE creature_text SET text='%s inhales the wispy smoke tendrils emanating from the burner.' WHERE entry=23975;
UPDATE creature_text SET text='Thank you, spirits.' WHERE entry=23975;
UPDATE creature_text SET text='Avenge my friends who have already been sacrificed' WHERE entry=24035;
UPDATE creature_text SET text='I don''t want to be sacrificed' WHERE entry=24035;
UPDATE creature_text SET text='I don''t want to be taken down into the catacombs' WHERE entry=24035;
UPDATE creature_text SET text='I think I saw a key on one of those Gjalerbron vrykul up top.' WHERE entry=24035;
UPDATE creature_text SET text='I think I saw a key on one of those vrykul.' WHERE entry=24035;
UPDATE creature_text SET text='Is there no hero to rescue me?' WHERE entry=24035;
UPDATE creature_text SET text='My thanks to you, hero' WHERE entry=24035;
UPDATE creature_text SET text='Oh, thank you, thank you' WHERE entry=24035;
UPDATE creature_text SET text='Please, let me out of here' WHERE entry=24035;
UPDATE creature_text SET text='Thank goodness for you' WHERE entry=24035;
UPDATE creature_text SET text='Thank you. I will not forget this' WHERE entry=24035;
UPDATE creature_text SET text='The key... you have to find the key' WHERE entry=24035;
UPDATE creature_text SET text='The vrykul are evil and must be destroyed' WHERE entry=24035;
UPDATE creature_text SET text='They''re performing unholy rites down in the catacombs, and I''m about to be the sacrifice' WHERE entry=24035;
UPDATE creature_text SET text='This is the end.' WHERE entry=24035;
UPDATE creature_text SET text='You have to put a stop to this madness before it''s too late' WHERE entry=24035;
UPDATE creature_text SET text='You saved my life' WHERE entry=24035;
UPDATE creature_text SET text='We don''t shoe no mules here. ''Sides, it''s strictly expedition business right now.' WHERE entry=24052;
UPDATE creature_text SET text='Not my problem! If yer so antsy to get yerself a house built, do it ''ere in the fort and quit yer whinin''!' WHERE entry=24052;
UPDATE creature_text SET text='Now, if you''d be so kind as to get your ass away from my forge...' WHERE entry=24052;
UPDATE creature_text SET text='%s wakes up from the smell of fresh meat!' WHERE entry=24178;
UPDATE creature_text SET text='Blessings of the spirits of the land and air upon you.' WHERE entry=24211;
UPDATE creature_text SET text='I must return. Good hunting to you.' WHERE entry=24211;
UPDATE creature_text SET text='I owe you a life debt, stranger.' WHERE entry=24211;
UPDATE creature_text SET text='Strange ghosts walk the land. Be careful!' WHERE entry=24211;
UPDATE creature_text SET text='Thank you, stranger.' WHERE entry=24211;
UPDATE creature_text SET text='They took us one by one. I''m sure there are other survivors.' WHERE entry=24211;
UPDATE creature_text SET text='We should never have traveled through the Rivenwood. Everyone knows this!' WHERE entry=24211;
UPDATE creature_text SET text='You saved me from certain death. I owe you.' WHERE entry=24211;
UPDATE creature_text SET text='Drive the invaders out! For Queen Angerboda!' WHERE entry=24238;
UPDATE creature_text SET text='No one speaks of my mother in that manner!' WHERE entry=24238;
UPDATE creature_text SET text='Fight without fear and the Val''kyr will reward you!' WHERE entry=24238;
UPDATE creature_text SET text='The Winterskorn tribe will prevail!' WHERE entry=24238;
UPDATE creature_text SET text='%s motions for silence.' WHERE entry=24321;
UPDATE creature_text SET text='Vrykul, your king implores you to listen!' WHERE entry=24321;
UPDATE creature_text SET text='The crowd gasps in horror.' WHERE entry=24321;
UPDATE creature_text SET text='Even now, in our darkest hour, they mock us!' WHERE entry=24321;
UPDATE creature_text SET text='Where are the titans in our time of greatest need? Our women birth abberations - disfigured runts unable to even stand on their own! Weak and ugly... Useless...' WHERE entry=24321;
UPDATE creature_text SET text='Ymiron has toiled. Long have I sat upon my throne and thought hard of our plight. There is only one answer... one reason...' WHERE entry=24321;
UPDATE creature_text SET text='For who but the titans themselves could bestow such a curse? What could have such power?' WHERE entry=24321;
UPDATE creature_text SET text='And the answer is nothing... For it is the titans that have cursed us!' WHERE entry=24321;
UPDATE creature_text SET text='The crowd cheers.' WHERE entry=24321;
UPDATE creature_text SET text='On this day all Vrykul will shed their old beliefs! We denounce our old gods! All Vrykul will pledge their allegiance to Ymiron! Ymiron will protect our noble race!' WHERE entry=24321;
UPDATE creature_text SET text='And now my first decree upon the Vrykul! All malformed infants born of Vrykul mother and father are to be destroyed upon birth! Our blood must remain pure always! Those found in violation of Ymiron''s decree will be taken to Gjalerbron for execution!' WHERE entry=24321;
UPDATE creature_text SET text='Silence!' WHERE entry=24322;
UPDATE creature_text SET text='Show them mercy, my king! They are of our flesh and blood!' WHERE entry=24322;
UPDATE creature_text SET text='All hail our glorious king, Ymiron!' WHERE entry=24322;
UPDATE creature_text SET text='Show the abberations no mercy, Ymiron!' WHERE entry=24323;
UPDATE creature_text SET text='They weaken us! Our strength is dilluted by their very existence! Destroy them all!' WHERE entry=24323;
UPDATE creature_text SET text='How much''ll it cost me to get my mules shod?' WHERE entry=24528;
UPDATE creature_text SET text='You don''t understand! If I''m not ready to go soon, all the good homesteading land will be taken!' WHERE entry=24528;
UPDATE creature_text SET text='That, sir, is a mule!' WHERE entry=24528;
UPDATE creature_text SET text='Yes, darling. You realize you''ll be eating dire ram mutton for dinner until the crops are planted...' WHERE entry=24531;
UPDATE creature_text SET text='I''d rather listen to his braying than yours, dear.' WHERE entry=24531;
UPDATE creature_text SET text='Of course, darling.' WHERE entry=24531;
UPDATE creature_text SET text='And I don''t want our land to have any of those horrible wolves, or giants, or ugly rams!' WHERE entry=24532;
UPDATE creature_text SET text='I''d sooner butcher that mule of yours! Why did you bring that beast in here, anyway?' WHERE entry=24532;
UPDATE creature_text SET text='Remember, honey, we need to get a plot of land with a nice hot spring.' WHERE entry=24532;
UPDATE creature_text SET text='Welcome to Fort Wildervar, brave homesteaders! There''s a whole continent out there just waiting to be claimed!' WHERE entry=24534;
UPDATE creature_text SET text='True, Northrend is a hard land, but our people are strong, hardy, and equal to the task!' WHERE entry=24534;
UPDATE creature_text SET text='We will win this land with the sword, and break it with the plow! You are the men and women who will be remembered for taming the wild continent!' WHERE entry=24534;
UPDATE creature_text SET text='But, you will not be alone out there. My men and I have prepared pack mules carrying the supplies you''ll need most.' WHERE entry=24534;
UPDATE creature_text SET text='Axes, picks, seed, nails, food, blankets, water... it''s all there, waiting for you. I think you''ll find my prices quite reasonable, too.' WHERE entry=24534;
UPDATE creature_text SET text='There are more than enough to go around. Should you need other goods, don''t hesitate to ask!' WHERE entry=24534;
UPDATE creature_text SET text='Now, my loyal custo... err, friends, go forth and conquer this land for our people!' WHERE entry=24534;
UPDATE creature_text SET text='Keep quiet, will you? If anyone catches on, we''re both dead.' WHERE entry=24639;
UPDATE creature_text SET text='All right, fellas! Who ordered the spiced rum? Was it you, Jackie boy?' WHERE entry=24639;
UPDATE creature_text SET text='It''s okay, sweetheart. This one''s on the house.' WHERE entry=24639;
UPDATE creature_text SET text='Right! Let''s try this so-called dire brew...' WHERE entry=24710;
UPDATE creature_text SET text='Bronzebeard''s beard! What a drink!' WHERE entry=24710;
UPDATE creature_text SET text='$N, this beer... well, it might be the best of Brewfest!' WHERE entry=24710;
UPDATE creature_text SET text='It is a shame Coren''s Dire Brew can''t quench more thirsting throats! It''s blasphemy, I know, but I envy those Dark Iron dwarves!' WHERE entry=24710;
UPDATE creature_text SET text='Ho there, and welcome to Brewfest!' WHERE entry=24710;
UPDATE creature_text SET text='Hello, friend! Welcome to the Brewfest Grounds!' WHERE entry=24710;
UPDATE creature_text SET text='Hail, good $c! Welcome to Ironforge''s annual Brewfest celebration!' WHERE entry=24710;
UPDATE creature_text SET text='Well time''s money, and time''s wasting! Let''s have that drink...' WHERE entry=24711;
UPDATE creature_text SET text='Wow! This really greases the steamplugs!' WHERE entry=24711;
UPDATE creature_text SET text='If I were an honest goblin, I''d say this was the best beer of the festival...' WHERE entry=24711;
UPDATE creature_text SET text='Too bad Coren''s dead. If I could buy that brew from him and resell it - watered down and rebottled under my own label, of course - I''d be rich!' WHERE entry=24711;
UPDATE creature_text SET text='Hey there, and welcome to Brewfest. Come in and have a drink or three!' WHERE entry=24711;
UPDATE creature_text SET text='What''s up, friend? Welcome to the Brewfest Grounds! Now go buy some drinks!' WHERE entry=24711;
UPDATE creature_text SET text='Hey hey, it''s another $r! Welcome to my annual Brewfest celebration... now go feast and drink some!' WHERE entry=24711;
UPDATE creature_text SET text='Tonight we feast on you!' WHERE entry=24779;
UPDATE creature_text SET text='Such easy prey...' WHERE entry=24779;
UPDATE creature_text SET text='Who''s hunting who?' WHERE entry=24779;
UPDATE creature_text SET text='Sure thing, love. Put it on Harry''s tab, will ya? He owes me a drink!' WHERE entry=24788;
UPDATE creature_text SET text='Free rum? Why... that''s me favorite kind!' WHERE entry=24788;
UPDATE creature_text SET text='Sweet Neptulon! That was... one drink... too many!' WHERE entry=24788;
UPDATE creature_text SET text='Thank you for freeing me! May the tides always favor you.' WHERE entry=25321;
UPDATE creature_text SET text='Do not allow Kaskala to forget what has happened here.' WHERE entry=25321;
UPDATE creature_text SET text='May the ancestors always aid you, $n, as you have aided me.' WHERE entry=25322;
UPDATE creature_text SET text='Thank you, $n. May the winds and seas always deliver you safely.' WHERE entry=25322;
UPDATE creature_text SET text='Ah, good... more parts!' WHERE entry=25678;
UPDATE creature_text SET text='Clear!' WHERE entry=25678;
UPDATE creature_text SET text='Fresh meat!' WHERE entry=25678;
UPDATE creature_text SET text='I recommened evisceration!' WHERE entry=25678;
UPDATE creature_text SET text='It''s no good... you need more work first.' WHERE entry=25678;
UPDATE creature_text SET text='Live, damn you!' WHERE entry=25678;
UPDATE creature_text SET text='The doctor is in!' WHERE entry=25678;
UPDATE creature_text SET text='Warning! Warning! Intruder alert! Intruder alert!' WHERE entry=25753;
UPDATE creature_text SET text='You have been detected. You will be assimilated or eliminated.' WHERE entry=25753;
UPDATE creature_text SET text='Activate counter-measures. Repel intruder.' WHERE entry=25753;
UPDATE creature_text SET text='Incoming $r flier! Shoot $g him:her;
 down!' WHERE entry=25758;
UPDATE creature_text SET text='I survived and I''m flesh again!' WHERE entry=25773;
UPDATE creature_text SET text='But... but... I was perfect!' WHERE entry=25773;
UPDATE creature_text SET text='Where am I? Who are you? What''s that strange feeling?' WHERE entry=25773;
UPDATE creature_text SET text='I''m flesh and blood again! Thank you!' WHERE entry=25773;
UPDATE creature_text SET text='I''m flesh and blood again. That''s all that matters!' WHERE entry=25783;
UPDATE creature_text SET text='We are Mechagnome...resistance is futile.' WHERE entry=25814;
UPDATE creature_text SET text='The flesh is weak. We will make you better, stronger...faster.' WHERE entry=25814;
UPDATE creature_text SET text='We can decurse you, we have the technology.' WHERE entry=25814;
UPDATE creature_text SET text='Who disturbs my meditation?!' WHERE entry=26073;
UPDATE creature_text SET text='The Hulking Jormungar falters for a moment, opening its mouth wide.' WHERE entry=26293;
UPDATE creature_text SET text='Ah, yes. Loken is well known to me.' WHERE entry=26420;
UPDATE creature_text SET text='It is he who commands the sons of iron in their war against us.' WHERE entry=26420;
UPDATE creature_text SET text='From his hiding place, he oversees their preparations for war with the goal of exterminating the stone giants!' WHERE entry=26420;
UPDATE creature_text SET text='He''s out to get me, too! I''d be careful around here if I was you, traveler. You never know which tree he''s hiding behind!' WHERE entry=26484;
UPDATE creature_text SET text='That''s not something Limpy Joe would ask! But yeah, I know Loken.' WHERE entry=26484;
UPDATE creature_text SET text='I''ll blast those gnomish wannabes back to the scrap heap!' WHERE entry=26817;
UPDATE creature_text SET text='You''re sending me back there?!' WHERE entry=26817;
UPDATE creature_text SET text='Mortal champions have long used these weapons to combat evil. I see no reason to keep the swords from them in this battle.' WHERE entry=26917;
UPDATE creature_text SET text='You are being misled! The Onslaught is all lies! The Scourge and the Forsaken are not our enemies! Wake up!' WHERE entry=27234;
UPDATE creature_text SET text='Renounce the Scarlet Onslaught! Don''t listen to the lies of the high general and the grand admiral any longer!' WHERE entry=27235;
UPDATE creature_text SET text='Abbendis is nothing but a harlot and Grand Admiral Westwind is selling her cheap like he sold us out!' WHERE entry=27236;
UPDATE creature_text SET text='High general Abbendis personally told me that it was a mistake to come north and that we''re doomed! I urge you all to lay down your weapons and leave before it''s too late!' WHERE entry=27237;
UPDATE creature_text SET text='Stand back, $N, the beast might lash out and harm you.' WHERE entry=27316;
UPDATE creature_text SET text='GODFREY! Hear me, fiend! Hear me, for I am the Light, here to deliver you from evil!' WHERE entry=27316;
UPDATE creature_text SET text='Good. I have your attention, then, Godfrey?' WHERE entry=27316;
UPDATE creature_text SET text='We can do this in one of two ways, Godfrey. First, I will simply ask you to tell me what the unholy markings etched upon the pages of this tome mean. What say you?' WHERE entry=27316;
UPDATE creature_text SET text='Then it is option two.' WHERE entry=27316;
UPDATE creature_text SET text='I say a prayer for you now, lost soul. May the Light take you gracefully.' WHERE entry=27316;
UPDATE creature_text SET text='Let the sermon begin.' WHERE entry=27316;
UPDATE creature_text SET text='LIGHT TAKE YOU, BEAST!' WHERE entry=27316;
UPDATE creature_text SET text='BURN IN HOLY FIRE!' WHERE entry=27316;
UPDATE creature_text SET text='LET THE LIGHT IN, GODFREY GOODARD!' WHERE entry=27316;
UPDATE creature_text SET text='May the power of Light compel you!' WHERE entry=27316;
UPDATE creature_text SET text='I thought you would see the Light, Godfrey... Now speak quickly, fiend. What does it say?' WHERE entry=27316;
UPDATE creature_text SET text='RUBBISH! Godfrey do you take me for a fool? Do not spew your Scourge propaganda at a man of the Light, heathen! Speak now or I will have the peasants craft a holy water bath and dip you into it like a dog with fleas!' WHERE entry=27316;
UPDATE creature_text SET text='What? There is a mausoleum beneath the old village? What fools we are to not have noticed! We will find and strike down your master now, Godfrey. We will end this nightmare.' WHERE entry=27316;
UPDATE creature_text SET text='You let us worry about how we kill the monster, Godfrey.' WHERE entry=27316;
UPDATE creature_text SET text='Return to Halford with the information that the good mayor was kind enough to submit, $N. I will finish here and squeeze whatever else this wretch might know about Thel''zan. Now, I will show Godfrey the rarely seen "option three."' WHERE entry=27316;
UPDATE creature_text SET text='Let''s you and I have a chat about some things, Godfrey.' WHERE entry=27316;
UPDATE creature_text SET text='The Destructive Ward gains in power.' WHERE entry=27430;
UPDATE creature_text SET text='The Destructive Ward is fully charged!' WHERE entry=27430;
UPDATE creature_text SET text='There will be no mercy!' WHERE entry=27447;
UPDATE creature_text SET text='They are... too strong! Underestimated their... fortitude.' WHERE entry=27447;
UPDATE creature_text SET text='Blast them! Destroy them!' WHERE entry=27447;
UPDATE creature_text SET text='Take no prisoners! Attack!' WHERE entry=27447;
UPDATE creature_text SET text='Strike now! Obliterate them!' WHERE entry=27447;
UPDATE creature_text SET text='You have been warned!' WHERE entry=27447;
UPDATE creature_text SET text='The Oculus is ours!' WHERE entry=27447;
UPDATE creature_text SET text='Intruders, your victory will be short-lived. I am Commander Varos Cloudstrider. My drakes control the skies and protect this conduit. I will see to it personnaly that the Oculus does not fall into your hands!' WHERE entry=27447;
UPDATE creature_text SET text='%s 咆哮.' WHERE entry=27577;
UPDATE creature_text SET text='%s 嗤之以鼻!' WHERE entry=27577;
UPDATE creature_text SET text='Tell you nothing, preacher.' WHERE entry=27577;
UPDATE creature_text SET text='What can you do to me that Kel''Thuzad has not? That the Lich King will not?' WHERE entry=27577;
UPDATE creature_text SET text='The book is your salvation, yes... but nothing will you know! NOTHING I SAY! NOTHING! ' WHERE entry=27577;
UPDATE creature_text SET text='No more LIGHT! NO MORE! I BEG YOU!' WHERE entry=27577;
UPDATE creature_text SET text='Never felt hurt like this!' WHERE entry=27577;
UPDATE creature_text SET text='It tells of the coming apocalypse. How this world will burn and be reborn from death.' WHERE entry=27577;
UPDATE creature_text SET text='NOOOO!!! I tell you! I tell you everything!' WHERE entry=27577;
UPDATE creature_text SET text='Humans... Beneath the earth of Wintergarde Village you built a mausoleum! Why do you think Naxxramas attacked that spot? Thel''zan hides deep in your own crypt and sends a thousand-thousand corpses at you! Perish you will...' WHERE entry=27577;
UPDATE creature_text SET text='How? Humans truly are stupid, yes? Thel''zan the Duskbringer! Thel''zan the Lich! He who is born of human flesh and bone, sacrificed all for power, protected by the Lich King!' WHERE entry=27577;
UPDATE creature_text SET text='You cannot stop Thel''zan! He bears the dark gift, bestowed upon him by the Lich King himself!' WHERE entry=27577;
UPDATE creature_text SET text='The prisoners shall not go free. The word of Malygos is law!' WHERE entry=27654;
UPDATE creature_text SET text='A fitting punishment!' WHERE entry=27654;
UPDATE creature_text SET text='Sentence: executed!' WHERE entry=27654;
UPDATE creature_text SET text='Another casualty of war!' WHERE entry=27654;
UPDATE creature_text SET text='It is too late to run!' WHERE entry=27654;
UPDATE creature_text SET text='Gather ''round...' WHERE entry=27654;
UPDATE creature_text SET text='None shall escape!' WHERE entry=27654;
UPDATE creature_text SET text='I condemn you to death!' WHERE entry=27654;
UPDATE creature_text SET text='Tremble, worms!' WHERE entry=27654;
UPDATE creature_text SET text='I will crush you!' WHERE entry=27654;
UPDATE creature_text SET text='Can you fly?' WHERE entry=27654;
UPDATE creature_text SET text='The war... goes on.' WHERE entry=27654;
UPDATE creature_text SET text='Poor blind fools!' WHERE entry=27655;
UPDATE creature_text SET text='What do we have here... those would defy the Spell-Weaver? Those without foresight or understanding. How could I make you see? Malygos is saving the world from itself! Bah! You are hardly worth my time!' WHERE entry=27655;
UPDATE creature_text SET text='Clearly my pets failed. Perhaps another demonstration is in order.' WHERE entry=27655;
UPDATE creature_text SET text='Still you fight. Still you cling to misguided principles. If you survive, you''ll find me in the center ring.' WHERE entry=27655;
UPDATE creature_text SET text='If only you understood!' WHERE entry=27655;
UPDATE creature_text SET text='Now do you see? Do you?!' WHERE entry=27655;
UPDATE creature_text SET text='Unfortunate, but necessary.' WHERE entry=27655;
UPDATE creature_text SET text='A taste... just a small taste... of the Spell-Weaver''s power!' WHERE entry=27655;
UPDATE creature_text SET text='So much unstable energy... but worth the risk to destroy you!' WHERE entry=27655;
UPDATE creature_text SET text='Everything I''ve done... has been for Azeroth...' WHERE entry=27655;
UPDATE creature_text SET text='You brash interlopers are out of your element! I will ground you!' WHERE entry=27656;
UPDATE creature_text SET text='Simpletons! You cannot comprehend the forces you have set in motion. The ley line conduit will not be disrupted! Your defeat shall be absolute!' WHERE entry=27656;
UPDATE creature_text SET text='Such insolence... such arrogance... must be PUNISHED!' WHERE entry=27656;
UPDATE creature_text SET text='It''s a long way down...' WHERE entry=27656;
UPDATE creature_text SET text='Back to the earth with you!' WHERE entry=27656;
UPDATE creature_text SET text='Enjoy the fall!' WHERE entry=27656;
UPDATE creature_text SET text='Savor this small victory, foolish little creatures. You and your dragon allies have won this battle. But we will win... the Nexus War.' WHERE entry=27656;
UPDATE creature_text SET text='Anomalies form as Ley-Guardian Eregos shifts into the Astral Plane!' WHERE entry=27656;
UPDATE creature_text SET text='Bat gizzards again for the gnomes tonight...' WHERE entry=27842;
UPDATE creature_text SET text='What do they expect, making the bats come in at that angle? Broken necks and gamey bat stew, that''s what they get.' WHERE entry=27842;
UPDATE creature_text SET text='We like trees, Fenrick. They provide cover. They won''t let me chop them down, either.' WHERE entry=27842;
UPDATE creature_text SET text='I wonder how many reinforcements need to suffer injury before they allows us to chop down these idiotic trees. They''re costing us a fortune in bats. Maybe I''ll rig a harness or two...' WHERE entry=27842;
UPDATE creature_text SET text='Arrrhhh...Guards!' WHERE entry=27842;
UPDATE creature_text SET text='Good work with the crates! Come talk to me in front of Stratholme for your next assignment!' WHERE entry=27915;
UPDATE creature_text SET text='You''re too late, $n. Another visitor from Dalaran came asking after information about the same prismatic dragon blades.' WHERE entry=27990;
UPDATE creature_text SET text='From your description, I''m certain the book I loaned our visitor could allow you to easily identify the weapon.' WHERE entry=27990;
UPDATE creature_text SET text='I''m afraid you''ll have to ask the -- Well, perhaps Kalecgos can help.' WHERE entry=27990;
UPDATE creature_text SET text='$n may have found the remains of a prismatic blade, Kalecgos. Will you offer your help to our visitor?' WHERE entry=27990;
UPDATE creature_text SET text='You believe our allies will not be able to control the power of the swords?' WHERE entry=27990;
UPDATE creature_text SET text='As will we all.' WHERE entry=27990;
UPDATE creature_text SET text='Please, mortal, speak with Arcanist Tybalin in Dalaran. He may be able to negotiate with the Sunreavers for access to the book.' WHERE entry=27990;
UPDATE creature_text SET text='Please, mortal, seek out Magister Hathorel in Dalaran. He might be able to negotiate with the Silver Covenant for access to the book.' WHERE entry=27990;
UPDATE creature_text SET text='The trickster Mage-Lord Urom protects the third ring. He will appear alone and defenseless, but do not be fooled by appearences! Urom is a powerful conjurer who commands a menagerie of Phantasmal creatures. Seek him out above.' WHERE entry=28012;
UPDATE creature_text SET text='Your greatest challenge lies ahead. Ley-Guardian Eregos is a Blue dragon of immense power. You will find him flying above the uppermost ring.' WHERE entry=28012;
UPDATE creature_text SET text='The Lich King reacted swiftly to the breach. Faster than I anticipated.' WHERE entry=28179;
UPDATE creature_text SET text='What would you have me do, Darion?' WHERE entry=28179;
UPDATE creature_text SET text='Choose your words wisely, death knight. You stand amidst the company of the devoted.' WHERE entry=28179;
UPDATE creature_text SET text='We will do this with honor, Darion. We will not sink to the levels of the Scourge to be victorious. To do so would make us no better than the monster that we fight to destroy!' WHERE entry=28179;
UPDATE creature_text SET text='5秒鐘后开始蒸馏过程。' WHERE entry=28566;
UPDATE creature_text SET text='再多放一个柳橙!动作快点!' WHERE entry=28566;
UPDATE creature_text SET text='在蒸馏器裡放一颗木瓜!' WHERE entry=28566;
UPDATE creature_text SET text='把香蕉放进去!' WHERE entry=28566;
UPDATE creature_text SET text='压力太高了!打开压力阀!' WHERE entry=28566;
UPDATE creature_text SET text='需要加热蒸馏器!把火盆点燃!' WHERE entry=28566;
UPDATE creature_text SET text='干得好!现在，保持清醒。' WHERE entry=28566;
UPDATE creature_text SET text='快完成了。永远都不知道下一步会需要什麼……' WHERE entry=28566;
UPDATE creature_text SET text='做得好!继续弄下去!' WHERE entry=28566;
UPDATE creature_text SET text='干得好!什麼都有了!' WHERE entry=28566;
UPDATE creature_text SET text='糟糕!我要关掉它……' WHERE entry=28566;
UPDATE creature_text SET text='我们做到了!来拿酒桶。' WHERE entry=28566;
UPDATE creature_text SET text='Fool! You led us to the only being that could stand up to our armies! You will never bring the Etymidian back to Northrend!' WHERE entry=28601;
UPDATE creature_text SET text='我的耐心到此为止了,我要亲自消灭你们!' WHERE entry=28859;
UPDATE creature_text SET text='你们的愚蠢必将葬送自己!' WHERE entry=28859;
UPDATE creature_text SET text='有又更多的神器可以没收了.' WHERE entry=28859;
UPDATE creature_text SET text='<奸笑> 太... 天真了...' WHERE entry=28859;
UPDATE creature_text SET text='我原本只是想尽快结束你们的生命……可你们竟然远比我想象得要坚韧。虽然如此，你们的努力仍将付诸东流。事实上，这场战争本身就是因为你们凡人不计后果的行为而起，我只是在尽自己的责任罢了。如果这责任意味着要灭绝你们……那就这样吧！' WHERE entry=28859;
UPDATE creature_text SET text='没有人体验过,你们将要承受的痛苦.' WHERE entry=28859;
UPDATE creature_text SET text='我要让你们这些无知的孩子,重新了解魔法的概念.' WHERE entry=28859;
UPDATE creature_text SET text='就这样无助地看着希望破灭吧！' WHERE entry=28859;
UPDATE creature_text SET text='我会妥善利用你们留下的魔法能量。' WHERE entry=28859;
UPDATE creature_text SET text='我是织法者！我的力量是无穷无尽的！' WHERE entry=28859;
UPDATE creature_text SET text='你们的灵魂将永远在这里游荡！' WHERE entry=28859;
UPDATE creature_text SET text='够了！既然你们这么想夺回艾泽拉斯的魔法，我就给你们！' WHERE entry=28859;
UPDATE creature_text SET text='现在你们幕后的主使终于出现了，但已经太迟了！这里弥漫着的能量已经足以将世界毁灭十次。你们觉得他们会对你们做些什么呢？' WHERE entry=28859;
UPDATE creature_text SET text='投降吧!' WHERE entry=28859;
UPDATE creature_text SET text='在这里涌动的力量,早已超越了你们的理解与想象.' WHERE entry=28859;
UPDATE creature_text SET text='我无坚不摧!' WHERE entry=28859;
UPDATE creature_text SET text='阿莱克丝塔萨，又有一个你的孩子倒下了！' WHERE entry=28859;
UPDATE creature_text SET text='就比小虫子强了一点点！' WHERE entry=28859;
UPDATE creature_text SET text='红龙军团也将步你们的后尘！' WHERE entry=28859;
UPDATE creature_text SET text='竟然还没倒下?不会太久了.' WHERE entry=28859;
UPDATE creature_text SET text='你们的妄想破灭了.' WHERE entry=28859;
UPDATE creature_text SET text='你们脆弱的精神即将崩溃.' WHERE entry=28859;
UPDATE creature_text SET text='Unthinkable! The mortals will destroy... everything... my sister... what have you...' WHERE entry=28859;
UPDATE creature_text SET text='It''s an angry male!' WHERE entry=29327;
UPDATE creature_text SET text='Grrrrr!' WHERE entry=29618;
UPDATE creature_text SET text='Me not afraid!' WHERE entry=29618;
UPDATE creature_text SET text='Net not stop me! No... net stop me.' WHERE entry=29618;
UPDATE creature_text SET text='No kill me!' WHERE entry=29618;
UPDATE creature_text SET text='不!' WHERE entry=29618;
UPDATE creature_text SET text='你不能杀... 我!' WHERE entry=29618;
UPDATE creature_text SET text='%s attempts to run away in fear!' WHERE entry=30111;
UPDATE creature_text SET text='Curse you! You will not treat me like a beast!' WHERE entry=30146;
UPDATE creature_text SET text='Enough! I will teach you some manners, wench!' WHERE entry=30146;
UPDATE creature_text SET text='I''d rather die fighting than live like a slave!' WHERE entry=30146;
UPDATE creature_text SET text='Back... to work...' WHERE entry=30146;
UPDATE creature_text SET text='We will have revenge... some day.' WHERE entry=30146;
UPDATE creature_text SET text='You treat us worse than animals!' WHERE entry=30146;
UPDATE creature_text SET text='%s attempts to run away in fear!' WHERE entry=30179;
UPDATE creature_text SET text='Metallic specimen of foreign origin detected.' WHERE entry=30190;
UPDATE creature_text SET text='Beginning analysis...' WHERE entry=30190;
UPDATE creature_text SET text='Specimen identified as an alloy of saronite and iron.' WHERE entry=30190;
UPDATE creature_text SET text='The ore used in this sample originated deep wihin the crust of Azeroth and was recently unearthed.' WHERE entry=30190;
UPDATE creature_text SET text='The saronite in this sample is nearly pure. Ores like this do not occur naturally on the surface of Azeroth.' WHERE entry=30190;
UPDATE creature_text SET text='This ore can only have been created by a powerful, malevolent force. Attempting to access databanks for more information...' WHERE entry=30190;
UPDATE creature_text SET text='Access denied?!' WHERE entry=30190;
UPDATE creature_text SET text='Further information can only be accessed from the archives within Ulduar, by order of Keeper Loken.' WHERE entry=30190;
UPDATE creature_text SET text='But one thing is for certain: this plate''s size, thickness, and bolt holes point to a use as armor for a colossal structure.' WHERE entry=30190;
UPDATE creature_text SET text='Directive completed. Returning TO standby mode.' WHERE entry=30190;
UPDATE creature_text SET text='What''s on yer mind, lad?' WHERE entry=30224;
UPDATE creature_text SET text='Eversong Woods, Dalfors. I''m thinking about how beautiful it was before Arthas cut a swathe of death through it...' WHERE entry=30225;
UPDATE creature_text SET text='Thank you and farewell, friend. I must return to the Argent Vanguard.' WHERE entry=30274;
UPDATE creature_text SET text='%s becomes enraged!' WHERE entry=30277;
UPDATE creature_text SET text='%s becomes enraged!' WHERE entry=30284;
UPDATE creature_text SET text='%s attempts to run away in fear!' WHERE entry=30319;
UPDATE creature_text SET text='%s becomes enraged!' WHERE entry=30329;
UPDATE creature_text SET text='You are dealing with a being that holds within it the consciousness of the most cunning, intelligent, and ruthless individuals to ever live.' WHERE entry=30377;
UPDATE creature_text SET text='The Lich King is unlike any foe that you have ever faced, Highlord. Though you bested him upon the holy ground of Light''s Hope Chapel, you tread now upon his domain.$B' WHERE entry=30377;
UPDATE creature_text SET text='You cannot win. Not like this...$B' WHERE entry=30377;
UPDATE creature_text SET text='Nothing. There is nothing that you can do while the Light binds you. It controls you wholly, shackling you to the ground with its virtues.' WHERE entry=30377;
UPDATE creature_text SET text='%s shakes his head.' WHERE entry=30377;
UPDATE creature_text SET text='Look upon the field, Highlord. The Lich King has halted your advance completely and won the upper hand!' WHERE entry=30377;
UPDATE creature_text SET text='The breach you created was sealed with Nerubian webbing almost as quickly as it was opened.' WHERE entry=30377;
UPDATE creature_text SET text='Your soldiers are being used as living shields to stave off artillery fire in the Valley of Echoes, allowing the forces of the Lich King to assault your base without impediment.' WHERE entry=30377;
UPDATE creature_text SET text='The Lich King knows your boundaries, Highlord. He knows that you will not fire on your own men. Do you not understand? He has no boundaries. No rules to abide. $B' WHERE entry=30377;
UPDATE creature_text SET text='Then you have lost, Highlord.$B' WHERE entry=30377;
UPDATE creature_text SET text='Let''s get out of here! Quickly!' WHERE entry=30407;
UPDATE creature_text SET text='Faster, hero! We must get back to the Argent Vanguard and warn them of the impending attack!' WHERE entry=30407;
UPDATE creature_text SET text='There are hundreds of them! Maybe thousands! They will attack at any moment! I''m sure of it!' WHERE entry=30407;
UPDATE creature_text SET text='Had you not come along I would have died for sure!' WHERE entry=30407;
UPDATE creature_text SET text='They''re planning a huge attack! We need to warn Highlord Fordring!' WHERE entry=30407;
UPDATE creature_text SET text='感谢你, 英雄.' WHERE entry=30407;
UPDATE creature_text SET text='Thank you, friend, but we''re not out of trouble yet!' WHERE entry=30407;
UPDATE creature_text SET text='%s becomes enraged!' WHERE entry=31104;
UPDATE creature_text SET text='You shouldn''t have done that!  He''s not going to like it.' WHERE entry=31237;
UPDATE creature_text SET text='AHAHAHAHA... you''ll join us soon enough!' WHERE entry=31397;
UPDATE creature_text SET text='I don''t want to leave! I want to stay here!' WHERE entry=31397;
UPDATE creature_text SET text='NO! You''re wrong! The voices in my head are beautiful!' WHERE entry=31397;
UPDATE creature_text SET text='My life for you!' WHERE entry=31397;
UPDATE creature_text SET text='I''m coming, master!' WHERE entry=31397;
UPDATE creature_text SET text='I did what I had to, brother. You gave me no alternative.' WHERE entry=32295;
UPDATE creature_text SET text='And so ends the Nexus War.' WHERE entry=32295;
UPDATE creature_text SET text='This resolution pains me deeply, but the destruction, the monumental loss of life had to end. Regardless of Malygos'' recent transgressions, I will mourn his loss. He was once a guardian, a protector. This day, one of the world''s mightiest has fallen.' WHERE entry=32295;
UPDATE creature_text SET text='The red dragonflight will take on the burden of mending the devastation wrought on Azeroth. Return home to your people and rest. Tomorrow will bring you new challenges, and you must be ready to face them. Life... goes on.' WHERE entry=32295;
UPDATE creature_text SET text='The view up here is amazing!' WHERE entry=32736;
UPDATE creature_text SET text='Too bad I left my light feathers at home... Slow Fall would work perfect here!' WHERE entry=32736;
UPDATE creature_text SET text='The view up here is amazing!' WHERE entry=32739;
UPDATE creature_text SET text='Too bad I left my light feathers at home... Slow Fall would work perfect here!' WHERE entry=32739;
UPDATE creature_text SET text='The view up here is amazing!' WHERE entry=32741;
UPDATE creature_text SET text='Too bad I left my light feathers at home... Slow Fall would work perfect here!' WHERE entry=32741;
UPDATE creature_text SET text='Your actions are illogical. All possible results for this encounter have been calculated. The Pantheon will receive the Observer''s message regardless of outcome.' WHERE entry=32871;
UPDATE creature_text SET text='Loss of life, unavoidable.' WHERE entry=32871;
UPDATE creature_text SET text='I do what I must.' WHERE entry=32871;
UPDATE creature_text SET text='See your world through my eyes: A universe so vast as to be immeasurable - incomprehensible even to your greatest minds.' WHERE entry=32871;
UPDATE creature_text SET text='The stars come to my aid.' WHERE entry=32871;
UPDATE creature_text SET text='I have seen worlds bathed in the Makers'' flames. Their denizens fading without so much as a whimper. Entire planetary systems born and raised in the time that it takes your mortal hearts to beat once. Yet all throughout, my own heart, devoid of emotion...' WHERE entry=32871;
UPDATE creature_text SET text='Perhaps it is your imperfection that which grants you free will. That allows you to persevere against all cosmically calculated odds. You prevailed where the Titans'' own perfect creations have failed.' WHERE entry=32871;
UPDATE creature_text SET text='I''ve rearranged the reply code. Your planet will be spared. I cannot be certain of my own calculations anymore.' WHERE entry=32871;
UPDATE creature_text SET text='I lack the strength to transmit the signal. You must hurry. Find a place of power close to the skies.' WHERE entry=32871;
UPDATE creature_text SET text='Do not worry about my fate Bronzen. If the signal is not transmitted in time re-origination will proceed regardless. Save. Your. World.' WHERE entry=32871;
UPDATE creature_text SET text='You are... out of time.' WHERE entry=32871;
UPDATE creature_text SET text='Witness the fury of the cosmos!' WHERE entry=32871;
UPDATE creature_text SET text='Behold the tools of creation!' WHERE entry=32871;
UPDATE creature_text SET text='Trans-location complete. Commencing planetary analysis of Azeroth.' WHERE entry=32871;
UPDATE creature_text SET text='Stand back, mortals. I am not here to fight you.' WHERE entry=32871;
UPDATE creature_text SET text='It is in the universe''s best interest to re-originate this planet should my analysis find systemic corruption. Do not interfere.' WHERE entry=32871;
UPDATE creature_text SET text='Analysis complete. There is partial corruption in the planet''s life-support systems as well as complete corruption in most of the planet''s defense mechanisms.' WHERE entry=32871;
UPDATE creature_text SET text='Begin uplink: Reply Code: ''Omega''. Planetary re-origination requested..' WHERE entry=32871;
UPDATE creature_text SET text='Farewell, mortals. Your bravery is admirable, for such flawed creatures.' WHERE entry=32871;
UPDATE creature_text SET text='Algalon the Observer begins to Summon Collapsing Stars!' WHERE entry=32871;
UPDATE creature_text SET text='Algalon the Observer begins to cast Cosmic Smash' WHERE entry=32871;
UPDATE creature_text SET text='Algalon the Observer begins to cast Big Bang!' WHERE entry=32871;
UPDATE creature_text SET text='It''s an angry male!' WHERE entry=33008;
UPDATE creature_text SET text='Thank you, mortal, for freeing me from this curse. I beg you, take this blade.' WHERE entry=33303;
UPDATE creature_text SET text='It has brought me naught but ill. Mayhap you can find someone who will contain its power.' WHERE entry=33303;
UPDATE creature_text SET text='Help shield us from these cutting winds, little sapling.' WHERE entry=33788;
UPDATE creature_text SET text='你在这里.' WHERE entry=33788;
UPDATE creature_text SET text='Grow, little one.' WHERE entry=33788;
UPDATE creature_text SET text='We did it, lads! We got here before Algalon''s arrival. Maybe we can rig the systems to interfere with his analysis--' WHERE entry=34064;
UPDATE creature_text SET text='I''ll head back to the archivum and see if I can jam his signal. I might be able to buy us some time while you take care of him.' WHERE entry=34064;
UPDATE creature_text SET text='I know just the place. Will you be all right?' WHERE entry=34064;
UPDATE creature_text SET text='If you''ll excuse me, I''m afraid I have other business I must attend to. Please call on me again in the future.' WHERE entry=35642;
UPDATE creature_text SET text='怎么，自诩正义的圣光终于来了？我是不是该丢下霜之哀伤，恳求您的宽恕呢，弗丁？' WHERE entry=36597;
UPDATE creature_text SET text='让我来亲自告诉你。当一切结束，你将跪求我的宽恕－－而我会拒绝你。你痛苦的哀号将是我狂野力量的最好证明……' WHERE entry=36597;
UPDATE creature_text SET text='我会让你活着目睹这个末日，弗丁。这悲惨的世界将在我手中重铸，我不想让圣光最强大的勇士错过这一切。' WHERE entry=36597;
UPDATE creature_text SET text='Come then champions, feed me your rage!' WHERE entry=36597;
UPDATE creature_text SET text='我会让你的血脉和躯壳化为寒冰！' WHERE entry=36597;
UPDATE creature_text SET text='你周围的世界将在眼前崩塌！' WHERE entry=36597;
UPDATE creature_text SET text='华尔其，主人在召唤你！' WHERE entry=36597;
UPDATE creature_text SET text='霜之哀伤饿了……' WHERE entry=36597;
UPDATE creature_text SET text='霜之哀伤!服从我!' WHERE entry=36597;
UPDATE creature_text SET text='霜之哀伤会饱餐你们盟友的灵魂！' WHERE entry=36597;
UPDATE creature_text SET text='希望破灭……' WHERE entry=36597;
UPDATE creature_text SET text='末日降临！' WHERE entry=36597;
UPDATE creature_text SET text='迎接你的凄惨结局吧!' WHERE entry=36597;
UPDATE creature_text SET text='%s begins to cast Defile!' WHERE entry=36597;
UPDATE creature_text SET text='|TInterface\Icons\ability_creature_disease_02.blp:16|tYou have been infected by |cFFCF00FFNecrotic Plague!|r' WHERE entry=36597;
UPDATE creature_text SET text='我不再有问题，也不再有疑问。你是艾泽拉斯最强大的勇士。我的阻挠都被你一一化解。我最悍勇的仆从也都倒在了你的无情怒火和利刃之下……' WHERE entry=36597;
UPDATE creature_text SET text='真的是正义在驱使你吗？我很好奇……' WHERE entry=36597;
UPDATE creature_text SET text='你把他们训练的很好，弗丁。你把世界上最强大的勇士都送到我了的面前，这正合我意！你们的默默牺牲会得到我的褒奖。' WHERE entry=36597;
UPDATE creature_text SET text='亲眼目睹吧，我会把他们从尸骸变为天灾军团的战士。艾泽拉斯会在他们的手中陷入混乱，走向毁灭！而你，将是第一具尸体。' WHERE entry=36597;
UPDATE creature_text SET text='我会享受这种讽刺。' WHERE entry=36597;
UPDATE creature_text SET text='这不可能...' WHERE entry=36597;
UPDATE creature_text SET text='我如同羊群前的雄狮，但它们不畏惧我。' WHERE entry=36597;
UPDATE creature_text SET text='也不敢畏惧。' WHERE entry=36597;
UPDATE creature_text SET text='这就是你们的开始与终结之地，凡人们。休想进入主人的密室！' WHERE entry=36612;
UPDATE creature_text SET text='强大的天灾军团将让死亡和毁灭席卷整个世界！' WHERE entry=36612;
UPDATE creature_text SET text='白骨风暴！' WHERE entry=36612;
UPDATE creature_text SET text='白骨的束缚！' WHERE entry=36612;
UPDATE creature_text SET text='定住吧！' WHERE entry=36612;
UPDATE creature_text SET text='死亡是唯一的解脱！' WHERE entry=36612;
UPDATE creature_text SET text='又一份给主人的献礼！' WHERE entry=36612;
UPDATE creature_text SET text='到下面去挣扎吧！' WHERE entry=36612;
UPDATE creature_text SET text='我的眼前……只有黑暗。' WHERE entry=36612;
UPDATE creature_text SET text='主人的怒火!赐予我力量!' WHERE entry=36612;
UPDATE creature_text SET text='Lord Marrowgar creates a whirling storm of bone!' WHERE entry=36612;
UPDATE creature_text SET text='不！你杀了大臭！你赔！' WHERE entry=36626;
UPDATE creature_text SET text='玩吧!' WHERE entry=36626;
UPDATE creature_text SET text='%s 开始施放|cFFFF7F00刺鼻毒气！|r' WHERE entry=36626;
UPDATE creature_text SET text='%s releases Gas Spores!' WHERE entry=36626;
UPDATE creature_text SET text='我有点不舒服……*呕*' WHERE entry=36626;
UPDATE creature_text SET text='%s begins to cast |cFFFF7F00Pungent Blight!|r' WHERE entry=36626;
UPDATE creature_text SET text='%s vomits.' WHERE entry=36626;
UPDATE creature_text SET text='哈哈，我做到了！' WHERE entry=36626;
UPDATE creature_text SET text='死吧，死吧，死！' WHERE entry=36626;
UPDATE creature_text SET text='你……玩完了！' WHERE entry=36626;
UPDATE creature_text SET text='我的妈呀！' WHERE entry=36626;
UPDATE creature_text SET text='什么？我的心肝？不！！！' WHERE entry=36627;
UPDATE creature_text SET text='WEEEEEE!' WHERE entry=36627;
UPDATE creature_text SET text='%s begins to cast Slime Spray!' WHERE entry=36627;
UPDATE creature_text SET text='粘啊,真粘啊!' WHERE entry=36627;
UPDATE creature_text SET text='|TInterface\Icons\spell_shadow_unstableaffliction_2.blp:16|t%s begins to cast |cFFFF0000Unstable Ooze Explosion!|r' WHERE entry=36627;
UPDATE creature_text SET text='吹个球，吹个“卟卟”会爆的大气球！' WHERE entry=36627;
UPDATE creature_text SET text='我会拿你做新玩具！' WHERE entry=36627;
UPDATE creature_text SET text='我把它弄坏了……' WHERE entry=36627;
UPDATE creature_text SET text='该睡了!' WHERE entry=36627;
UPDATE creature_text SET text='真是糟糕……' WHERE entry=36627;
UPDATE creature_text SET text='|TInterface\Icons\ability_creature_disease_02.blp:16|tYou have |cFF00FF00Mutated Infection!|r' WHERE entry=36627;
UPDATE creature_text SET text='It''s good to finally see you, courier. Krasus has entrusted us with one of the few remaining copies of Ancient Dragonforged Blades.' WHERE entry=36669;
UPDATE creature_text SET text='Here is the book. You must ensure it gets to Caladis Brightspear in Icecrown before the Sunreavers realize what is happening.' WHERE entry=36669;
UPDATE creature_text SET text='Travel quickly! The Sunreavers will not waste any time once they realize that we have the information they seek.' WHERE entry=36669;
UPDATE creature_text SET text='You''re late, courier. No, I don''t want any excuses;
 this errand is far too important.' WHERE entry=36670;
UPDATE creature_text SET text='Here''s the tome our representative brought from Wyrmrest. Get this to Myralion Sunblaze immediately.' WHERE entry=36670;
UPDATE creature_text SET text='Watch your back, courier. I needn''t remind you of the value of the book, nor the fact that the Silver Covenant will stop at nothing to take it from us.' WHERE entry=36670;
UPDATE creature_text SET text='这是普通的毒云，但请千万小心，这毒云其实并不普通！' WHERE entry=36678;
UPDATE creature_text SET text='哦烂肠，你是我的最爱，仅次于腐面。不过你的死给我留下了那么多毒气，我都快被熏死了！' WHERE entry=36678;
UPDATE creature_text SET text='重大喜讯！各位！软泥又开始流动啦！' WHERE entry=36678;
UPDATE creature_text SET text='好消息！各位！我修好了毒性软泥管道！' WHERE entry=36678;
UPDATE creature_text SET text='惊天噩耗，我作的腐面，刚刚死了。但重大喜讯，他留下了，大量软泥！哇，我居然还有这么出众的诗歌才华……雷死了！' WHERE entry=36678;
UPDATE creature_text SET text='喜讯，各位！我想我已经研制出一种能够毁灭艾泽拉斯的药剂了！' WHERE entry=36678;
UPDATE creature_text SET text='%s begins to cast Unstable Experiment!' WHERE entry=36678;
UPDATE creature_text SET text='两泥，一室。会有无限惊喜哦！' WHERE entry=36678;
UPDATE creature_text SET text='嗯，什么感觉也没有。什么？！这是哪儿来的？' WHERE entry=36678;
UPDATE creature_text SET text='味道像……樱桃！哦！见笑了！' WHERE entry=36678;
UPDATE creature_text SET text='|TInterface\Icons\inv_misc_herb_evergreenmoss.blp:16|t%s cast |cFF00FF00Malleable Goo!|r' WHERE entry=36678;
UPDATE creature_text SET text='%s cast |cFFFF7F00Choking Gas Bomb!|r' WHERE entry=36678;
UPDATE creature_text SET text='嗯，有趣……' WHERE entry=36678;
UPDATE creature_text SET text='这是个意外！' WHERE entry=36678;
UPDATE creature_text SET text='重大喜讯！各位' WHERE entry=36678;
UPDATE creature_text SET text='噩耗，各位……我觉得我要失败了……' WHERE entry=36678;
UPDATE creature_text SET text='You Sunreaver lackeys are all the same.' WHERE entry=36774;
UPDATE creature_text SET text='You won''t escape from us so easily!' WHERE entry=36774;
UPDATE creature_text SET text='Did you think you would escape with your life?' WHERE entry=36776;
UPDATE creature_text SET text='You''ll never run us out of the city, Silver Covenant thug!' WHERE entry=36776;
UPDATE creature_text SET text='英雄们，请快些帮助我，我……我快要抵挡不住他们了。请治疗我的伤口！' WHERE entry=36789;
UPDATE creature_text SET text='我打开了进入梦境的传送门。英雄们，救赎就在其中……' WHERE entry=36789;
UPDATE creature_text SET text='我的力量回来了。坚持，英雄们！' WHERE entry=36789;
UPDATE creature_text SET text='我坚持不了多久了.' WHERE entry=36789;
UPDATE creature_text SET text='原谅我所做的一切,我……无法……做到……死吧！才是归宿！' WHERE entry=36789;
UPDATE creature_text SET text='一场悲剧……' WHERE entry=36789;
UPDATE creature_text SET text='受死吧!' WHERE entry=36789;
UPDATE creature_text SET text='我获得了新生！伊瑟拉的恩泽赐予我消灭邪恶的力量！' WHERE entry=36789;
UPDATE creature_text SET text='你是来审判阿尔萨斯的吗？想要看到巫妖王的灭亡？' WHERE entry=36823;
UPDATE creature_text SET text='首先，你需要摆脱霜之哀伤的控制，否则就会像我一样，永世成为这把邪剑的囚徒。' WHERE entry=36823;
UPDATE creature_text SET text='帮我摧毁这些痛苦的灵魂！我们合力就能弱化霜之哀伤的控制，从内部削弱巫妖王！' WHERE entry=36823;
UPDATE creature_text SET text='你们这些蠢货胆敢闯入这里。诺森德的冰风将卷走你们的灵魂！' WHERE entry=36853;
UPDATE creature_text SET text='痛苦吧，凡人，你们可怜的魔法背叛了你们！' WHERE entry=36853;
UPDATE creature_text SET text='%s prepares to unleash a wave of blistering cold!' WHERE entry=36853;
UPDATE creature_text SET text='你能感受到死神之手的那股寒意吗？' WHERE entry=36853;
UPDATE creature_text SET text='啊啊啊!强烈的灼痛!这是什么魔法?' WHERE entry=36853;
UPDATE creature_text SET text='你们的入侵结束了！无人可以生还！' WHERE entry=36853;
UPDATE creature_text SET text='绝望吧，体会主人那无穷无尽的力量吧！' WHERE entry=36853;
UPDATE creature_text SET text='%s fires a frozen orb towards $N!' WHERE entry=36853;
UPDATE creature_text SET text='毁灭吧！' WHERE entry=36853;
UPDATE creature_text SET text='软弱的凡人……' WHERE entry=36853;
UPDATE creature_text SET text='够了！我厌倦了这些游戏！' WHERE entry=36853;
UPDATE creature_text SET text='终于……自由了……' WHERE entry=36853;
UPDATE creature_text SET text='你们之所以在这里，那是因为你们是少数几个拥有特殊能力，能够洞悉这诅咒世界的人。' WHERE entry=36855;
UPDATE creature_text SET text='你们能够看穿遮蔽世界的迷雾，掌握真正的力量。' WHERE entry=36855;
UPDATE creature_text SET text='好好看看你粗陋的手：看看那肌腱、软肉和其中的黑暗之血。' WHERE entry=36855;
UPDATE creature_text SET text='多么的软弱和不堪……这真是造物主的玩笑。' WHERE entry=36855;
UPDATE creature_text SET text='你只有承认自己必然的失败，才有可能早日获得更强的力量，重获新生。' WHERE entry=36855;
UPDATE creature_text SET text='我的主人是无所不能的，他有无比强大的力量，不可抗拒的意志。' WHERE entry=36855;
UPDATE creature_text SET text='反抗者必将被毁灭。而那些全身心的，坚定不移的，有虔诚的思想与灵魂的效忠者们，必将得到超乎你们想象范畴的强大的力量。' WHERE entry=36855;
UPDATE creature_text SET text='是谁在打扰我？你们竟敢擅闯这神圣的地方？这里将会是你们的埋骨之地！' WHERE entry=36855;
UPDATE creature_text SET text='够了！看来需要我亲自上阵了！' WHERE entry=36855;
UPDATE creature_text SET text='%s''s Mana Barrier shimmers and fades away!' WHERE entry=36855;
UPDATE creature_text SET text='软弱的你抵挡不了我强大的意志！' WHERE entry=36855;
UPDATE creature_text SET text='来接受这祝福，让入侵者尝尝主人伟大的力量吧！' WHERE entry=36855;
UPDATE creature_text SET text='忠诚的追随者，从血肉的诅咒中解脱吧！' WHERE entry=36855;
UPDATE creature_text SET text='来吧，为纯粹的形态欢喜吧！' WHERE entry=36855;
UPDATE creature_text SET text='你还不明白自己的徒劳吗？' WHERE entry=36855;
UPDATE creature_text SET text='拥抱黑暗吧……永恒的黑暗。' WHERE entry=36855;
UPDATE creature_text SET text='陪你们玩的够久了！' WHERE entry=36855;
UPDATE creature_text SET text='这全是主人的计划……你的结局是必然的……' WHERE entry=36855;
UPDATE creature_text SET text='有人闯进了主人的房间！' WHERE entry=37007;
UPDATE creature_text SET text='我醒了!' WHERE entry=37007;
UPDATE creature_text SET text='那里是谁？' WHERE entry=37007;
UPDATE creature_text SET text='这是我们最后的阵地。今天的一切都将千古流传。无论是生是死，我们都是为了荣誉而战。我们都是为了自由和人民而战！' WHERE entry=37119;
UPDATE creature_text SET text='记住，英雄们，在这邪恶之地，恐惧是你们最大的敌人。勇气将让你们的灵魂比千颗太阳还要明亮。敌人会在你们面前溃不成军。正义的光芒将彻底摧毁他们！' WHERE entry=37119;
UPDATE creature_text SET text='现在，我们向冰冠堡垒进军！' WHERE entry=37119;
UPDATE creature_text SET text='阿尔萨斯！我发誓会彻底消灭你和天灾军团！昔日的恩怨会在今天做个了断！' WHERE entry=37119;
UPDATE creature_text SET text='圣光的力量没有止境,萨鲁法尔,他的灵魂饱受压抑,但他现在,还活着.' WHERE entry=37119;
UPDATE creature_text SET text='圣光在上，胜利属于我们！' WHERE entry=37119;
UPDATE creature_text SET text='别想……从这里……过去……' WHERE entry=37122;
UPDATE creature_text SET text='你们这些傻瓜永远找不到一只像样的蝙蝠翅膀。' WHERE entry=37122;
UPDATE creature_text SET text='我要的是变质的蜘蛛毒液!' WHERE entry=37122;
UPDATE creature_text SET text='不要……让芬克斯坦拿我……做药……' WHERE entry=37122;
UPDATE creature_text SET text='战斗难免牺牲，而我们的战友无论生死，都会效忠银色北伐军。' WHERE entry=37122;
UPDATE creature_text SET text='我宁愿死在这里，也不要为那个疯子芬克斯坦收集材料。' WHERE entry=37122;
UPDATE creature_text SET text='我已经救不活了。兄弟们，继续战斗……' WHERE entry=37123;
UPDATE creature_text SET text='什么？这种力量是……？所有的痛苦都消失了！你……？难道我们都投入了永恒的死亡怀抱？' WHERE entry=37123;
UPDATE creature_text SET text='一点都不疼了,是不是?' WHERE entry=37123;
UPDATE creature_text SET text='很抱歉……' WHERE entry=37123;
UPDATE creature_text SET text='你在与天灾的战争中立下了大功。愿圣光给你恩泽。' WHERE entry=37123;
UPDATE creature_text SET text='去……将我火化，让我在死后得到温暖……' WHERE entry=37124;
UPDATE creature_text SET text='不！不！为什么我不能在火中死去？ 都烧成焦炭吧！' WHERE entry=37124;
UPDATE creature_text SET text='能感到那灼热吗？' WHERE entry=37124;
UPDATE creature_text SET text='我……做了什么？不！' WHERE entry=37124;
UPDATE creature_text SET text='拯救这个邪恶之地非你莫属,谢谢你.' WHERE entry=37124;
UPDATE creature_text SET text='我死的……很值得……' WHERE entry=37125;
UPDATE creature_text SET text='巫妖王的意志不可逃避。准备好迎接一场爆炸吧！' WHERE entry=37125;
UPDATE creature_text SET text='这就是你距离炸弹太近的结果!' WHERE entry=37125;
UPDATE creature_text SET text='多么……爆炸性的结局啊！' WHERE entry=37125;
UPDATE creature_text SET text='小心前面潜伏的危险……就是死也要留个全尸。' WHERE entry=37125;
UPDATE creature_text SET text='你也许曾和我并肩作战，科罗克，但现在你只不过是一个叛徒。接受你的第二次死亡吧！' WHERE entry=37126;
UPDATE creature_text SET text='可怜的生物！死吧！' WHERE entry=37126;
UPDATE creature_text SET text='愚蠢的科罗克。你带来了我的援军。银色勇士们，用你们的死来效忠巫妖王吧！' WHERE entry=37126;
UPDATE creature_text SET text='来吧，斩亡者。我会让主人知道，我们谁才配得上“勇士”之名！' WHERE entry=37126;
UPDATE creature_text SET text='怎么选这种低能的盟友，科罗克！' WHERE entry=37126;
UPDATE creature_text SET text='什么?这就死了?这也不错嘛.' WHERE entry=37126;
UPDATE creature_text SET text='也许……你是对的，科罗克。' WHERE entry=37126;
UPDATE creature_text SET text='%s has impaled $N!' WHERE entry=37126;
UPDATE creature_text SET text='%s''s Aether Shield has been shattered by $N!' WHERE entry=37126;
UPDATE creature_text SET text='准备战斗，北伐军的弟兄们。维库人会用他们的生命保护冰霜女王。' WHERE entry=37129;
UPDATE creature_text SET text='都给我严肃点！我们的勇士已经到了，我们要奋勇战斗，支援他们！' WHERE entry=37129;
UPDATE creature_text SET text='把他们引到这里来。我们会支援你。' WHERE entry=37129;
UPDATE creature_text SET text='快！推进！' WHERE entry=37129;
UPDATE creature_text SET text='她的援兵就要到了！我们必须迅速消灭她！' WHERE entry=37129;
UPDATE creature_text SET text='我来挡住她。让我的兄弟回到坟墓中去，然后帮我消灭她！' WHERE entry=37129;
UPDATE creature_text SET text='啊！我必须休息一下了。' WHERE entry=37129;
UPDATE creature_text SET text='勇士们!我就要挡不住他了!' WHERE entry=37129;
UPDATE creature_text SET text='仅靠仇恨,还不够.' WHERE entry=37129;
UPDATE creature_text SET text='这是天灾军团的“神圣”土地。圣光在这里毫无用处，圣骑士。你将孤立无援……' WHERE entry=37181;
UPDATE creature_text SET text='弗丁，你本应是我最强大的战士，你的黑暗力量将清洗这个世界，开启一个新的世代。' WHERE entry=37181;
UPDATE creature_text SET text='不过这份荣誉已经不再属于你。很快，我就会拥有一名新的勇士。' WHERE entry=37181;
UPDATE creature_text SET text='我为这个灵魂耗费了巨大的力量，让他承受了无数痛苦……他抵抗了那么长时间，但用不了多久就会屈服了。' WHERE entry=37181;
UPDATE creature_text SET text='你们最终全都会效忠我。' WHERE entry=37181;
UPDATE creature_text SET text='绝不！我……绝不……服从你。' WHERE entry=37183;
UPDATE creature_text SET text='库卡隆，行动！勇士们，提高警惕！天灾军团已经...' WHERE entry=37187;
UPDATE creature_text SET text='我儿子战死在天谴之门，我来只是想带走他的尸体。' WHERE entry=37187;
UPDATE creature_text SET text='我给他起名为德拉诺什，意思是“德拉诺之心”。我不会让那些术士带走他。我的孩子会安全的葬在加拉达尔长老那里。' WHERE entry=37187;
UPDATE creature_text SET text='我在他的母亲弥留之际许下诺言，我会孤身穿过黑暗之门，不论我是生是死，我都孩子都不会受到污染，都会纯净如初...' WHERE entry=37187;
UPDATE creature_text SET text='今天，我兑现了诺言！' WHERE entry=37187;
UPDATE creature_text SET text='萨鲁法尔咆哮着向他的儿子冲去.' WHERE entry=37187;
UPDATE creature_text SET text='躺在那里的是我唯一的儿子。无论什么也不能把我和他分离。' WHERE entry=37187;
UPDATE creature_text SET text='High Overlord Saurfang walks over to his son and kneels before his son''s body.' WHERE entry=37187;
UPDATE creature_text SET text='[兽人语] No''ku kil zil''nok ha tar.' WHERE entry=37187;
UPDATE creature_text SET text='Higher Overlord Saurfang picks up the body of his son and walks over towards Varian' WHERE entry=37187;
UPDATE creature_text SET text='我不会忘记您的……仁慈。感谢您，殿下。' WHERE entry=37187;
UPDATE creature_text SET text='%s 走到他儿子的尸体前咳嗽了两声.' WHERE entry=37187;
UPDATE creature_text SET text='%s 然后对着儿子的尸体流下了眼泪.' WHERE entry=37187;
UPDATE creature_text SET text='你会在纳格兰有一个隆重的葬礼，就安睡在你母亲和先祖身边...' WHERE entry=37187;
UPDATE creature_text SET text='年轻的英雄们，不论战斗多么残酷，都不要忘记荣耀！' WHERE entry=37187;
UPDATE creature_text SET text='那名圣骑士还活着?是真的吗?大领主,他居然还活着?' WHERE entry=37187;
UPDATE creature_text SET text='那我们必须去救他,如果我们救出了伯瓦尔·弗塔根,就能平息联盟和部落无休止的纷争.' WHERE entry=37187;
UPDATE creature_text SET text='任务已经明确,巫妖王将为他的罪行付出代价,我们一定要救出伯瓦尔·弗塔根公爵.' WHERE entry=37187;
UPDATE creature_text SET text='库卡隆,为最后的冲锋做好准备.勇士们,炮船将在那座堡垒的顶部着陆,我们在那里汇合.' WHERE entry=37187;
UPDATE creature_text SET text='%s 哭了起来。' WHERE entry=37188;
UPDATE creature_text SET text='没什么，陛下……我只是，为国王而自豪。' WHERE entry=37188;
UPDATE creature_text SET text='那我们要行动了，我们要……' WHERE entry=37200;
UPDATE creature_text SET text='区区一个兽人竟然想与联盟对抗？？？' WHERE entry=37200;
UPDATE creature_text SET text='冲锋！！！' WHERE entry=37200;
UPDATE creature_text SET text='%s 气喘吁吁。' WHERE entry=37200;
UPDATE creature_text SET text='这就是萨鲁法尔的儿子——部落在天谴之门的指挥官。真是个悲剧……' WHERE entry=37200;
UPDATE creature_text SET text='远处那里……那里是什么！' WHERE entry=37200;
UPDATE creature_text SET text='A Horde Zeppelin flies up to the rise.' WHERE entry=37200;
UPDATE creature_text SET text='士兵们，集合！看样子部落马上又要射击了！' WHERE entry=37200;
UPDATE creature_text SET text='The Zeppelin docks, and High Overlord Saurfang hops out, confronting the Alliance soldiers and Muradin' WHERE entry=37200;
UPDATE creature_text SET text='别逼我，兽人。我不能让你过去。' WHERE entry=37200;
UPDATE creature_text SET text='我，我不能这样做。回到船上去，我就饶你一命。' WHERE entry=37200;
UPDATE creature_text SET text='A mage portal from Stormwind appears between the two and Varian Wrynn and Jaina Proudmoore emerge.' WHERE entry=37200;
UPDATE creature_text SET text='这就去，陛下！' WHERE entry=37200;
UPDATE creature_text SET text='弗丁领主，这是真的？如果伯瓦尔还活着，也许联盟和部落之间还有和平的希望。我们必须冲到堡垒顶层，救出圣骑士！' WHERE entry=37200;
UPDATE creature_text SET text='让破天号做好空袭城堡的准备！' WHERE entry=37200;
UPDATE creature_text SET text='英雄们，你们必须尽快在冰冠堡垒内部夺取一个立足点。我们在城墙上汇合！' WHERE entry=37200;
UPDATE creature_text SET text='%s cries out with a loud, baying howl!' WHERE entry=37217;
UPDATE creature_text SET text='你们这些傻瓜永远找不到一只像样的蝙蝠翅膀。' WHERE entry=37491;
UPDATE creature_text SET text='我要的是变质的蜘蛛毒液.' WHERE entry=37491;
UPDATE creature_text SET text='不要……让芬克斯坦拿我……做药……' WHERE entry=37491;
UPDATE creature_text SET text='什么？这种力量是……？所有的痛苦都消失了！你……？难道我们都投入了永恒的死亡怀抱？' WHERE entry=37493;
UPDATE creature_text SET text='一点都不疼,是不是?' WHERE entry=37493;
UPDATE creature_text SET text='抱歉……' WHERE entry=37493;
UPDATE creature_text SET text='不！不！为什么我不能在火中死去？ 都烧成焦炭吧！' WHERE entry=37494;
UPDATE creature_text SET text='能感到那灼热吗？' WHERE entry=37494;
UPDATE creature_text SET text='我……做了什么？不！' WHERE entry=37494;
UPDATE creature_text SET text='巫妖王的意志不可逃避。准备好迎接一场爆炸吧！' WHERE entry=37495;
UPDATE creature_text SET text='这就是你距离炸弹太近的结果!' WHERE entry=37495;
UPDATE creature_text SET text='多么……爆炸性的结局啊！' WHERE entry=37495;
UPDATE creature_text SET text='你每消灭一名部落士兵，或是杀死一只联盟狗。巫妖王的军力就会增长一分。瓦格里正在把你们的阵亡者变为天灾战士。' WHERE entry=37813;
UPDATE creature_text SET text='你们就要大祸临头了。来吧，尝尝巫妖王赐予我的力量吧！' WHERE entry=37813;
UPDATE creature_text SET text='矮人……' WHERE entry=37813;
UPDATE creature_text SET text='%s immobilizes Muradin and his guards.' WHERE entry=37813;
UPDATE creature_text SET text='加入我,父亲.让我们一同以天灾之名,来粉碎这个渺小的世界--巫妖王万岁!' WHERE entry=37813;
UPDATE creature_text SET text='顽固的老头，你以为你能赢？就算是你最强壮的时候，也不如我现在的力量！' WHERE entry=37813;
UPDATE creature_text SET text='可怜的老兽人！来吧,英雄们,来尝尝天灾军团的力量吧!' WHERE entry=37813;
UPDATE creature_text SET text='以巫妖王的力量为名！' WHERE entry=37813;
UPDATE creature_text SET text='血兽获得了血之气息！' WHERE entry=37813;
UPDATE creature_text SET text='吃吧，奴仆们！' WHERE entry=37813;
UPDATE creature_text SET text='无能之辈！' WHERE entry=37813;
UPDATE creature_text SET text='你们将在这里魂飞魄散！' WHERE entry=37813;
UPDATE creature_text SET text='%s goes into frenzy!' WHERE entry=37813;
UPDATE creature_text SET text='我变成了……死神！' WHERE entry=37813;
UPDATE creature_text SET text='我……终于……解脱了……' WHERE entry=37813;
UPDATE creature_text SET text='退后，穆拉丁，让这位伤心的父亲过去。' WHERE entry=37879;
UPDATE creature_text SET text='我……那时不在天谴之门。但活下来的士兵告诉了我当时的情况。你的儿子为荣耀而战，他英勇地战死，应该得到英雄般的厚葬。' WHERE entry=37879;
UPDATE creature_text SET text='吉安娜，你怎么哭了？' WHERE entry=37879;
UPDATE creature_text SET text='穆拉丁，守住甲板，组织士兵向城堡上层发动进攻。我会带另一支暴风城部队过去。' WHERE entry=37879;
UPDATE creature_text SET text='你做了一个……愚蠢的……决定。' WHERE entry=37955;
UPDATE creature_text SET text='就咬一小口……' WHERE entry=37955;
UPDATE creature_text SET text='我饿了！' WHERE entry=37955;
UPDATE creature_text SET text='对！吃吧，宝贝！你是我的了！' WHERE entry=37955;
UPDATE creature_text SET text='You thirst for blood!' WHERE entry=37955;
UPDATE creature_text SET text='死吧！' WHERE entry=37955;
UPDATE creature_text SET text='Shadows amass and swarm around $N!' WHERE entry=37955;
UPDATE creature_text SET text='你受得了吗？' WHERE entry=37955;
UPDATE creature_text SET text='就要来了……' WHERE entry=37955;
UPDATE creature_text SET text='真的……？你就这点能耐？' WHERE entry=37955;
UPDATE creature_text SET text='真是可怜。' WHERE entry=37955;
UPDATE creature_text SET text='多么的……不幸啊。' WHERE entry=37955;
UPDATE creature_text SET text='一切都结束了！' WHERE entry=37955;
UPDATE creature_text SET text='真是的……我们相处得……那么……好……' WHERE entry=37955;
UPDATE creature_text SET text='纳克萨纳尔的失败早已过去！有了这颗宝珠，瓦拉纳就能完成复仇！' WHERE entry=37970;
UPDATE creature_text SET text='Invocation of Blood jumps to Prince Valanar!' WHERE entry=37970;
UPDATE creature_text SET text='杯子已经被斟满了。' WHERE entry=37970;
UPDATE creature_text SET text='%s begins casting Empowered Schock Vortex!' WHERE entry=37970;
UPDATE creature_text SET text='晚餐……开席。' WHERE entry=37970;
UPDATE creature_text SET text='见识到黑暗堕落者的力量了吧？' WHERE entry=37970;
UPDATE creature_text SET text='向萨莱因屈服吧！' WHERE entry=37970;
UPDATE creature_text SET text='...什么...?' WHERE entry=37970;
UPDATE creature_text SET text='如此汹涌的力量！黑暗堕落宝珠让我所向无敌！' WHERE entry=37972;
UPDATE creature_text SET text='Invocation of Blood jumps to Prince Keleseth!' WHERE entry=37972;
UPDATE creature_text SET text='血溅当场吧！' WHERE entry=37972;
UPDATE creature_text SET text='你们也敢来冒犯？' WHERE entry=37972;
UPDATE creature_text SET text='死亡才是真谛。' WHERE entry=37972;
UPDATE creature_text SET text='%s 变得狂暴了！' WHERE entry=37972;
UPDATE creature_text SET text='我的女王，他们……来了。' WHERE entry=37972;
UPDATE creature_text SET text='在塔达拉姆面前颤抖吧，因为我拥有黑暗堕落宝珠的力量！' WHERE entry=37973;
UPDATE creature_text SET text='Invocation of Blood jumps to Prince Taldaram!' WHERE entry=37973;
UPDATE creature_text SET text='承受痛苦吧！' WHERE entry=37973;
UPDATE creature_text SET text='Inferno Flames speed toward $N!' WHERE entry=37973;
UPDATE creature_text SET text='蛆虫。' WHERE entry=37973;
UPDATE creature_text SET text='乞求宽恕吧！' WHERE entry=37973;
UPDATE creature_text SET text='%s 变得狂暴了！' WHERE entry=37973;
UPDATE creature_text SET text='%s gurgles and dies.' WHERE entry=37973;
UPDATE creature_text SET text='愚蠢的凡人。你以为能轻易打败我们？萨莱因是巫妖王永生的战士！现在他们将合力撕碎你！' WHERE entry=38004;
UPDATE creature_text SET text='站起来，兄弟们，消灭这些敌人！' WHERE entry=38004;
UPDATE creature_text SET text='Are you certain you should be helping these mortals in their quest for the sword?' WHERE entry=38017;
UPDATE creature_text SET text='These blades, Krasus... They were made long ago, when things were... different.' WHERE entry=38017;
UPDATE creature_text SET text='Our enemies once turned our strongest weapon against us. What makes you think the prismatic blades will be any different?' WHERE entry=38017;
UPDATE creature_text SET text='As you wish, my queen. I will not stand in their way, but I will keep a close watch.' WHERE entry=38017;
UPDATE creature_text SET text='Die, intruders! None shall interfere with the Cult''s plans!' WHERE entry=38472;
UPDATE creature_text SET text='Wh- where am I...? What a nightmare I have had... But this is no time to reflect, I have much information to report!' WHERE entry=38472;
UPDATE creature_text SET text='Die, intruders! None shall interfere with the Cult''s plans!' WHERE entry=38485;
UPDATE creature_text SET text='Wh- where am I...? What a nightmare I have had... But this is no time to reflect, I have much information to report!' WHERE entry=38485;
UPDATE creature_text SET text='$n is infected with the Death Plague!' WHERE entry=38490;
UPDATE creature_text SET text='$n is infected with the Death Plague!' WHERE entry=38494;
UPDATE creature_text SET text='终于自由了！结束了，我的儿子。清算的时候到了。' WHERE entry=38579;
UPDATE creature_text SET text='圣光的勇士们！集结起来！' WHERE entry=38579;
UPDATE creature_text SET text='我们会让你死个痛快，阿尔萨斯。对于犯下累累罪行的你，这是最大的仁慈了。' WHERE entry=38995;
UPDATE creature_text SET text='好吧，勇士们，进攻！' WHERE entry=38995;
UPDATE creature_text SET text='无上的圣光啊！请祝福我！赐予我力量……帮助我冲破这些枷锁！' WHERE entry=38995;
UPDATE creature_text SET text='结束了，阿尔萨斯！你残害生灵的日子今天结束了！' WHERE entry=38995;
UPDATE creature_text SET text='你是来审判阿尔萨斯的吗？想要看到巫妖王的灭亡？' WHERE entry=39217;
UPDATE creature_text SET text='首先，你需要摆脱霜之哀伤的控制，否则就会像我一样，永世成为这把邪剑的囚徒。' WHERE entry=39217;
UPDATE creature_text SET text='All right, you twisted mess of broken gears, let''s get to work!' WHERE entry=39368;
UPDATE creature_text SET text='I am going to teach you all what it takes to be a proper soldier!' WHERE entry=39368;
UPDATE creature_text SET text='The first thing you need to learn is proper discipline.' WHERE entry=39368;
UPDATE creature_text SET text='Show me that discipline with a proper salute when I say so!' WHERE entry=39368;
UPDATE creature_text SET text='Okay, recruits, salute!' WHERE entry=39368;
UPDATE creature_text SET text='Nice job!' WHERE entry=39368;
UPDATE creature_text SET text='When you go into combat, it is important that you know how to intimidate the enemy with a deafening battle roar!' WHERE entry=39368;
UPDATE creature_text SET text='When I give the signal, let loose your greatest roar!' WHERE entry=39368;
UPDATE creature_text SET text='Let me hear that battle roar!' WHERE entry=39368;
UPDATE creature_text SET text='Wow, nice and scary!' WHERE entry=39368;
UPDATE creature_text SET text='Remember though, a key factor in winning any battle is positive reinforcement.' WHERE entry=39368;
UPDATE creature_text SET text='Reward your fellow soldiers in battle with a resounding cheer.  Now, cheer at me when I tell you to!' WHERE entry=39368;
UPDATE creature_text SET text='Everyone, cheer!' WHERE entry=39368;
UPDATE creature_text SET text='Fantastic!' WHERE entry=39368;
UPDATE creature_text SET text='However, the most important part of battle is how you celebrate a good hard earned victory!' WHERE entry=39368;
UPDATE creature_text SET text='Show me your best victory dance when I give the signal!' WHERE entry=39368;
UPDATE creature_text SET text='Now, dance!' WHERE entry=39368;
UPDATE creature_text SET text='Superb!' WHERE entry=39368;
UPDATE creature_text SET text='You might be the best set of recruits I''ve ever seen!  Let''s go through all of that again!' WHERE entry=39368;
UPDATE creature_text SET text='阿莱克丝塔萨选对了盟友……很可惜，你们都将死在这里！' WHERE entry=39746;
UPDATE creature_text SET text='不要心存侥幸！' WHERE entry=39746;
UPDATE creature_text SET text='这是最好的结局。' WHERE entry=39746;
UPDATE creature_text SET text='让他们化为灰烬，仆从们！' WHERE entry=39746;
UPDATE creature_text SET text='海里昂，我……' WHERE entry=39746;
UPDATE creature_text SET text='擅闯者死！' WHERE entry=39747;
UPDATE creature_text SET text='在主人的烈焰中抽搐吧！' WHERE entry=39747;
UPDATE creature_text SET text='%s becomes enraged!' WHERE entry=39747;
UPDATE creature_text SET text='海里昂会高兴的。' WHERE entry=39747;
UPDATE creature_text SET text='本该如此……' WHERE entry=39747;
UPDATE creature_text SET text='你的力量在减弱，老家伙……准备下去见你的朋友吧。' WHERE entry=39751;
UPDATE creature_text SET text='啊，娱乐要开始了！' WHERE entry=39751;
UPDATE creature_text SET text='巴尔萨鲁斯从不留活口！' WHERE entry=39751;
UPDATE creature_text SET text='这个世界的英雄够多了。' WHERE entry=39751;
UPDATE creature_text SET text='痛苦带来欢愉!' WHERE entry=39751;
UPDATE creature_text SET text='我……没想到会这样……' WHERE entry=39751;
UPDATE creature_text SET text='O spirit of de tigers, lend $N your power and help us find de answers we seek!' WHERE entry=40184;
UPDATE creature_text SET text='Sign me up!' WHERE entry=40260;
UPDATE creature_text SET text='Anythin'' for Vol''jin!' WHERE entry=40260;
UPDATE creature_text SET text='I''d be glad to help.' WHERE entry=40260;
UPDATE creature_text SET text='Just point me at de enemy!' WHERE entry=40260;
UPDATE creature_text SET text='Reportin'' for duty.' WHERE entry=40260;
UPDATE creature_text SET text='Ready to take de fight to Zalazane.' WHERE entry=40260;
UPDATE creature_text SET text='Ready to fight beside Vol''jin!' WHERE entry=40260;
UPDATE creature_text SET text='New troll here!' WHERE entry=40260;
UPDATE creature_text SET text='When does de trainin'' start?' WHERE entry=40260;
UPDATE creature_text SET text='Sign me up!' WHERE entry=40264;
UPDATE creature_text SET text='Anythin'' for Vol''jin!' WHERE entry=40264;
UPDATE creature_text SET text='I''d be glad to help.' WHERE entry=40264;
UPDATE creature_text SET text='Just point me at de enemy!' WHERE entry=40264;
UPDATE creature_text SET text='Reportin'' for duty.' WHERE entry=40264;
UPDATE creature_text SET text='Ready to take de fight to Zalazane.' WHERE entry=40264;
UPDATE creature_text SET text='Ready to fight beside Vol''jin!' WHERE entry=40264;
UPDATE creature_text SET text='New troll here!' WHERE entry=40264;
UPDATE creature_text SET text='When does de trainin'' start?' WHERE entry=40264;
UPDATE creature_text SET text='The tiger matriarch appears! Prove yourself in combat!' WHERE entry=40301;
UPDATE creature_text SET text='Dat be enough for now!' WHERE entry=40329;
UPDATE creature_text SET text='Don''t be lookin'' so surprised. Your shaman friend has sharp eyes, or should I say, sharp frogs.' WHERE entry=40329;
UPDATE creature_text SET text='My kind, da druids, we been layin'' low for some time now. We been waitin'' to see when an'' if Vol''jin might return.' WHERE entry=40329;
UPDATE creature_text SET text='Now dat it looks like de Darkspear be returnin'' to these isles, maybe de time has come for us to reveal ourselves.' WHERE entry=40329;
UPDATE creature_text SET text='Go back to Vol''jin an'' tell him dis: Zen''tabra stands ready to help him in de coming battle.' WHERE entry=40329;
UPDATE creature_text SET text='Darkspears, we consult de spirits! Drummers, take your places!' WHERE entry=40352;
UPDATE creature_text SET text='Spirits, we be gathered here to ask for your guidance.' WHERE entry=40352;
UPDATE creature_text SET text='Our leader, Vol''jin, son of Sen''jin, issued de call to all Darkspears: reclaim de Echo Isles for our tribe.' WHERE entry=40352;
UPDATE creature_text SET text='Spirits! I offer me own body to you! Speak through me! Is de time right for mighty Vol''jin''s undertaking?' WHERE entry=40352;
UPDATE creature_text SET text='De ancestors hear ya, witch doctor!' WHERE entry=40352;
UPDATE creature_text SET text='Know dat your plans please us, Darkspears. De son of Sen''jin walks de right path.' WHERE entry=40352;
UPDATE creature_text SET text='De task in front of ya will not be easy, but ya have our blessin''.' WHERE entry=40352;
UPDATE creature_text SET text='Ya gave up your home an'' ya gave up de loas of your ancestors when ya left de Echo Isles. Dey will not be pleased dat you been ignorin'' dem.' WHERE entry=40352;
UPDATE creature_text SET text='Ya must make amends wit'' Bwonsamdi, de guardian of de dead, if ya hope to defeat Zalazane. It be de only way. Tell de son of Sen''jin dese things.' WHERE entry=40352;
UPDATE creature_text SET text='De spirits have blessed us wit'' an answer! De Echo Isles will be ours again!' WHERE entry=40352;
UPDATE creature_text SET text='Thank ya, scout. Keep up da patrols. But for now, a rest is in order. Dismissed.' WHERE entry=40391;
UPDATE creature_text SET text='He got a big army, an'' he be plannin'' somethin'' down dere.' WHERE entry=40416;
UPDATE creature_text SET text='Zalazane got most of his hexes trolls hidden under de canopy on de big island.' WHERE entry=40416;
UPDATE creature_text SET text='谢谢你的帮助！我已经濒临崩溃了……这里发生了可怕的事情。' WHERE entry=40429;
UPDATE creature_text SET text='我们相信圣殿是坚不可摧的，但我们没想到会遭受这样的攻击。' WHERE entry=40429;
UPDATE creature_text SET text='黑龙人凭空出现，在我们反应过来之前就发动了攻击。' WHERE entry=40429;
UPDATE creature_text SET text='我们全面溃败。同胞们一个个死去。只有我撤退到这里，并封住了入口。' WHERE entry=40429;
UPDATE creature_text SET text='他们冷酷无情地屠杀我们，但他们真正的目标似乎是圣殿里的那些卵。' WHERE entry=40429;
UPDATE creature_text SET text='指挥他们的是一个名叫萨瑞瑟里安的残忍家伙。但我担心他背后还有更强大的力量。' WHERE entry=40429;
UPDATE creature_text SET text='刚受到攻击时，我看见了他们真正的首领，一头恐怖的暮光巨龙。' WHERE entry=40429;
UPDATE creature_text SET text='我还不知道他们的全盘计划，但我知道，英雄们，绝不能让他们得逞！' WHERE entry=40429;
UPDATE creature_text SET text='救命！我被困在这棵树里了！我需要帮助！' WHERE entry=40429;

