UPDATE db_script_string SET content_default='The deeds are mine, brother! Soon you shall be out of my way for good!' WHERE entry=2000000001;
UPDATE db_script_string SET content_default='Honor your heroes! On this day, they have dealt a great blow against one of our most hated enemies! The false Warchief, Rend Blackhand, has fallen! ' WHERE entry=2000000002;
UPDATE db_script_string SET content_default='Be bathed in my power! Drink in my might! Battle for the glory of the Horde!' WHERE entry=2000000003;
UPDATE db_script_string SET content_default='这是它！ 这真的它－－大乌鸦的帐本！' WHERE entry=2000000004;
UPDATE db_script_string SET content_default='它会花数年在没有你的情况下找大乌鸦的帐本，年轻的雀鹰和我们感谢的心情伴随你回到你的家。' WHERE entry=2000000005;
UPDATE db_script_string SET content_default='他们是跟随我，$R!  很快地，在我们被发现之前告诉我你为什么在这里！ 如果他们决定抓我，它将会意味着我和你一起死亡！' WHERE entry=2000000006;
UPDATE db_script_string SET content_default='你－－你不是他们的其中之一！ 在他们找到我们之前，让我们离开这里！快！' WHERE entry=2000000007;
UPDATE db_script_string SET content_default='你正在亚瑟的王国做什么？无营业执照者！我叫道，离开我们！ 你的货物在这里不受欢迎！' WHERE entry=2000000008;
UPDATE db_script_string SET content_default='威胁结束！ $N 是 萨文是我们所有的！' WHERE entry=2000000009;
UPDATE db_script_string SET content_default='你有多少埋怨，我需要送回的妈妈和爸爸在一个运尸袋里包着，是军团头杀死的还是自杀?你不要向我点你的头骨,尽管你知道我废话!' WHERE entry=2000000010;
UPDATE db_script_string SET content_default='好吧，那就行动。 现在来，回到商店完成我们的事业！' WHERE entry=2000000011;
UPDATE db_script_string SET content_default='跟着我，好＄$C. 艾尔文烈啤酒你竟然比我更快速地喝完了。 Mmmm。。。 烈啤酒。' WHERE entry=2000000012;
UPDATE db_script_string SET content_default='向万能者鞠躬！ 在我的地狱主宰之前弯腰。。。 小鸡？' WHERE entry=2000000013;
UPDATE db_script_string SET content_default='往后站！站开！地狱者将会需要有一个宽的船位！' WHERE entry=2000000014;
UPDATE db_script_string SET content_default='要由耐心 $N. 火炬几乎都是完整的.' WHERE entry=2000000019;
UPDATE db_script_string SET content_default='这很有趣......' WHERE entry=2000000020;
UPDATE db_script_string SET content_default='可爱的歌曲，不是吗？' WHERE entry=2000000021;
UPDATE db_script_string SET content_default='精神的水,我赞美你,我求你帮个忙。你有听到$N的请求,我信任他是高贵的。请你帮助我们?' WHERE entry=2000000026;
UPDATE db_script_string SET content_default='%s gestures to the pitcher of water sitting on the edge of the well.' WHERE entry=2000000027;
UPDATE db_script_string SET content_default='西部荒野的人民敬礼,$N,一个自由的勇敢的防御者。' WHERE entry=2000000028;
UPDATE db_script_string SET content_default='这是后勒的帐篷，但是后勒在哪？' WHERE entry=2000000029;
UPDATE db_script_string SET content_default='它也没在这，奇怪了，它在哪？' WHERE entry=2000000030;
UPDATE db_script_string SET content_default='Beware, $n! Look to the west!' WHERE entry=2000000031;
UPDATE db_script_string SET content_default='Gird yourself $N, for the demon in this orb is a fel beast.' WHERE entry=2000000032;
UPDATE db_script_string SET content_default='来吧, $N. 等着主人的怒火吧.' WHERE entry=2000000034;
UPDATE db_script_string SET content_default='There’s nothing like some scalding mornbrew on a chilly Dun Morogh day to get things started right!' WHERE entry=2000000035;
UPDATE db_script_string SET content_default='从桌上拿一块石头。你的任务会需要它。' WHERE entry=2000000036;
UPDATE db_script_string SET content_default='你们听着,里斯的居住者!请让人们知道 $n 是崇高的成员。铁匠的荣誉、奉献和无限的耐心。为$n欢呼三次！' WHERE entry=2000000041;
UPDATE db_script_string SET content_default='和平和耐性和你在一起,$N。总是保持强劲。' WHERE entry=2000000042;
UPDATE db_script_string SET content_default='"直到我们再次见面,勇敢的人。直到我们再次见面,勇敢的人。"' WHERE entry=2000000043;
UPDATE db_script_string SET content_default='你必须保护我,谁敢生活在这片森林里!' WHERE entry=2000000044;
UPDATE db_script_string SET content_default='这片森林对我们非常危险。我们必须留心!' WHERE entry=2000000045;
UPDATE db_script_string SET content_default='杀了两个怪物,他们留在附近的植物,我收集了一些' WHERE entry=2000000046;
UPDATE db_script_string SET content_default='我再搜集一些植物，这得需要一些时间' WHERE entry=2000000047;
UPDATE db_script_string SET content_default='现在我可以把这些种到我的庄园里' WHERE entry=2000000048;
UPDATE db_script_string SET content_default='再次感谢你 $N，这对于地球和我的实验都非常有利' WHERE entry=2000000049;
UPDATE db_script_string SET content_default='恩，好吧，我现在派人，我们必须找到并救他' WHERE entry=2000000050;
UPDATE db_script_string SET content_default='你知道他在哪？' WHERE entry=2000000051;
UPDATE db_script_string SET content_default='他不见了?' WHERE entry=2000000052;
UPDATE db_script_string SET content_default='发生什么事？' WHERE entry=2000000053;
UPDATE db_script_string SET content_default='方法,新手!' WHERE entry=2000000054;
UPDATE db_script_string SET content_default='这里是灯塔，$n保持自给，如果您找到我们需要的东西。' WHERE entry=2000000056;
UPDATE db_script_string SET content_default='请，凡人，请与奥术师在达拉然进行谈判。' WHERE entry=2000000057;
UPDATE db_script_string SET content_default='谢谢你的伟大精神。非常感谢！' WHERE entry=2000000058;
UPDATE db_script_string SET content_default='我在此销毁这些文书的邪恶！为了部落！' WHERE entry=2000000059;
UPDATE db_script_string SET content_default='请，凡人，在达拉然寻找魔导师。他可以与银色盟约谈判。' WHERE entry=2000000063;
UPDATE db_script_string SET content_default='这一切意味着什么呢？住手！我会付你工资的两倍了！' WHERE entry=2000000064;
UPDATE db_script_string SET content_default='你是什么意思，他说“我的时间已经到来”？我就当场杀了你！' WHERE entry=2000000065;
UPDATE db_script_string SET content_default='你如果不能真正记住，我是不会一直沉默的 | 3-6 ($ c)!' WHERE entry=2000000066;
UPDATE db_script_string SET content_default='快点我的朋友' WHERE entry=2000000074;
UPDATE db_script_string SET content_default='你好。' WHERE entry=2000000076;
UPDATE db_script_string SET content_default='跛脚乔不问！但是 -是的，我知道洛肯。' WHERE entry=2000000082;
UPDATE db_script_string SET content_default='他要我抢！如果我在你的地方是这里的旅客。你永远不知道他是如何躲在树下！' WHERE entry=2000000083;
UPDATE db_script_string SET content_default='我们不能容忍任何恶魔的仆人在我们的家园出现!' WHERE entry=2000000090;
UPDATE db_script_string SET content_default='Ribbit ! 不! ! !这是绝对不可能…ribbit…!你骗我…. ribbit……你的诡计!Ribbit !' WHERE entry=2000000091;
UPDATE db_script_string SET content_default='“嘿,Belm !给我一个马克杯的雷声,一袋啤酒给我的好朋友!' WHERE entry=2000000092;
UPDATE db_script_string SET content_default='一旦我们的敌人转而反对我们，我们强大的武器。是什么让你觉得棱形刀片将有什么不同？' WHERE entry=2000000105;
UPDATE db_script_string SET content_default='如你愿意，我的皇后。我不会站在他们的对面，但我会继续密切留意。' WHERE entry=2000000106;
UPDATE db_script_string SET content_default='[PH]你好, $N.' WHERE entry=2000000107;
UPDATE db_script_string SET content_default='检查炮弹...' WHERE entry=2000000108;
UPDATE db_script_string SET content_default='You were right to come. My wisdom will be yours.' WHERE entry=2000000109;
UPDATE db_script_string SET content_default='%s creates his toxin...' WHERE entry=2000000110;
UPDATE db_script_string SET content_default='There we are, $N. The toxin is ready.' WHERE entry=2000000111;
UPDATE db_script_string SET content_default='%s fills a container with the toxin.' WHERE entry=2000000112;
UPDATE db_script_string SET content_default='The toxin is ready, $N.' WHERE entry=2000000113;
UPDATE db_script_string SET content_default='Okay, crew. Get to work on getting these bones installed.' WHERE entry=2000000114;
UPDATE db_script_string SET content_default='%s watches as his blood begins to stir, and the guile of the raptor slips through him.' WHERE entry=2000000115;
UPDATE db_script_string SET content_default='What is this power that flows through me? Is this the power of shamanism that Tor’gan spoke of...?' WHERE entry=2000000116;
UPDATE db_script_string SET content_default='Amazing! I feel... renewed. My strength returns!' WHERE entry=2000000117;
UPDATE db_script_string SET content_default='Easier then I expected... the sigil of Thoradin is whole, once again.' WHERE entry=2000000118;
UPDATE db_script_string SET content_default='%s takes big swig of ale.' WHERE entry=2000000119;
UPDATE db_script_string SET content_default='That was refreshing. Now there’s information that needs to be told...' WHERE entry=2000000120;
UPDATE db_script_string SET content_default='I believe the Forsaken are misleading the allies of the Horde... wait... I feel so... dizzy...' WHERE entry=2000000121;
UPDATE db_script_string SET content_default='%s writhes in pain.' WHERE entry=2000000122;
UPDATE db_script_string SET content_default='AAAAAAAAAAAAAAAARGH!' WHERE entry=2000000123;
UPDATE db_script_string SET content_default='%s begins to cast a spell over the hearts and tongues.' WHERE entry=2000000124;
UPDATE db_script_string SET content_default='The brood of Onyxia!' WHERE entry=2000000125;
UPDATE db_script_string SET content_default='%s snorts a speck of dream dust up his nose...' WHERE entry=2000000126;
UPDATE db_script_string SET content_default='%s is dazed...' WHERE entry=2000000127;
UPDATE db_script_string SET content_default='ACHOO!' WHERE entry=2000000128;
UPDATE db_script_string SET content_default='Wow! $N, that dream dust is powerful stuff!' WHERE entry=2000000129;
UPDATE db_script_string SET content_default='Thank you, $N.' WHERE entry=2000000130;
UPDATE db_script_string SET content_default='I’m sure I can find a use for this mixture...' WHERE entry=2000000131;
UPDATE db_script_string SET content_default='%s tries opening Maury’s Clubbed Foot...' WHERE entry=2000000132;
UPDATE db_script_string SET content_default='This shouldn’t take long...' WHERE entry=2000000133;
UPDATE db_script_string SET content_default='The invisibility liquor is ready for you, $n' WHERE entry=2000000134;
UPDATE db_script_string SET content_default='Here goes nothing...' WHERE entry=2000000135;
UPDATE db_script_string SET content_default='Almost done...' WHERE entry=2000000136;
UPDATE db_script_string SET content_default='At last, the serum is complete, $N. Now, come closer. We must talk.' WHERE entry=2000000137;
UPDATE db_script_string SET content_default='当我的变化出现...我的妻子和孩子们…' WHERE entry=2000000138;
UPDATE db_script_string SET content_default='Corbett, dear. Harlan needs a load of knitted shirts and pants as soon as we can manage.' WHERE entry=2000000139;
UPDATE db_script_string SET content_default='Corbett, you there? Harlan needs another load of knitted goods. Can you take it to him?' WHERE entry=2000000140;
UPDATE db_script_string SET content_default='My pleasure, sugar drop. I’ll be back soon...' WHERE entry=2000000141;
UPDATE db_script_string SET content_default='Business must be good down at the bazaar. I’ll get him resupplied right away!' WHERE entry=2000000142;
UPDATE db_script_string SET content_default='Hm... after dropping this off, I think I’ll head to that cheese shop for a snack.' WHERE entry=2000000143;
UPDATE db_script_string SET content_default='I should have a few extra coins from this sale. Maybe I’ll buy myself some lunch...' WHERE entry=2000000144;
UPDATE db_script_string SET content_default='Hey Harlan. Here’s a load of knitted cloth for you.' WHERE entry=2000000145;
UPDATE db_script_string SET content_default='Oomph! Here’s a load of supplies. It must be selling fast!' WHERE entry=2000000146;
UPDATE db_script_string SET content_default='Ah yes, and promptly delivered. As always, it’s a pleasure doing business with you, Corbett.' WHERE entry=2000000147;
UPDATE db_script_string SET content_default='Ahh, much appreciated, Corbett. We’ll get these on the racks immediately.' WHERE entry=2000000148;
UPDATE db_script_string SET content_default='Glad to see you’re doing so well, Harlan. And I hope to see you again soon?' WHERE entry=2000000149;
UPDATE db_script_string SET content_default='Well, I am off than. Take care, Harlan!' WHERE entry=2000000150;
UPDATE db_script_string SET content_default='Now for that snack...' WHERE entry=2000000151;
UPDATE db_script_string SET content_default='Hullo, Trias clan! A ball of your smoked mozzarella, if you please!' WHERE entry=2000000152;
UPDATE db_script_string SET content_default='Good day. Elling! Hullo Elaine! Let me have a wheel of blue cheese, eh?' WHERE entry=2000000153;
UPDATE db_script_string SET content_default='Good day, Corbett. Here’s your cheese, fresh made this morning! And how are things at your shop?' WHERE entry=2000000154;
UPDATE db_script_string SET content_default='Hi Corbett! Here, you go! I trust business is faring well at your clothier shop...?' WHERE entry=2000000155;
UPDATE db_script_string SET content_default='Yes ma’am, business is brisk!' WHERE entry=2000000156;
UPDATE db_script_string SET content_default='Thanks for the cheese!' WHERE entry=2000000157;
UPDATE db_script_string SET content_default='Time to get back to the shop...' WHERE entry=2000000158;
UPDATE db_script_string SET content_default='I’m back!' WHERE entry=2000000159;
UPDATE db_script_string SET content_default='Ma reth bromo zoln kilagrin dra ma zoern tu ko fraht ka tadrom Ma krin drinor zaln dirnor Ma krin kan aasrugel korsul' WHERE entry=2000000160;
UPDATE db_script_string SET content_default='ROARRRRR!!' WHERE entry=2000000161;
UPDATE db_script_string SET content_default='DARKSHIRE... I HUNGER!!' WHERE entry=2000000162;
UPDATE db_script_string SET content_default='I said GOOD DAY!' WHERE entry=2000000163;
UPDATE db_script_string SET content_default='My sword Archeus served me well in life, but as at last my spirit may pass from the unhappy existence, I need it no longer.' WHERE entry=2000000164;
UPDATE db_script_string SET content_default='I shall cling to the love of my daughter and hope that I will find forgiveness under the Light for my sins.' WHERE entry=2000000165;
UPDATE db_script_string SET content_default='OH NOES! Da king is dead! Uh... hail to da new king! Yeah!' WHERE entry=2000000166;
UPDATE db_script_string SET content_default='Yar, he’s dead all right. That makes you da new king... well, all of you! Gordok is yours now, boss! You should talk to me so you can learn everything there is about being da king! I was... is his assistant! Yeah, that’s why I’m called da crafty one!' WHERE entry=2000000167;
UPDATE db_script_string SET content_default='%s stares to the northwest and lets out a long, drawn out howl.' WHERE entry=2000000168;
UPDATE db_script_string SET content_default='%s lets forth a mighty howl.' WHERE entry=2000000169;
UPDATE db_script_string SET content_default='By your command!' WHERE entry=2000000170;
UPDATE db_script_string SET content_default='Wait here, $N. Spybot will make Lescovar come out as soon as possible. Be ready! Attack only after you’ve overheard their conversation.' WHERE entry=2000000171;
UPDATE db_script_string SET content_default='Good day to you both. I would speak to Lord Lescovar.' WHERE entry=2000000172;
UPDATE db_script_string SET content_default='Of course. He awaits you in the library.' WHERE entry=2000000173;
UPDATE db_script_string SET content_default='Thank you. The Light be with you both.' WHERE entry=2000000174;
UPDATE db_script_string SET content_default='Milord, your guest has arrived. He awaits your presence.' WHERE entry=2000000175;
UPDATE db_script_string SET content_default='Ah, thank you kindly. I will leave you to the library while I tend to this small matter.' WHERE entry=2000000176;
UPDATE db_script_string SET content_default='I shall use this time wisely, milord. Thank you.' WHERE entry=2000000177;
UPDATE db_script_string SET content_default='It’s time for my meditation, leave me.' WHERE entry=2000000178;
UPDATE db_script_string SET content_default='Yes, sir!' WHERE entry=2000000179;
UPDATE db_script_string SET content_default='%s waits for the guards to be out of sight.' WHERE entry=2000000180;
UPDATE db_script_string SET content_default='There you are. What news from Westfall?' WHERE entry=2000000181;
UPDATE db_script_string SET content_default='VanCleef sends word that the plans are underway. But he’s heard rumors about someone snooping about.' WHERE entry=2000000182;
UPDATE db_script_string SET content_default='Hmm, it could be that meddler Shaw. I will see what I can discover. Be off with you. I’ll contact you again soon.' WHERE entry=2000000183;
UPDATE db_script_string SET content_default='Very well. I will return then.' WHERE entry=2000000184;
UPDATE db_script_string SET content_default='That’s it! That’s what you were waiting for! KILL THEM!' WHERE entry=2000000185;
UPDATE db_script_string SET content_default='Defend yourself, fool!' WHERE entry=2000000186;
UPDATE db_script_string SET content_default='The abomination has overrun the Night Watch camp! Quickly, we must intercept it before it reaches town!' WHERE entry=2000000187;
UPDATE db_script_string SET content_default='The beast is slain! All is well in Darkshire.' WHERE entry=2000000188;
UPDATE db_script_string SET content_default='Quillboar scraps! These should do the trick. Fish love Quillboar.' WHERE entry=2000000189;
UPDATE db_script_string SET content_default='Caught one! I’ll see if any of the guards are hungry. Come on Fang!' WHERE entry=2000000190;
UPDATE db_script_string SET content_default='I caught a fish if you are hungry...' WHERE entry=2000000191;
UPDATE db_script_string SET content_default='A nice catch it is at that! You bring honor to the Horde boy, We thank you!' WHERE entry=2000000192;
UPDATE db_script_string SET content_default='As you wish...' WHERE entry=2000000195;
UPDATE db_script_string SET content_default='I very much doubt that he will have anything to say, stranger...' WHERE entry=2000000196;
UPDATE db_script_string SET content_default='I personally didn’t mind him. It was the Prince who took exception to a high elf in his domain. Alas, I am not one to question the Prince. In his defense, he did not incinerate Master Winthalus immediately.' WHERE entry=2000000197;
UPDATE db_script_string SET content_default='We most definitely do not need any more attention drawn to us, stranger. Return to those that sent you in search of the lost master and tell them that nothing could be found. When this is done - and I will know when it is so - return and I shall reveal the secrets of the deceased.' WHERE entry=2000000198;
UPDATE db_script_string SET content_default='Athrikus came to us. He told us that he could save us from harm. He cast a spell upon us to protect us from harm.' WHERE entry=2000000202;
UPDATE db_script_string SET content_default='When the shaking stopped, his true motives were revealed. We were trapped, and he was slowly draining our powers.' WHERE entry=2000000203;
UPDATE db_script_string SET content_default='There were hundreds imprisoned by his spell. Now only a few remain in their prisons. He would speak to us sometimes.' WHERE entry=2000000204;
UPDATE db_script_string SET content_default='He worried that his power weakened, that soon even we last of his precious soulgems would fade and die.' WHERE entry=2000000205;
UPDATE db_script_string SET content_default='His lieutenant, Ilkurd Magthrull possesses a tome which might indicate the location of the remaining soulgems.' WHERE entry=2000000206;
UPDATE db_script_string SET content_default='%s sniffs the elixir then eagerly digs in!' WHERE entry=2000000207;
UPDATE db_script_string SET content_default='It has been a long time, Bethor, my friend.' WHERE entry=2000000208;
UPDATE db_script_string SET content_default='When time permits, we must speak at length.  For we have much to discuss.' WHERE entry=2000000209;
UPDATE db_script_string SET content_default='And thank you, $N.  Without your aid I may never have found my way to the Forsaken.' WHERE entry=2000000210;
UPDATE db_script_string SET content_default='Farewell, my friend.' WHERE entry=2000000211;
UPDATE db_script_string SET content_default='%s summons a messenger...' WHERE entry=2000000212;
UPDATE db_script_string SET content_default='Go, my servant. Send word of Stonetalon to Apothecary Zamah.' WHERE entry=2000000213;
UPDATE db_script_string SET content_default='%s gives message to Apothecary Zamah.' WHERE entry=2000000214;
UPDATE db_script_string SET content_default='Apothecary Zamah smiles.' WHERE entry=2000000215;
UPDATE db_script_string SET content_default='What? $N, you served me well, but...' WHERE entry=2000000234;
UPDATE db_script_string SET content_default='Why have you summoned me so soon? I haven’t yet reached my full power!' WHERE entry=2000000235;
UPDATE db_script_string SET content_default='No matter. You were a fool to help me, and now you will pay!' WHERE entry=2000000236;
UPDATE db_script_string SET content_default='Thank again, $n. Now I’ll just wait here until it’s safe to leave.' WHERE entry=2000000237;
UPDATE db_script_string SET content_default='The power of the Tear of the Moons is mine! Mine I say!' WHERE entry=2000000240;
UPDATE db_script_string SET content_default='Feegly the Exiled begins to rub the Tear of the Moons.' WHERE entry=2000000241;
UPDATE db_script_string SET content_default='Power! Glorious power!' WHERE entry=2000000242;
UPDATE db_script_string SET content_default='Feegly the Exiled begins to make strange grunting noises. The Tear of the Moons drops to the ground and shatters.' WHERE entry=2000000243;
UPDATE db_script_string SET content_default='Terenthis, Raene sent me to find you. The Sentinels are in need of help in Ashenvale.' WHERE entry=2000000260;
UPDATE db_script_string SET content_default='Hey Nagmara! How about a mug of Dark Iron Ale?' WHERE entry=2000000261;
UPDATE db_script_string SET content_default='Nagmara! Have any mutton left?' WHERE entry=2000000262;
UPDATE db_script_string SET content_default='Mistress, you tell Plugger that I want more of his ale. I can’t get enough!' WHERE entry=2000000263;
UPDATE db_script_string SET content_default='Hey Nag, how about you slice me off a piece of that...' WHERE entry=2000000264;
UPDATE db_script_string SET content_default='You got it!' WHERE entry=2000000265;
UPDATE db_script_string SET content_default='Coming right up!' WHERE entry=2000000266;
UPDATE db_script_string SET content_default='I’ll bring it right over, baby...' WHERE entry=2000000267;
UPDATE db_script_string SET content_default='Here’s a beacon, $N. Keep it to yourself, if you’re gonna find mutilated things that we need.' WHERE entry=2000000318;
UPDATE db_script_string SET content_default='Give to the charities who seek to help the victims of these hard times! Please.' WHERE entry=2000000349;
UPDATE db_script_string SET content_default='Don’t forget the orphans of Stormwind!' WHERE entry=2000000350;
UPDATE db_script_string SET content_default='Give of your hearts and your purses! Give to the children of Stormwind who have lost their parents.' WHERE entry=2000000351;
UPDATE db_script_string SET content_default='Help the children of Stormwind... victims of the war and plague!' WHERE entry=2000000352;
UPDATE db_script_string SET content_default='You will perish here. <Your mind fills with visions of chaos and destruction.>' WHERE entry=2000000353;
UPDATE db_script_string SET content_default='Leave this place. <The relic emits a white hot arc of flame. A memory has been gained: A lone Dark Iron dwarf is surrounded by seven corpses, kneeling before a monolith of flame.>' WHERE entry=2000000354;
UPDATE db_script_string SET content_default='Defiler... you will be punished for this incursion. <A symbol of flame radiates from the relic before it crumbles to the earth.>' WHERE entry=2000000355;
UPDATE db_script_string SET content_default='Help us, outsider. <The relic crumbles to dust. A vision of eight Dark Iron dwarves performing some sort of ritual fills your head.>' WHERE entry=2000000356;
UPDATE db_script_string SET content_default='Your existence is acknowledged. <The relic turns to dust. Your head throbs with newfound wisdom. Something evil lurks in the heart of the mountain.>' WHERE entry=2000000357;
UPDATE db_script_string SET content_default='Leave this place. <The relic emits a white hot arc of flame. A memory has been gained: A lone Dark Iron dwarf is surrounded by seven corpses, kneeling before a monolith of flame.>' WHERE entry=2000000358;
UPDATE db_script_string SET content_default='He cannot be defeated. <The relic burns to nothing. The memories it held are now your own. This city was destroyed by a being not of this world.>' WHERE entry=2000000359;
UPDATE db_script_string SET content_default='Do not taint these ruins, mortal. <You are engulfed in a blinding flash of light. A creature composed entirely of flame is the only thing you can remember seeing.>' WHERE entry=2000000360;
UPDATE db_script_string SET content_default='Come,  $N. The lake is around the bend.' WHERE entry=2000000375;
UPDATE db_script_string SET content_default='Stand near me,  $N. I will protect you should anything go wrong.' WHERE entry=2000000376;
UPDATE db_script_string SET content_default='Malfurion!' WHERE entry=2000000377;
UPDATE db_script_string SET content_default='Remulos,  old friend. It is good to see you once more. I knew the message would find its way to you - one way or another.' WHERE entry=2000000378;
UPDATE db_script_string SET content_default='It was shrouded in nightmares,  Malfurion. What is happening in the Dream? What could cause such atrocities?' WHERE entry=2000000379;
UPDATE db_script_string SET content_default='I fear for the worst,  old friend. Within the Dream we fight a new foe,  born of an ancient evil. Ysera’s noble brood has fallen victim to the old whisperings. It seems as if the Nightmare has broken through the realm to find a new host on Azeroth.' WHERE entry=2000000380;
UPDATE db_script_string SET content_default='I sensed as much,  Malfurion. Dark days loom ahead.' WHERE entry=2000000381;
UPDATE db_script_string SET content_default='Aye Remulos,  prepare the mortal races.' WHERE entry=2000000382;
UPDATE db_script_string SET content_default='You have been gone too long,  Malfurion. Peace between the Children of Azeroth has become tenuous at best. What of my father? Of your brother? Have you any news?' WHERE entry=2000000383;
UPDATE db_script_string SET content_default='Cenarius fights at my side. Illidan sits atop his throne in Outland - brooding. I’m afraid that the loss to Arthas proved to be his breaking point. Madness has embraced him,  Remulos. He replays the events in his mind a thousand times per day,  but in his mind,  he is the victor and Arthas is utterly defeated. He is too far gone,  old friend. I fear that the time may soon come that our bond is tested and it will not be as it was at the Well in Zin-Azshari. ' WHERE entry=2000000384;
UPDATE db_script_string SET content_default='Remulos,  I am being drawn back... Tyrande... send her my love... Tell her I am safe... Tell her... Tell her I will return... Farewell...' WHERE entry=2000000385;
UPDATE db_script_string SET content_default='Farewell,  old friend... Farewell...' WHERE entry=2000000386;
UPDATE db_script_string SET content_default='Let us return to the grove,  mortal.' WHERE entry=2000000387;
UPDATE db_script_string SET content_default='Hello, Selarin. I’m afraid I cannot help you at the moment, but perhaps some of the adventurers here in Auberdine can...' WHERE entry=2000000395;
UPDATE db_script_string SET content_default='Thank you, Terenthis. I shall remain here for as long as I can.' WHERE entry=2000000396;
UPDATE db_script_string SET content_default='Hopefully I can send a worthy few to help Ashenvale and the Sentinels.' WHERE entry=2000000397;
UPDATE db_script_string SET content_default='So sorry to leave a customer but we have places to go and people to swindle. We will be back sometime later today. Good-bye!' WHERE entry=2000000400;
UPDATE db_script_string SET content_default='I am looking for some bodyguards that would like to protect the Gizelton Caravan. We are stopped on the road east of Kormek’s Hut, north of Kolkar Centaur Village.' WHERE entry=2000000401;
UPDATE db_script_string SET content_default='Time for the Gizelton Caravan to head on out! We’ll be back soon but if you cannot wait, head north to Kormek’s Hut. We open shop in about an hour.' WHERE entry=2000000402;
UPDATE db_script_string SET content_default='This is Rigger Gizelton asking for assistance escorting my caravan past Mannoroc Coven. I’m on the road east of Shadowprey village.' WHERE entry=2000000403;
UPDATE db_script_string SET content_default='Stand Prepared! The naga won’t wait long to press their advantage once they know we’re alive.' WHERE entry=2000000466;
UPDATE db_script_string SET content_default='I will need to focus my energies onto this knife. By doing so, I should catch some of the stronger psychic impressions associated with it.' WHERE entry=2000000521;
UPDATE db_script_string SET content_default='I... I’ve seen enough I think... so very draining...' WHERE entry=2000000522;
UPDATE db_script_string SET content_default='A History... Hmmmm... Let me examine this for a moment.' WHERE entry=2000000523;
UPDATE db_script_string SET content_default='%s skims the pages of the book.' WHERE entry=2000000524;
UPDATE db_script_string SET content_default='Amazing! I think I have found it, $N.' WHERE entry=2000000525;
UPDATE db_script_string SET content_default='Glorious, indeed, Maltrake. It looks as if my plan worked perfectly. Wouldn’t you say so, mortal?' WHERE entry=2000000526;
UPDATE db_script_string SET content_default='%s lets loose a reptilian laugh... at least you think it’s a laugh.' WHERE entry=2000000527;
UPDATE db_script_string SET content_default='You would not have helped the legion of Blackrock had we just asked for your assistance, now would you?' WHERE entry=2000000528;
UPDATE db_script_string SET content_default='What will we do with them, master? They are of no use to us anymore.' WHERE entry=2000000529;
UPDATE db_script_string SET content_default='SILENCE FOOL!' WHERE entry=2000000530;
UPDATE db_script_string SET content_default='They will live of only to see the fruits of their labor: the destruction and chaos that will surely ensue as the legion of Blackrock invade the gorge.' WHERE entry=2000000531;
UPDATE db_script_string SET content_default='I leave you now, mortals. Alive and with these trinkets. Maltrake! Present them with the trinkets!' WHERE entry=2000000532;
UPDATE db_script_string SET content_default='Right away, master!' WHERE entry=2000000533;
UPDATE db_script_string SET content_default='%s begins to flap his massive wings faster. He is preparing for flight.' WHERE entry=2000000534;
UPDATE db_script_string SET content_default='Oh yes, the molt - do not lose it. There are those of my kin in the Burning Steppes that would craft items that only the molt of the black dragonflight could fortify.' WHERE entry=2000000535;
UPDATE db_script_string SET content_default='The legion of Blackrock comes, dwarflings! We shall scorch the earth and set fire to the heavens. None shall survive...' WHERE entry=2000000536;
UPDATE db_script_string SET content_default='Now, let’s see... If I am correct, then... Hmmm...' WHERE entry=2000000540;
UPDATE db_script_string SET content_default='Blue plus red... I predict...' WHERE entry=2000000541;
UPDATE db_script_string SET content_default='$N, that’s it! I have finally figured it out!' WHERE entry=2000000542;
UPDATE db_script_string SET content_default='Whoa! This is way more than what I bargained for, you’re on your own, Slim!' WHERE entry=2000000602;
UPDATE db_script_string SET content_default='%s loosens her grasp on the journal she had been clutching.' WHERE entry=2000000612;
UPDATE db_script_string SET content_default='Ready. Set. GO!' WHERE entry=2000000613;
UPDATE db_script_string SET content_default='HEY! No fair!' WHERE entry=2000000614;
UPDATE db_script_string SET content_default='I win!' WHERE entry=2000000615;
UPDATE db_script_string SET content_default='You cheated!' WHERE entry=2000000616;
UPDATE db_script_string SET content_default='Wanna race again? Best two out of three!' WHERE entry=2000000617;
UPDATE db_script_string SET content_default='%s wildly flips through the pages of a large tome.' WHERE entry=2000000786;
UPDATE db_script_string SET content_default='The sweet irony -- Stormwind forces cut down in defense of their city, only to rise and fight alongside the Brotherhood as instruments of destruction. ' WHERE entry=2000000787;
UPDATE db_script_string SET content_default='And should one die, two shall rise!' WHERE entry=2000000788;
UPDATE db_script_string SET content_default='%s shuffles through the books.' WHERE entry=2000000789;
UPDATE db_script_string SET content_default='Now where did I put the Venture Company formulations?' WHERE entry=2000000790;
UPDATE db_script_string SET content_default='Hey, Raven...' WHERE entry=2000000791;
UPDATE db_script_string SET content_default='Yea?' WHERE entry=2000000792;
UPDATE db_script_string SET content_default='Can we take a break? My feet are killing me and those ... those things down there are creeping me out.' WHERE entry=2000000793;
UPDATE db_script_string SET content_default='I dunno, Jill. If Klaven comes down while we’re slacking, we may end up as one of those things!' WHERE entry=2000000794;
UPDATE db_script_string SET content_default='Klaven doesn’t pay me enough to deal with those zombies, drones or whatever he calls ’em. I don’t know, Jill. If Klaven comes down while we’re slacking, we might end up as those things!' WHERE entry=2000000795;
UPDATE db_script_string SET content_default='*Sigh* You’re probably right, Raven. I’m going back on patrol....' WHERE entry=2000000796;
UPDATE db_script_string SET content_default='I thank you. $n. And my brother thanks you.' WHERE entry=2000000808;
UPDATE db_script_string SET content_default='Speak with me to hear my tale.' WHERE entry=2000000813;
UPDATE db_script_string SET content_default='Greetings, mortals! I have been activated by the Discs of Norgannon to assist you!' WHERE entry=2000000817;
UPDATE db_script_string SET content_default='The discs are now ready! Engage the Discs of Norgannon once again to retrieve them!' WHERE entry=2000000818;
UPDATE db_script_string SET content_default='Opus wants some Cuergo’s Gold... with worm.' WHERE entry=2000005001;
UPDATE db_script_string SET content_default='Bijou lost! SQUAWK! *cough' WHERE entry=2000005002;
UPDATE db_script_string SET content_default='Kibler is being investigated by G.E.T.A.' WHERE entry=2000005003;
UPDATE db_script_string SET content_default='Bijou knows where treasures are hidden.' WHERE entry=2000005004;
UPDATE db_script_string SET content_default='Dragons controlling orcs!? SQUAWK!' WHERE entry=2000005005;
UPDATE db_script_string SET content_default='They all go to the Spire but none never come back... just like Bijou.' WHERE entry=2000005006;
UPDATE db_script_string SET content_default='Ask Kibler about the treasure! SQUAWK!' WHERE entry=2000005007;
UPDATE db_script_string SET content_default='SQUAWK!! *cough* *cough* I need to quit smoking!' WHERE entry=2000005008;
UPDATE db_script_string SET content_default='Well done, soldiers! At ease!' WHERE entry=2000005009;
UPDATE db_script_string SET content_default='呵呵! 很乐意为你效劳!' WHERE entry=2000005010;
UPDATE db_script_string SET content_default='Yes right away momma!' WHERE entry=2000005011;
UPDATE db_script_string SET content_default='I thought we talked about this, Brogg. You can’t stay in this building. Sure, it can house you, but there’s no room for anyone else!' WHERE entry=2000005015;
UPDATE db_script_string SET content_default='Yes, we said you can stay here, but this building is our headquarters! All of our manuals and blueprints are stored here!' WHERE entry=2000005016;
UPDATE db_script_string SET content_default='I’m inclined to say they made ogres too big! I can see I’m not going to convince you to move now, but don’t think this is permanent!' WHERE entry=2000005017;
UPDATE db_script_string SET content_default='Ah, this must be him now... no?' WHERE entry=2000005018;
UPDATE db_script_string SET content_default='When you’re off duty, let’s go to the inn. I’ll buy a round and we can reminisce about the good old days.' WHERE entry=2000005021;
UPDATE db_script_string SET content_default='Wouldn’t you like to bring those days back? I have some friends who know just the way to do that.' WHERE entry=2000005022;
UPDATE db_script_string SET content_default='Every item that I have for sale I acquired myself. You have my personal guarantee of authenticity.' WHERE entry=2000005023;
UPDATE db_script_string SET content_default='它越来越远了!' WHERE entry=2000005024;
UPDATE db_script_string SET content_default='Prizes! Get your prizes right here! Get over here and turn in your Darkmoon Faire Prize Tickets for valuable prizes!' WHERE entry=2000005025;
UPDATE db_script_string SET content_default='Come speak with me, and what once was cloudy shall become crystal clear.' WHERE entry=2000005026;
UPDATE db_script_string SET content_default='The Lich King’s forces are building. It is imperative that our timetable supports his plans.' WHERE entry=2000005027;
UPDATE db_script_string SET content_default='Tomorrow we will begin training of our promising dragons, so don’t forget your chew toys.' WHERE entry=2000005028;
UPDATE db_script_string SET content_default='Our oldest clutch of dragons are still far from maturity, but with patience and study, we are confident the dragons will soon be ready.' WHERE entry=2000005029;
UPDATE db_script_string SET content_default='I come from the land down under... where women plague and men sunder.' WHERE entry=2000005031;
UPDATE db_script_string SET content_default='...And then the tauren said, "13 INCHES!"' WHERE entry=2000005032;
UPDATE db_script_string SET content_default='它越来越远了!' WHERE entry=2000005035;
UPDATE db_script_string SET content_default='爱哭鬼！爱哭鬼！' WHERE entry=2000005057;
UPDATE db_script_string SET content_default='宝宝想要她的多莉!' WHERE entry=2000005058;
UPDATE db_script_string SET content_default='我不知道你的洋娃娃会游泳！' WHERE entry=2000005059;
UPDATE db_script_string SET content_default='哈哈！我有贝齐！' WHERE entry=2000005060;
UPDATE db_script_string SET content_default='宝宝希望得到她的洋娃娃！' WHERE entry=2000005061;
UPDATE db_script_string SET content_default='我有你的洋娃娃！尼亚尼亚！' WHERE entry=2000005062;
UPDATE db_script_string SET content_default='爱哭鬼！爱哭鬼！' WHERE entry=2000005063;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005078;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005079;
UPDATE db_script_string SET content_default='不要伤害贝齐，你个小气鬼！' WHERE entry=2000005080;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005081;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005082;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005083;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005084;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005085;
UPDATE db_script_string SET content_default='不要伤害贝齐，你个小气鬼！' WHERE entry=2000005086;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005087;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005088;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005089;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005090;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005091;
UPDATE db_script_string SET content_default='不要伤害贝齐，你个小气鬼！' WHERE entry=2000005092;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005093;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005094;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005095;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005096;
UPDATE db_script_string SET content_default='把洋娃娃还给我！' WHERE entry=2000005097;
UPDATE db_script_string SET content_default='不要伤害贝齐，你个小气鬼！' WHERE entry=2000005098;
UPDATE db_script_string SET content_default='新鲜面包出售' WHERE entry=2000005099;
UPDATE db_script_string SET content_default='我能感觉到它的炙热。' WHERE entry=2000005100;
UPDATE db_script_string SET content_default='刚出炉的面包。您需要看看吗？' WHERE entry=2000005101;
UPDATE db_script_string SET content_default='我能感觉到它的炙热。' WHERE entry=2000005102;
UPDATE db_script_string SET content_default='Jack and Jill my wrinkled patoot! I do all the water luggin round here.' WHERE entry=2000005103;
UPDATE db_script_string SET content_default='Wheres the water Emma? Get the water Emma? Ifn it werent fer me that lot wouldnt know what water looks like.' WHERE entry=2000005104;
UPDATE db_script_string SET content_default='Of Course Im talking to myself. Only way to get a decent conversation in this city.' WHERE entry=2000005105;
UPDATE db_script_string SET content_default='As if I dont have better things to do in my old age than carry buckets of water.' WHERE entry=2000005106;
UPDATE db_script_string SET content_default='Seems like a hundred times a day I walk all the way to get more water. No respect for their elders I tell ya.' WHERE entry=2000005107;
UPDATE db_script_string SET content_default='Deja vu. For a moment I thought I was back home... before the plague...' WHERE entry=2000005108;
UPDATE db_script_string SET content_default='他们说，有时他可以变成乌鸦。' WHERE entry=2000005109;
UPDATE db_script_string SET content_default='他们说，有时他可以变成乌鸦。' WHERE entry=2000005110;
UPDATE db_script_string SET content_default='And then the rabbit just bit his head off... I swear.' WHERE entry=2000005111;
UPDATE db_script_string SET content_default='I swear, people have actualy seen them. Pandaren really do exist!!' WHERE entry=2000005112;
UPDATE db_script_string SET content_default='You know why Orcs eyes glow red? It’s because they drink blood!' WHERE entry=2000005113;
UPDATE db_script_string SET content_default='I dont think there’s any fish in these canals.' WHERE entry=2000005114;
UPDATE db_script_string SET content_default='And that’s how Lother killed thirty six orcs with his bare hands!' WHERE entry=2000005115;
UPDATE db_script_string SET content_default='额...这并不是一条鱼！' WHERE entry=2000005116;
UPDATE db_script_string SET content_default='I got worm guts on my shoes.' WHERE entry=2000005117;
UPDATE db_script_string SET content_default='我觉得我应该看看这些.' WHERE entry=2000005118;
UPDATE db_script_string SET content_default='额...这并不是一条鱼！' WHERE entry=2000005119;
UPDATE db_script_string SET content_default='我觉得我应该看看这些.' WHERE entry=2000005120;
UPDATE db_script_string SET content_default='我希望这是一条鱼！' WHERE entry=2000005121;
UPDATE db_script_string SET content_default='Worm goes on the hook, hook goes in the water, Fish is in the water, our fish.' WHERE entry=2000005122;
UPDATE db_script_string SET content_default='你能想象的到吗？' WHERE entry=2000005123;
UPDATE db_script_string SET content_default='真的吗？' WHERE entry=2000005124;
UPDATE db_script_string SET content_default='哇。' WHERE entry=2000005125;
UPDATE db_script_string SET content_default='我父亲说，这只是一个故事。' WHERE entry=2000005126;
UPDATE db_script_string SET content_default='真的吗？' WHERE entry=2000005127;
UPDATE db_script_string SET content_default='哇。' WHERE entry=2000005128;
UPDATE db_script_string SET content_default='真整齐.' WHERE entry=2000005129;
UPDATE db_script_string SET content_default='哇。' WHERE entry=2000005130;
UPDATE db_script_string SET content_default='真的吗？' WHERE entry=2000005131;
UPDATE db_script_string SET content_default='Look alive, dogs! We got an operation to run here!' WHERE entry=2000005132;
UPDATE db_script_string SET content_default='Here we have the Cathedral of Light, the center of spiritual enlightenment here in Stormwind.' WHERE entry=2000005134;
UPDATE db_script_string SET content_default='Yes, that is true. Paladins and Priests alike train their skills and research great truths behind the walls of the Cathedral.' WHERE entry=2000005135;
UPDATE db_script_string SET content_default='Children if you would please follow me, we will now be going to see the keep where King Anduin Wrynn himself sits on this throne.' WHERE entry=2000005136;
UPDATE db_script_string SET content_default='Here we have Stormwind Keep. Built upon the ruins of Stormwind Castle, which was destroyed by the Horde in the first Great War.' WHERE entry=2000005137;
UPDATE db_script_string SET content_default='When the Horde was shattered, men returned here and began to rebuild the once great city as a testament to our own survival.' WHERE entry=2000005138;
UPDATE db_script_string SET content_default='Yes, well...let’s head on to the monument dedicated to the heroes of the two Great Wars, the Valley of Heroes. Follow Me.' WHERE entry=2000005139;
UPDATE db_script_string SET content_default='Isn’t it amazing, children? All who enter the city must walk beneath the watchful eyes of the greatest heroes of our lands.' WHERE entry=2000005140;
UPDATE db_script_string SET content_default='Breathtaking. Children, when we return to the school, you will each give an oral report on one of these legendary people.' WHERE entry=2000005141;
UPDATE db_script_string SET content_default='Now, take another long look before we make our way to the Holy District and the great Cathedral of Light.' WHERE entry=2000005142;
UPDATE db_script_string SET content_default='把12个中心的焦点汇聚,以形成更多的魔法能量、多渠道增加必要的稳定性。' WHERE entry=2000005148;
UPDATE db_script_string SET content_default='至少我们不能来把它收拾干净。' WHERE entry=2000005149;
UPDATE db_script_string SET content_default='只有我们不遵循正确的初始化过程。' WHERE entry=2000005150;
UPDATE db_script_string SET content_default='虽然最终的能量将会消失,这可能会导致一个能量流,会让你头痛几个星期。' WHERE entry=2000005151;
UPDATE db_script_string SET content_default='只有我们不遵循正确的初始化过程。' WHERE entry=2000005152;
UPDATE db_script_string SET content_default='只有我们不遵循正确的初始化过程。' WHERE entry=2000005153;
UPDATE db_script_string SET content_default='至少我们不能来把它收拾干净。' WHERE entry=2000005154;
UPDATE db_script_string SET content_default='但是,这不是他娴熟的神奇配方引起的初值问题?' WHERE entry=2000005155;
UPDATE db_script_string SET content_default='我想这才能行得通,如果我们有二十人赶出它。' WHERE entry=2000005156;
UPDATE db_script_string SET content_default='但是由此产生的多普勒频移是发送的魔法反馈流吗?' WHERE entry=2000005157;
UPDATE db_script_string SET content_default='对齐时碰撞与积极能量带负电荷的能量,他们不排斥彼此。' WHERE entry=2000005158;
UPDATE db_script_string SET content_default='那不平衡的神奇焦点,显然,和一种反向的振动有关。' WHERE entry=2000005159;
UPDATE db_script_string SET content_default='"但那不意味着要穿越小溪吗?那真不好办了?"' WHERE entry=2000005160;
UPDATE db_script_string SET content_default='为什么我们不能只改变数组通量差异？' WHERE entry=2000005161;
UPDATE db_script_string SET content_default='但是，这不正是造成神奇公式与Adept Syleria初期问题的原因吗？' WHERE entry=2000005162;
UPDATE db_script_string SET content_default='我想不会，我需要再被炸上天了。' WHERE entry=2000005163;
UPDATE db_script_string SET content_default='主人说，扭曲而引起正面能量交流电流向实际上就是建立一个更加稳定的流量。' WHERE entry=2000005164;
UPDATE db_script_string SET content_default='但是，那不就意味着要穿过风暴？这真的很不好？' WHERE entry=2000005165;
UPDATE db_script_string SET content_default='但是，这不正是造成神奇公式与Adept Syleria初期问题的原因吗？' WHERE entry=2000005166;
UPDATE db_script_string SET content_default='这是真的，骑士坐骑在这里？' WHERE entry=2000005167;
UPDATE db_script_string SET content_default='我们为什么要学习这些莫名其妙的东西？?' WHERE entry=2000005168;
UPDATE db_script_string SET content_default='如果我们扭转这一本质流动也许我们能改变极性。' WHERE entry=2000005169;
UPDATE db_script_string SET content_default='如果我们用三个重点在Tyrean模式?应该能解决它。' WHERE entry=2000005170;
UPDATE db_script_string SET content_default='哇,这一切为了一份爱情药剂。希望他是值得的。' WHERE entry=2000005171;
UPDATE db_script_string SET content_default='如果我们使用适当的顺序，应该没问题。在我们开始前将会带走一些重要的研究。' WHERE entry=2000005172;
UPDATE db_script_string SET content_default='传送门转移的效果。在这里,如果你施放一个有约束力的法术，你就会把地方具体化。' WHERE entry=2000005173;
UPDATE db_script_string SET content_default='Hello, Charys. I have my list, could you get me all of that, especially the last ingredient.' WHERE entry=2000005180;
UPDATE db_script_string SET content_default='Sure Paige. Just be gentle.' WHERE entry=2000005181;
UPDATE db_script_string SET content_default='Thanks, Charys. C’mon Paige, sweetie.' WHERE entry=2000005182;
UPDATE db_script_string SET content_default='Mommy? Can I pet Fizzles?' WHERE entry=2000005183;
UPDATE db_script_string SET content_default='Fizzles used to be a great wizard. But got turned into a rabbit when one of his spells went bad.' WHERE entry=2000005184;
UPDATE db_script_string SET content_default='学习魔法强化你的大脑?放松!' WHERE entry=2000005185;
UPDATE db_script_string SET content_default='在暴风城最好的饮料!' WHERE entry=2000005186;
UPDATE db_script_string SET content_default='蓝色的隐居者在上头。在那里所有的人都知道你的名字!' WHERE entry=2000005187;
UPDATE db_script_string SET content_default='感觉忧郁?快点下来和蓝色的隐居者过一段美好时光!' WHERE entry=2000005188;
UPDATE db_script_string SET content_default='在暴风城最好的饮料!' WHERE entry=2000005189;
UPDATE db_script_string SET content_default='学习魔法强化你的大脑?放松!' WHERE entry=2000005190;
UPDATE db_script_string SET content_default='问我你如何才能得到从蓝色隐居者手中获得一杯免费饮料!' WHERE entry=2000005191;
UPDATE db_script_string SET content_default='蓝色的隐居者在上头。在那里所有的人都知道你的名字!' WHERE entry=2000005192;
UPDATE db_script_string SET content_default='"来自于蓝色隐居者的免费饮料!来自于蓝色隐居者的免费饮料!"' WHERE entry=2000005193;
UPDATE db_script_string SET content_default='感觉忧郁?快点下来和蓝色的隐居者过一段美好时光!' WHERE entry=2000005194;
UPDATE db_script_string SET content_default='学习魔法强化你的大脑?放松!' WHERE entry=2000005195;
UPDATE db_script_string SET content_default='在暴风城最好的饮料!' WHERE entry=2000005196;
UPDATE db_script_string SET content_default='问我你如何才能得到从蓝色隐居者手中获得一杯免费饮料!' WHERE entry=2000005197;
UPDATE db_script_string SET content_default='蓝色的隐居者在上头。在那里所有的人都知道你的名字!' WHERE entry=2000005198;
UPDATE db_script_string SET content_default='在暴风城最好的饮料!' WHERE entry=2000005199;
UPDATE db_script_string SET content_default='Hey! Do you like the sauce? The sauce is good, no?' WHERE entry=2000005214;
UPDATE db_script_string SET content_default='The what-bringer? Oh, ASHbringer? Never heard of it... What? Stop bothering me!' WHERE entry=2000005215;
UPDATE db_script_string SET content_default='Hey, someone help me catch this thing!' WHERE entry=2000005218;
UPDATE db_script_string SET content_default='I should have taken the translucent pill.' WHERE entry=2000005228;
UPDATE db_script_string SET content_default='I don’t get paid enough for this bull excrement!' WHERE entry=2000005229;
UPDATE db_script_string SET content_default='Just sit right back and you’ll hear a ta... *hic* a tai... *hic* a taiii *hic* Damnit!' WHERE entry=2000005233;
UPDATE db_script_string SET content_default='I can’t take these taxes! F.I.C.A. me? F.I.C.A. YOU!' WHERE entry=2000005234;
UPDATE db_script_string SET content_default='Time for my patrol. I’ll be back shortly.' WHERE entry=2000005235;
UPDATE db_script_string SET content_default='People of the Horde, citizens of Orgrimmar, come, gather round and celebrate heroes of the Horde. On this day, $N, under the auspices of our glorious Warchief, laid a mortal blow against the Black Dragonflight. The brood mother, Onyxia, has been slain!' WHERE entry=2000005236;
UPDATE db_script_string SET content_default='这些大火已经燃烧好几年了。巨魔不寻常的奉献。' WHERE entry=2000005237;
UPDATE db_script_string SET content_default='奇怪…这些马赛克不像任何已知的巨魔的传统。' WHERE entry=2000005238;
UPDATE db_script_string SET content_default='是的,是的,我确信这代表了铸锭的实体。令人着迷。' WHERE entry=2000005239;
UPDATE db_script_string SET content_default='通过研究显示其能学习一种文化。' WHERE entry=2000005240;
UPDATE db_script_string SET content_default='呃。聚集的头发,羽毛、残骨,部分烧毁的资料-也许还有服装?' WHERE entry=2000005241;
UPDATE db_script_string SET content_default='What... what is this? Could this by the answer to my prayers? Elune has granted me a weapon -- this scythe -- to defeat the demons.' WHERE entry=2000005242;
UPDATE db_script_string SET content_default='I have failed... I have failed in my duty... failed my people... The worgen run rampant, and the Scythe of my goddess is lost.' WHERE entry=2000005243;
UPDATE db_script_string SET content_default='This evil I have unleashed... In whose hand does the power my goddess granted to me now lie... By whose hand is it directed?' WHERE entry=2000005244;
UPDATE db_script_string SET content_default='The Stonewrought Dam has been saved! Three cheers for $N!' WHERE entry=2000005300;
UPDATE db_script_string SET content_default='The boss wants all hands on high alert. The rusty anchor sinks tonight.' WHERE entry=2000005301;
UPDATE db_script_string SET content_default='Stonemasons. . .errr. . Defias be warned:  The rusty anchor sinks tonight.' WHERE entry=2000005302;
UPDATE db_script_string SET content_default='begins to manipulate the Stone of Relu over the two fossils.' WHERE entry=2000005303;
UPDATE db_script_string SET content_default='By the stars! A spirit has been summoned!' WHERE entry=2000005304;
UPDATE db_script_string SET content_default='Who hath summoned forth Aman?' WHERE entry=2000005305;
UPDATE db_script_string SET content_default='Ah, I see you toil with relics of the past.' WHERE entry=2000005306;
UPDATE db_script_string SET content_default='Be warned that even your creators are fallible.' WHERE entry=2000005307;
UPDATE db_script_string SET content_default='Digging too deep into your past might bring an abrupt end to your future.' WHERE entry=2000005308;
UPDATE db_script_string SET content_default='dissipates before your eyes.' WHERE entry=2000005309;
UPDATE db_script_string SET content_default='It’s a mystery of the past indeed! But a key to our future!' WHERE entry=2000005310;
UPDATE db_script_string SET content_default='My, that Black Claw stout packs quite a punch!' WHERE entry=2000005311;
UPDATE db_script_string SET content_default='I feel... dizzy. It’s so hot... in... here...' WHERE entry=2000005312;
UPDATE db_script_string SET content_default='What does allergic mean anyway? And what does it have to do with either of my kitties?' WHERE entry=2000005314;
UPDATE db_script_string SET content_default='I can’t believe dad won’t let me keep your sister.' WHERE entry=2000005315;
UPDATE db_script_string SET content_default='Don’t worry, I’ll find a good home for ya.' WHERE entry=2000005316;
UPDATE db_script_string SET content_default='Can anyone give my adorable, extra little kitty a home?' WHERE entry=2000005317;
UPDATE db_script_string SET content_default='Will someone please give my little kitten a good home?' WHERE entry=2000005318;
UPDATE db_script_string SET content_default='Kitten for sale, looking for a good home.' WHERE entry=2000005319;
UPDATE db_script_string SET content_default='Can I go collect more rocks for my necklace, Papa?' WHERE entry=2000005320;
UPDATE db_script_string SET content_default='Yes you may, Okla. But do not stray too far from home.' WHERE entry=2000005321;
UPDATE db_script_string SET content_default='Dabu! I will be careful Papa!' WHERE entry=2000005322;
UPDATE db_script_string SET content_default='Ooohh... This rock is nice and colorful. Let’s see if I can find more like it...' WHERE entry=2000005323;
UPDATE db_script_string SET content_default='Hmm... That rock is nice, but too small.' WHERE entry=2000005324;
UPDATE db_script_string SET content_default='This is a shiney rock. I’ll put it in my bucket. Ok, I just need a few more...' WHERE entry=2000005325;
UPDATE db_script_string SET content_default='I bet my friend Gruk would like this rock for the spear he is making! It’s very sharp... I hope he likes it.' WHERE entry=2000005326;
UPDATE db_script_string SET content_default='There... That should be enough rocks to make a necklace. I should probably get home now anyway.' WHERE entry=2000005327;
UPDATE db_script_string SET content_default='Anaya...? Do my eyes deceive me? Is it really you?' WHERE entry=2000005336;
UPDATE db_script_string SET content_default='The ages have been cruel to you and I, my love, but be assured, it is, and at long last we are reunited.' WHERE entry=2000005337;
UPDATE db_script_string SET content_default='That the fates should be so cruel as to permit us only this after a thousand years apart...' WHERE entry=2000005338;
UPDATE db_script_string SET content_default='Do you hate me, my love? That I was forced to destroy your living form, that your spirit be released from unhappy bondage.' WHERE entry=2000005339;
UPDATE db_script_string SET content_default='Let it not trouble your heart, beloved. You have freed me from slavery, and for that I love you all the more.' WHERE entry=2000005340;
UPDATE db_script_string SET content_default='Sadly, even this must be cut short... The ties that bind me to this world weaken, and pull me away...' WHERE entry=2000005341;
UPDATE db_script_string SET content_default='No! Anaya... Anaya! Don’t leave me! Please...' WHERE entry=2000005342;
UPDATE db_script_string SET content_default='Farewell, Cerellean, until we are joined once again...' WHERE entry=2000005343;
UPDATE db_script_string SET content_default='’s soft voice trails away into the mists. "Know that I love you always..."' WHERE entry=2000005344;
UPDATE db_script_string SET content_default='How, my love? How will I find the strength to face the ages of the world without you by my side...' WHERE entry=2000005345;
UPDATE db_script_string SET content_default='Thank you, $N. And luck to you.' WHERE entry=2000005346;
UPDATE db_script_string SET content_default='Cliffspring Falls lies along the mountains to the east and north.' WHERE entry=2000005347;
UPDATE db_script_string SET content_default='%s dusts the base of the artifact.' WHERE entry=2000005348;
UPDATE db_script_string SET content_default='%s meticulously examines the large vase.' WHERE entry=2000005349;
UPDATE db_script_string SET content_default='Poor Dorius. If I ever get my hands on those Dark Irons, so help me...' WHERE entry=2000005350;
UPDATE db_script_string SET content_default='What was that noise? It sounded like a roar.' WHERE entry=2000005384;
UPDATE db_script_string SET content_default='Grimclaw roars at Terenthis to get his attention.' WHERE entry=2000005385;
UPDATE db_script_string SET content_default='Grimclaw?! Easy there, my friend... where is your master Volcor?' WHERE entry=2000005386;
UPDATE db_script_string SET content_default='Grimclaw begins to moan and roar at Terenthis while stomping his paws on the ground.' WHERE entry=2000005387;
UPDATE db_script_string SET content_default='Whoa, whoa there, my friend. One moment...' WHERE entry=2000005388;
UPDATE db_script_string SET content_default='Terenthis begins to cast a spell on Grimclaw.' WHERE entry=2000005389;
UPDATE db_script_string SET content_default='There... that should help. Now, tell me what’s happened, Grimclaw.' WHERE entry=2000005390;
UPDATE db_script_string SET content_default='Grimclaw roars at Terenthis more, but this time the druid seems to understand the bear.' WHERE entry=2000005391;
UPDATE db_script_string SET content_default='I understand, my friend. I shall find someone to help your master. Go back to him now, or at least stay close.' WHERE entry=2000005392;
UPDATE db_script_string SET content_default='Grimclaw roars in acknowledgement at Terenthis.' WHERE entry=2000005393;
UPDATE db_script_string SET content_default='If you have the time, Grimclaw and his master Volcor could use your help. If you’re interested, speak with me further...' WHERE entry=2000005394;
UPDATE db_script_string SET content_default='Oh man, I thought I was dead for sure. Ugh... still dizzy...' WHERE entry=2000005395;
UPDATE db_script_string SET content_default='I can get back to the Stronghold on my own, I think. Now that you bought me some time, I should be able to stealth out of here. Who ever you are... thank you. May Elune bless you always!' WHERE entry=2000005396;
UPDATE db_script_string SET content_default='If you want the key, you’ll have to catch me!' WHERE entry=2000005460;
UPDATE db_script_string SET content_default='Chase me if you dare! I run without a care!' WHERE entry=2000005461;
UPDATE db_script_string SET content_default='Why would you ever want to harm me!? Come. Friends we can be!' WHERE entry=2000005462;
UPDATE db_script_string SET content_default='DIE?! You make Pusillin cry!' WHERE entry=2000005463;
UPDATE db_script_string SET content_default='Say hello to my little friends!' WHERE entry=2000005464;
UPDATE db_script_string SET content_default='$N, please take a look at the sample of the Vylestem vine that I took from the caverns, so that you know what to look for...' WHERE entry=2000005465;
UPDATE db_script_string SET content_default='Oh no! Here they come!' WHERE entry=2000005547;
UPDATE db_script_string SET content_default='Ok, here I go!' WHERE entry=2000005548;
UPDATE db_script_string SET content_default='What? How dare you say that to me?!?' WHERE entry=2000005549;
UPDATE db_script_string SET content_default='After all we’ve been through? Well, I didn’t like you anyway!!' WHERE entry=2000005550;
UPDATE db_script_string SET content_default='I’m out of here!' WHERE entry=2000005551;
UPDATE db_script_string SET content_default='Who dares step into my domain! Come! Come, and be consumed!' WHERE entry=2000005552;
UPDATE db_script_string SET content_default='Let’s move forward!' WHERE entry=2000005553;
UPDATE db_script_string SET content_default='None may steal the secrets of the Makers!' WHERE entry=2000005555;
UPDATE db_script_string SET content_default='Search this rubble.' WHERE entry=2000005556;
UPDATE db_script_string SET content_default='Find me something good, you dogs!' WHERE entry=2000005557;
UPDATE db_script_string SET content_default='No! Get away from me! Help!!' WHERE entry=2000005626;
UPDATE db_script_string SET content_default='Wait... did you hear that? Something approaches from the west!' WHERE entry=2000005627;
UPDATE db_script_string SET content_default='I’ve run out of arrows! I’m afraid if any more come you will need to take them on by yourself my friend.' WHERE entry=2000005628;
UPDATE db_script_string SET content_default='Praise Elune! I don’t know if I could have survived the day without you, friend.' WHERE entry=2000005629;
UPDATE db_script_string SET content_default='My legs feels much better now, the remedy must be working. If you will excuse me, I must go report to my superiors about what has transpired here.' WHERE entry=2000005630;
UPDATE db_script_string SET content_default='Please speak with Sentinel Onaeya at Maestra’s Post in Ashenvale, she will see to it that you are properly rewarded for your bravery this day.' WHERE entry=2000005631;
UPDATE db_script_string SET content_default='All hands to battle stations! Naga incoming!' WHERE entry=2000005632;
UPDATE db_script_string SET content_default='If we can just hold them now, I am sure we will be in the clear.' WHERE entry=2000005633;
UPDATE db_script_string SET content_default='You wish to learn of the stone? Follow me.' WHERE entry=2000005646;
UPDATE db_script_string SET content_default='For so long I have drifted in my cursed form. You have freed me... Your hard work shall be repaid.' WHERE entry=2000005647;
UPDATE db_script_string SET content_default='Please do as I instruct you, $N.' WHERE entry=2000005648;
UPDATE db_script_string SET content_default='Read this tome I have placed before you, and speak the words aloud.' WHERE entry=2000005649;
UPDATE db_script_string SET content_default='%s begins to channel his energy, focusing on the stone.' WHERE entry=2000005650;
UPDATE db_script_string SET content_default='Together, the two parts shall become one, once again.' WHERE entry=2000005651;
UPDATE db_script_string SET content_default='Shal myrinan ishnu daldorah...' WHERE entry=2000005652;
UPDATE db_script_string SET content_default='My scepter will once again become whole!' WHERE entry=2000005653;
UPDATE db_script_string SET content_default='%s picks the orc target...' WHERE entry=2000005730;
UPDATE db_script_string SET content_default='%s misses...' WHERE entry=2000005731;
UPDATE db_script_string SET content_default='%s takes a more careful aim...' WHERE entry=2000005732;
UPDATE db_script_string SET content_default='%s misses again...' WHERE entry=2000005733;
UPDATE db_script_string SET content_default='%s casually points at the orc target...' WHERE entry=2000005734;
UPDATE db_script_string SET content_default='%s hits!' WHERE entry=2000005735;
UPDATE db_script_string SET content_default='%s takes aim at the bottles...' WHERE entry=2000005736;
UPDATE db_script_string SET content_default='%s misses...' WHERE entry=2000005737;
UPDATE db_script_string SET content_default='%s takes aim at the bottles again...' WHERE entry=2000005738;
UPDATE db_script_string SET content_default='%s misses again...' WHERE entry=2000005739;
UPDATE db_script_string SET content_default='%s quickly shoots the middle target dead center...' WHERE entry=2000005740;
UPDATE db_script_string SET content_default='%s then takes aim at the bottles...' WHERE entry=2000005741;
UPDATE db_script_string SET content_default='%s only hits the side of the box!' WHERE entry=2000005742;
UPDATE db_script_string SET content_default='%s quickly shoots the orc dummy...' WHERE entry=2000005743;
UPDATE db_script_string SET content_default='%s turns to the paper target...' WHERE entry=2000005744;
UPDATE db_script_string SET content_default='%s shoots from the hip at the bottles...' WHERE entry=2000005745;
UPDATE db_script_string SET content_default='Now let’s try it...' WHERE entry=2000005752;
UPDATE db_script_string SET content_default='Ugh! That’s terrible!' WHERE entry=2000005753;
UPDATE db_script_string SET content_default='I am going to practice and become a warrior like my father!' WHERE entry=2000005767;
UPDATE db_script_string SET content_default='Now to find an unsuspecting Harpy!' WHERE entry=2000005768;
UPDATE db_script_string SET content_default='There’s one! For the Horde!' WHERE entry=2000005769;
UPDATE db_script_string SET content_default='Take that you mangy Harpy! Hyaa!' WHERE entry=2000005770;
UPDATE db_script_string SET content_default='You can’t get away from a warrior of the Horde! Take that! And that!' WHERE entry=2000005771;
UPDATE db_script_string SET content_default='Now go back home where you belong!' WHERE entry=2000005772;
UPDATE db_script_string SET content_default='Aaahhh... Another glorious victory for The Horde!' WHERE entry=2000005773;
UPDATE db_script_string SET content_default='Mogg, get inside. It is not safe out there while your father is gone.' WHERE entry=2000005774;
UPDATE db_script_string SET content_default='When is pappa comming back from the fights in Warsong? It has been so long...' WHERE entry=2000005775;
UPDATE db_script_string SET content_default='$N, I’ll make sure all my friends in the Cartel know that you’ve saved my life today. Here - I’m going to need to be able to travel light, so please help yourself to my cache of tailoring and leatherworking supplies! Thanks again - see ya!' WHERE entry=2000005776;
UPDATE db_script_string SET content_default='%s listens to Sigilbringer’s report...' WHERE entry=2000005777;
UPDATE db_script_string SET content_default='What?? The Burning Blade is spreading! We must investigate!' WHERE entry=2000005778;
UPDATE db_script_string SET content_default='%s smashes the dead, twisted claw. ' WHERE entry=2000005779;
UPDATE db_script_string SET content_default='We must hurry.' WHERE entry=2000005780;
UPDATE db_script_string SET content_default='Spirits of the forest come forth and heed nature’s call!' WHERE entry=2000005781;
UPDATE db_script_string SET content_default='Spirits of the forest, you are needed! Make haste to the Charred Vale!' WHERE entry=2000005782;
UPDATE db_script_string SET content_default='%s enters a trance...' WHERE entry=2000005800;
UPDATE db_script_string SET content_default='%s I have created the totem. You, %n, must cleanse the well.' WHERE entry=2000005801;
UPDATE db_script_string SET content_default='Zarlman Two-Moons begins chanting as he mixes the well stones and ambercom before the Tribal Fire.' WHERE entry=2000005802;
UPDATE db_script_string SET content_default='The Water of the Seers is ready for your consumption, $N.' WHERE entry=2000005803;