UPDATE game_event SET description='仲夏火焰节' WHERE eventEntry=1;
UPDATE game_event SET description='冬幕节' WHERE eventEntry=2;
UPDATE game_event SET description='焚木村 - 狼人的诅咒' WHERE eventEntry=3;
UPDATE game_event SET description='暗月马戏团（艾尔文森林）' WHERE eventEntry=4;
UPDATE game_event SET description='暗月马戏团（莫高雷）' WHERE eventEntry=5;
UPDATE game_event SET description='新年' WHERE eventEntry=6;
UPDATE game_event SET description='春节' WHERE eventEntry=7;
UPDATE game_event SET description='情人节' WHERE eventEntry=8;
UPDATE game_event SET description='复活节' WHERE eventEntry=9;
UPDATE game_event SET description='儿童周' WHERE eventEntry=10;
UPDATE game_event SET description='万圣节' WHERE eventEntry=12;
UPDATE game_event SET description='元素入侵' WHERE eventEntry=13;
UPDATE game_event SET description='钓鱼大赛 开始' WHERE eventEntry=14;
UPDATE game_event SET description='钓鱼大赛' WHERE eventEntry=15;
UPDATE game_event SET description='古拉巴什竞技场战斗' WHERE eventEntry=16;
UPDATE game_event SET description='天灾入侵' WHERE eventEntry=17;
UPDATE game_event SET description='战斗的召唤：奥特兰克山谷' WHERE eventEntry=18;
UPDATE game_event SET description='战斗的召唤：战歌峡谷' WHERE eventEntry=19;
UPDATE game_event SET description='战斗的召唤：阿拉希盆地' WHERE eventEntry=20;
UPDATE game_event SET description='冬幕节:礼物' WHERE eventEntry=21;
UPDATE game_event SET description='安其拉之战' WHERE eventEntry=22;
UPDATE game_event SET description='暗月马戏团搭建（艾尔文森林）' WHERE eventEntry=23;
UPDATE game_event SET description='夜幕' WHERE eventEntry=27;
UPDATE game_event SET description='疯狂之缘，格里雷克' WHERE eventEntry=29;
UPDATE game_event SET description='疯狂之缘，哈拉扎丝' WHERE eventEntry=30;
UPDATE game_event SET description='疯狂之缘，瑞纳卡奇' WHERE eventEntry=31;
UPDATE game_event SET description='疯狂之缘，乌苏雷' WHERE eventEntry=32;
UPDATE game_event SET description='收获节' WHERE eventEntry=33;
UPDATE game_event SET description='钓鱼大赛' WHERE eventEntry=34;
UPDATE game_event SET description='冬季钓鱼大赛' WHERE eventEntry=35;
UPDATE game_event SET description='夏季钓鱼大赛' WHERE eventEntry=36;
UPDATE game_event SET description='暴风城 - 监狱越狱' WHERE eventEntry=61;