UPDATE game_event SET description='仲夏焰火节 ' WHERE eventEntry=1;
UPDATE game_event SET description='冬幕节 ' WHERE eventEntry=2;
UPDATE game_event SET description='暗月马戏团（泰罗卡森林） ' WHERE eventEntry=3;
UPDATE game_event SET description='暗月马戏团（艾尔文森林） ' WHERE eventEntry=4;
UPDATE game_event SET description='暗月马戏团（莫高雷） ' WHERE eventEntry=5;
UPDATE game_event SET description='除夕' WHERE eventEntry=6;
UPDATE game_event SET description='农历节庆' WHERE eventEntry=7;
UPDATE game_event SET description='爱意弥漫的天空 ' WHERE eventEntry=8;
UPDATE game_event SET description='贵族花园 ' WHERE eventEntry=9;
UPDATE game_event SET description='儿童周 ' WHERE eventEntry=10;
UPDATE game_event SET description='收获节 ' WHERE eventEntry=11;
UPDATE game_event SET description='万圣节 ' WHERE eventEntry=12;
UPDATE game_event SET description='安其拉之战 ' WHERE eventEntry=22;
UPDATE game_event SET description='天灾入侵 ' WHERE eventEntry=17;
UPDATE game_event SET description='元素生物入侵 ' WHERE eventEntry=13;
UPDATE game_event SET description='钓鱼比赛 ' WHERE eventEntry=14;
UPDATE game_event SET description='古拉巴什竞技场战斗 ' WHERE eventEntry=16;
UPDATE game_event SET description='钓鱼比赛 ' WHERE eventEntry=15;
UPDATE game_event SET description='战斗的召唤：奥特兰克山谷 ' WHERE eventEntry=18;
UPDATE game_event SET description='战斗的召唤：战歌峡谷 ' WHERE eventEntry=19;
UPDATE game_event SET description='战斗的召唤：阿拉希盆地 ' WHERE eventEntry=20;
UPDATE game_event SET description='战斗的召唤：风暴之眼 ' WHERE eventEntry=21;
UPDATE game_event SET description='奥格瑞玛狼群进攻 ( 队伍一 ) ' WHERE eventEntry=23;
UPDATE game_event SET description='奥格瑞玛狼群进攻 ( 队伍二 ) ' WHERE eventEntry=24;
UPDATE game_event SET description='奥格瑞玛防守战斗 ' WHERE eventEntry=25;
UPDATE game_event SET description='金亚莱之主, 库图比萨 ' WHERE eventEntry=27;
UPDATE game_event SET description='亡灵军队进攻暴风城 (亡灵进攻) ' WHERE eventEntry=28;
UPDATE game_event SET description='夜幕 ' WHERE eventEntry=29;
UPDATE game_event SET description='战斗的召唤：远古海滩 ' WHERE eventEntry=30;
UPDATE game_event SET description='达拉然 - 冠军邀请' WHERE eventEntry=31;
UPDATE game_event SET description='海盗节日 ' WHERE eventEntry=32;
UPDATE game_event SET description='金亚莱之主, 加瓦尼尔 ' WHERE eventEntry=33;
UPDATE game_event SET description='L70ETC 音乐会 ' WHERE eventEntry=34;
UPDATE game_event SET description='钓鱼任务 ' WHERE eventEntry=35;
UPDATE game_event SET description='疯狂之缘，哈拉扎丝 ' WHERE eventEntry=36;
UPDATE game_event SET description='疯狂之缘，瑞纳卡奇 ' WHERE eventEntry=37;
UPDATE game_event SET description='疯狂之缘，乌苏雷 ' WHERE eventEntry=38;
UPDATE game_event SET description='金亚莱之主, 『疯子』丘洛 ' WHERE eventEntry=39;
UPDATE game_event SET description='亡者之日 ' WHERE eventEntry=40;
UPDATE game_event SET description='朝圣者的恩赐 ' WHERE eventEntry=41;
UPDATE game_event SET description='战斗的召唤：征服之岛 ' WHERE eventEntry=42;
UPDATE game_event SET description='落锤镇战斗 ' WHERE eventEntry=43;
UPDATE game_event SET description='萨尔玛恶魔攻击 ' WHERE eventEntry=44;
UPDATE game_event SET description='卡鲁亚克钓鱼大赛 ' WHERE eventEntry=45;
UPDATE game_event SET description='札拉赞恩的死亡 ' WHERE eventEntry=46;
UPDATE game_event SET description='行动：诺莫瑞根 ' WHERE eventEntry=47;
UPDATE game_event SET description='三月 ' WHERE eventEntry=52;
UPDATE game_event SET description='二月 ' WHERE eventEntry=51;
UPDATE game_event SET description='元素生物 & 暮光之锤的入侵 ' WHERE eventEntry=48;
UPDATE game_event SET description='冬幕节:礼物 ' WHERE eventEntry=49;
UPDATE game_event SET description='四月 ' WHERE eventEntry=53;
UPDATE game_event SET description='六月 ' WHERE eventEntry=55;
UPDATE game_event SET description='七月 ' WHERE eventEntry=56;
UPDATE game_event SET description='八月 ' WHERE eventEntry=57;
UPDATE game_event SET description='九月 ' WHERE eventEntry=58;
UPDATE game_event SET description='十月 ' WHERE eventEntry=59;
UPDATE game_event SET description='十一月 ' WHERE eventEntry=60;
UPDATE game_event SET description='五月 ' WHERE eventEntry=54;
UPDATE game_event SET description='一月 ' WHERE eventEntry=50;
UPDATE game_event SET description='十二月 ' WHERE eventEntry=61;
UPDATE game_event SET description='世界的尽头旅店：佩里·盖特的公告 ' WHERE eventEntry=62;
UPDATE game_event SET description='世界的尽头旅店：佩里·盖特的表演 ' WHERE eventEntry=63;
UPDATE game_event SET description='冬季钓鱼大赛 ' WHERE eventEntry=64;
UPDATE game_event SET description='Beer of the Month - Januar' WHERE eventEntry=86;
UPDATE game_event SET description='Beer of the Month - Februar' WHERE eventEntry=87;
UPDATE game_event SET description='Beer of the Month - March' WHERE eventEntry=88;
UPDATE game_event SET description='Beer of the Month - April' WHERE eventEntry=89;
UPDATE game_event SET description='Beer of the Month - May' WHERE eventEntry=90;
UPDATE game_event SET description='Beer of the Month - June' WHERE eventEntry=91;
UPDATE game_event SET description='Beer of the Month - July' WHERE eventEntry=92;
UPDATE game_event SET description='Beer of the Month - August' WHERE eventEntry=93;
UPDATE game_event SET description='Pilgrim''s Bounty' WHERE eventEntry=125;
UPDATE game_event SET description='Beer of the Month - September' WHERE eventEntry=94;
UPDATE game_event SET description='Daily Magisters Terrace' WHERE eventEntry=123;
UPDATE game_event SET description='Beer of the Month - Oktober' WHERE eventEntry=95;
UPDATE game_event SET description='Beer of the Month - November' WHERE eventEntry=96;
UPDATE game_event SET description='Brewfest - Attack of The Dark Iron Dwarfs' WHERE eventEntry=85;
UPDATE game_event SET description='Beer of the Month - December' WHERE eventEntry=97;
UPDATE game_event SET description='Pilgrim''s Bounty' WHERE eventEntry=70;

