UPDATE game_event SET description='仲夏火焰节' WHERE entry=1;
UPDATE game_event SET description='冬幕节' WHERE entry=2;
UPDATE game_event SET description='焚木村 - 狼人的诅咒' WHERE entry=3;
UPDATE game_event SET description='暗月马戏团（艾尔文森林）' WHERE entry=4;
UPDATE game_event SET description='暗月马戏团（莫高雷）' WHERE entry=5;
UPDATE game_event SET description='新年' WHERE entry=6;
UPDATE game_event SET description='春节' WHERE entry=7;
UPDATE game_event SET description='情人节' WHERE entry=8;
UPDATE game_event SET description='复活节' WHERE entry=9;
UPDATE game_event SET description='儿童周' WHERE entry=10;
UPDATE game_event SET description='万圣节' WHERE entry=12;
UPDATE game_event SET description='元素入侵' WHERE entry=13;
UPDATE game_event SET description='钓鱼大赛 开始' WHERE entry=14;
UPDATE game_event SET description='钓鱼大赛' WHERE entry=15;
UPDATE game_event SET description='古拉巴什竞技场战斗' WHERE entry=16;
UPDATE game_event SET description='天灾入侵' WHERE entry=17;
UPDATE game_event SET description='战斗的召唤：奥特兰克山谷' WHERE entry=18;
UPDATE game_event SET description='战斗的召唤：战歌峡谷' WHERE entry=19;
UPDATE game_event SET description='战斗的召唤：阿拉希盆地' WHERE entry=20;
UPDATE game_event SET description='冬幕节:礼物' WHERE entry=21;
UPDATE game_event SET description='安其拉之战' WHERE entry=22;
UPDATE game_event SET description='暗月马戏团搭建（艾尔文森林）' WHERE entry=23;
UPDATE game_event SET description='夜幕' WHERE entry=27;
UPDATE game_event SET description='疯狂之缘，格里雷克' WHERE entry=29;
UPDATE game_event SET description='疯狂之缘，哈拉扎丝' WHERE entry=30;
UPDATE game_event SET description='疯狂之缘，瑞纳卡奇' WHERE entry=31;
UPDATE game_event SET description='疯狂之缘，乌苏雷' WHERE entry=32;
UPDATE game_event SET description='收获节' WHERE entry=33;
UPDATE game_event SET description='钓鱼大赛' WHERE entry=34;
UPDATE game_event SET description='冬季钓鱼大赛' WHERE entry=35;
UPDATE game_event SET description='夏季钓鱼大赛' WHERE entry=36;
UPDATE game_event SET description='暴风城 - 监狱越狱' WHERE entry=61;