UPDATE mangos_string SET content_default='您应该选择角色或生物.' WHERE entry=1;
UPDATE mangos_string SET content_default='您应该选择一个生物.' WHERE entry=2;
UPDATE mangos_string SET content_default='|cffff0000[系统消息]: %s|r' WHERE entry=3;
UPDATE mangos_string SET content_default='|cffff0000[游戏广播]: %s|r' WHERE entry=4;
UPDATE mangos_string SET content_default='这里没有此命令的帮助信息' WHERE entry=5;
UPDATE mangos_string SET content_default='这个命令不存在' WHERE entry=6;
UPDATE mangos_string SET content_default='这里没有此类子命令' WHERE entry=7;
UPDATE mangos_string SET content_default='命令的 %s 子命令有:' WHERE entry=8;
UPDATE mangos_string SET content_default='你可以使用的命令有:' WHERE entry=9;
UPDATE mangos_string SET content_default='命令语法格式错误.' WHERE entry=10;
UPDATE mangos_string SET content_default='你的账号级别是: %i' WHERE entry=11;
UPDATE mangos_string SET content_default='在线人数: %u (最多时: %u) 排队人数: %u (最多时: %u)' WHERE entry=12;
UPDATE mangos_string SET content_default='服务器正常运行时间: %s' WHERE entry=13;
UPDATE mangos_string SET content_default='系统提示：玩家数据保存成功.' WHERE entry=14;
UPDATE mangos_string SET content_default='系统提示：保存所有玩家数据成功.' WHERE entry=15;
UPDATE mangos_string SET content_default='系统提示：在此服务器上有以下在线的GM:' WHERE entry=16;
UPDATE mangos_string SET content_default='系统提示：当前没有G M登录在这台服务器上.' WHERE entry=17;
UPDATE mangos_string SET content_default='系统提示：当处于飞行中时，无法这样做.' WHERE entry=18;
UPDATE mangos_string SET content_default='系统提示：在战场里无法这样做.' WHERE entry=19;
UPDATE mangos_string SET content_default='系统提示：目标在飞行中，你无法这样做.' WHERE entry=20;
UPDATE mangos_string SET content_default='系统提示：%s 正在飞行中, 命令无效.' WHERE entry=21;
UPDATE mangos_string SET content_default='系统提示：你没有在骑乘状态, 因此你不能卸下骑乘.' WHERE entry=22;
UPDATE mangos_string SET content_default='系统提示：在战斗中无法这样做.' WHERE entry=23;
UPDATE mangos_string SET content_default='系统提示：您最近已经使用过它.' WHERE entry=24;
UPDATE mangos_string SET content_default='系统提示：密码修改失败(未知错误)!' WHERE entry=25;
UPDATE mangos_string SET content_default='系统提示：密码已经修改.' WHERE entry=26;
UPDATE mangos_string SET content_default='系统提示：旧密码是错误的.' WHERE entry=27;
UPDATE mangos_string SET content_default='系统提示：你的账号现在被锁定.' WHERE entry=28;
UPDATE mangos_string SET content_default='系统提示：你的账号已取消锁定.' WHERE entry=29;
UPDATE mangos_string SET content_default='排名' WHERE entry=30;
UPDATE mangos_string SET content_default='[学会]' WHERE entry=31;
UPDATE mangos_string SET content_default='[学习]' WHERE entry=32;
UPDATE mangos_string SET content_default='[被动的]' WHERE entry=33;
UPDATE mangos_string SET content_default='[天赋]' WHERE entry=34;
UPDATE mangos_string SET content_default=' [激活]' WHERE entry=35;
UPDATE mangos_string SET content_default=' [完成]' WHERE entry=36;
UPDATE mangos_string SET content_default=' (离线)' WHERE entry=37;
UPDATE mangos_string SET content_default='开' WHERE entry=38;
UPDATE mangos_string SET content_default='关' WHERE entry=39;
UPDATE mangos_string SET content_default='你是: %s' WHERE entry=40;
UPDATE mangos_string SET content_default='显示' WHERE entry=41;
UPDATE mangos_string SET content_default='隐藏' WHERE entry=42;
UPDATE mangos_string SET content_default='完成' WHERE entry=43;
UPDATE mangos_string SET content_default='你' WHERE entry=44;
UPDATE mangos_string SET content_default='<未知>' WHERE entry=45;
UPDATE mangos_string SET content_default='<错误>' WHERE entry=46;
UPDATE mangos_string SET content_default='<查无此人>' WHERE entry=47;
UPDATE mangos_string SET content_default='未知' WHERE entry=48;
UPDATE mangos_string SET content_default='你必须达到 %u 级后才能进入.' WHERE entry=49;
UPDATE mangos_string SET content_default='你必须拥有道具 %s 才能进入.' WHERE entry=50;
UPDATE mangos_string SET content_default='你好! 准备学习什么技能吗?' WHERE entry=51;
UPDATE mangos_string SET content_default='Invaid item count (%u) for item %u' WHERE entry=52;
UPDATE mangos_string SET content_default='Mail can’t have more %u item stacks' WHERE entry=53;
UPDATE mangos_string SET content_default='系统提示：新密码不匹配.' WHERE entry=54;
UPDATE mangos_string SET content_default='系统提示：您的密码不能超过16个字符（客户端限制），密码没有更改！' WHERE entry=55;
UPDATE mangos_string SET content_default='每日消息: %s' WHERE entry=56;
UPDATE mangos_string SET content_default='使用的世界数据库: %s' WHERE entry=57;
UPDATE mangos_string SET content_default='使用的脚本库' WHERE entry=58;
UPDATE mangos_string SET content_default='使用的 creature EventAI: %s' WHERE entry=59;
UPDATE mangos_string SET content_default='用户名: ' WHERE entry=61;
UPDATE mangos_string SET content_default='密码: ' WHERE entry=62;
UPDATE mangos_string SET content_default='接受悄悄话' WHERE entry=63;
UPDATE mangos_string SET content_default='不接受悄悄话' WHERE entry=64;
UPDATE mangos_string SET content_default='使用脚本库：<未知脚本库>' WHERE entry=65;
UPDATE mangos_string SET content_default='使用脚本库：<不存在脚本库>' WHERE entry=66;
UPDATE mangos_string SET content_default='你必须是部落的成员才能进入。' WHERE entry=67;
UPDATE mangos_string SET content_default='你必须是联盟的成员才能进入。' WHERE entry=68;
UPDATE mangos_string SET content_default='你的等级必须达到%u级才能进入.' WHERE entry=69;
UPDATE mangos_string SET content_default='你的等级必须为%u才能进入.' WHERE entry=70;
UPDATE mangos_string SET content_default='全区广播:' WHERE entry=100;
UPDATE mangos_string SET content_default='地图: %u (%s) 地域: %u (%s) 地区: %u (%s)X: %f Y: %f Z: %f Orientation: %fgrid[%u,%u]cell[%u,%u] InstanceID: %u ZoneX: %f ZoneY: %fGroundZ: %f FloorZ: %f Have height data (Map: %u VMap: %u)' WHERE entry=101;
UPDATE mangos_string SET content_default='%s 已被远距传送.' WHERE entry=102;
UPDATE mangos_string SET content_default='你可以召唤一个玩家到你的副本，前提是必须在同一队伍，而且你是队长.' WHERE entry=103;
UPDATE mangos_string SET content_default='你无法传送到玩家的副本，因为你们不在同一队伍.' WHERE entry=104;
UPDATE mangos_string SET content_default='传送到不是同一队伍的玩家的副本需要开启ＧＭ模式.' WHERE entry=105;
UPDATE mangos_string SET content_default='你无法传送到玩家  %s 从副本到副本.' WHERE entry=106;
UPDATE mangos_string SET content_default='你不能召唤这个玩家 %s 从副本到副本.' WHERE entry=107;
UPDATE mangos_string SET content_default='你正在召唤 %s%s.' WHERE entry=108;
UPDATE mangos_string SET content_default='系统提示：你正在被 %s 召唤中.' WHERE entry=109;
UPDATE mangos_string SET content_default='你正在传送  %s%s 到 %s.' WHERE entry=110;
UPDATE mangos_string SET content_default='系统提示：你正在被 %s 传送.' WHERE entry=111;
UPDATE mangos_string SET content_default='玩家 (%s) 不存在.' WHERE entry=112;
UPDATE mangos_string SET content_default='出现在 %s 的地点.' WHERE entry=113;
UPDATE mangos_string SET content_default='%s 出现在你的位置.' WHERE entry=114;
UPDATE mangos_string SET content_default='无效参数.' WHERE entry=115;
UPDATE mangos_string SET content_default='没有选定角色.' WHERE entry=116;
UPDATE mangos_string SET content_default='%s 不在同一队伍里.' WHERE entry=117;
UPDATE mangos_string SET content_default='你改变了 %s 的血量值到 %i/%i.' WHERE entry=118;
UPDATE mangos_string SET content_default='%s 改变了你的血量值到 %i/%i.' WHERE entry=119;
UPDATE mangos_string SET content_default='你改变了 %s 的魔法值到 %i/%i.' WHERE entry=120;
UPDATE mangos_string SET content_default='%s 改变了你的魔法值到 %i/%i.' WHERE entry=121;
UPDATE mangos_string SET content_default='你改变了 %s 的能量值到 %i/%i.' WHERE entry=122;
UPDATE mangos_string SET content_default='%s 改变了你的能量值到 %i/%i.' WHERE entry=123;
UPDATE mangos_string SET content_default='当前的能量: %u' WHERE entry=124;
UPDATE mangos_string SET content_default='你改变了 %s 的怒气值到 %i/%i.' WHERE entry=125;
UPDATE mangos_string SET content_default='%s 改变了你的怒气值到 %i/%i.' WHERE entry=126;
UPDATE mangos_string SET content_default='你改变了 %s 的等级到 %i.' WHERE entry=127;
UPDATE mangos_string SET content_default='GUID %i, faction is %i, flags is %i, npcflag is %i, DY flag is %i' WHERE entry=128;
UPDATE mangos_string SET content_default='Wrong faction: %u (not found in factiontemplate.dbc).' WHERE entry=129;
UPDATE mangos_string SET content_default='You changed GUID=%i ’s Faction to %i, flags to %i, npcflag to %i, dyflag to %i.' WHERE entry=130;
UPDATE mangos_string SET content_default='You changed the %s spellmod %u to value %i for spell with family bit %u for %s.' WHERE entry=131;
UPDATE mangos_string SET content_default='%s changed your spellmod %u to value %i for spell with family bit %u.' WHERE entry=132;
UPDATE mangos_string SET content_default='%s 获得了所有的飞行节点 (直到注销).' WHERE entry=133;
UPDATE mangos_string SET content_default='%s 没有更多可获得的飞行节点(仅显示已开通的).' WHERE entry=134;
UPDATE mangos_string SET content_default='%s 给你进入所有飞行节点 (直到注销).' WHERE entry=135;
UPDATE mangos_string SET content_default='%s 已取消进出所有飞行节点(仅显示已开通的).' WHERE entry=136;
UPDATE mangos_string SET content_default='你设置了所有的速度到 %2.2f 从基础值 %s.' WHERE entry=137;
UPDATE mangos_string SET content_default='%s 设置了你所有的速度到 %2.2f 从基础值.' WHERE entry=138;
UPDATE mangos_string SET content_default='你设置了移动速度到 %2.2f 从基础值 %s.' WHERE entry=139;
UPDATE mangos_string SET content_default='%s 设置了你的移动速度到 %2.2f 从基础值.' WHERE entry=140;
UPDATE mangos_string SET content_default='你设置了游泳速度到 %2.2f 从基础值 %s.' WHERE entry=141;
UPDATE mangos_string SET content_default='%s 设置了你的游泳速度到 %2.2f 从基础值.' WHERE entry=142;
UPDATE mangos_string SET content_default='设置了后退速度到 %2.2f 从基础值 %s.' WHERE entry=143;
UPDATE mangos_string SET content_default='%s 设置了你的后退速度到 %2.2f 从基础值.' WHERE entry=144;
UPDATE mangos_string SET content_default='你设置了模型大小 %2.2f of %s.' WHERE entry=147;
UPDATE mangos_string SET content_default='%s 设置你的模型大小为 %2.2f.' WHERE entry=148;
UPDATE mangos_string SET content_default='没有此类骑术.' WHERE entry=149;
UPDATE mangos_string SET content_default='你把一个骑术送给 %s.' WHERE entry=150;
UPDATE mangos_string SET content_default='%s 送给你一个骑术.' WHERE entry=151;
UPDATE mangos_string SET content_default='用户1: %i, 添加: %i, 结果: %i' WHERE entry=152;
UPDATE mangos_string SET content_default='你拿走了所有的铜币从 %s.' WHERE entry=153;
UPDATE mangos_string SET content_default='%s 拿走了你所有的铜币.' WHERE entry=154;
UPDATE mangos_string SET content_default='你拿走了 %i 铜币从 %s.' WHERE entry=155;
UPDATE mangos_string SET content_default='%s 拿走了 %i 铜币从你这里.' WHERE entry=156;
UPDATE mangos_string SET content_default='你把 %i 铜币给了 %s.' WHERE entry=157;
UPDATE mangos_string SET content_default='%s 给你 %i  铜币.' WHERE entry=158;
UPDATE mangos_string SET content_default='你听到声音 %u.' WHERE entry=159;
UPDATE mangos_string SET content_default='用户2: %i, 添加: %i, 结果: %i' WHERE entry=160;
UPDATE mangos_string SET content_default='Removed bit %i in field %i.' WHERE entry=161;
UPDATE mangos_string SET content_default='Set bit %i in field %i.' WHERE entry=162;
UPDATE mangos_string SET content_default='传送地点表是空的!' WHERE entry=163;
UPDATE mangos_string SET content_default='传送地点没被发现!' WHERE entry=164;
UPDATE mangos_string SET content_default='需要搜索参数.' WHERE entry=165;
UPDATE mangos_string SET content_default='没有传送地点匹配您的请求.' WHERE entry=166;
UPDATE mangos_string SET content_default='发现地点是: %s' WHERE entry=168;
UPDATE mangos_string SET content_default='邮件寄给 %s' WHERE entry=169;
UPDATE mangos_string SET content_default='你试着听声音 %u 但是它并不存在.' WHERE entry=170;
UPDATE mangos_string SET content_default='你不能传送自己!' WHERE entry=171;
UPDATE mangos_string SET content_default='服务器控制台命令' WHERE entry=172;
UPDATE mangos_string SET content_default='Liquid level: %f, ground: %f, type flags %u, status: %d.' WHERE entry=175;
UPDATE mangos_string SET content_default='没有选择.' WHERE entry=200;
UPDATE mangos_string SET content_default='Object GUID is: %s' WHERE entry=201;
UPDATE mangos_string SET content_default='这个名字长度超过了 %i 字符.' WHERE entry=202;
UPDATE mangos_string SET content_default='错误,名字只能包含字符 A-Z 和 a-z.' WHERE entry=203;
UPDATE mangos_string SET content_default='次级名字太长超过了 %i 字符.' WHERE entry=204;
UPDATE mangos_string SET content_default='未能改变' WHERE entry=205;
UPDATE mangos_string SET content_default='物品 ’%i’ ’%s’以加入到列表且最大数 ’%i’刷新时间 ’%i’' WHERE entry=206;
UPDATE mangos_string SET content_default='物品 ’%i’ 在数据库里没有找到.' WHERE entry=207;
UPDATE mangos_string SET content_default='物品 ’%i’ ’%s’ 已经从商人列表中删除.' WHERE entry=208;
UPDATE mangos_string SET content_default='物品 ’%i’ 没有找到在商人的列表里.' WHERE entry=209;
UPDATE mangos_string SET content_default='物品 ’%i’ 已存在于商人的列表里.' WHERE entry=210;
UPDATE mangos_string SET content_default='法术 %s 重置.' WHERE entry=211;
UPDATE mangos_string SET content_default='法术 %s 将在下次登陆时重置.' WHERE entry=212;
UPDATE mangos_string SET content_default='天赋 %s 重置.' WHERE entry=213;
UPDATE mangos_string SET content_default='天赋 %s 将在下次登陆时重置.' WHERE entry=214;
UPDATE mangos_string SET content_default='你的法术已经重置了.' WHERE entry=215;
UPDATE mangos_string SET content_default='你的天赋已经重置了.' WHERE entry=216;
UPDATE mangos_string SET content_default='未知的参数  ’%s’ 为 .resetall 命令. 键入完整的正确参数名字.' WHERE entry=217;
UPDATE mangos_string SET content_default='法术将重置在所有玩家在重新登录后. 强烈推荐重新登录!' WHERE entry=218;
UPDATE mangos_string SET content_default='天赋将重置在所有玩家在重新登录后. 强烈推荐重新登录!' WHERE entry=219;
UPDATE mangos_string SET content_default='Cannot find waypoint id %u for %s (in path %i, loaded from %s)' WHERE entry=220;
UPDATE mangos_string SET content_default='Last Waypoint not found for %s' WHERE entry=221;
UPDATE mangos_string SET content_default='%s has no path or path empty, path-id %i (loaded from %s)' WHERE entry=222;
UPDATE mangos_string SET content_default='Creature (GUID: %u) No waypoints found - This is a MaNGOS db problem (single float).' WHERE entry=223;
UPDATE mangos_string SET content_default='Cannot access %s on map, maybe you are too far away from its spawn location' WHERE entry=224;
UPDATE mangos_string SET content_default='生物 (GUID: %u) 没有找到.' WHERE entry=225;
UPDATE mangos_string SET content_default='您必须选择一个视觉飞行点.' WHERE entry=226;
UPDATE mangos_string SET content_default='没有找到视觉飞行点.' WHERE entry=227;
UPDATE mangos_string SET content_default='不能创建视觉飞行点的 生物ID: %d' WHERE entry=228;
UPDATE mangos_string SET content_default='所有视觉飞行点消除.' WHERE entry=229;
UPDATE mangos_string SET content_default='Could not add waypoint %u to %s (pathId %i stored by %s)' WHERE entry=230;
UPDATE mangos_string SET content_default='没有 GUID 被提供.' WHERE entry=231;
UPDATE mangos_string SET content_default='没有提供飞行点数值.' WHERE entry=232;
UPDATE mangos_string SET content_default='根据要求为  ’%s’.' WHERE entry=233;
UPDATE mangos_string SET content_default='Added Waypoint %u to %s (PathId %i, path stored by %s)' WHERE entry=234;
UPDATE mangos_string SET content_default='未使用' WHERE entry=235;
UPDATE mangos_string SET content_default='飞行点已变动.' WHERE entry=236;
UPDATE mangos_string SET content_default='飞行点 %s 已修改.' WHERE entry=237;
UPDATE mangos_string SET content_default='飞行点出口成功.' WHERE entry=238;
UPDATE mangos_string SET content_default='没有飞行点被发现在数据库里.' WHERE entry=239;
UPDATE mangos_string SET content_default='文件已导入.' WHERE entry=240;
UPDATE mangos_string SET content_default='飞行点取消.' WHERE entry=241;
UPDATE mangos_string SET content_default='未使用' WHERE entry=242;
UPDATE mangos_string SET content_default='未使用' WHERE entry=243;
UPDATE mangos_string SET content_default='未使用' WHERE entry=244;
UPDATE mangos_string SET content_default='未使用' WHERE entry=245;
UPDATE mangos_string SET content_default='Waypoint %u for %s (from pathId %i, stored by %s)' WHERE entry=246;
UPDATE mangos_string SET content_default='等待时间: %d' WHERE entry=247;
UPDATE mangos_string SET content_default=' Orientation: %f' WHERE entry=248;
UPDATE mangos_string SET content_default='脚本ID: %u' WHERE entry=249;
UPDATE mangos_string SET content_default='ScriptID set to non-existing id %u, add it to DBScriptsEngine and reload the table.' WHERE entry=250;
UPDATE mangos_string SET content_default='未使用' WHERE entry=251;
UPDATE mangos_string SET content_default='AI脚本名称: %s' WHERE entry=252;
UPDATE mangos_string SET content_default='强制修改玩家名 %s, 将于下次登录时生效.' WHERE entry=253;
UPDATE mangos_string SET content_default='强制修改玩家名 %s (GUID #%u), 将于下次登录时生效.' WHERE entry=254;
UPDATE mangos_string SET content_default='飞行点-生物 (GUID: %u) 没有找到.' WHERE entry=255;
UPDATE mangos_string SET content_default='不能查找NPC...' WHERE entry=256;
UPDATE mangos_string SET content_default='生物运动方式设置为 ’%s’, 飞行点去除 (如果存在).' WHERE entry=257;
UPDATE mangos_string SET content_default='生物运动方式设置为 ’%s’, 飞行点没有去除..' WHERE entry=258;
UPDATE mangos_string SET content_default='错误值, 请用 on 或 off' WHERE entry=259;
UPDATE mangos_string SET content_default='设置已保存.' WHERE entry=260;
UPDATE mangos_string SET content_default='设置已保存, 你可能需要重新清理你的客户缓存.' WHERE entry=261;
UPDATE mangos_string SET content_default='区域触发(传送门) ID %u 没有发现! ' WHERE entry=262;
UPDATE mangos_string SET content_default='目标地图或坐标无效 (X: %f Y: %f 地图Id: %u)' WHERE entry=263;
UPDATE mangos_string SET content_default='区域传送门无效 (X: %f Y: %f 地区Id: %u)' WHERE entry=264;
UPDATE mangos_string SET content_default='Zone %u (%s) is part of instanceable map %u (%s)' WHERE entry=265;
UPDATE mangos_string SET content_default='没任何发现!' WHERE entry=266;
UPDATE mangos_string SET content_default='对象没有找到!' WHERE entry=267;
UPDATE mangos_string SET content_default='生物没有找到!' WHERE entry=268;
UPDATE mangos_string SET content_default='生物已经移除.' WHERE entry=270;
UPDATE mangos_string SET content_default='生物已经移动.' WHERE entry=271;
UPDATE mangos_string SET content_default='生物 (GUID:%u) 必须与玩家在同样的地图!' WHERE entry=272;
UPDATE mangos_string SET content_default='游戏对象 (GUID: %u) 没有找到.' WHERE entry=273;
UPDATE mangos_string SET content_default='游戏对象 (GUID: %u) 有一个参考于没有找到生物 %u 的名单, 不能被删除.' WHERE entry=274;
UPDATE mangos_string SET content_default='游戏对象 (GUID: %u) 去除.' WHERE entry=275;
UPDATE mangos_string SET content_default='游戏对象 |cffffffff|Hgameobject:%d|h[%s]|h|r (GUID: %u) 转动.' WHERE entry=276;
UPDATE mangos_string SET content_default='游戏对象 |cffffffff|Hgameobject:%d|h[%s]|h|r (GUID: %u) 移动.' WHERE entry=277;
UPDATE mangos_string SET content_default='你必须选择一个商人' WHERE entry=278;
UPDATE mangos_string SET content_default='你必须使用物品的id' WHERE entry=279;
UPDATE mangos_string SET content_default='商人设置了太多的物品 (最多128)' WHERE entry=280;
UPDATE mangos_string SET content_default='你不能踢出你自己，使用退出代替.' WHERE entry=281;
UPDATE mangos_string SET content_default='角色 %s 已踢出.' WHERE entry=282;
UPDATE mangos_string SET content_default='接受悄悄话: %s' WHERE entry=284;
UPDATE mangos_string SET content_default='接受悄悄话: 开启' WHERE entry=285;
UPDATE mangos_string SET content_default='接受悄悄话: 关闭' WHERE entry=286;
UPDATE mangos_string SET content_default='生物 (GUID: %u) 没有找到.' WHERE entry=287;
UPDATE mangos_string SET content_default='票数量: %i 出示新的票: %s ' WHERE entry=288;
UPDATE mangos_string SET content_default='新票开始于 %s' WHERE entry=289;
UPDATE mangos_string SET content_default='Ticket of %s (Last updated: %s): %s' WHERE entry=290;
UPDATE mangos_string SET content_default='新票显示: 开启' WHERE entry=291;
UPDATE mangos_string SET content_default='新票显示: 关闭' WHERE entry=292;
UPDATE mangos_string SET content_default='票 %i 不存在.' WHERE entry=293;
UPDATE mangos_string SET content_default='所有票已删除.' WHERE entry=294;
UPDATE mangos_string SET content_default='角色 %s 票已删除.' WHERE entry=295;
UPDATE mangos_string SET content_default='票已删除.' WHERE entry=296;
UPDATE mangos_string SET content_default='刷新时间间隔改变为: %i' WHERE entry=297;
UPDATE mangos_string SET content_default='刷新时间改变为: %i' WHERE entry=298;
UPDATE mangos_string SET content_default='%s 的荣誉被设置到 %u!' WHERE entry=299;
UPDATE mangos_string SET content_default='你的聊天将被关闭 %u 分钟.' WHERE entry=300;
UPDATE mangos_string SET content_default='你被关闭了 %s 的聊天时间 %u 分钟.' WHERE entry=301;
UPDATE mangos_string SET content_default='玩的聊天已经可以使用.' WHERE entry=302;
UPDATE mangos_string SET content_default='你的聊天已经可以使用.' WHERE entry=303;
UPDATE mangos_string SET content_default='你已经可以使用 %s 的聊天了.' WHERE entry=304;
UPDATE mangos_string SET content_default='Faction %s (%u) reputation of %s was set to %5d!' WHERE entry=305;
UPDATE mangos_string SET content_default='没有阵营被发现' WHERE entry=307;
UPDATE mangos_string SET content_default='阵营 %i 未知!' WHERE entry=308;
UPDATE mangos_string SET content_default='无效的参数 %s' WHERE entry=309;
UPDATE mangos_string SET content_default='delta must be between 0 and %d (inclusive)' WHERE entry=310;
UPDATE mangos_string SET content_default='%d - |cffffffff|Hfaction:%d|h[%s]|h|r' WHERE entry=311;
UPDATE mangos_string SET content_default=' [显示状态]' WHERE entry=312;
UPDATE mangos_string SET content_default=' [交战状态]' WHERE entry=313;
UPDATE mangos_string SET content_default=' [和平状态]' WHERE entry=314;
UPDATE mangos_string SET content_default=' [潜行状态]' WHERE entry=315;
UPDATE mangos_string SET content_default=' [invisible forced]' WHERE entry=316;
UPDATE mangos_string SET content_default=' [inactive]' WHERE entry=317;
UPDATE mangos_string SET content_default='仇恨' WHERE entry=318;
UPDATE mangos_string SET content_default='敌对' WHERE entry=319;
UPDATE mangos_string SET content_default='不友好' WHERE entry=320;
UPDATE mangos_string SET content_default='中立' WHERE entry=321;
UPDATE mangos_string SET content_default='友好的' WHERE entry=322;
UPDATE mangos_string SET content_default='荣誉的' WHERE entry=323;
UPDATE mangos_string SET content_default='尊敬的' WHERE entry=324;
UPDATE mangos_string SET content_default='高贵的' WHERE entry=325;
UPDATE mangos_string SET content_default='Faction %s (%u) can’not have reputation.' WHERE entry=326;
UPDATE mangos_string SET content_default=' [no reputation]' WHERE entry=327;
UPDATE mangos_string SET content_default='Characters at account %s (Id: %u)' WHERE entry=328;
UPDATE mangos_string SET content_default='  %s (GUID %u)' WHERE entry=329;
UPDATE mangos_string SET content_default='没找到玩家!' WHERE entry=330;
UPDATE mangos_string SET content_default='Extended item cost %u not exist' WHERE entry=331;
UPDATE mangos_string SET content_default='GM 模式开启' WHERE entry=332;
UPDATE mangos_string SET content_default='GM 模式关闭' WHERE entry=333;
UPDATE mangos_string SET content_default='GM 聊条前缀开启' WHERE entry=334;
UPDATE mangos_string SET content_default='GM 聊条前缀关闭' WHERE entry=335;
UPDATE mangos_string SET content_default='You repair all %s’s items.' WHERE entry=336;
UPDATE mangos_string SET content_default='All your items repaired by %s.' WHERE entry=337;
UPDATE mangos_string SET content_default='You set waterwalk mode %s for %s.' WHERE entry=338;
UPDATE mangos_string SET content_default='Your waterwalk mode %s by %s.' WHERE entry=339;
UPDATE mangos_string SET content_default='%s is now following you.' WHERE entry=340;
UPDATE mangos_string SET content_default='%s is not following you.' WHERE entry=341;
UPDATE mangos_string SET content_default='%s is now not following you.' WHERE entry=342;
UPDATE mangos_string SET content_default='Creature (Entry: %u) cannot be tamed.' WHERE entry=343;
UPDATE mangos_string SET content_default='You already have pet.' WHERE entry=344;
UPDATE mangos_string SET content_default='TaxiNode ID %u not found!' WHERE entry=347;
UPDATE mangos_string SET content_default='Game Object (Entry: %u) have invalid data and can’t be spawned' WHERE entry=348;
UPDATE mangos_string SET content_default='Areatrigger %u not has target coordinates' WHERE entry=357;
UPDATE mangos_string SET content_default='No areatriggers found!' WHERE entry=358;
UPDATE mangos_string SET content_default='%s|cffffffff|Hareatrigger_target:%u|h[Trigger target %u]|h|r Map %u X:%f Y:%f Z:%f%s' WHERE entry=359;
UPDATE mangos_string SET content_default='%s[Trigger target %u] Map %u X:%f Y:%f Z:%f' WHERE entry=360;
UPDATE mangos_string SET content_default='|cffffffff|Hareatrigger:%u|h[Trigger %u]|h|r Map %u X:%f Y:%f Z:%f%s%s%s' WHERE entry=361;
UPDATE mangos_string SET content_default='[Trigger %u] Map %u X:%f Y:%f Z:%f%s%s' WHERE entry=362;
UPDATE mangos_string SET content_default=' (距离 %f)' WHERE entry=363;
UPDATE mangos_string SET content_default=' [旅店]' WHERE entry=364;
UPDATE mangos_string SET content_default=' [任务]' WHERE entry=365;
UPDATE mangos_string SET content_default='查询任务:' WHERE entry=366;
UPDATE mangos_string SET content_default='条件: %u' WHERE entry=367;
UPDATE mangos_string SET content_default='结果: %s' WHERE entry=373;
UPDATE mangos_string SET content_default='"Tickets count: %i
"' WHERE entry=374;
UPDATE mangos_string SET content_default='Player %s not have tickets.' WHERE entry=375;
UPDATE mangos_string SET content_default='%u - |cffffffff|Hpool:%u|h[%s]|h|r AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u' WHERE entry=376;
UPDATE mangos_string SET content_default='No pools found for map ’%s’ (Id:%u)' WHERE entry=377;
UPDATE mangos_string SET content_default='You can’t use this command at non-instanceable map ’%s’ (Id:%u). Use .lookup pool command instead.' WHERE entry=378;
UPDATE mangos_string SET content_default='You can’t use this command without args at non-instanceable map ’%s’ (Id:%u).' WHERE entry=379;
UPDATE mangos_string SET content_default='%d%s - |cffffffff|Hcreature:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r Chance:%f %s' WHERE entry=380;
UPDATE mangos_string SET content_default='%d%s - [%s] X:%f Y:%f Z:%f MapId:%d Chance:%f %s' WHERE entry=381;
UPDATE mangos_string SET content_default='%d%s - |cffffffff|Hcreature:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r %s' WHERE entry=382;
UPDATE mangos_string SET content_default='%d%s - [%s] X:%f Y:%f Z:%f MapId:%d %s' WHERE entry=383;
UPDATE mangos_string SET content_default='%d%s - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r Chance:%f %s' WHERE entry=384;
UPDATE mangos_string SET content_default='%d%s - [%s] X:%f Y:%f Z:%f MapId:%d Chance:%f %s' WHERE entry=385;
UPDATE mangos_string SET content_default='%d%s - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r %s' WHERE entry=386;
UPDATE mangos_string SET content_default='%d%s - [%s] X:%f Y:%f Z:%f MapId:%d %s' WHERE entry=387;
UPDATE mangos_string SET content_default='Creatures with explicitly chance:' WHERE entry=388;
UPDATE mangos_string SET content_default='Creatures with equal chance:' WHERE entry=389;
UPDATE mangos_string SET content_default='Gameobjects with explicitly chance:' WHERE entry=390;
UPDATE mangos_string SET content_default='Gameobjects with equal chance:' WHERE entry=391;
UPDATE mangos_string SET content_default='Pool %u - Mother pool: %u |cffffffff|Hpool:%u|h[%s]|h|r AutoSpawn: %u MaxLimit: %u' WHERE entry=392;
UPDATE mangos_string SET content_default='Pool %u - Mother pool: %u [%s] AutoSpawn: %u MaxLimit: %u' WHERE entry=393;
UPDATE mangos_string SET content_default='Pool %u - Mother pool: none AutoSpawn: %u MaxLimit: %u' WHERE entry=394;
UPDATE mangos_string SET content_default='No pools found' WHERE entry=395;
UPDATE mangos_string SET content_default='%u - [%s] AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u' WHERE entry=396;
UPDATE mangos_string SET content_default='Pools with explicitly chance:' WHERE entry=397;
UPDATE mangos_string SET content_default='Pools with equal chance:' WHERE entry=398;
UPDATE mangos_string SET content_default='%u - |cffffffff|Hpool:%u|h[%s]|h|r AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u Chance: %f %s' WHERE entry=399;
UPDATE mangos_string SET content_default='|cffff0000[系统信息]:|r加载脚本' WHERE entry=400;
UPDATE mangos_string SET content_default='你改变了 %s 的安全等级为 %i.' WHERE entry=401;
UPDATE mangos_string SET content_default='%s 改变了你的安全等级为 %i.' WHERE entry=402;
UPDATE mangos_string SET content_default='你这是低的防护等级.' WHERE entry=403;
UPDATE mangos_string SET content_default='生物移动点取消.' WHERE entry=404;
UPDATE mangos_string SET content_default='生物移动点生效.' WHERE entry=405;
UPDATE mangos_string SET content_default='这个区域的天气不能被更改.' WHERE entry=406;
UPDATE mangos_string SET content_default='服务器天气系统取消.' WHERE entry=407;
UPDATE mangos_string SET content_default='%s 被禁止的为 %s. 操作: %s.' WHERE entry=408;
UPDATE mangos_string SET content_default='%s 被永久禁止的为 %s.' WHERE entry=409;
UPDATE mangos_string SET content_default='%s %s 没有发现.' WHERE entry=410;
UPDATE mangos_string SET content_default='%s 已解除禁止.' WHERE entry=411;
UPDATE mangos_string SET content_default='出现错误取消禁令 %s.' WHERE entry=412;
UPDATE mangos_string SET content_default='帐户不存在: %s' WHERE entry=413;
UPDATE mangos_string SET content_default='没有这个角色.' WHERE entry=414;
UPDATE mangos_string SET content_default='禁止名单上没有这样的IP.' WHERE entry=415;
UPDATE mangos_string SET content_default='账号 %s 从来没被禁止.' WHERE entry=416;
UPDATE mangos_string SET content_default='历史禁止帐户 %s:' WHERE entry=417;
UPDATE mangos_string SET content_default='禁止日期: %s 禁止时间: %s 激活间隔: %s  原因: %s 操作者: %s' WHERE entry=418;
UPDATE mangos_string SET content_default='信息.' WHERE entry=419;
UPDATE mangos_string SET content_default='从未' WHERE entry=420;
UPDATE mangos_string SET content_default='是' WHERE entry=421;
UPDATE mangos_string SET content_default='不' WHERE entry=422;
UPDATE mangos_string SET content_default='禁止IP: %s禁止日期: %s 禁止时间: %s 剩余: %s 原因: %s 操着者: %s' WHERE entry=423;
UPDATE mangos_string SET content_default='没有匹配的IP禁止地址.' WHERE entry=424;
UPDATE mangos_string SET content_default='没有匹配的帐户.' WHERE entry=425;
UPDATE mangos_string SET content_default='没有禁用的账号相匹配.' WHERE entry=426;
UPDATE mangos_string SET content_default='下面的IP地址符合您的匹配:' WHERE entry=427;
UPDATE mangos_string SET content_default='以下帐户匹配您的查询:' WHERE entry=428;
UPDATE mangos_string SET content_default='你学会了全部法术或技能.' WHERE entry=429;
UPDATE mangos_string SET content_default='你已经学会了所有的会职业法术.' WHERE entry=430;
UPDATE mangos_string SET content_default='你已经学会了所有的本职业天赋.' WHERE entry=431;
UPDATE mangos_string SET content_default='你已经学会了所有的语言.' WHERE entry=432;
UPDATE mangos_string SET content_default='你学会了所有手工艺技能和食谱.' WHERE entry=433;
UPDATE mangos_string SET content_default='不能查找 ’%s’' WHERE entry=434;
UPDATE mangos_string SET content_default='无效的物品 id: %u' WHERE entry=435;
UPDATE mangos_string SET content_default='没有找到物品!' WHERE entry=436;
UPDATE mangos_string SET content_default='无效的游戏物品对象 id: %u' WHERE entry=437;
UPDATE mangos_string SET content_default='找到物品 %u: %u ( 库存 %u 邮件 %u 拍卖 %u guild %u)' WHERE entry=438;
UPDATE mangos_string SET content_default='找到物品对象 %u: %u' WHERE entry=439;
UPDATE mangos_string SET content_default='无效的生物 id: %u’' WHERE entry=440;
UPDATE mangos_string SET content_default='找到生物 %u: %u' WHERE entry=441;
UPDATE mangos_string SET content_default='没有地区被发现!' WHERE entry=442;
UPDATE mangos_string SET content_default='没有找到物品!' WHERE entry=443;
UPDATE mangos_string SET content_default='没有找到此技能!' WHERE entry=444;
UPDATE mangos_string SET content_default='没有找到此法术!' WHERE entry=445;
UPDATE mangos_string SET content_default='没有找到此任务!' WHERE entry=446;
UPDATE mangos_string SET content_default='没有找到此生物!' WHERE entry=447;
UPDATE mangos_string SET content_default='没有找到此游戏物品对象!' WHERE entry=448;
UPDATE mangos_string SET content_default='墓地 #%u 不存在.' WHERE entry=449;
UPDATE mangos_string SET content_default='墓地 #%u 已经连接到区域 #%u (当前).' WHERE entry=450;
UPDATE mangos_string SET content_default='墓地 #%u 连接到区域 #%u (当前).' WHERE entry=451;
UPDATE mangos_string SET content_default='墓地 #%u 不能连接到子区域或不存在的区域 #%u (内部错误).' WHERE entry=452;
UPDATE mangos_string SET content_default='没有阵营在墓地且 entry= #%u , 请修复你的DB数据库' WHERE entry=454;
UPDATE mangos_string SET content_default='错误的队伍, 请修复你的数据库' WHERE entry=455;
UPDATE mangos_string SET content_default='任何' WHERE entry=456;
UPDATE mangos_string SET content_default='联盟' WHERE entry=457;
UPDATE mangos_string SET content_default='部落' WHERE entry=458;
UPDATE mangos_string SET content_default='墓地ID #%u (阵营faction: %s) 是最近的距此区域zoneID #%u.' WHERE entry=459;
UPDATE mangos_string SET content_default='区域Zone #%u 没有一个连接的墓地.' WHERE entry=460;
UPDATE mangos_string SET content_default='区域Zone #%u 没有一个连接的墓地为阵营faction: %s.' WHERE entry=461;
UPDATE mangos_string SET content_default='传送地点已经存在!' WHERE entry=462;
UPDATE mangos_string SET content_default='传送地点增加.' WHERE entry=463;
UPDATE mangos_string SET content_default='传送地点没增加: 数据库错误.' WHERE entry=464;
UPDATE mangos_string SET content_default='传送地点被删除.' WHERE entry=465;
UPDATE mangos_string SET content_default='No taxinodes found!' WHERE entry=466;
UPDATE mangos_string SET content_default='Target unit has %d auras:' WHERE entry=467;
UPDATE mangos_string SET content_default='id: %d eff: %d type: %d duration: %d maxduration: %d name: %s%s%s caster: %s (stacks: %d)' WHERE entry=468;
UPDATE mangos_string SET content_default='Target unit has %d auras of type %d:' WHERE entry=469;
UPDATE mangos_string SET content_default='id: %d eff: %d name: %s%s%s caster: %s' WHERE entry=470;
UPDATE mangos_string SET content_default='任务 %u 没有找到.' WHERE entry=471;
UPDATE mangos_string SET content_default='任务 %u 由物品触发. 为正确工作, 请, 添加物品到库里并且开始这个任务的正常方式: .additem %u' WHERE entry=472;
UPDATE mangos_string SET content_default='任务清除.' WHERE entry=473;
UPDATE mangos_string SET content_default=' [奖赏]' WHERE entry=474;
UPDATE mangos_string SET content_default=' [完成]' WHERE entry=475;
UPDATE mangos_string SET content_default=' [active]' WHERE entry=476;
UPDATE mangos_string SET content_default='%s 的飞行模式为 %s' WHERE entry=477;
UPDATE mangos_string SET content_default='操作代码Opcode %u 发送到(sent to) %s' WHERE entry=478;
UPDATE mangos_string SET content_default='角色加载成功!' WHERE entry=479;
UPDATE mangos_string SET content_default='加载角色失败!' WHERE entry=480;
UPDATE mangos_string SET content_default='卸载角色成功!' WHERE entry=481;
UPDATE mangos_string SET content_default='卸载角色失败!' WHERE entry=482;
UPDATE mangos_string SET content_default='法术 %u 禁止，并且不允许使用或学习!' WHERE entry=483;
UPDATE mangos_string SET content_default='技能值 %u (%s) 为角色 %s 设置到 %u 并且当前最大设置到 %u (没有固定(天赋)奖励).' WHERE entry=484;
UPDATE mangos_string SET content_default='角色 %s 必须拥有技能 %u (%s) 在使用这个命令之前.' WHERE entry=485;
UPDATE mangos_string SET content_default='错误的技能 id (%u)' WHERE entry=486;
UPDATE mangos_string SET content_default='你学会了ＧＭ默认的法术和技能.' WHERE entry=487;
UPDATE mangos_string SET content_default='你已经学了这个法术.' WHERE entry=488;
UPDATE mangos_string SET content_default='目标(%s) 已经学习了那些法术.' WHERE entry=489;
UPDATE mangos_string SET content_default='%s 不能学习那些法术.' WHERE entry=490;
UPDATE mangos_string SET content_default='您已经忘记了那个法术.' WHERE entry=491;
UPDATE mangos_string SET content_default='所有的法术冷却清除 %s.' WHERE entry=492;
UPDATE mangos_string SET content_default='法术 %u 冷却清除 %s.' WHERE entry=493;
UPDATE mangos_string SET content_default='命令: Additem, itemId = %i, amount = %i' WHERE entry=494;
UPDATE mangos_string SET content_default='命令: Additemset, itemsetId = %i' WHERE entry=495;
UPDATE mangos_string SET content_default='移除物品ID = %i, amount = %i from %s' WHERE entry=496;
UPDATE mangos_string SET content_default='不能创建物品  ''%i'' (数量amount: %i)' WHERE entry=497;
UPDATE mangos_string SET content_default='系统提示：你需要提供一个公会名字!' WHERE entry=498;
UPDATE mangos_string SET content_default='系统提示：玩家没有被找到!' WHERE entry=499;
UPDATE mangos_string SET content_default='系统提示：玩家已经有一个公会!' WHERE entry=500;
UPDATE mangos_string SET content_default='公会没被创建! (是否已经存在?)' WHERE entry=501;
UPDATE mangos_string SET content_default='没有物品从物品库’%u’ 里找到.' WHERE entry=502;
UPDATE mangos_string SET content_default='The distance is: (3D) %f (2D) %f - (3D, point-to-point) %f yards.' WHERE entry=503;
UPDATE mangos_string SET content_default='物品 ’%i’ ’%s’ 背包 %i' WHERE entry=504;
UPDATE mangos_string SET content_default='物品 ’%i’不存在.' WHERE entry=505;
UPDATE mangos_string SET content_default='物品 ’%i’ ’%s’ 已加入背包 %i' WHERE entry=506;
UPDATE mangos_string SET content_default='物品保存失败!' WHERE entry=507;
UPDATE mangos_string SET content_default='%d - owner: %s (guid: %u account: %u ) %s' WHERE entry=508;
UPDATE mangos_string SET content_default='%d - sender: %s (guid: %u account: %u ) receiver: %s (guid: %u account: %u ) %s' WHERE entry=509;
UPDATE mangos_string SET content_default='%d - owner: %s (guid: %u account: %u ) %s' WHERE entry=510;
UPDATE mangos_string SET content_default='Wrong link type!' WHERE entry=511;
UPDATE mangos_string SET content_default='%d - |cffffffff|Hitem:%d:0:0:0:0:0:0:0|h[%s]|h|r %s' WHERE entry=512;
UPDATE mangos_string SET content_default='%d - |cffffffff|Hquest:%d:%d|h[%s]|h|r %s' WHERE entry=513;
UPDATE mangos_string SET content_default='%d - |cffffffff|Hcreature_entry:%d|h[%s]|h|r ' WHERE entry=514;
UPDATE mangos_string SET content_default='%d%s - |cffffffff|Hcreature:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ' WHERE entry=515;
UPDATE mangos_string SET content_default='%d - |cffffffff|Hgameobject_entry:%d|h[%s]|h|r ' WHERE entry=516;
UPDATE mangos_string SET content_default='%d%s, Entry %d - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r' WHERE entry=517;
UPDATE mangos_string SET content_default='%d - |cffffffff|Hitemset:%d|h[%s %s]|h|r ' WHERE entry=518;
UPDATE mangos_string SET content_default='|cffffffff|Htele:%s|h[%s]|h|r ' WHERE entry=519;
UPDATE mangos_string SET content_default='%d - |cffffffff|Hspell:%d|h[%s]|h|r ' WHERE entry=520;
UPDATE mangos_string SET content_default='%d - |cffffffff|Hskill:%d|h[%s %s]|h|r %s %s' WHERE entry=521;
UPDATE mangos_string SET content_default='Game Object (Entry: %u) not found' WHERE entry=522;
UPDATE mangos_string SET content_default='>> Game Object %s (GUID: %u) at %f %f %f. Orientation %f.' WHERE entry=523;
UPDATE mangos_string SET content_default='Selected object:|cffffffff|Hgameobject:%d|h[%s]|h|r GUID: %u ID: %uX: %f Y: %f Z: %f MapId: %uOrientation: %f' WHERE entry=524;
UPDATE mangos_string SET content_default='>> Add Game Object ’%i’(%s) (GUID: %i) added at ’%f %f %f’.' WHERE entry=525;
UPDATE mangos_string SET content_default='%s (lowguid: %u) movement generators stack:' WHERE entry=526;
UPDATE mangos_string SET content_default='   空闲' WHERE entry=527;
UPDATE mangos_string SET content_default='   随机' WHERE entry=528;
UPDATE mangos_string SET content_default='   航点' WHERE entry=529;
UPDATE mangos_string SET content_default='   Animal random' WHERE entry=530;
UPDATE mangos_string SET content_default='   Confused' WHERE entry=531;
UPDATE mangos_string SET content_default='   Targeted to player %s (lowguid %u)' WHERE entry=532;
UPDATE mangos_string SET content_default='   Targeted to creature %s (lowguid %u)' WHERE entry=533;
UPDATE mangos_string SET content_default='   Targeted to <NULL>' WHERE entry=534;
UPDATE mangos_string SET content_default='   Home movement to (X:%f Y:%f Z:%f)' WHERE entry=535;
UPDATE mangos_string SET content_default='   Home movement used for player?!?' WHERE entry=536;
UPDATE mangos_string SET content_default='   Taxi flight' WHERE entry=537;
UPDATE mangos_string SET content_default='   Unknown movement generator (%u)' WHERE entry=538;
UPDATE mangos_string SET content_default='"Player selected: %s.
Faction: %u.
npcFlags: %u.
Entry: %u.
DisplayID: %u (Native: %u)."' WHERE entry=539;
UPDATE mangos_string SET content_default='等级: %u.' WHERE entry=540;
UPDATE mangos_string SET content_default='Health (base): %u. (max): %u. (current): %u.' WHERE entry=541;
UPDATE mangos_string SET content_default='"Unit Flags: %u.
Dynamic Flags: %u.
Faction Template: %u."' WHERE entry=542;
UPDATE mangos_string SET content_default='战利品: %u 偷窃: %u Skinning: %u' WHERE entry=543;
UPDATE mangos_string SET content_default='位置: %f %f %f.' WHERE entry=544;
UPDATE mangos_string SET content_default='*** 是一个销售师!' WHERE entry=545;
UPDATE mangos_string SET content_default='*** 是一个训练师!' WHERE entry=546;
UPDATE mangos_string SET content_default='副本ID: %u' WHERE entry=547;
UPDATE mangos_string SET content_default='玩家%s %s (guid: %u) 帐号: %s (id: %u) GM等级: %u 邮箱: %s 最后IP: %s 最后登陆: %s 延迟: %ums' WHERE entry=548;
UPDATE mangos_string SET content_default='角色已登录时间: %s 等级: %u 金钱: %ug%us%uc' WHERE entry=549;
UPDATE mangos_string SET content_default='命令提示：命令 .pinfo 不支持  ’rep’ 选择,玩家不在线.' WHERE entry=550;
UPDATE mangos_string SET content_default='%s 探索了所有地区.' WHERE entry=551;
UPDATE mangos_string SET content_default='%s 没有更多的探索区.' WHERE entry=552;
UPDATE mangos_string SET content_default='%s 你探索了所有区域.' WHERE entry=553;
UPDATE mangos_string SET content_default='%s 你掩藏了所有区域.' WHERE entry=554;
UPDATE mangos_string SET content_default='%s 的等级提高 (%i)' WHERE entry=557;
UPDATE mangos_string SET content_default='%s 的等级下降 (%i)' WHERE entry=558;
UPDATE mangos_string SET content_default='%s 重置了你的等级.' WHERE entry=559;
UPDATE mangos_string SET content_default='该地区已被设置为探索.' WHERE entry=560;
UPDATE mangos_string SET content_default='该地区已被设置为未探索.' WHERE entry=561;
UPDATE mangos_string SET content_default='The value index %u is too big to %s (count: %u).' WHERE entry=564;
UPDATE mangos_string SET content_default='Set for %s field:%u to uint32 value:%u' WHERE entry=565;
UPDATE mangos_string SET content_default='You set for %s field:%u to uint32 value: %u' WHERE entry=566;
UPDATE mangos_string SET content_default='Set for %s field:%u to to float value:%f' WHERE entry=567;
UPDATE mangos_string SET content_default='You set for %s field:%u to float value: %f' WHERE entry=568;
UPDATE mangos_string SET content_default='Get %s uint32 value:[FIELD]:%u [VALUE]:%u' WHERE entry=569;
UPDATE mangos_string SET content_default='%s has uint32 value:[FIELD]:%u [VALUE]:%u' WHERE entry=570;
UPDATE mangos_string SET content_default='Get %s float value:[FIELD]:%u [VALUE]:%f' WHERE entry=571;
UPDATE mangos_string SET content_default='%s has float value:[FIELD]:%u [VALUE]:%f' WHERE entry=572;
UPDATE mangos_string SET content_default='The lootstate of GO lowGuid %u is %u.' WHERE entry=573;
UPDATE mangos_string SET content_default='The GO state of GO lowGuid %u is %u.' WHERE entry=574;
UPDATE mangos_string SET content_default='Modify %s uint32 field:%u to sum with:%i = %u (%i)' WHERE entry=575;
UPDATE mangos_string SET content_default='You modify for %s uint32 field:%u to sum with:%i = %u (%i)' WHERE entry=576;
UPDATE mangos_string SET content_default='你现在处于隐身状态.' WHERE entry=577;
UPDATE mangos_string SET content_default='你现在处于可见状态.' WHERE entry=578;
UPDATE mangos_string SET content_default='Selected player or creature not have victim.' WHERE entry=579;
UPDATE mangos_string SET content_default='玩家 %s 学会了所有的本种族本职业的魔法,包括任何奖励的技能.' WHERE entry=580;
UPDATE mangos_string SET content_default='Found near gameobjects (distance %f): %u ' WHERE entry=581;
UPDATE mangos_string SET content_default='SpawnTime: Full:%s Remain:%s' WHERE entry=582;
UPDATE mangos_string SET content_default='%d - |cffffffff|Hgameevent:%d|h[%s]|h|r%s' WHERE entry=583;
UPDATE mangos_string SET content_default='没有事件被找到!' WHERE entry=584;
UPDATE mangos_string SET content_default='事件不存在!' WHERE entry=585;
UPDATE mangos_string SET content_default='事件 %u: %s%s开始: %s 结束: %s 发生: %s 全程: %s下一次状态改变: %s' WHERE entry=586;
UPDATE mangos_string SET content_default='事件 %u 已经开始!' WHERE entry=587;
UPDATE mangos_string SET content_default='事件 %u 已经结束!' WHERE entry=588;
UPDATE mangos_string SET content_default='   Point movement to (X:%f Y:%f Z:%f)' WHERE entry=589;
UPDATE mangos_string SET content_default='   Fear movement' WHERE entry=590;
UPDATE mangos_string SET content_default='   Distract movement' WHERE entry=591;
UPDATE mangos_string SET content_default='你已经学会了所有的法术: %s' WHERE entry=592;
UPDATE mangos_string SET content_default='目前禁用的帐户:' WHERE entry=593;
UPDATE mangos_string SET content_default='|    帐户    |   禁止日期   |   禁止时间   |   操作员   |   禁止理由  | ' WHERE entry=594;
UPDATE mangos_string SET content_default='目前禁止IP:' WHERE entry=595;
UPDATE mangos_string SET content_default='|    地址    |   禁止日期   |   禁止时间   |   操作员   |   禁止理由  |' WHERE entry=596;
UPDATE mangos_string SET content_default='目前游戏管理员:' WHERE entry=597;
UPDATE mangos_string SET content_default='|    帐户    |  管理员  |' WHERE entry=598;
UPDATE mangos_string SET content_default='没有游戏管理员.' WHERE entry=599;
UPDATE mangos_string SET content_default='联盟获得胜利!' WHERE entry=600;
UPDATE mangos_string SET content_default='部落获得胜利!' WHERE entry=601;
UPDATE mangos_string SET content_default='战歌峡谷争夺1分钟倒计时中...' WHERE entry=602;
UPDATE mangos_string SET content_default='战歌峡谷争夺，在30秒后开始。大家做好准备!' WHERE entry=603;
UPDATE mangos_string SET content_default='战歌峡谷争夺正式开始!' WHERE entry=604;
UPDATE mangos_string SET content_default='$n 夺取了部落旗子!' WHERE entry=605;
UPDATE mangos_string SET content_default='$n 夺取了联盟旗子!' WHERE entry=606;
UPDATE mangos_string SET content_default='部落旗子被 $n 降下!' WHERE entry=607;
UPDATE mangos_string SET content_default='联盟旗子被 $n 降下!' WHERE entry=608;
UPDATE mangos_string SET content_default='联盟旗子被 $n 返回了到它的基地!' WHERE entry=609;
UPDATE mangos_string SET content_default='部落旗子被 $n 返回了到它的基地!' WHERE entry=610;
UPDATE mangos_string SET content_default='部落旗子被 $n 拾起!' WHERE entry=611;
UPDATE mangos_string SET content_default='联盟旗子被 $n 拾起!' WHERE entry=612;
UPDATE mangos_string SET content_default='旗子现在被安置在他们的基地.' WHERE entry=613;
UPDATE mangos_string SET content_default='T联盟旗帜已经被重置.' WHERE entry=614;
UPDATE mangos_string SET content_default='联盟旗帜已经被重置.' WHERE entry=615;
UPDATE mangos_string SET content_default='联盟' WHERE entry=650;
UPDATE mangos_string SET content_default='部落' WHERE entry=651;
UPDATE mangos_string SET content_default='兽栏' WHERE entry=652;
UPDATE mangos_string SET content_default='铁匠铺' WHERE entry=653;
UPDATE mangos_string SET content_default='农场' WHERE entry=654;
UPDATE mangos_string SET content_default='伐木' WHERE entry=655;
UPDATE mangos_string SET content_default='矿洞' WHERE entry=656;
UPDATE mangos_string SET content_default='%s 占领了 %s' WHERE entry=657;
UPDATE mangos_string SET content_default='$n 保卫了  %s' WHERE entry=658;
UPDATE mangos_string SET content_default='$n 攻击了  %s' WHERE entry=659;
UPDATE mangos_string SET content_default='$n 夺取了 %s ,如果听之任之, %s 将在1分钟之内控制它!' WHERE entry=660;
UPDATE mangos_string SET content_default='战场阿拉西盆地争夺1分钟倒计时中..' WHERE entry=661;
UPDATE mangos_string SET content_default='战场阿拉西盆地争夺，在30秒后开始。大家做好准备!' WHERE entry=662;
UPDATE mangos_string SET content_default='战场阿拉西盆地争夺正式开始!' WHERE entry=663;
UPDATE mangos_string SET content_default='联盟已收集到$1776W资源, 并已接近胜利!' WHERE entry=664;
UPDATE mangos_string SET content_default='部落已收集到$1777W资源, 并已接近胜利!' WHERE entry=665;
UPDATE mangos_string SET content_default='你在最近的 %s 战斗之后,我们努力想为你颁发一个荣誉标志却没有成功,结束后你会发现这个荣誉标志的,但不是此刻,感谢你在 %s 的战斗.' WHERE entry=666;
UPDATE mangos_string SET content_default='你必须等待 %s 才能继续喊话.' WHERE entry=705;
UPDATE mangos_string SET content_default='这些道具在装备/存放中出现一个问题.' WHERE entry=706;
UPDATE mangos_string SET content_default='%s 免打扰状态下无法收到悄悄话: %s' WHERE entry=707;
UPDATE mangos_string SET content_default='%s 不在机器旁: %s' WHERE entry=708;
UPDATE mangos_string SET content_default='请勿打扰' WHERE entry=709;
UPDATE mangos_string SET content_default='离开' WHERE entry=710;
UPDATE mangos_string SET content_default='队列状态 %s (等级: %u - %u)Queued alliances: %u (Need at least %u more)Queued hordes: %u (Need at least %u more)' WHERE entry=711;
UPDATE mangos_string SET content_default='|cffff0000[战场召唤]:|r %s -- [%u-%u] 联盟人数: %u/%u, 部落人数: %u/%u|r' WHERE entry=712;
UPDATE mangos_string SET content_default='这个战场已被管理员禁用.' WHERE entry=714;
UPDATE mangos_string SET content_default='你的等级不够,不满足进入战场的要求.' WHERE entry=715;
UPDATE mangos_string SET content_default='|cffff0000[战场召唤]:|r %s -- [%u-%u] 战斗开始!|r' WHERE entry=717;
UPDATE mangos_string SET content_default='你的团队成员太多,无法加入战场. 请重新加入.' WHERE entry=720;
UPDATE mangos_string SET content_default='你的小组有一个离线成员. 请踢出该成员重新加入.' WHERE entry=727;
UPDATE mangos_string SET content_default='你的团队有来自对方阵营的玩家. You can’t join the battleground as a group.' WHERE entry=728;
UPDATE mangos_string SET content_default='Your group has players from different battleground brakets. You can’t join as group.' WHERE entry=729;
UPDATE mangos_string SET content_default='Someone in your party is already in this battleground queue. (S)he must leave it before joining as group.' WHERE entry=730;
UPDATE mangos_string SET content_default='Someone in your party is Deserter. You can’t join as group.' WHERE entry=731;
UPDATE mangos_string SET content_default='Someone in your party is already in three battleground queues. You cannot join as group.' WHERE entry=732;
UPDATE mangos_string SET content_default='你不能传送到战场地图.' WHERE entry=733;
UPDATE mangos_string SET content_default='你不能召唤玩家到战场或竞技场地图.' WHERE entry=734;
UPDATE mangos_string SET content_default='你必须在GM模式才能传送到战场的玩家身边.' WHERE entry=735;
UPDATE mangos_string SET content_default='你不能传送到另一个战场. 请先离开现在的战场.' WHERE entry=736;
UPDATE mangos_string SET content_default='单人战场开启.战场设置（1V0）.' WHERE entry=739;
UPDATE mangos_string SET content_default='战场模式已更改为：正常状态.' WHERE entry=740;
UPDATE mangos_string SET content_default='该地区被游戏管理员禁用.' WHERE entry=747;
UPDATE mangos_string SET content_default='没有足够的玩家. 这个战场将在%u分钟后关闭.' WHERE entry=750;
UPDATE mangos_string SET content_default='没有足够的玩家. 该战场将在%u秒后关闭.' WHERE entry=751;
UPDATE mangos_string SET content_default='只有联盟玩家才能使用这个入口' WHERE entry=752;
UPDATE mangos_string SET content_default='只有部落玩家才能使用这个入口' WHERE entry=753;
UPDATE mangos_string SET content_default='%s 被摧毁 %s!' WHERE entry=759;
UPDATE mangos_string SET content_default='The %s is under attack! If left unchecked, the %s will destroy it!' WHERE entry=760;
UPDATE mangos_string SET content_default='The %s was taken by the %s!' WHERE entry=761;
UPDATE mangos_string SET content_default='The %s was taken by the %s!' WHERE entry=762;
UPDATE mangos_string SET content_default='The %s was taken by the %s!' WHERE entry=763;
UPDATE mangos_string SET content_default='The %s is under attack! If left unchecked, the %s will capture it!' WHERE entry=764;
UPDATE mangos_string SET content_default='The %s has taken the %s! Its supplies will now be used for reinforcements!' WHERE entry=765;
UPDATE mangos_string SET content_default='Irondeep Mine' WHERE entry=766;
UPDATE mangos_string SET content_default='Coldtooth Mine' WHERE entry=767;
UPDATE mangos_string SET content_default='Stormpike Aid Station' WHERE entry=768;
UPDATE mangos_string SET content_default='Dun Baldar South Bunker' WHERE entry=769;
UPDATE mangos_string SET content_default='Dun Baldar North Bunker' WHERE entry=770;
UPDATE mangos_string SET content_default='Stormpike Graveyard' WHERE entry=771;
UPDATE mangos_string SET content_default='Icewing Bunker' WHERE entry=772;
UPDATE mangos_string SET content_default='Stonehearth Graveyard' WHERE entry=773;
UPDATE mangos_string SET content_default='Stonehearth Bunker' WHERE entry=774;
UPDATE mangos_string SET content_default='Snowfall Graveyard' WHERE entry=775;
UPDATE mangos_string SET content_default='Iceblood Tower' WHERE entry=776;
UPDATE mangos_string SET content_default='Iceblood Graveyard' WHERE entry=777;
UPDATE mangos_string SET content_default='Tower Point' WHERE entry=778;
UPDATE mangos_string SET content_default='Frostwolf Graveyard' WHERE entry=779;
UPDATE mangos_string SET content_default='East Frostwolf Tower' WHERE entry=780;
UPDATE mangos_string SET content_default='West Frostwolf Tower' WHERE entry=781;
UPDATE mangos_string SET content_default='Frostwolf Relief Hut' WHERE entry=782;
UPDATE mangos_string SET content_default='1 minute until the battle for Alterac Valley begins.' WHERE entry=784;
UPDATE mangos_string SET content_default='30 seconds until the battle for Alterac Valley begins. Prepare yourselves!' WHERE entry=785;
UPDATE mangos_string SET content_default='The battle for Alterac Valley has begun!' WHERE entry=786;
UPDATE mangos_string SET content_default='The Alliance Team is running out of reinforcements!' WHERE entry=787;
UPDATE mangos_string SET content_default='The Horde Team is running out of reinforcements!' WHERE entry=788;
UPDATE mangos_string SET content_default='The Frostwolf General is Dead!' WHERE entry=789;
UPDATE mangos_string SET content_default='The Stormpike General is Dead!' WHERE entry=790;
UPDATE mangos_string SET content_default='You do not have enough gold' WHERE entry=801;
UPDATE mangos_string SET content_default='You do not have enough free slots' WHERE entry=802;
UPDATE mangos_string SET content_default='Your partner does not have enough free bag slots' WHERE entry=803;
UPDATE mangos_string SET content_default='You do not have permission to perform that function' WHERE entry=804;
UPDATE mangos_string SET content_default='未知的语言' WHERE entry=805;
UPDATE mangos_string SET content_default='You don’t know that language' WHERE entry=806;
UPDATE mangos_string SET content_default='Please provide character name' WHERE entry=807;
UPDATE mangos_string SET content_default='Player %s not found or offline' WHERE entry=808;
UPDATE mangos_string SET content_default='Account for character %s not found' WHERE entry=809;
UPDATE mangos_string SET content_default='会长' WHERE entry=811;
UPDATE mangos_string SET content_default='官员' WHERE entry=812;
UPDATE mangos_string SET content_default='精英' WHERE entry=813;
UPDATE mangos_string SET content_default='会员' WHERE entry=814;
UPDATE mangos_string SET content_default='新人' WHERE entry=815;
UPDATE mangos_string SET content_default='Exiting daemon...' WHERE entry=1000;
UPDATE mangos_string SET content_default='Account deleted: %s' WHERE entry=1001;
UPDATE mangos_string SET content_default='Account %s NOT deleted (probably sql file format was updated)' WHERE entry=1002;
UPDATE mangos_string SET content_default='Account %s NOT deleted (unknown error)' WHERE entry=1003;
UPDATE mangos_string SET content_default='Account created: %s' WHERE entry=1004;
UPDATE mangos_string SET content_default='Account name cannot be longer than 16 characters (client limit), account not created!' WHERE entry=1005;
UPDATE mangos_string SET content_default='Account with this name already exist!' WHERE entry=1006;
UPDATE mangos_string SET content_default='Account %s NOT created (probably sql file format was updated)' WHERE entry=1007;
UPDATE mangos_string SET content_default='Account %s NOT created (unknown error)' WHERE entry=1008;
UPDATE mangos_string SET content_default='Player %s (Guid: %u) Account %s (Id: %u) deleted.' WHERE entry=1009;
UPDATE mangos_string SET content_default='| ID         |    Account    |       Character      |       IP        | GM | Expansion |' WHERE entry=1010;
UPDATE mangos_string SET content_default='========================================================================================' WHERE entry=1012;
UPDATE mangos_string SET content_default='| %10u |%15s| %20s | %15s |%4d| %9d |' WHERE entry=1013;
UPDATE mangos_string SET content_default='No online players.' WHERE entry=1014;
UPDATE mangos_string SET content_default='Can only quit from a Remote Admin console or the quit command was not entered in full (quit).' WHERE entry=1015;
UPDATE mangos_string SET content_default='| GUID       | Name                 | Account                      | Delete Date         |' WHERE entry=1016;
UPDATE mangos_string SET content_default='| %10u | %20s | %15s (%10u) | %19s |' WHERE entry=1017;
UPDATE mangos_string SET content_default='==========================================================================================' WHERE entry=1018;
UPDATE mangos_string SET content_default='没有找到这个人物.' WHERE entry=1019;
UPDATE mangos_string SET content_default='Restoring the following characters:' WHERE entry=1020;
UPDATE mangos_string SET content_default='Deleting the following characters:' WHERE entry=1021;
UPDATE mangos_string SET content_default='ERROR: You can only assign a new name for a single selected character!' WHERE entry=1022;
UPDATE mangos_string SET content_default='Character ’%s’ (GUID: %u Account %u) can’t be restored: account doesn’t exist!' WHERE entry=1023;
UPDATE mangos_string SET content_default='Character ’%s’ (GUID: %u Account %u) can’t be restored: account character list full!' WHERE entry=1024;
UPDATE mangos_string SET content_default='Character ’%s’ (GUID: %u Account %u) can’t be restored: name already in use!' WHERE entry=1025;
UPDATE mangos_string SET content_default='GUID: %u Name: %s Account: %s (%u) Date: %s' WHERE entry=1026;
UPDATE mangos_string SET content_default='Log filters state:' WHERE entry=1027;
UPDATE mangos_string SET content_default='All log filters set to: %s' WHERE entry=1028;
UPDATE mangos_string SET content_default='Command can only be called from a Remote Admin console.' WHERE entry=1029;
UPDATE mangos_string SET content_default='Account %s (Id: %u) has been granted %u expansion rights.' WHERE entry=1100;
UPDATE mangos_string SET content_default='Message of the day changed to:%s' WHERE entry=1101;
UPDATE mangos_string SET content_default='Message sent to %s: %s' WHERE entry=1102;
UPDATE mangos_string SET content_default='%d - %s %s' WHERE entry=1103;
UPDATE mangos_string SET content_default='%d - %s' WHERE entry=1104;
UPDATE mangos_string SET content_default='%d - %s %s' WHERE entry=1105;
UPDATE mangos_string SET content_default='%d - %s %s' WHERE entry=1106;
UPDATE mangos_string SET content_default='%d - %s' WHERE entry=1107;
UPDATE mangos_string SET content_default='%d - %s %s' WHERE entry=1108;
UPDATE mangos_string SET content_default='%d - %s %s %s %s' WHERE entry=1109;
UPDATE mangos_string SET content_default='%d%s - %s X:%f Y:%f Z:%f MapId:%d' WHERE entry=1110;
UPDATE mangos_string SET content_default='%d%s - %s X:%f Y:%f Z:%f MapId:%d' WHERE entry=1111;
UPDATE mangos_string SET content_default='Failed to open file: %s' WHERE entry=1112;
UPDATE mangos_string SET content_default='Account %s (%u) have max amount allowed characters (client limit)' WHERE entry=1113;
UPDATE mangos_string SET content_default='Dump file have broken data!' WHERE entry=1114;
UPDATE mangos_string SET content_default='Invalid character name!' WHERE entry=1115;
UPDATE mangos_string SET content_default='Invalid character guid!' WHERE entry=1116;
UPDATE mangos_string SET content_default='Character guid %u in use!' WHERE entry=1117;
UPDATE mangos_string SET content_default='%d - guild: %s (guid: %u) %s' WHERE entry=1118;
UPDATE mangos_string SET content_default='You must use male or female as gender.' WHERE entry=1119;
UPDATE mangos_string SET content_default='You change gender of %s to %s.' WHERE entry=1120;
UPDATE mangos_string SET content_default='Your gender changed to %s by %s.' WHERE entry=1121;
UPDATE mangos_string SET content_default='(%u/%u +perm %u +temp %u)' WHERE entry=1122;
UPDATE mangos_string SET content_default='%d - |cffffffff|Htaxinode:%u|h[%s %s]|h|r (Map:%u X:%f Y:%f Z:%f)' WHERE entry=1128;
UPDATE mangos_string SET content_default='%d - %s %s (Map:%u X:%f Y:%f Z:%f)' WHERE entry=1129;
UPDATE mangos_string SET content_default='event started %u "%s"' WHERE entry=1130;
UPDATE mangos_string SET content_default='event stopped %u "%s"' WHERE entry=1131;
UPDATE mangos_string SET content_default='   Follow player %s (lowguid %u)' WHERE entry=1132;
UPDATE mangos_string SET content_default='   Follow creature %s (lowguid %u)' WHERE entry=1133;
UPDATE mangos_string SET content_default='   Follow <NULL>' WHERE entry=1134;
UPDATE mangos_string SET content_default='List known talents:' WHERE entry=1135;
UPDATE mangos_string SET content_default='   (Found talents: %u used talent points: %u)' WHERE entry=1136;
UPDATE mangos_string SET content_default='%d%s - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ' WHERE entry=1137;
UPDATE mangos_string SET content_default='=================================================================================' WHERE entry=1138;
UPDATE mangos_string SET content_default='| GUID       | Name                 | Race            | Class           | Level |' WHERE entry=1139;
UPDATE mangos_string SET content_default='| %10u | %20s | %15s | %15s | %5u |' WHERE entry=1140;
UPDATE mangos_string SET content_default='%u - |cffffffff|Hplayer:%s|h[%s]|h|r %s %s %u' WHERE entry=1141;
UPDATE mangos_string SET content_default='%u - %s (Online:%s IP:%s GM:%u Expansion:%u)' WHERE entry=1142;
UPDATE mangos_string SET content_default='Spawned by event %u (%s)' WHERE entry=1143;
UPDATE mangos_string SET content_default='Despawned by event %u (%s)' WHERE entry=1144;
UPDATE mangos_string SET content_default='Part of pool %u' WHERE entry=1145;
UPDATE mangos_string SET content_default='Part of pool %u, top pool %u' WHERE entry=1146;
UPDATE mangos_string SET content_default='The (top)pool %u is spawned by event %u (%s)' WHERE entry=1147;
UPDATE mangos_string SET content_default='The (top)pool %u is despawned by event %u (%s)' WHERE entry=1148;
UPDATE mangos_string SET content_default=' (Pool %u)' WHERE entry=1149;
UPDATE mangos_string SET content_default=' (Event %i)' WHERE entry=1150;
UPDATE mangos_string SET content_default=' (Pool %u Event %i)' WHERE entry=1151;
UPDATE mangos_string SET content_default='[usable]' WHERE entry=1152;
UPDATE mangos_string SET content_default='Get %s bitstr value:[FIELD]:%u [VALUE]:%s' WHERE entry=1153;
UPDATE mangos_string SET content_default='%s has bitstr value:[FIELD]:%u [VALUE]:%s' WHERE entry=1154;
UPDATE mangos_string SET content_default='Get %s hex value:[FIELD]:%u [VALUE]:%x' WHERE entry=1155;
UPDATE mangos_string SET content_default='%s has hex value:[FIELD]:%u [VALUE]:%x' WHERE entry=1156;
UPDATE mangos_string SET content_default='Modify %s hex field:%u %s %x = %x (hex)' WHERE entry=1157;
UPDATE mangos_string SET content_default='You modify for %s hex field:%u %s %x = %x (hex)' WHERE entry=1158;
UPDATE mangos_string SET content_default='Modify %s float field:%u to sum with:%f = %f' WHERE entry=1159;
UPDATE mangos_string SET content_default='You modify for %s float field:%u to sum with:%f = %f' WHERE entry=1160;
UPDATE mangos_string SET content_default='Spell %u not have auras.' WHERE entry=1165;
UPDATE mangos_string SET content_default='Scripting library not found or not accessible.' WHERE entry=1166;
UPDATE mangos_string SET content_default='Scripting library has wrong list functions (outdated?).' WHERE entry=1167;
UPDATE mangos_string SET content_default='Scripting library reloaded.' WHERE entry=1168;
UPDATE mangos_string SET content_default='Scripting library build for different mangosd revision.' WHERE entry=1169;
UPDATE mangos_string SET content_default='All config are reloaded from ahbot configuration file.' WHERE entry=1171;
UPDATE mangos_string SET content_default='Error while trying to reload ahbot config.' WHERE entry=1172;
UPDATE mangos_string SET content_default='==========================================================' WHERE entry=1173;
UPDATE mangos_string SET content_default='|--------------------------------------------------------|' WHERE entry=1174;
UPDATE mangos_string SET content_default='|            | Alliance |  Horde   | Neutral  |  Total   |' WHERE entry=1175;
UPDATE mangos_string SET content_default='          Alliance/Horde/Neutral/Total' WHERE entry=1176;
UPDATE mangos_string SET content_default='| %-10s | %8u | %8u | %8u | %8u |' WHERE entry=1177;
UPDATE mangos_string SET content_default='%-10s = %6u / %6u / %6u / %6u' WHERE entry=1178;
UPDATE mangos_string SET content_default='Count' WHERE entry=1179;
UPDATE mangos_string SET content_default='Item Ratio' WHERE entry=1180;
UPDATE mangos_string SET content_default='|            | Alliance |   Horde  | Neutral  |  Amount  |' WHERE entry=1181;
UPDATE mangos_string SET content_default='          Alliance/Horde/Neutral/Amount' WHERE entry=1182;
UPDATE mangos_string SET content_default='灰色' WHERE entry=1183;
UPDATE mangos_string SET content_default='白色' WHERE entry=1184;
UPDATE mangos_string SET content_default='绿色' WHERE entry=1185;
UPDATE mangos_string SET content_default='蓝色' WHERE entry=1186;
UPDATE mangos_string SET content_default='紫色' WHERE entry=1187;
UPDATE mangos_string SET content_default='橙色' WHERE entry=1188;
UPDATE mangos_string SET content_default='黄色' WHERE entry=1189;
UPDATE mangos_string SET content_default='Amount of %s items is set to %u.' WHERE entry=1190;
UPDATE mangos_string SET content_default='Items ratio for %s is set to %u.' WHERE entry=1191;
UPDATE mangos_string SET content_default='Effect movement' WHERE entry=1192;
UPDATE mangos_string SET content_default='Current State Information: GOState %u, LootState %u. Collision %s' WHERE entry=1194;
UPDATE mangos_string SET content_default='Current State Information: GOState %u, LootState %u. Collision %s, (door %s by default)' WHERE entry=1195;
UPDATE mangos_string SET content_default='You try to view cinematic %u but it doesn’t exist.' WHERE entry=1200;
UPDATE mangos_string SET content_default='Spell %u %s = %f (*1.88 = %f) DB = %f AP = %f' WHERE entry=1202;
UPDATE mangos_string SET content_default='治疗' WHERE entry=1203;
UPDATE mangos_string SET content_default='伤害' WHERE entry=1204;
UPDATE mangos_string SET content_default='愈合' WHERE entry=1205;
UPDATE mangos_string SET content_default='持续伤害' WHERE entry=1206;
UPDATE mangos_string SET content_default='Private ' WHERE entry=1400;
UPDATE mangos_string SET content_default='下士' WHERE entry=1401;
UPDATE mangos_string SET content_default='中士' WHERE entry=1402;
UPDATE mangos_string SET content_default='军士长' WHERE entry=1403;
UPDATE mangos_string SET content_default='Sergeant Major ' WHERE entry=1404;
UPDATE mangos_string SET content_default='Knight ' WHERE entry=1405;
UPDATE mangos_string SET content_default='Knight-Lieutenant ' WHERE entry=1406;
UPDATE mangos_string SET content_default='Knight-Captain ' WHERE entry=1407;
UPDATE mangos_string SET content_default='Knight-Champion ' WHERE entry=1408;
UPDATE mangos_string SET content_default='Lieutenant Commander ' WHERE entry=1409;
UPDATE mangos_string SET content_default='Commander ' WHERE entry=1410;
UPDATE mangos_string SET content_default='元帅' WHERE entry=1411;
UPDATE mangos_string SET content_default='Field Marshal ' WHERE entry=1412;
UPDATE mangos_string SET content_default='大元帅' WHERE entry=1413;
UPDATE mangos_string SET content_default='侦察兵' WHERE entry=1414;
UPDATE mangos_string SET content_default='Grunt ' WHERE entry=1415;
UPDATE mangos_string SET content_default='Sergeant ' WHERE entry=1416;
UPDATE mangos_string SET content_default='Senior Sergeant ' WHERE entry=1417;
UPDATE mangos_string SET content_default='First Sergeant ' WHERE entry=1418;
UPDATE mangos_string SET content_default='Stone Guard ' WHERE entry=1419;
UPDATE mangos_string SET content_default='Blood Guard ' WHERE entry=1420;
UPDATE mangos_string SET content_default='Legionnare ' WHERE entry=1421;
UPDATE mangos_string SET content_default='Centurion ' WHERE entry=1422;
UPDATE mangos_string SET content_default='Champion ' WHERE entry=1423;
UPDATE mangos_string SET content_default='Lieutenant General ' WHERE entry=1424;
UPDATE mangos_string SET content_default='General ' WHERE entry=1425;
UPDATE mangos_string SET content_default='Warlord ' WHERE entry=1426;
UPDATE mangos_string SET content_default='High Warlord ' WHERE entry=1427;
UPDATE mangos_string SET content_default='Game Master ' WHERE entry=1428;
UPDATE mangos_string SET content_default='No Rank ' WHERE entry=1429;
UPDATE mangos_string SET content_default='Dishonored ' WHERE entry=1430;
UPDATE mangos_string SET content_default='Exiled ' WHERE entry=1431;
UPDATE mangos_string SET content_default='Outlaw ' WHERE entry=1432;
UPDATE mangos_string SET content_default='Pariah ' WHERE entry=1433;
UPDATE mangos_string SET content_default='Player: %s - %s (Rank %u)' WHERE entry=1434;
UPDATE mangos_string SET content_default='Today: [Honorable Kills: |c0000ff00%u|r] [Dishonorable Kills: |c00ff0000%u|r]' WHERE entry=1435;
UPDATE mangos_string SET content_default='Yesterday: [Kills: |c0000ff00%u|r] [Honor: %u]' WHERE entry=1436;
UPDATE mangos_string SET content_default='This Week: [Kills: |c0000ff00%u|r] [Honor: %u]' WHERE entry=1437;
UPDATE mangos_string SET content_default='Last Week: [Kills: |c0000ff00%u|r] [Honor: %u] [Standing: %u]' WHERE entry=1438;
UPDATE mangos_string SET content_default='Life Time: [Rank Points: |c0000ff00%f|r] [Honorable Kills: |c0000ff00%u|r] [Dishonorable Kills: |c00ff0000%u|r] [Highest Rank %u: %s]' WHERE entry=1439;
UPDATE mangos_string SET content_default='%u - [%s] AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u Chance: %f %s' WHERE entry=1500;
UPDATE mangos_string SET content_default='%u - |cffffffff|Hpool:%u|h[%s]|h|r AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u %s' WHERE entry=1501;
UPDATE mangos_string SET content_default='%u - [%s] AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u %s' WHERE entry=1502;
UPDATE mangos_string SET content_default='Cannot add spawn because no free guids for static spawn in reserved guids range. Server restart is required before command can be used. Also look GuidReserveSize.* config options.' WHERE entry=1503;
UPDATE mangos_string SET content_default='AI-Information for Npc Entry %u' WHERE entry=1504;
UPDATE mangos_string SET content_default='AIName: %s (%s) ScriptName: %s' WHERE entry=1505;
UPDATE mangos_string SET content_default='Current phase = %u' WHERE entry=1506;
UPDATE mangos_string SET content_default='Combat-Movement is %s' WHERE entry=1507;
UPDATE mangos_string SET content_default='Melee attacking is %s' WHERE entry=1508;
UPDATE mangos_string SET content_default='Pool %u not found (Maximal pool entry is %u)' WHERE entry=1509;
UPDATE mangos_string SET content_default='Closed ticket for player %s' WHERE entry=1510;
UPDATE mangos_string SET content_default='Ticket system is globally on, accepting all tickets' WHERE entry=1511;
UPDATE mangos_string SET content_default='Ticket system is globally off, not accepting tickets at all' WHERE entry=1512;
UPDATE mangos_string SET content_default='You cant close a ticket for offline players' WHERE entry=1513;
UPDATE mangos_string SET content_default='ID %u from %s (%s), changed %s' WHERE entry=1514;
UPDATE mangos_string SET content_default='= Shown %u tickets out of total %u from online players.' WHERE entry=1515;
UPDATE mangos_string SET content_default='ID %u from GUID %u (%s), changed %s' WHERE entry=1516;
UPDATE mangos_string SET content_default='= Shown %u tickets of total %u.' WHERE entry=1517;
UPDATE mangos_string SET content_default='Informing you about arriving tickets is %s.' WHERE entry=1518;
UPDATE mangos_string SET content_default='|cffffff00Northpass Tower has been taken by the Horde!|r' WHERE entry=1600;
UPDATE mangos_string SET content_default='|cffffff00Northpass Tower has been taken by the Alliance!|r' WHERE entry=1601;
UPDATE mangos_string SET content_default='|cffffff00Crown Guard Tower has been taken by the Horde!|r' WHERE entry=1602;
UPDATE mangos_string SET content_default='|cffffff00Crown Guard Tower has been taken by the Alliance!|r' WHERE entry=1603;
UPDATE mangos_string SET content_default='|cffffff00Eastwall Tower has been taken by the Horde!|r' WHERE entry=1604;
UPDATE mangos_string SET content_default='|cffffff00Eastwall Tower has been taken by the Alliance!|r' WHERE entry=1605;
UPDATE mangos_string SET content_default='|cffffff00The Plaguewood Tower has been taken by the Horde!|r' WHERE entry=1606;
UPDATE mangos_string SET content_default='|cffffff00The Plaguewood Tower has been taken by the Alliance!|r' WHERE entry=1607;
UPDATE mangos_string SET content_default='|cffffff00The Horde has collected 200 silithyst!|r' WHERE entry=1635;
UPDATE mangos_string SET content_default='|cffffff00The Alliance has collected 200 silithyst!|r' WHERE entry=1636;